### ISSUE TITLE
mysql failed to build on 10.10

### ISSUE THREAD

**Issue by keewek** [Homebrew/homebrew#33448]
https://gist.github.com/keewek/5e05a1968e3d205c0ab7#file-02-make-L346-L414

htonll detection failure, same as in https://github.com/Homebrew/homebrew/issues/33439

**Comment by RandomDSdevel** [comment]
@jacknagel:  I've read [that bug](http://bugs.mysql.com/bug.php?id=73405)'s comments, and I _don't_ think that its resolution is stalled by 'red tape.'  In the second-to-last comment, Sveta Smirnova specifically stated the following:  

```
Thank you for the report.

I can verify this as feature request only unless you provide example of any OS which is supported by MySQL officially and has htonll defined as a macro.
```

So, the problem is that Ryan Schmidt, the individual who reported the bug and submitted some patches for it, did not put enough details about this bug into either his initial report or his later comments.  Maybe somebody could drop an info dump about this on the bug's upstream page?

**Comment by RandomDSdevel** [comment]
Oops, that was thread necromancy…the bug still isn't fixed, though, and _I'd_ like to have Homebrew build MySQL with `memcached` support before it installs it, _too_.  (Just sayin'.)  Oh, well; guess I'll have to keep my eye on this issue and reinstall MySQL when it gets fixed.

**Comment by jacknagel** [comment]
Personally, I don't have the time or interest to pursue the issue, but if you're interested, by all means, try to help move the upstream issue along.

**Comment by RandomDSdevel** [comment]
OK, I might as well look into doing so, but it's not that high on _my_ priority list, either…

**Comment by Cam** [comment]
Is there another way to build MySQL using Homebrew? This thing has me stopped in my tracks, and I can't seem to find any valuable info anywhere on workarounds or solutions :(

**Comment by mikemcquaid** [comment]
@Cam Build without `memcached` support.

**Comment by Cam** [comment]
Thanks @mikemcquaid. I figured ou that memchache wasn't needed eventually. Cheers!

**Comment by RandomDSdevel** [comment]
Ah, good!  I'll try a `brew reinstall mysql --with-memcached` once #44928 gets resolved and pulled into `master`, then.
