### ISSUE TITLE
ansible formula missing modules

### ISSUE THREAD

**Issue by ebridges** [Homebrew/homebrew#33630]
When I run `ansible-playbook` using the brew installed version of Ansible, i get the following error:

`ERROR: xxx is not a legal parameter in an Ansible task or handler`

(Where `xxx` is a module e.g. the `file` task). This message indicates that it's not finding the `xxx` module.  

When I install v1.7.2 of Ansible from git, it works fine (see this [test script](https://gist.github.com/ebridges/7cbdcc708c2078f74690) that demonstrates that).  However, if I run `ansible-playbook playbook.yml -i hosts.ini` with the playbook generated by that test script, using Homebrew's version of Ansible i get the above error.

Here's a gist-log of my setup:
https://gist.github.com/anonymous/39276585019813690891

**Comment by lastobelus** [comment]
I also have no modules when installing ansible. As I understand they should end up in
```/usr/local/Cellar/ansible/1.9.1/share/ansible``` but after ```brew install ansible``` there is no such directory.

**Comment by lastobelus** [comment]
actually this was a misunderstanding because of the combination of `ansible --version` returning `configured module search path = None` and that modules now live in `/usr/local/Cellar/ansible/1.9.1/libexec/lib/python2.7/site-packages/ansible/modules`

Perhaps the OP had a similar misunderstanding? @ebridges did you sort this out? You can do `ansible-doc -l` to see what modules ansible knows about

**Comment by tdsmith** [comment]
Assuming this is resolved; holler if there's something we can do here.
