### ISSUE TITLE
Haskell formulas using cabal are not reliable

### ISSUE THREAD

**Issue by carlmod** [Homebrew/homebrew#34003]
Due to new versions of libraries uploaded to Hackage, currently working Formulas can suddenly fail. To avoid this, it would be resonable to pin the versions used to build a software, similar to how it is done with  ruby gems and python modules.

Using the command: `cabal install xxx --dry-run` one gets a list of the packages that fulfills all version requirements, and in what order the could be installed.

One way of dealing with this would be to  specify them as resources in the formula and then sequentially build them. I currently see two drawbacks with this:

1: For git-annex this is about 200 resources that needs to be specified, and inspected when upgrading the Formula.
2: Building speed will be reduced, since we would not have access to the smarts of cabal to see what could be built in parallel.

**Comment by carlmod** [comment]
Possibly the "curated" list of hackage packages in https://www.stackage.org/ could be of some help to get packages reliably built, as I understand it they publish a versioned list of package contraints. For Haskell software on this list it could be pulled in as an dependency.

**Comment by Blaisorblade** [comment]
It sounds like a good idea, though details can be tricky. If people like the idea, we might want to ask the people at https://github.com/fpco/lts-haskell for tips — their README even says they encourage such usage:

> While Stackage Server is currently the only means of using the LTS Haskell package set, we strongly encourage other means of distribution, such as Linux package managers. If you are interested in putting together such a release, please feel free to contact us (via issue tracker, or the Stackage mailing list).

### Some details

Disclaimer: I'm not informed enough on stackage.

But I think the goals of stackage, in particular of [LTS Haskell](https://www.fpcomplete.com/blog/2014/12/backporting-bug-fixes), while different, are similar enough. 
AFAIK, however, stackage does not coexist well with hackage. But since. with hackage, people recommend using separate sandboxes for each program... having a Homebrew Stackage sandbox, somewhere inside /usr/local/, would probably be an acceptable tradeoff. (I suspect some people might dislike using Stackage, but I'd assume all of those can install Haskell software by hand, without Homebrew).

I'm also not sure one should keep that sandbox around safely or if it needs some cache invalidation (as I'd guess)*. IIUC, the sandbox stays valid forever for any Stackage LTS point release (e.g., 7.1).

> For Haskell software on this list it could be pulled in as an dependency.

That sounded confusing, because installing "stackage" just means downloading a cabal config file pointing to a different hackage-like repo. However, it would make sense to have a "stackage" formula matching a Stackage LTS release, and to clean the cache when the formula is updated.

Some might want a flag for this package, to *not* keep the sandbox around. Since Haskell software is statically linked, binaries are huge, and sandboxes just contain copies of these huge binaries (which should move elsewhere) and of libraries (which aren't needed when running the program, only when compiling new ones that happen to share dependencies).

*Just to recap the standard cabal issue at hand: What if package Z depends on package A, A depends on package B, and at some point stackage upgrades package B (assuming all packages are libraries)? You'd need to rebuild A against B, creating a (typically) incompatible version of A that has the same version number and hence replaces the old install of A; however, Z is compiled against the old A, and breakage follows (when compiling packages linking against Z and A).

**Comment by mikemcquaid** [comment]
I'm not really sure this is a Homebrew bug or something we can fix. We'll review pull requests to improve the situation, of course.

**Comment by Blaisorblade** [comment]
@mikemcquaid Things changed. Reproducible builds are now guaranteed by using the `stack` command (see `haskell-stack` formula) instead of the `cabal` command, and doing some more work to convert the build.

Hence, I _propose to solve the issue_ by encouraging formula authors to switch to `stack`, somehow — say by *deprecating* `cabal`-based builds, but you know your community.

# Details
## Is this enough?
Reproducible builds seem the main issue here (see 1st paragraph of OP):

> Due to new versions of libraries uploaded to Hackage, currently working Formulas can suddenly fail. To avoid this, it would be resonable to pin the versions used to build a software, similar to how it is done with ruby gems and python modules.

In fact, reproducible builds are also possible with `cabal` used in a certain way (with `cabal freeze`), except nobody knew, while `stack` makes builds reproducible by default.

## Are all packages supported?
Furthermore, `stack` can be used whether the package is on Stackage or not — in the latter case one needs just a bit more work to find a suitable install plan.

## Is stack itself supported?

Most of the Haskell community moved to Stack, and it seems especially suited for repeatable builds (as in our scenario).

**Comment by mikemcquaid** [comment]
@Blaisorblade I believe there was some previous discussion that @ilovezfs was involved with around this topic. Could you create a pull request to tray and convert, say, one formula?

**Comment by Blaisorblade** [comment]
@mikemcquaid Sorry, I don't have significant time right now...
