### ISSUE TITLE
Suggestion on qca.rb

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/homebrew#35443]
Hi to make QtCreator work smoothly

I need to link
/usr/local/homebrew/Cellar/qca/2.1.0/include/QtCrypto to ../lib/qca.framework/Headers

Can you kindly add that to the rb file?
If possible I would also like to print some message for users, so that they'll know how to use the library with QtCreator, something like this,

To use the QCA library with homebrew Qt, you may add the following lines to the project file:
INCLUDEPATH += /usr/local/homebrew/Cellar/qca/2.1.0/include/
LIBS += -F/usr/local/homebrew/Cellar/qca/2.1.0/lib -framework qca
(Replace the 2.1.0 with installation path ..)

Thanks!

**Comment by CaledoniaProject** [comment]
FYI It took me so long to make this work and its not available online ..

**Comment by mikemcquaid** [comment]
Could you try and open a pull request and explain how to reproduce the bug that this is fixing? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by CaledoniaProject** [comment]
Oh sure, I'll do a pull-request. Closing this one.

**Comment by dakcarto** [comment]
@CaledoniaProject I'm not sure why this would be needed (why would `<prefix>/include/QtCrypto` be needed if QCA is already a framework with proper Headers?). I am using the `qca` formula's framework just fine in my project.pro in Qt Creator with:

```
mac {
  INCLUDEPATH += $(HOMEBREW_PREFIX)/opt/qca/lib/qca.framework/Headers
  LIBS += -F$(HOMEBREW_PREFIX)/opt/qca/lib -framework qca
}
```
or, if you expect `qca` to _always_ be linked in Homebrew, then just:

```
INCLUDEPATH += $(HOMEBREW_PREFIX)/lib/qca.framework/Headers
LIBS += -F$(HOMEBREW_PREFIX)/lib -framework qca
```

Then, set `HOMEBREW_PREFIX` in the Build Environment of your Qt Creator project's Build/Run setup.

These are basic qmake project.pro settings for building on Mac ([see also](http://qt-project.org/doc/qt-4.8/qmake-platform-notes.html)) and aren't really relevant to the output of a formula's `caveats`.

Also, you have installed Homebrew to a custom prefix of `/usr/local/homebrew`, which will require you to define many build dependency resources manually in your build setup files, since build tools will not be looking there by default.
