### ISSUE TITLE
(Error: Empty archive) `gettext` on 10.9.5

### ISSUE THREAD

**Issue by miogalang** [Homebrew/homebrew#35591]
I am trying to install `gettext` on 10.9.5. I used to have it and was installed fine but recently while updating php has to try a reinstall and that is where the install failures occured.

	$ brew -v install --debug gettext
	Homebrew 0.9.5
	/opt/boxen/homebrew/Library/brew.rb (Formulary::FormulaLoader): loading /opt/boxen/homebrew/Library/Formula/gettext.rb
	Warning: You have an outdated version of /usr/bin/install_name_tool installed.
	This will cause binary package installations to fail.
	This can happen if you install osx-gcc-installer or RailsInstaller.
	To restore it, you must reinstall OS X or restore the binary from
	the OS packages.
	/opt/boxen/homebrew/Library/brew.rb (Formulary::FormulaLoader): loading /opt/boxen/homebrew/Library/Formula/xz.rb
	Warning: Building source; cellar of gettext's bottle is /usr/local/Cellar
	/opt/boxen/homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /opt/boxen/homebrew/Library/Formula/gettext.rb
	/opt/boxen/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /opt/boxen/homebrew/Library/Formula/xz.rb
	==> Downloading http://ftpmirror.gnu.org/gettext/gettext-0.19.4.tar.xz
	/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.9.5) http://ftpmirror.gnu.org/gettext/gettext-0.19.4.tar.xz -C 0 -o /opt/boxen/cache/homebrew/gettext-0.19.4.tar.xz.incomplete --connect-timeout 5
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	100   331  100   331    0     0    198      0  0:00:01  0:00:01 --:--:--   198
	100 6500k  100 6500k    0     0   283k      0  0:00:22  0:00:22 --:--:--  356k
	==> Verifying gettext-0.19.4.tar.xz checksum
	Error: Empty archive
	/opt/boxen/homebrew/Library/Homebrew/download_strategy.rb:198:in `chdir'
	/opt/boxen/homebrew/Library/Homebrew/download_strategy.rb:178:in `stage'
	/opt/boxen/homebrew/Library/Homebrew/resource.rb:89:in `block in unpack'
	/opt/boxen/homebrew/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
	/opt/boxen/homebrew/Library/Homebrew/resource.rb:88:in `unpack'
	/opt/boxen/homebrew/Library/Homebrew/resource.rb:81:in `stage'
	/opt/boxen/homebrew/Library/Homebrew/formula.rb:736:in `stage'
	/opt/boxen/homebrew/Library/Homebrew/formula.rb:382:in `brew'
	/opt/boxen/homebrew/Library/Homebrew/build.rb:114:in `install'
	/opt/boxen/homebrew/Library/Homebrew/build.rb:185:in `<main>'

I keep on getting the error `Error: Empty archive`
I ran `brew update` before this with no issues.

here is my `brew config`:

	$ brew config
	HOMEBREW_VERSION: 0.9.5
	ORIGIN: https://github.com/Homebrew/homebrew.git
	HEAD: 659b14c4d2eb5c6cf2fc75d5026f0672735563fb
	Last commit: 23 minutes ago
	HOMEBREW_PREFIX: /opt/boxen/homebrew
	HOMEBREW_CELLAR: /opt/boxen/homebrew/Cellar
	CPU: quad-core 64-bit ivybridge
	OS X: 10.9.5-x86_64
	Xcode: 6.1.1
	CLT: 6.1.1.0.1.1416017670
	Clang: 6.0 build 600
	X11: 2.7.7 => /opt/X11
	System Ruby: 2.0.0-p481
	Perl: /usr/bin/perl
	Python: /opt/boxen/homebrew/bin/python => /opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /opt/boxen/rbenv/shims/ruby

and here is my `brew doctor`:

	$ brew doctor
	Please note that these warnings are just used to help the Homebrew maintainers
	with debugging if you file an issue. If everything you use Homebrew for is
	working fine: please don't worry and just ignore them. Thanks!

	Warning: You have an outdated version of /usr/bin/install_name_tool installed.
	This will cause binary package installations to fail.
	This can happen if you install osx-gcc-installer or RailsInstaller.
	To restore it, you must reinstall OS X or restore the binary from
	the OS packages.

	Warning: /opt/boxen/homebrew/share/python is not needed in PATH.
	Formerly homebrew put Python scripts you installed via `pip` or `pip3`
	(or `easy_install`) into that directory above but now it can be removed
	from your PATH variable.
	Python scripts will now install into /opt/boxen/homebrew/bin.
	You can delete anything, except 'Extras', from the /opt/boxen/homebrew/share/python
	(and /opt/boxen/homebrew/share/python3) dir and install affected Python packages
	anew with `pip install --upgrade`.

	Warning: Your Homebrew is not installed to /usr/local
	You can install Homebrew anywhere you want, but some brews may only build
	correctly if you install in /usr/local. Sorry!

	Warning: Some installed formula are missing dependencies.
	You should `brew install` the missing dependencies:

	    brew install gettext

	Run `brew missing` for more details.

Upon further investigation. I am unsure if it is an issue with the sha1 because from the formula I found this:

    sha1 "1720f95c4392d4f26d60f39c5722f99e91b09330" => :mavericks

when I check the downloaded file.

	$ shasum -a 1 /opt/boxen/cache/homebrew/gettext-0.19.4.tar.xz
	16c90342f3a59c7df364ebb3209a48be42b7ffd9  /opt/boxen/cache/homebrew/gettext-0.19.4.tar.xz

I am not too versed in this topic so I am unsure if this is the issue. I tried manually editing the file to see if that could work to no avail so it might just be speculation on my part.

Is this a problem possibly with the tar file?

**Comment by DomT4** [comment]
The checksums should be different in this case:

` sha1 "1720f95c4392d4f26d60f39c5722f99e91b09330" => :mavericks ` is from the ` bottle ` field, and doesn't apply unless you're using a bottle from Homebrew, which in this case you're not because your Homebrew isn't based in ` /usr/local ` and ` gettext `'s bottle isn't ` cellar :any `.

Curiously, ` 16c90342f3a59c7df364ebb3209a48be42b7ffd9 ` is actually the correct ` gettext ` checksum. Given the ` Empty archive ` issue though, I wondered if the checksum was going to be off too, which would be expected if the archive was just bunk.

Your ` brew ` install is pretty custom though, in terms of location and the ` install_name_tool ` problem, so I'm going to let one of the maintainers offer comments here :).

**Comment by miogalang** [comment]
Yeah my brew install is at `/opt/boxen/homebrew` because I used https://boxen.github.com/ to set up my computer.

Honestly I am not too versed in actually brewing, so I am unsure what some of the stuff you are referring to means.

 I actually tried using older versions of gettext by checking out older formulas only to get the same error.

To be specific I tried versions `0.19.4`, `0.19.3_1`, `0.19.3`, and `0.19.2`

**Comment by DomT4** [comment]
> Honestly I am not too versed in actually brewing, so I am unsure what some of the stuff you are referring to means.

Apologies for the jargon. ` bottle ` = binary package. Since Homebrew's very own HAL (@BrewTestBot) came online, Homebrew has been building things for each OS, taking the end product, the compiled binaries, libs, headers, etc, wrapping them up in a tarball and hosting them on Sourceforge. 

The bot also generates a SHA1 checksum for each bottle, to ensure the bottle doesn't change between SourceForge and the end user.

Then, typically, when a user does ` brew install gettext ` it grabs that precompiled package from SourceForge, checks the checksum for validity and installs it in the expected location if all is good. This allows Homebrew to save users lengthy build times, which for the larger packages like ` gcc ` or ` qt ` can be hours long, and turns them into a simple untar, all of which is automated.

` install_name_tool ` is a small blob that usually ships with the ` Xcode ` install, but as mentioned in the ` brew doctor ` is packaged in some external packages as well, and those external packages can break things, sadly.

**Comment by miogalang** [comment]
Thanks @DomT4. That is actually extremely informative.

**Comment by jacknagel** [comment]
Is xz installed?

**Comment by miogalang** [comment]
Thank you @jacknagel. Awesome work! Thank you for the quick reply.

Steps I did to fix this.

1. Reinstall OS X
2. `brew reinstall xz`
3. `brew install gettext`
