### ISSUE TITLE
Can't run sox after installing it?

### ISSUE THREAD

**Issue by csu** [Homebrew/homebrew#35643]
I installed sox via `brew install sox`. Running `sox file1.wav file1.dat` doesn't work. I get a command not found error:
```
csu:project1$ sox
-bash: sox: command not found
```

**Comment by mistydemeo** [comment]
What happens if you try to run:

```
brew link sox
```

**Comment by csu** [comment]
Found the binary at `/usr/local/Cellar/sox/14.4.1_1/bin/sox`. Does not appear to be in PATH.

**Comment by csu** [comment]
```
csu:project1$ brew link sox
Linking /usr/local/Cellar/sox/14.4.1_1...
Error: Could not symlink bin/play
Target /usr/local/bin/play
is a symlink belonging to play22. You can unlink it:
  brew unlink play22

To force the link and overwrite all conflicting files:
  brew link --overwrite sox

To list all files that would be deleted:
  brew link --overwrite --dry-run sox
csu:project1$
```

**Comment by mistydemeo** [comment]
It looks like the `play22` and `sox` formulae conflict, because they both install binaries by the same names. You have a couple of options:

1) Add `/usr/local/opt/sox/bin` to your PATH, and run sox without linking it to `/usr/local`.
2) Delete one of the two `play` tools, then relink both packages.

**Comment by csu** [comment]
Got it! Thanks! Closing now.
