### ISSUE TITLE
ansible mavericks bottle 1.8.2 different from http://releases.ansible.com/ansible/

### ISSUE THREAD

**Issue by iheitlager** [Homebrew/homebrew#35914]
The ansible mavericks bottle 1.8.2 is slightly different from the actual release from http://releases.ansible.com/ansible/

All python executables, in the files bin/ansible-* in the bottle are set the `#!/usr/bin/python` while the true release is set to `#!/usr/bin/env python` .  therefore the homebrew release is using the native python interpreter instead of my brew deployed python. This causes issues with additional packages (httplib2). 

I have checked the original formula https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ansible.rb but that is also pointing to releases.ansible.com. 

So I have no clocking foo why the bottle is different, nor what to propose to update

![screen shot 2015-01-15 at 21 40 44](https://cloud.githubusercontent.com/assets/864490/5766111/32a42d60-9cff-11e4-8851-69f42f2c3ec2.png)

![screen shot 2015-01-15 at 21 41 14](https://cloud.githubusercontent.com/assets/864490/5766118/449a08d2-9cff-11e4-9ec9-3ff8869c5a8a.png)

![screen shot 2015-01-15 at 21 41 54](https://cloud.githubusercontent.com/assets/864490/5766132/5aa95132-9cff-11e4-8b02-bc2cbf10c0cb.png)

**Comment by tdsmith** [comment]
This is intentional (and occurs because of the way pip writes shebangs during installation); if you need to use ansible with your own python, please install it with pip. Sorry!

Your other option is to install your additional packages to the /Library site-packages directory, which all framework python builds should add to sys.path.
