### ISSUE TITLE
Error installing llvm 3.5.1 --with-clang on Yosemite

### ISSUE THREAD

**Issue by jtbandes** [Homebrew/homebrew#36113]
I'm getting the following errors ([02.make](https://gist.githubusercontent.com/anonymous/2590be258679bdd6c1fa/raw/d30cb909f21ef5b60f12c1b5d0dba292f91d926b/02.make) — [full logs](https://gist.github.com/anonymous/2590be258679bdd6c1fa)) when trying to `brew install llvm --with-clang` on Yosemite (10.10.1).

```
dyld: Library not loaded: /usr/local/Cellar/llvm/3.5.1/lib/libLLVM-3.5.dylib
  Referenced from: /private/tmp/llvm-JGfxdt/llvm-3.5.1.src/Release+Asserts/bin/clang
  Reason: image not found
/bin/sh: line 1: 25596 Trace/BPT trap: 5       /private/tmp/llvm-JGfxdt/llvm-3.5.1.src/Release+Asserts/bin/clang -arch $arch -c -integrated-as /private/tmp/llvm-JGfxdt/llvm-3.5.1.src/projects/compiler-rt/make/platform/clang_darwin_test_input.c -isysroot /private/tmp/llvm-JGfxdt/llvm-3.5.1.src/projects/compiler-rt/SDKs/darwin -o /dev/null > /dev/null 2> /dev/null
warning: clang_darwin.mk: dropping arch 'i386' from lib 'eprintf' (clang does not support it)

...snip...

make/platform/clang_linux.mk:16: *** "unable to infer compiler target triple for /private/tmp/llvm-JGfxdt/llvm-3.5.1.src/Release+Asserts/bin/clang".  Stop.
make[4]: *** [BuildRuntimeLibraries] Error 2
rm /private/tmp/llvm-JGfxdt/llvm-3.5.1.src/Release+Asserts/lib/clang/3.5.1/lib/macho_embedded/.dir /private/tmp/llvm-JGfxdt/llvm-3.5.1.src/Release+Asserts/lib/clang/3.5.1/lib/darwin/.dir
make[3]: *** [compiler-rt/.makeall] Error 2
make[2]: *** [all] Error 1
make[1]: *** [clang/.makeall] Error 2
make: *** [all] Error 1
```

I suspect this is related to #32566, and possibly caused by changes in https://github.com/Homebrew/homebrew/commit/3099fa4d2c4f0718f6dc6802cfdc4b1daec38124. When I remove the `patch :DATA` line, the `brew install` succeeds, but then I experience the original problem from #32566 when I try to run an executable that I linked with libclang.

**Comment by jacknagel** [comment]
I removed the problematic addition in 3288c4f and 12bb8ab. I'll have to figure out how to make it work with 3099fa4.

**Comment by jtbandes** [comment]
Perhaps there is some flag that needs to be passed to make dyld recognize `/usr/local/opt/llvm/lib`? Otherwise, I would think `@rpath` or something similar is the right approach, rather than using an absolute path as was done in 3099fa4d2c4f0718f6dc6802cfdc4b1daec38124.

**Comment by jacknagel** [comment]
The problem here is only that the built clang (`/private/tmp/llvm-JGfxdt/llvm-3.5.1.src/Release+Asserts/bin/clang`) is being used before the libraries that it references are installed. That is, `/usr/local/Cellar/llvm/3.5.1/lib/libLLVM-3.5.dylib` doesn't exist yet, because `make install` has not yet been called.

>Otherwise, I would think @rpath or something similar is the right approach, rather than using an absolute path as was done in 3099fa4.

The entire point of 3099fa4 is that users do not have to set the rpath, so I don't think that's a good solution.

MacPorts is installing the compiler-rt components and applying the same patch, so I know that it can be made to work.

Anyway, I've removed compiler-rt from the build for the time being, so `brew install llvm --with-clang` is working now.

**Comment by jtbandes** [comment]
I suppose absolute paths are safe as long as the libraries are never moved on disk? Would an executable built with libclang continue to work if it were moved to another machine with those libraries in different locations?

**Comment by jtbandes** [comment]
My understanding of the dynamic linker is limited, but can't `-rpath /some/path` be passed when linking libclang, and then users wouldn't have to pass it in themselves?

**Comment by jacknagel** [comment]
>My understanding of the dynamic linker is limited, but can't -rpath /some/path be passed when linking libclang, and then users wouldn't have to pass it in themselves?

If you can figure out how to get the llvm buildsystem to do this, by all means, please do so and send a pull request.

Otherwise, we're working within the constraints of the (hugely complicated) llvm buildsystem here, and doing the best we can. Making the resultant compiler produce relocatable executables is not super high up on my priority list at this time.

**Comment by jacknagel** [comment]
I think there is some miscommunication here.

I'm pretty sure user-compiled executables had an absolute linkage to `libclang.dylib` before and after 3099fa4. The change made in 3099fa4 fixed a problem in libclang.dylib's own linkage to libLLVM.dylib:

```
dyld: Library not loaded: @rpath/libLLVM-3.5.dylib
  Referenced from: /usr/local/opt/llvm/lib/libclang.dylib
  Reason: image not found
Trace/BPT trap: 5
```

Whether or not libclang.dylib uses `@rpath` or an absolute path to libLLVM should not affect how user-compiled executables are linked.

**Comment by tamird** [comment]
Is this good to close?
