### ISSUE TITLE
ENV["HOMEBREW_ARCHFLAGS"] is nil, causing NoMethodError

### ISSUE THREAD

**Issue by lvh** [Homebrew/homebrew#36217]
I'm trying to create a formula for [lfe](http://lfe.io). This is my first formula.

`make compile` works fine outside brew. I did `brew create`, edited the formula, and am now doing `brew install -di lfe`. I get the following exception when doing `make compile` inside that interactive install environment (truncated):

```
Compiling c_src/lfeexec.c
/usr/local/Library/ENV/4.3/clang:241:in `archflags': undefined method `split' for nil:NilClass (NoMethodError)
	from /usr/local/Library/ENV/4.3/clang:220:in `cflags'
	from /usr/local/Library/ENV/4.3/clang:106:in `args'
	from /usr/local/Library/ENV/4.3/clang:334:in `<main>'
ERROR: compile failed while processing /private/tmp/lfe-AKG7YN/lfe-0.9.0: rebar_abort
```

Full output both inside the environment and out is available [in this gist](https://gist.github.com/lvh/8ad7e6dac535d0d80846).

I started debugging this. The `Makefile` just calls `cc`, which is something else in the interactive environment than outside of it. Specifically, inside, it's `/usr/local/Library/ENV/4.3/cc`, which is leads to that Ruby script from which I saw the traceback. [`archflags` basically just does](https://github.com/Homebrew/homebrew/blob/master/Library/ENV/4.3/cc#L241):

```ruby
  def archflags
    ENV["HOMEBREW_ARCHFLAGS"].split(" ")
  end
```

So, to get that error, `ENV["HOMEBREW_ARCHFLAGS"]` has to be nil, which means that environment variable is unset. However, running `env`, it's definitely set. Manually running with `env HOMEBREW_ARCHFLAGS= make` (which is the `fish` way of spelling "run make with that env var as the empty string", I get exactly the same error. If I manually set it to be just a single space (so `env HOMEBREW_ARCHFLAGS=" " make`), it works absolutely fine, so setting that is doing something. The best explanation I have is that something is throwing away all environment variables that are set to empty strings, but that makes no sense at all!

The thing is, I don't understand how this setup could ever work for compiling any C source. None of this is specific to the formula I'm trying to build...

**Comment by jacknagel** [comment]
>The best explanation I have is that something is throwing away all environment variables that are set to empty strings, but that makes no sense at all!

Does the build use the `rebar` tool? If so, this is exactly what is happening.

**Comment by lvh** [comment]
Oh, wow. In that case, yes, that's why. Is there precedent in homebrew for how to resolve this?

**Comment by lvh** [comment]
(I did a quick `ag, but only found something about running in a git repo.)

```
Formula/disco.rb
32:    # Disco's "rebar" build tool refuses to build unless it's in a git repo, so
34:    system "git init && git add master/rebar && git commit -a -m 'dummy commit'"
```

**Comment by dch** [comment]
copying in my notes from #erlang-lisp IRC channel so they're not lost in the ether.

- https://gist.github.com/dch/6274ded6104e8188fe1b is a partial solution - directly calling rebar for compilation is IMO simplest and it DTRT for lfeexec.c too
- this gets us to https://gist.github.com/dch/26f23b3006074b5d5922 but needs to alter `ERL_LIBS`
- https://github.com/lfe/lfe/blob/master/bin/lfe#L18-L26 is where the problem lies and should be able to cope with an absolute path and not just a relative one, which will help `lfe-test` run as well

/cc @rvirding @oubiwann for shellscript inspiration

**Comment by rvirding** [comment]
You have found the problem but not the cause. My lfe script explicitly assumes the ebin directory is directly under the lfe directory and not anywhere else, check L68. I am now reworking the script so that is use ERL_LIBS instead which should solve the problem as it will then automatically find lfe in the lib directory. I think.

/cc @oubiwann @rvirding
