### ISSUE TITLE
xulrunner formula no longer up-to-date

### ISSUE THREAD

**Issue by icoach** [Homebrew/homebrew#36348]
Latest release source contains newer xulrunner-35.0.1.source.tar.bz2

**Comment by mikemcquaid** [comment]
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by icoach** [comment]
Ok, I have tried, however I am not a developer... I followed instructions, updated URL and hash, but there  was an error during build (I am running Lion).  
```
==> make -f client.mk build

*** Fix above errors and then restart with               "/usr/bin/make -f client.mk build"
make[2]: *** [configure] Error 1
make[1]: *** [/private/tmp/xulrunner-L9ZheR/mozilla-release/objdir/Makefile] Error 2
make: *** [build] Error 2
```
Seems to be related to #33558

**Comment by skycaptain** [comment]
@icoach: your error is related to #33558. but that issue is fixable. i'm currently preparing a comment.

But after sucessfully building, xulrunner will crash with "Couldn't load XPCOM". There are some issues with the new app signing on 10.9.5 and 10.10.
https://bugzilla.mozilla.org/show_bug.cgi?id=1105044
http://hearsum.ca/blog/upcoming-changes-to-mac-package-layout-signing.html

I think the only thing we could do is to wait until the mozilla developers have resolved that issue.

**Comment by jacknagel** [comment]
folding this into #33558
