### ISSUE TITLE
Make `brew fetch --retry` the default

### ISSUE THREAD

**Issue by mikemcquaid** [Homebrew/homebrew#36732]
If you're not aware of what it does exactly: if a checksum match fails it'll delete the cached file and retry the download. @Homebrew/owners thoughts?

**Comment by DomT4** [comment]
Will it retry the download using the ` url ` or will it fallback on the ` mirror ` if one is available, out of interest?

**Comment by mikemcquaid** [comment]
Not sure.

**Comment by DomT4** [comment]
It'd be good if we could fallback on the mirror. Might guard against URL failures for upstream downtime a little better - Although if Homebrew moves away from SF the main use case of that fallback wouldn't be an issue any more.

**Comment by jacknagel** [comment]
Falling back to a mirror happens at a lower level than this code, so it will always happen regardless of this feature.

**Comment by DomT4** [comment]
Oh, neat. I presume we just weren't seeing much of that because SF formulae rarely have additional mirrors?

**Comment by jacknagel** [comment]
The mirror fallback only happens if the download fails, not on checksum mismatches.

**Comment by DomT4** [comment]
I could potentially just be being stupid here, so apologies, but I thought checksum mismatches is what Mike was talking about in his original comment? I presumed he was talking about doing ` brew install blah => blah downloads from url => checksum mismatch discovered => brew deletes file => brew re-downloads file and checks again `. I was pondering if we could insert a stage where it falls back on the mirror if the formulae has one, rather than just pulling from the ` url ` again. Feel free to erase my comments if I'm completely getting my wires crossed here.

**Comment by jacknagel** [comment]
I am just saying that `--retry` is an entirely separate feature from mirrors. `--retry` does exactly what Mike says it does; mirrors are a different thing, that only take effect if the actual download part fails (due to some kind of network error).

**Comment by chdiza** [comment]
I suppose that I would like no cache-file deletion to occur, in the special case where no checksum is defined in the formula.  This will help keep brewing from custom formulas (where sometimes one needs to just forget about the checksum) free of pitfalls.

**Comment by mikemcquaid** [comment]
Spent some time on this but it's harder than I expected so passing on it.
