### ISSUE TITLE
Can't install bottles from SourceForge, SHA1 mismatch and broken certs?

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew#36865]
Brand new Mac running OS X 10.10.1, no other configuration except having installed Homebrew through the default instructions.

```
localhost:~ werner$ brew install ffmpeg --with-faac --with-fdk-aac --with-ffplay --with-fontconfig --with-freetype --with-frei0r --with-libass --with-libbluray --with-libcaca --with-libquvi --with-libsoxr --with-libssh --with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools --with-webp --with-x265 --with-faac
==> Installing dependencies for ffmpeg: lame, libvo-aacenc, xvid, faac, libpng, freetype, fontconfig, libogg, lib
==> Installing ffmpeg dependency: lame
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/lame-3.99.5.yosemite.bottle.1.tar.gz

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "lame"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/lame-3.99.5.yosemite.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sourceforge.net/sourceforge/lame/lame-3.99.5.tar.gz
Already downloaded: /Library/Caches/Homebrew/lame-3.99.5.tar.gz
Error: SHA1 mismatch
Expected: 03a0bfa85713adcc6b3383c12e2cc68a9cfbf4c4
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/lame-3.99.5.tar.gz
To retry an incomplete download, remove the file above.
```

Brew version 0.9.5. 

I already went to `https://downloads.sourceforge.net/` in Safari and checked to always trust the certificate that they somehow screwed up. And I rebooted too.

Any workarounds?

**Comment by slhck** [comment]
Hm, seems to be a duplicate of 36861

**Comment by DomT4** [comment]
Sourceforge is having some downtime. Homebrew is working on mitigating this problem in future, but there's no instant solution other than to wait out Sourceforge's downtime alas. Sorry!

**Comment by JHKennedy4** [comment]
Same here

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "ctags"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/ctags-5.8.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sourceforge.net/ctags/ctags-5.8.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 482da1ecd182ab39bbdc09f2f02c9fba8cd20030
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/ctags-5.8.tar.gz
To retry an incomplete download, remove the file above.
rake aborted!
Command failed with status (1): [brew install ctags ...]
/Users/john/Public/maximum-awesome/Rakefile:9:in `brew_install'
/Users/john/Public/maximum-awesome/Rakefile:155:in `block (2 levels) in <top (required)>'
/Users/john/Public/maximum-awesome/Rakefile:233:in `block in <top (required)>'
Tasks: TOP => install:ctags
(See full trace by running task with --trace)

**Comment by slhck** [comment]
@DomT4 Seems crazy to be so dependent on SF—wouldn't even GitHub be available for storing bottles, or *some* other service?

**Comment by chrisopedia** [comment]
You can get around the broken certs by opening up Soundforge in Safari and accepting the certificate or changing the trust level to "Always Trust" but still no hope with the SHA1 mismatch.

**Comment by mikemcquaid** [comment]
> @DomT4 Seems crazy to be so dependent on SF—wouldn't even GitHub be available for storing bottles, or some other service?

@slhck That's not helpful. I'm working on it and I'm not paid to do so.

**Comment by slhck** [comment]
@mikemcquaid I was just curious as to why SF was chosen or what would (technically) prevent another service from being used. I just don't know what is planned and what the circumstances are, hence my question. I'm just interested. I've never blamed anyone for this.

**Comment by DomT4** [comment]
@slhck Sourceforge provides a CDN, whereas Github does not. This matters less for people based in the US, but anyone outside the US can face not insignificant lag and other issues. 

Sourceforge also provides storage and content delivery for what is probably north of 100GB worth of Homebrew bottles, at no cost to the project.

They've been pretty invaluable, despite the recent downtime. The maintainers are looking at alternatives already, which you can keep track of progress on in #36710. It's an awful lot of work to move the project elsewhere, but Mike and the others are working on it :).

**Comment by slhck** [comment]
Thanks, @DomT4, that's what I wanted to know.

**Comment by slhck** [comment]
Seems to be functional again.
