### ISSUE TITLE
People find it very hard to install Homebrew because the instructions are so far down the page.

### ISSUE THREAD

**Issue by melodykramer** [Homebrew/homebrew#36970]
Hi! A lot of people I know are confused by your homepage, because they think they have to type in 'brew install wget' to install homebrew. It's not clear. Is it possible to move the actual instructions up, or indicate that the terminal commands at the top of the page are not the instructions? Thank you!

Mel

**Comment by mikemcquaid** [comment]
Thanks for the feedback @melodykramer, I'll have a look and think.

**Comment by melodykramer** [comment]
No prob! Keep up the good work @mikemcquaid

**Comment by mikemcquaid** [comment]
Thanks for your kind words!

**Comment by trevormcleod** [comment]
For what it's worth, I have also seen a lot of people get confused per @melodykramer 's point.

P.S. Homebrew rocks! Use it all the time :)

**Comment by skycaptain** [comment]
+1. Indeed the text is misleading. You may also rethink styling the installation claim as a hero element and rewrite the claim for the first example to s.th like `Using Homebrew is simple. After installing, you can install all the stuff you need that Apple didn’t.`

**Comment by chdiza** [comment]
While I never got misled myself, this was *only* because I happened to already know what `wget` was.

It may help to put the "Install Homebrew" portion right at the top, but I think would be an equally helpful alternative if the top said "Homebrew installs...Apple didn't, **for example, to install wget, do:**", and then make it clear that that's what the `brew install wget` box is attached to.  Then the installation instructions can remain near the bottom.

**Comment by DomT4** [comment]
Proposed a fairly basic rejiggle, with new headers in https://github.com/Homebrew/homebrew.github.io/pull/54

**Comment by DomT4** [comment]
Discussion now in https://github.com/Homebrew/homebrew.github.io/pull/55 because I'm an idiot :smile_cat:
