### ISSUE TITLE
Suggestion: official Homebrew GPG key

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew#37074]
As I mentioned in the mail list, I deeply suggest Homebrew has its own official GPG key(under the email address of security@brew.sh). This key can be helpful to:
* Verify the authenticity of security notification by Homebrew.
* Encrypt messages to send to Homebrew.

I know we don't have too many needs on this. But a GPG key is pretty much industry standard.

Sorry to resend this again as there is no response on the mail list.

**Comment by xu-cheng** [comment]
Ping @DomT4 for security related advice.

**Comment by DomT4** [comment]
Makes sense to me at least. We haven't had many major vulnerabilities yet, but it'd be good to have a more secure capability to accept vulnerability reports/bugs/etc.

I don't know how well versed the maintainers are in GPG, and securely maintaining a cross-computer GPG key can be fun as GPG has a few measures in place to prevent secret key sharing. If one person primarily maintains the security mailing list it's nice and easy, but presumably every maintainer would need access. There's a [decent tutorial](http://www.debuntu.org/how-to-importexport-gpg-key-pair/) on key sharing here to avoid rambling on my part.

Ease of use depends largely on which mail clients the maintainers use to handle the list. Various clients handle it better, some not so much.

General recommendations are to create short-term GPG keys, revoke them at the end of that short period and generate new keys, but almost nobody does because it's a nightmare. Generating a single, strong key with an expiration period of upwards of a year is strong enough for Homebrew's purposes.

Would probably recommend sticking the GPG long fingerprint on the main README here, and then stick the public key into ` share/doc/homebrew/security ` or similar.

**Comment by tdsmith** [comment]
Thanks, Dominyk; I was going to ask about best practices for managing keys owned by a team. If we do this I probably wouldn't mind anointing a particular (senior?) maintainer as security czar.

Having a PGP key for signatures seems most useful if everyone knows when and why we would use it. Maybe it's worth thinking about what security-related promises Homebrew makes and when and how would we issue a security bulletin; to my knowledge, Homebrew never has.

FWIW, we haven't received an email to security@ yet. If someone emailed security@ and wanted to have an encrypted conversation, Misty and I are on Keybase; possibly others have keys published somewhere.

**Comment by DomT4** [comment]
Yeah, the initial fun post-setup is getting the key phrase securely transferred. In person is ideal, but obviously not very practical given the differing locations of Homebrew's maintainers. But once you work out how to transfer the key phrase and the private keys securely everything after that is *relatively* simple (Or at least, as simple as GPG ever is).

Personally, using the key to sign security announcements and reply to any encrypted mail the Security mailing list gets would seem reasonable, and not too much of a burden to work with. As for what would be announced, I'd lean towards A) Vulnerabilities discovered in Homebrew's core code, B) Vulnerabilities discovered in certain packages that we addressed before upstream did (Recent events on this are probably the Pinentry-mac issue and the GPG insecure curl issue some time back). That should keep it relatively minimal.

**Comment by tdsmith** [comment]
We don't have any formal way of deciding whether something is a vulnerability; I think it's not totally obvious. Is there anything that `brew` should never do? "Downloads that occur as a direct result of `brew install` should be verified by TLS, a signature, or a checksum" is probably a good rule; is a failure to follow that policy a vulnerability or an opportunity for hardening? Rhetorically: what are the larger principles governing that reasoning? I think there are a lot of questions like this. I'm sure other packagers have security policies; it would be interesting to compare them. But I see that I have departed from the instant question. :p

An encryption key for receiving security@ correspondence (probably distinct from and less tightly controlled than any key we would eventually use for security announcements) seems reasonable to me; it might be nice to keep things like "hey, here's how to compromise your build server" safe from prying eyes. Probably all maintainers should have it? If whoever generates the key can separate the encryption subkey from the signing master key and distribute only the former, so much the better, I think. Maybe I'm overthinking this.

**Comment by DomT4** [comment]
> We don't have any formal way of deciding whether something is a vulnerability; I think it's not totally obvious.

It's kind of difficult. Most of Debian's security announcements are actually along the lines of *Er, this upstream package was found to have x vulnerability, we've pushed x update to fix it, you should update*, etc. It's hard to compare to the Linux distros in the regards that they handle so much more than we do in terms of supporting more systems, supporting unusual archs, and they ship kernel-level updates which we obviously don't.

So a vulns disclosure or even basic security policy is relatively unheard of in regards to OS X Package Managers. As far as I'm aware, MacPorts doesn't have one; Whilst I don't want to rag on them a lot of their security packages are lacking SSL/TLS links, they still support MD5 in places, and you can still roll around in the glory that is SSLv2 with their OpenSSL.

As far as basic goals go, I'd certainly agree with you. My personal list would be along the lines of:

* Homebrew will use SSL/TLS protected links for homepages, downloads and resources where possible.
* Homebrew's own binary packages, bottles, will always be served over SSL/TLS.
* Homebrew will verify the integrity of packages with a checksum no weaker than SHA1.
* Homebrew does not permit third-party remote code execution during compile.
* Homebrew is actively mandating the use of an up-to-date OpenSSL for Homebrew formulae that require OpenSSL; Usage of the deprecated system version is not permitted. In addition Homebrew will attempt to follow Debian Stable in removing outdated/vulnerable ciphersuites.
* Homebrew will disclose security flaws to upstream developers and fix them as quickly and practically as possible.

That's a little preachy and formal, but there's nothing in there that we're not already working on or have done. I don't think it'd be a bad idea to actually stick something like that in the ` share/doc/homebrew/security ` area.

But yes, I'm afraid I have joined you in wandering off the subject. I apologise :smile_cat:.

> (probably distinct from and less tightly controlled than any key we would eventually use for security announcements)

Are you proposing essentially two GPG team keys here? One for signing, the other for more sensitive encrypted communication? Could work. It seems reasonable to supply it to all the maintainers, although potentially, the question of what to do if a maintainer left is probably worth asking - Would the keys be revoked and regenerated or is the security threat not worth that level of heightened paranoia? *(For the record, I'm not suggesting Homebrew shouldn't trust maintainers, just generally pondering the theoretical what if questions)*.

Presumably going forwards on something like this would require complete maintainer consensus, as otherwise a maintainer could find themselves locked out of the mailing thread/security emails/etc, which isn't ideal. It'll be good to hear Jack/Mike/Misty/Adam/etc on this, and see what the wider thinking is.

**Comment by tdsmith** [comment]
To be clear, my concerns are of the form "what if I'm sloppy about this and I leak the key and someone uses it to impersonate us oh god" but that's probably an exaggerated fear.

**Comment by jacknagel** [comment]
I volunteer to generate the key(s) when we decide on specifics.

**Comment by mikemcquaid** [comment]
Somewhat related: Bintray will let us automatically GPG sign our packages if we ever want to do this.

**Comment by xu-cheng** [comment]
Another thing is related: If wanted, we can use GPG key to sign http://brew.sh and @BrewTestBot on [Keybase](https://keybase.io).

**Comment by DomT4** [comment]
> that's probably an exaggerated fear.

Generate a [revocation cert](https://www.gnupg.org/gph/en/manual/c14.html) after creation. That would pretty much cover such an eventuality.

> Bintray will let us automatically GPG sign our packages if we ever want to do this.

This excites me.

**Comment by xu-cheng** [comment]
tdsmith, Misty and I are all in the keybase. If any other maintainers want to have keybase invitation, I have 9 invitations on my account.

**Comment by DomT4** [comment]
Yeah, I've got 9 as well if there are further needs.

**Comment by DomT4** [comment]
Looking at the way Bintray handles automated ` gpg ` signing, I'd pretty strongly suggest that we use one ` gpg ` key specifically for signing Homebrew binary packages on Bintray, and another for secure communication.

Ideally, we want to insert a way to check the signature of the bottles if the user already has ` gpg ` / `gpg2` available on their system. I've been working on a framework for a while, but it isn't pretty, or as Ruby as Homebrew would like, yet.

**Comment by xu-cheng** [comment]
>  but it isn't pretty, or as Ruby as Homebrew would like, yet.

If you work out a prototype, I think we can help to refactor the code together..

**Comment by xu-cheng** [comment]
Also keep a note before I forget. We should control when the bottle will be signed. Currently, we upload all the bottles from all PR. We need to make sure only bottles from merged PR get signed.

**Comment by DomT4** [comment]
I think Bintray provide an automatically sign everything or automatically sign nothing option. I don't know if there's a particularly fine-grained approach. Might be buried in the API though.

**Comment by xu-cheng** [comment]
Will file get signed during uploading or publishing?

**Comment by xu-cheng** [comment]
There is a API for gpg signing: https://bintray.com/docs/api/#_gpg_sign_a_file . We can put it int `brew pull --bottle`

**Comment by DomT4** [comment]
The documentation suggests during upload. Looks like we can use the [API for some more fine-grained control over signing though](https://bintray.com/docs/api/#_content_signing).

**Comment by DomT4** [comment]
Heh, we posted the same link there I think. Yeah, tucking it into ` brew pull ` is desirable.

**Comment by lloeki** [comment]
Is it really necessary to sign bottles? By homebrew's design choice of using git, one might consider that as long as a formula is signed (with git's Signed-off-by field), then its content (including both the source and bottle hashes) is validated.

**Comment by mikemcquaid** [comment]
@lloeki It would potentially me we could stop embedding bottle blocks in formulae which would make shipping bottles significantly easier.

**Comment by DomT4** [comment]
We also wouldn't lose anything by doing it. There's no real downside for anyone involved, once all the code is in place it'll be an automated affair.

It's not an unheard of situation, plenty of sites publish checksums and GPG sign their packages. It's a stronger verification process, and it's harder to compromise than our current setup. The latter is particularly valuable given how difficult it is to verify a remotely-generated binary hasn't been fiddled with compared to building everything from source locally.

**Comment by chdiza** [comment]
I'm unclear.  Is this going to force everyone to brew gnupg in order to verify sigs if they want to pour bottles?

**Comment by mikemcquaid** [comment]
Probably not, certainly not manually.

**Comment by DomT4** [comment]
I can't speak for Mike, but the general plan is to take advantage of GnuPG where it's present on the system and otherwise skip over the GPG verification of stuff.

**Comment by DomT4** [comment]
Oops. There's Mike. Apologies for the quick double posting :smile_cat:

**Comment by xu-cheng** [comment]
85719820508ce888c1e00559e641cf66e43839b5
