### ISSUE TITLE
pdf-tools failed to build on 10.10.2

### ISSUE THREAD

**Issue by imohan** [Homebrew/homebrew#37265]
Hi,

pdf-tools failed to build here's gist for this issue https://gist.github.com/705519316f6444c5e529

Thank you

regards,

-Inder

**Comment by tdsmith** [comment]
Fixed in upstream: https://github.com/politza/pdf-tools/commit/70feb99dd87b68c4539100a2aa4acc3fc36a9bdb

We accepted a private fork in #28019; we should probably switch the formula to the maintained version.

**Comment by mistydemeo** [comment]
The maintained version doesn't officially support OS X: https://github.com/politza/pdf-tools/issues/38#issuecomment-73091700

**Comment by tdsmith** [comment]
Although the fix in the fork we're using was accepted upstream: https://github.com/politza/pdf-tools/pull/44

**Comment by mistydemeo** [comment]
Doesn't look like the 0.4.0 version builds on OS X do to some GNU cp stuff in the makefile. The buildsystem was completely changed since then; the HEAD build works fine.

**Comment by mistydemeo** [comment]
Given we're using an unofficial fork anyway, how about removing (not boneyarding) for now, with an eye to bringing it back pointing at the original project when 0.5.0 comes out?

**Comment by zbeekman** [comment]
Does this issue manifest itself by printing `couldn’t understand kern.osversion ’14.3.0’` during the make step or am I suffering from a different issue?

**Comment by zbeekman** [comment]
Ok, I went through my logs and compared to the gist posted by @imohan and it seems like I am suffering from the same problem and the `couldn’t understand kern.osversion ’14.3.0’` appears to be unrelated. I took a look at https://github.com/politza/pdf-tools/pull/44 and tried building from source there, but ran into issues there too.

So my question is this: Does the pdf-tools.rb formula work for anyone? Is there a work around to build and install pdf-tools on Mac? If the Formula is broken should it be removed?

Tagging @mistydemeo and @tdsmith because they seem to know what they’re doing.

**Comment by mistydemeo** [comment]
PR for the new release in #39785.

**Comment by mistydemeo** [comment]
New version merged.

**Comment by zbeekman** [comment]
:tada: :pray: :bow:
