### ISSUE TITLE
mongodb fails to build on 10.7

### ISSUE THREAD

**Issue by chris-huxtable** [Homebrew/homebrew#37691]
Despite [mongodb's claims](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/) this formula doesn't build on a 10.7, 64bit machine. 

I don't have the skills myself to fix this, I hope someone can get to it soon.

    ==> Cloning https://github.com/mongodb/mongo-tools.git
    Cloning into '/Library/Caches/Homebrew/mongodb--github.com-mongodb-mongo-tools--git'...
    remote: Counting objects: 1138, done.
    remote: Compressing objects: 100% (907/907), done.
    remote: Total 1138 (delta 187), reused 783 (delta 144), pack-reused 0
    Receiving objects: 100% (1138/1138), 1.79 MiB | 1.32 MiB/s, done.
    Resolving deltas: 100% (187/187), done.
    Note: checking out 'e35a2e87876251835fcb60f5eb0c29baca04bc5e'.
    
    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
    git checkout -b new_branch_name
    
    ==> Checking out tag r3.0.0
    ==> ./build.sh
    ==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.0.0 -j2 --cc=/u
    Checking if C++ compiler "/usr/bin/clang++" is clang... yes
    Checking if C compiler "/usr/bin/clang" is clang... yes
    Checking if C compiler is clang 3.4 (or Apple XCode 5.1.1) or newer...no
    Checking if C++ compiler is clang 3.4 (or Apple XCode 5.1.1) or newer...no
    ERROR: Refusing to build with compiler that does not meet requirements

    READ THIS: https://git.io/brew-troubleshooting

**Comment by adamv** [comment]
Can you also post your `brew --config`? Thanks.

**Comment by mistydemeo** [comment]
Can you try this:

```
brew install gcc
brew install mongodb --cc=gcc-4.9
```

**Comment by chris-huxtable** [comment]
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit core2
OS X: 10.7.5-i386
Xcode: 4.6.3
CLT: 1.0.0.9000000000.1.1249367152
GCC-4.2: build 5666
LLVM-GCC: build 2336
Clang: 4.2 build 425
X11: 2.6.5 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.1/bin/ruby
Java: 1.6.0_65

**Comment by priyankshukla** [comment]
I am also facing same problem..

brew --config
-------------------------
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 89d0188003c4a9d17b90af0c3330f8982aeb37b1
Last commit: 71 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.7.5-x86_64
Xcode: 4.6.3
CLT: N/A
LLVM-GCC: build 2336
Clang: 4.2 build 425
X11: 2.6.5 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65

**Comment by priyankshukla** [comment]
brew install gcc
------------------------
brew install gcc too time consuming and it stucks on the "Installing gcc" part (make bootstrap specially) after downloading all 5 dependencies.

**Comment by lendenmc** [comment]
I've got the same problem (and `brew upgrade mongodb --cc=gcc-4.9` didn't solve it either): 

==> Checking out tag r3.0.1
==> ./build.sh
==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.0.1 -j2 --
Checking if C++ compiler "/usr/bin/clang++" is clang... yes
Checking if C compiler "/usr/bin/clang" is clang... yes
Checking if C compiler is clang 3.4 (or Apple XCode 5.1.1) or newer...no
Checking if C++ compiler is clang 3.4 (or Apple XCode 5.1.1) or newer...no
ERROR: Refusing to build with compiler that does not meet requirements

Here is my config:

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 89d0188003c4a9d17b90af0c3330f8982aeb37b1
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.7.5-i386
Xcode: 4.6.3
CLT: 4.6.0.0.1.1365549073
LLVM-GCC: build 2336
Clang: 4.2 build 425
X11: 2.7.7 => /opt/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/local/opt/pyenv/shims/python => /usr/local/var/lib/pyenv/versions/2.7.9/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.1/bin/ruby
Java: 1.7.0_67

**Comment by ariariel** [comment]
Same problem here. Mac OS 10.7 and GCC compiler is version 4.2.1

Here is the brew config:
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 2ec86641deab37baafe7a5b5adedec3667f7f356
Last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.7-i386
Xcode: 4.2
CLT: N/A
LLVM-GCC: build 2336
Clang: 3.0 build 211
X11: 2.6.3 => /usr/X11
System Ruby: 1.8.7-p249
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65

**Comment by visualcookie** [comment]
Guess I got the same problem over here:

**Error:**
```txt
Error: Homebrew doesn't know what compiler versions ship with your version
of Xcode (6.2). Please `brew update` and if that doesn't help, file
an issue with the output of `brew --config`:
  https://github.com/Homebrew/homebrew/issues

Note that we only track stable, released versions of Xcode.

Thanks!

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
```


**Config:**
```txt
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: (none)
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit sandybridge
OS X: 10.10.2-x86_64
Xcode: 6.2
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
```

**Comment by themicmac** [comment]
PLEASE HELP:
Hi, I've been trying for days now to brew install mongodb but to no avail. When I type the command, I get the following output:
------------------------------------------------------------------------------------------------

==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.0.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/mongodb-3.0.2.tar.gz
==> Cloning https://github.com/mongodb/mongo-tools.git
Updating /Library/Caches/Homebrew/mongodb--github.com-mongodb-mongo-tools--git
==> Checking out tag r3.0.2
==> ./build.sh
==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.0.2 -j8 --cc=/usr/bi
Checking if C++ compiler "/usr/bin/llvm-g++" is GCC... yes
Checking if C compiler "/usr/bin/llvm-gcc" is GCC... yes
Checking if C compiler is GCC 4.8.2 or newer...no
Checking if C++ compiler is GCC 4.8.2 or newer...no
ERROR: Refusing to build with compiler that does not meet requirements

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
mongodb fails to build on 10.7 (https://github.com/Homebrew/homebrew/issues/37691)

------------------------------------------------------------------------------------------------

...And so, I've been trying to update gcc to anything above 4.8.2. But when I try with 
$ brew install gcc49 
I get the following:
-------------------------------------------------------------------------------------------------------------
mkdir common
mkdir common/.deps
config.status: executing default commands
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

--------------------------------------------------------------------------------------------------------------

Here's my brew --config. I cannot upgrade from Snow Leopard as this is a very old computer and does not have a dvd nor can I boot from USB.

--------------------------------------------------------------------------------------------------------------
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 09fdce7318b676eb9005d3001d00f524f8619582
Last commit: 23 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit penryn
OS X: 10.6.8-i386
Xcode: 4.2
CLT: N/A
GCC-4.0: build 5494
GCC-4.2: build 5666
LLVM-GCC: build 2336
Clang: 3.0 build 211
X11: 2.3.6 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /Applications/MAMP/Library/bin/perl
Python: /Applications/MAMP/Library/bin/python => /Applications/MAMP/Library/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65
--------------------------------------------------------------------------------------------------------------

Any advice on what the problem is or hat I am doing wrong would be much helpful. Thank you.

**Comment by hasanein** [comment]
Updating brew database via ```sudo brew update``` followed by ```brew install mongodb``` seem to have resolved the problem and it attempts to download a yosemite-specific version.

**Comment by mikemcquaid** [comment]
Don't do `sudo brew update`. Instead run `sudo chown -R $USER /usr/local` which will fix your permissions issues.

**Comment by slavomirvojacek** [comment]
Try using brew-cask: ```brew cask install mongodb```

**Comment by bronzovik** [comment]
scons fails during clang version check trying to compile test *.c file
config.log

  |#if \__apple_build_version__ < 5030040
  |#error clang 3.4 (or Apple XCode 5.1.1) or newer is required to build MongoDB
  |#endif

Check clang on 10.7:
echo | clang -dM -E -|grep \__apple_build_version__
#define \__apple_build_version__ 4250028

So I guess it won't build as it is on 10.7. This is MongoDB issue, not brew.

A.

**Comment by mistydemeo** [comment]
Yep, Xcode 5.x is only available on Mt. Lion. Marking the formula as incompatible with 10.7 and lower. Thanks!
