### ISSUE TITLE
What is the latest version of Homebrew?

### ISSUE THREAD

**Issue by ayushgoel** [Homebrew/homebrew#37757]
I have no idea if I should update brew from it's current version `0.9.5`.
Maybe marking changes and releasing new versions can be handled via [Releases](https://github.com/Homebrew/homebrew/releases).

**Comment by dunn** [comment]
You should run `brew update` before `brew install`ing anything.

**Comment by mistydemeo** [comment]
The version of Homebrew isn't currently a useful guide to updating, except to indicate how outdated you might be. Since both core code and formula code is packaged in the same repository, we recommend all users stay up-to-date and `brew update` regularly.

In the future, we'll be separating the application code into its own repository, in which case the version number will become more meaningful.

**Comment by ayushgoel** [comment]
I was always doing a `brew update` but didn't know it updated the program itself too. Thanks for the information! :relaxed:
