### ISSUE TITLE
Executable code loaded over an insecure channel (High Risk)

### ISSUE THREAD

**Issue by TheRook** [Homebrew/homebrew#38307]
When downloading executable code form SourceForge brew choose to use an insecure channel (http),  which is vulnerable to a man-in-the-middle attack.  The transmission of executable code over HTTP is extremely hazardous as it leads to remote code execution.  The following insecure behavior was observed:
      ~> brew install Caskroom/cask/filezilla
      ==> brew cask install Caskroom/cask/filezilla
      ==> Downloading       http://downloads.sourceforge.net/project/filezilla/FileZilla_Client/3.10.3/FileZilla_3.10.3_macosx-x86.app.tar.bz2

Brew was installed on one our high security systems. A vulnerability which leads to remote code execution on this system is unacceptable,  and we are forced to uninstall brew until this high risk issue is addressed.

**Comment by tdsmith** [comment]
Please raise issues against formulas in `Caskroom/cask` here: https://github.com/Caskroom/homebrew-cask/issues

The download is verified against a sha256 hash in the cask formula so the contents of the file are known to be good, which prevents MITM attacks regardless of transport.

**Comment by TheRook** [comment]
Is brew downloading these verification hashes over HTTP?  Its 2015,  why would anyone default to HTTP?

**Comment by mistydemeo** [comment]
Cask is a separate project - we don't control how it downloads software. Homebrew itself downloads all packages from Sourceforge using HTTPS; in fact, our formula audit command will [explicitly flag](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/audit.rb#L378-L381) any Sourceforge URLs using HTTP instead of HTTPS.

It would be most constructive to raise the issue with Cask, and perhaps submit a pull request to migrate any URLs to HTTPS if they're interested in that.

> Is brew downloading these verification hashes over HTTP?

No, those hashes are a part of the formulae themselves, which are fetched as a part of the git checkout - typically over HTTPS.

**Comment by DomT4** [comment]
All Homebrew/homebrew formulae install from ` https://downloads.sourceforge.net `. What the Cask do is up to them.

> Is brew downloading these verification hashes over HTTP?

As in the SHA256 sums? They're stored on each local machine, and updated via Github over SSL/TLS.

**Comment by tdsmith** [comment]
Reference Caskroom/homebrew-cask#10377.
