### ISSUE TITLE
Missing Xcode command-line tools not detected by Homebrew

### ISSUE THREAD

**Issue by nhooey** [Homebrew/homebrew#38420]
It would be helpful if Homebrew would detect missing Xcode command-line tools that packages require to compile against libraries like `freetype` and `libmemcached`.

Without the tools installed, running `brew install libmemcached` and then compiling against it leads to errors like:

```
In file included from src/_pylibmcmodule.c:34:
src/_pylibmcmodule.h:42:10: fatal error: 'libmemcached/memcached.h' file not found
#include <libmemcached/memcached.h>
```

Even though `/usr/local/include/libmemcached/memcached.h` exists from Homebrew linking it.

An example of this issue and its solution is documented here:
http://stackoverflow.com/questions/23905661/on-mac-g-fails-to-search-usr-local-include-and-usr-local-lib-by-default/26404710

Homebrew should require the Xcode developer tools to install libmemcached, or at least advise the user, so the package installed by Homebrew can actually be used. It's misleading to suggest that libmemcached will just work after installing it with `brew install`.

**Comment by jacknagel** [comment]
Most things do not require both Xcode and the CLT. `brew doctor` will warn if neither are installed.

Can you provide build logs (via `brew gist-logs`) from a formula that fails? We can't address this without more details.

**Comment by nhooey** [comment]
I had Xcode installed, but not the CLT, so `brew doctor` gave no warning. It should probably warn when the CLT aren't installed.

It's not a Homebrew formula that was failing, it was the installation of some Python modules with Pip.

**Comment by jacknagel** [comment]
>I had Xcode installed, but not the CLT, so brew doctor gave no warning. It should probably warn when the CLT aren't installed.

We used to have a warning, but the Xcode-only support is mature now, so we support using Homebrew without the CLT installed. The Homebrew build system is "Xcode-aware" and knows how to find header files inside the SDK rather than in "normal" locations. So we're not going to add a warning again.

If you are building software outside of Homebrew (like python modules) that is not Xcode-aware, you'll have to compensate for that, either by adjusting build variables (which Homebrew does internally). or installing the CLT.
