### ISSUE TITLE
GCC fails to build with Xcode 6.3

### ISSUE THREAD

**Issue by ssbanerje** [Homebrew/homebrew#38501]
I am trying to build OpenMPI for OS X 10.10.3 (Xcode 6.3). As a dependency, it compiles GCC.

The GCC build seems to be failing at the moment (I tried it on two computers both running 10.10.3). There seem to be several GCC related open issues, this one in particular might be related to https://github.com/Homebrew/homebrew-versions/issues/738 (however I am not entirely sure).

The verbose build log has nearly 20k lines of output, I did a few preliminary searches for "error" and "Error", and this seems to be the only portions that they are mentioned (in the file `02.make`)--

```
cc/tree-ssa-threadupdate.o differs
gcc/tree-ssa-uncprop.o differs
gcc/tree-vectorizer.o differs
gcc/valtrack.o differs
gcc/vtable-verify.o differs
make[2]: *** [compare] Error 1
make[1]: *** [stage3-bubble] Error 2
make: *** [bootstrap] Error 2
==> Formula
.....
.....
Error: gcc 4.9.2 did not build
Logs:
     /Users/subho/Library/Logs/Homebrew/gcc/01.configure
     /Users/subho/Library/Logs/Homebrew/gcc/01.configure.cc
     /Users/subho/Library/Logs/Homebrew/gcc/02.make
     /Users/subho/Library/Logs/Homebrew/gcc/02.make.cc

These open issues may also help:
...
```

[Link to Logs](https://gist.github.com/e5dcc05b1fb932e4274f)

Any ideas how to fix this?

**Comment by aw94** [comment]
Same thing happened to me, and everything that requires gcc is also failing. The gist that I got is [here](https://gist.github.com/anonymous/0edeb37258345fc07aaf)

I want to guess that this may have something to do with the command line tools update Apple pushed out a bit ago, since I don't remember having this kind of issue before that...

**Comment by UniqMartin** [comment]
I have the same problem like @ssbanerje. I have no proper solution, but I can offer an explanation and a workaround. I think @aw94's issue is unrelated.

**Explanation:** Building GCC usually means building several intermediate compilers, i.e. the host compiler (Clang on OS X) builds a stage 1 GCC. Stage 1 then builds stage 2 and stage 2 builds stage 3. To ensure that the built compiler is not broken, the build system compares the object files of stage 2 and 3, which fails with Xcode 6.3 and/or OS X 10.10.3 (not sure what the culprit is). Excerpt from `02.make` (unfortunately several lines above the output from Homebrew):
```
Comparing stages 2 and 3
warning: gcc/cc1-checksum.o differs
warning: gcc/cc1obj-checksum.o differs
warning: gcc/cc1objplus-checksum.o differs
warning: gcc/cc1plus-checksum.o differs
Bootstrap comparison failure!
gcc/asan.o differs
gcc/attribs.o differs
[…]
```
The thing is, the object files are indeed different, but the difference is only to be found in the debug information (it is equivalent, but not bit-for-bit identical). On the other hand, the actual machine code is indeed bit-for-bit identical, as can be seen by stripping the object files.

**Workaround:** The trick is to use the knowledge from the explanation above and to instruct the GCC build system to compare stripped object files, by passing the additional configure flag `--with-build-config=bootstrap-debug` (see <https://gcc.gnu.org/install/build.html> for details). This should go somewhere into the `args` array in [gcc.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb#L87-109) (line 87-109).

**Comment by UniqMartin** [comment]
Gist of `gcc.rb` with my workaround: <https://gist.github.com/UniqMartin/a78ba807d41116836cd7>

**Comment by ssbanerje** [comment]
Is this something that should be changed in the homebrew build or in GCC?

**Comment by UniqMartin** [comment]
From what I understand, the debug information that causes the comparison to fail is generated by GCC. It seems a change in the underlying toolchain exposed some subtle bug or non-deterministic behavior in GCC itself. I might be totally wrong, but to me it looks like an upstream issue. Unfortunately, I neither have the experience nor the resources to get to the root of the problem.

I was hoping that someone more experienced would join the discussion and my analysis would help get them started. But maybe it's best to take this upstream.

**Comment by ssbanerje** [comment]
Looks like this is a bug with the latest version LLVM that comes along with Xcode 6.3. 
[(Link to GCC bug report)](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65733)

@UniqMartin Your workaround worked for me. I hope this does not lead to any correctness issues for generated code. Maybe you should submit your work-around as a pull-request. This might probably get fixed in the next release of the Xcode CLTs. Which might take some time.

**Comment by UniqMartin** [comment]
Thanks for finding this GCC bug report! I'll try to prepare a pull request for tomorrow.

(The other issue, that affects many packages is unrelated. That one is about a difference between the toolchain provided by Xcode 6.3 and the toolchain from Command Line Tools 6.3, where the latter misses a header file.)

**Comment by UniqMartin** [comment]
Also, can you change the issue title to something like “GCC fails to build with Xcode 6.3” to better reflect the problem?

**Comment by UniqMartin** [comment]
@ssbanerje, thanks for encouraging me to create my first pull request ever! It was already merged, so I guess you can close this issue. :)

**Comment by DomT4** [comment]
Might be good to keep it open so folks can keep track of when the patch is safe to remove again. Relying on people to notice inline formula comments isn't always reliable, heh.

**Comment by andrewgho** [comment]
This problem seems to have cropped up again with the Xcode 6.3.1 update, albeit with a smaller set of bootstrap object file comparison problems:

```sh
$ brew install gcc49
==> Installing gcc49 from homebrew/homebrew-versions
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc49-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.3.0 --prefix=/usr/local/Cellar/gc
==> make bootstrap
gcc/valtrack.o differs
gcc/vtable-verify.o differs
make[2]: *** [compare] Error 1
make[1]: *** [stage3-bubble] Error 2
make: *** [bootstrap] Error 2
```

The complete output of `HOMEBREW_MAKE_JOBS=1 brew install -v gcc49 2>&1` can be found here: https://gist.githubusercontent.com/andrewgho/06b5e31dbd7aa9d0ce13/raw/brew_install_gcc49.txt

This is on a stock Retina display 12" MacBook (the new 2015 model), with the Apple factory installed Yosemite, after all software updates as of April 27, 2015 were applied. Precise software versions:

```sh
$ uname -a
Darwin Andrews-MacBook.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

```sh
$ xcodebuild -version
Xcode 6.3.1
Build version 6D1002
```

```sh
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4cb6a9a9886b40c27c2d4f729ae66682717e27d4
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit broadwell
OS X: 10.10.3-x86_64
Xcode: 6.3.1
CLT: N/A
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: N/A
```

Homebrew itself is up to date and reports no errors (this is a fresh Homebrew installation):

```sh
$ brew update
Already up-to-date.
```

```sh
$ brew doctor
Your system is ready to brew.
```

This blocks RVM installation of any old Ruby versions (like Ruby 1.9.3 or earlier).

**Comment by DomT4** [comment]
Don't trust the ` gcc49 ` formula in Homebrew/versions to compile on 10.10 yet - It hasn't had the fix backported from Homebrew/homebrew. I'll set the test-bot on it shortly.

**Comment by andrewgho** [comment]
I'm trying a build now with a locally patched version:

```sh
$ (cd /usr/local/Library/Taps/homebrew/homebrew-versions && git diff)
diff --git a/gcc49.rb b/gcc49.rb
index c257811..a6dc532 100644
--- a/gcc49.rb
+++ b/gcc49.rb
@@ -103,6 +103,9 @@ class Gcc49 < Formula
       "--enable-stage1-checking",
       "--enable-checking=release",
       "--enable-lto",
+      # Use 'bootstrap-debug' build configuration to force stripping of object
+      # files prior to comparison during bootstrap (broken by Xcode 6.3).
+      "--with-build-config=bootstrap-debug",
       # A no-op unless --HEAD is built because in head warnings will
       # raise errors. But still a good idea to include.
       "--disable-werror",
```

I'll confirm if it works. I suspect we also need the same backport for `brew install gcc48` which is needed for even older Ruby versions (like REE).

**Comment by DomT4** [comment]
`gcc48` is already fixed.

**Comment by andrewgho** [comment]
You're right about `gcc48`, sorry (I didn't notice it was in a different part of the recipe file).

**Comment by DomT4** [comment]
`gcc49` is as well now. Will be available after a `brew update`.

**Comment by andrewgho** [comment]
Great, thanks! Testing `brew install gcc49` now (I cancelled my locally patched versions, these new MacBooks are damnably slow at compiling...).

**Comment by andrewgho** [comment]
Everything looks good now, thanks for the quick fix!

```sh
$ brew install gcc49
==> Installing gcc49 from homebrew/homebrew-versions
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc49-4.9.2.tar.bz2
==> ../configure --build=x86_64-apple-darwin14.3.0 --prefix=/usr/local/Cellar/gc
==> make bootstrap
==> make install
🍺  /usr/local/Cellar/gcc49/4.9.2_1: 1138 files, 164M, built in 61.8 minutes
```

```sh
$ rm -f hello.c hello && printf '#include <stdio.h>\nmain() { printf("Hello, world\\n"); }\n' > hello.c && gcc-4.9 -o hello hello.c && ./hello
Hello, world
```

RVM build of Ruby 1.9.3 versions now works, too.

**Comment by seekerFactory** [comment]
Was stuck in similar issue with gcc-4.9.0 throwing error.....

$ gcc -v
==> gcc: warning: couldn’t understand kern.osversion ‘14.3.0
==> Using built-in specs.
==> COLLECT_GCC=gcc
==> COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin13.1.0/4.9.0/lto-wrapper
==> Target: x86_64-apple-darwin13.1.0
==> Configured with: ../gcc-4.9.0/configure --enable-languages=fortran
==> Thread model: posix
==> gcc version 4.9.0 (GCC)

Thanks for the cue :) finally got it fixed with refference from an old link https://github.com/Homebrew/homebrew/issues/36944 and now have reinstalled gcc-4.9.2 using homebrew.

Is it safe to remove the older gcc which is still present in the system?

**Comment by jacknagel** [comment]
Yes.

I think this issue is resolved, if not, will someone please summarize the current state?

**Comment by sononix** [comment]
I havent used homebrew and ran into the same issue of the installation falling on a virgin install of 10.3 with xcode 6.3 - I ended up adding '--with-build-config=bootstrap-debug' to my config flags and installation went smoothly thereafter

gcc version 4.9.2
mpfr version 3.1.2
Gmp version 4.3.2
Mpfr version 2.4.2 
isl version 0.12.2
cloog version 0.18.1

sudo ../configure --prefix=/usr/gcc-4.9.2 --enable-checking=release --with-gmp=/usr/gcc-4.9.2 --with-mpfr=/usr/gcc-4.9.2 --with-mpc=/usr/gcc-4.9.2 --enable-languages=c,c++,fortran --with-isl=/usr/gcc-4.9.2 --with-cloog=/usr/gcc-4.9.2 --program-suffix=-4.9.2 --with-build-config=bootstrap-debug

**Comment by seekerFactory** [comment]
Sorry for being little late to reply. 
Didnt delete as you suggested but had to repeat the same steps(specifically mentioning the binaries with --cc and --cxx flags) again with other libraries as tried to compile boost and mongo after updated Yosemite. gcc may not have hand in this but is coming in between automatically at every small update of OSx.
Please summarize as it suits.

**Comment by leycec** [comment]
**Ugh.**

I'm stumbling over this exact same fatal error under the most recently available version of Xcode (5.1.1) for the most recently available version of OS X Mountain Lion (10.8.5):

```
rm -f stage_current
Comparing stages 2 and 3
warning: gcc/cc1-checksum.o differs
warning: gcc/cc1obj-checksum.o differs
warning: gcc/cc1objplus-checksum.o differs
warning: gcc/cc1plus-checksum.o differs
Bootstrap comparison failure!
x86_64-apple-darwin12.6.0/libstdc++-v3/src/.libs/compatibility-chrono.o differs
x86_64-apple-darwin12.6.0/libstdc++-v3/src/c++11/chrono.o differs
x86_64-apple-darwin12.6.0/libstdc++-v3/src/compatibility-chrono.o differs
make[2]: *** [compare] Error 1
make[1]: *** [stage3-bubble] Error 2
make: *** [bootstrap] Error 2
```

Unfortunately, OS X Mountain Lion is a hard business requirement for our client's use case. Thanks to the above discussion, I intuit that I have two equally unsavory options at this lamentable point:

1. Manually munge the `"--with-build-config=bootstrap-debug",` configuration option into the appropriate Homebrew `gcc*.rb` makefile(s). Sounds like fun! _Only not_.
1. Copiously vomit all over myself, squeamishly roll around in said vomit, and give up.

I wisely choose option **1**. :mask: 

Although `brew doctor` reports no issues, I harbour doubts as to whether Homebrew genuinely supports older major versions of OS X. I've had all manner of trouble attempting to install Homebrew-managed Python-oriented packages and transitive dependencies under both Mountain Lion (10.8) and Snow Leopard (10.6). This is only the latest in a deplorable string of pear-shaped Homebrew infirmities I've had to fiercely cudgel into submission. _It's getting old._

If Homebrew no longer guarantees backward compatibility with older OS X installations, that's fine. I sympathetically understand that older versions of the Xcode Command Line Tools (CLT) and `clang` in particular are widely considered to be broken. Continually working around Apple's intellectually impoverished compiler toolchain must be "fun," for certain values of "fun" synonymous with "drunken berserker blood rage."

That said, it would be helpful if there were some explicit acknowledgement (ideally delivered by `brew doctor` or on compilation failure) that older OS X installations are not necessarily a Homebrew testing priority and hence more likely to trip into a viper-strewn nest of untested and poorly documented installation woes.

Like this, for example.

**Comment by leycec** [comment]
**Ugh<sup>2</sup>.**

I appear to be in uncharted, post-apocalyptic, zombie-infested waters. The `/usr/local/Library/Formula/gcc.rb` makefile presumably used for `brew install gcc` _already_ unconditionally enables the `"--with-build-config=bootstrap-debug"` configuration option.

In bravely perusing this well-documented makefile (..._thanks, guys; it really is concisely and clearly well-documented_), I note the following related commentary:

```
    # Otherwise make fails during comparison at stage 3
    # See: http://gcc.gnu.org/bugzilla/show_bug.cgi?id=45248
    args << "--with-dwarf2" if MacOS.version < :leopard
```

Since DWARF-2 is a standardized debugging data format and the issue in question appears to be ignorable differences between compiled object files containing debugging symbols, it stands to bleary-eyed reason that locally enabling this configuration option might yield happiness. Specifically, I've modified the above line to read as follows and am optimistically retrying `brew install gcc`:

```
    args << "--with-dwarf2"
```

**May Valhalla be with me.**

**Comment by leycec** [comment]
Miraculously, **that worked.** I'm now contemplating submitting a pull request for this regression.

**Comment by leycec** [comment]
It is [done](https://github.com/Homebrew/homebrew/pull/46111) – and the neckbeard saw that it was good. :neckbeard:
