### ISSUE TITLE
wget installed by brew cannot verify Google certs

### ISSUE THREAD

**Issue by izzyleung** [Homebrew/homebrew#38800]
I have the latest version of wget installed on my Mac, which is also up-to-date.

I have this strange issue that I cannot use wget to fetch the page of youtube

This is what happened when I tried to use `wget https://youtube.com` to download the page:

```
$ wget https://youtube.com
--2015-04-18 17:33:52--  https://youtube.com/
Resolving youtube.com... 216.58.216.238, 2607:f8b0:4009:809::200e
Connecting to youtube.com|216.58.216.238|:443... connected.
ERROR: cannot verify youtube.com's certificate, issued by 'CN=Google Internet Authority G2,O=Google Inc,C=US':
  Unable to locally verify the issuer's authority.
To connect to youtube.com insecurely, use `--no-check-certificate'.
```

I have some problem with the certs in youtube-dl, and I found an temporary solution to it, you can refer to this link: https://github.com/rg3/youtube-dl/issues/5317

Would like to know how to solve this issue by not exporting the certs I have downloaded as an environment variable.

Thanks in advance for your reply.

**Comment by izzyleung** [comment]
Found out the ultimate solution.

Force uninstall openssl installed by Homebrew and then `rm -rf /usr/local/etc/openssl`

Then install openssl by `brew install openssl`, it will reinstall the certs and now wget works fine.

**Comment by DomT4** [comment]
The reinstall of ` openssl ` worked because of #38495. We put in a workaround to fix the Google connection issues until a time where we get upstream clarity from Apple or OpenSSL issue a fix to their cert chain handling.

This isn't an ultimate solution. The Equifax root we had to put back in place is weak, and old, and *should* die. Putting it back is a temporary solution that sucks; It just sucked less than breaking the whole range of Google domains across a variety of tools.
