### ISSUE TITLE
ossp-uuid Location of uuid.h Is Problematic

### ISSUE THREAD

**Issue by ramsey** [Homebrew/homebrew#38864]
I'm trying to build a package that is looking for `uuid/uuid.h`, but it can't find it because the ossp-uuid bottle places `uuid.h` in `/usr/local/include/ossp`. I can't even tell the package to look in `/usr/local/include/ossp` because it's expecting the header at `/usr/local/include/ossp/uuid/uuid.h`.

I'm not sure whether this is a bug in the ossp-uuid bottle or in the expectation of the package I'm trying to build. Short of editing the package source to look in `ossp/uuid.h`, do you have any recommendations, or should the bottle be updated to place the header in a more standard location?

**Comment by jacknagel** [comment]
The package in question should probably have logic in its build system to look for just "uuid.h" depending on what is detected at build time. I think there are autoconf macros for this.

The current layout of our ossp-uuid package is very much intentional, though (you can see this by reading through the commit history and associated pull requests / issues), and seems to match what other package managers are doing.

**Comment by ramsey** [comment]
Thanks. I'll see about having the other package updated.
