### ISSUE TITLE
Mongodb failed to build on 10.10.3

### ISSUE THREAD

**Issue by jenslind** [Homebrew/homebrew#38862]
I am unable to install mongodb on 10.10.3, I'm running boxen so I need this confirmed. Because this might just be a boxen issue, not sure yet.

`brew install mongodb`
generates:
```
==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.0.2.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/mongodb-3.0.2.tar.gz
==> Cloning https://github.com/mongodb/mongo-tools.git
Updating /opt/boxen/cache/homebrew/mongodb--github.com-mongodb-mongo-tools--git
==> Checking out tag r3.0.1
==> ./build.sh
==> /opt/boxen/homebrew/opt/scons/bin/scons install --prefix=/opt/boxen/homebrew
1 error generated.
scons: *** [build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/mongo/base/global_initializer_registerer.o] Error 1
1 error generated.
scons: *** [build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/mongo/base/initializer.o] Error 1
scons: building terminated because of errors.
```
Logs: https://gist.github.com/26dc0625d5bcbeb1f4f5

**Comment by DomT4** [comment]
It's the CLT error ` /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found `.

Should have been solved by @tdsmith' fix the other night. Are you up-to-date on ` brew update ` and ` brew upgrade `?

**Comment by jenslind** [comment]
Yepp, I'm up-to-date.

**Comment by tdsmith** [comment]
This is caused by the issue described in #38514, which is an Xcode CLT header bug.

We have a workaround that works for superenv environments, but mongodb uses scons, and we always use stdenv for scons.

Installing Xcode and running `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` to use Xcode's headers (instead of the CLT's) is the recommended workaround until Apple fixes this in the CLT. Sorry!

**Comment by jenslind** [comment]
Thanks! :)
