### ISSUE TITLE
Support SHA-512 for package integrity checks

### ISSUE THREAD

**Issue by gabehack** [Homebrew/homebrew#38945]
In particular, it seems like the GCC 5 release series is only publishing sha512.

**Comment by DomT4** [comment]
Meh, personally. We've started switching over to mandating SHA256, which is nowhere near provably broken. Until SHA1 dies in terms of Homebrew usage, reluctant to write-in a third hash type, personally. 

We might need to do something with the way formulae display SHASUMS if we do go ahead with this - SHA512 is kinda huge in length (For obvious reasons).

**Comment by mikemcquaid** [comment]
Agreed. Don't see any need for now.

**Comment by gabehack** [comment]
> We've started switching over to mandating SHA256...

That's partly the issue. They are only publishing SHA512 and MD5. Unless something changes with the GCC 5 release series, saying no to this implies homebrew can not install the current stable release for GCC (with integrity checks).

**Comment by DomT4** [comment]
That's not an issue. That's never been an issue for any package manager, really. Nobody ties themselves irreversibly to whatever checksum upstream are displaying, otherwise many of the packages we shipped would still be rolling a hot MD5 checksum.

When a package is submitted to Homebrew, more often than not, the checksum is user-generated rather than yanked from upstream somewhere. That checksum is then checked and verified on three different test-bots. Any failure at that level results in the test-bot throwing a giant ` FAILED ` across the build. On user download of said package, that checksum is verified again. Checksum manipulation of package management is not as easy as folks tend to presume.

**Comment by mikemcquaid** [comment]
What @DomT4 said.

**Comment by gabehack** [comment]
Good to know. Thanks for the comments.
