### ISSUE TITLE
mysql-connector-odbc doesn't depend on mysql

### ISSUE THREAD

**Issue by leoliu** [Homebrew/homebrew#39126]
Could someone verify that mysql-connector-odbc doesn't depend on mysql? The odbc driver needs to be installed on the client and server side. ODBC will be useless if every driver needs its database installed on the client side. Cheers, Leo

**Comment by mikemcquaid** [comment]
It does depend on the server. It maybe needs changed to `:mysql` instead? Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by leoliu** [comment]
@mikemcquaid,

I am not sure this is true. Could you elaborate how the driver is dependent on the mysql driver? I can't find any evidence.

Thanks,
Leo

**Comment by mikemcquaid** [comment]
> I am not sure this is true. Could you elaborate how the driver is dependent on the mysql driver? I can't find any evidence.

In the formula it has `depends_on "mysql"`. If this isn't needed please submit a pull request to tweak it. Thanks!

**Comment by jacknagel** [comment]
I tried to compile this against mysql-connector-c and it failed.

**Comment by apjanke** [comment]
Yeah, MySQL Connector/ODBC is just a client-side driver. It's built from a standalone distribution. It should not depend on `mysql`, which is the server/rich client package. I've put in a PR #41445 to remove the dependency from the formula.

@jacknagel: What do you mean by "tried to compile this against mysql-connector-c and it failed"? They're two different client libraries and AFAIK there's no linkage or relationship between the two of them. If you tried to just `brew install` both, that would have failed, because `mysql-connector-c` conflicts with `mysql`, so the unnecessary  `depends_on "mysql"` in `mysql-connector-odbc` prevents them from being installed side-by-side. That PR removes the `mysql` dependency, and from what I can see, `mysql-connector-odbc` and `mysql-connector-c` have no file conflicts, so they can be installed side-by-side now. I tested this on my 10.9.5 system and it worked (doing `brew install --build-from-source` for both).

**Comment by mikemcquaid** [comment]
> It should not depend on mysql, which is the server/rich client package

It does, though. From your PR: http://bot.brew.sh/job/Homebrew%20Pull%20Requests/29166/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_mysql_connector_odbc/

**Comment by jacknagel** [comment]
What I mean is that mysql-connector-odbc has a dependency on mysql client libs. I tried to satisfy that dependency using mysql-connector-c rather than full-blown mysql, but compilation failed.

fyi I'm not actively working on Homebrew anymore.

**Comment by apjanke** [comment]
@mikemcquaid, @jacknagel: Crap. I wonder why the build succeeded when I tested it after removing `mysql` on my own machine? Sorry about that. Looking in to it.

**Comment by apjanke** [comment]
I'm a moron. There's an old non-Homebrew MySQL installation sitting there under `/usr/local` on my box. (`brew doctor` didn't notice it.) Sorry about that.

**Comment by mikemcquaid** [comment]
No worries :wink:
