### ISSUE TITLE
Autoupdate Formulae Versions

### ISSUE THREAD

**Issue by mattdipasquale** [Homebrew/homebrew#39328]
[Heroku Toolbelt](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/heroku-toolbelt.rb) is outdated.

Is there someway to make it so that Homebrew formulae autoupdate (by themselves)? Maybe some sort of public API, standard, machine learning, etc?

For example, for Heroku Toolbelt, the URL https://s3.amazonaws.com/assets.heroku.com/heroku-client/heroku-client.tgz always points to the latest version.

**Comment by DomT4** [comment]
> Heroku Toolbelt is outdated.

Open a PR :wink:.

> always points to the latest version.

Homebrew doesn't use these types of URLs because Homebrew has no control/detection over when they're updated, and consequently are borderline impossible to bottle, update and (perhaps more importantly) checksum.

There are various implementations around as to detecting en-mass when packages are updated, but there's nothing completely reliable, scalable or removing the need for human intervention at some point yet, to my knowledge at least.

@asparagui has probably the best implementation of something that makes en-mass update detection a more pleasant experience [here](https://github.com/asparagui/homebrew-hydrometer), but it still requires a human to do the formulae changes and PR them.

**Comment by jacknagel** [comment]
We continue to see value in human verification of updates.
