### ISSUE TITLE
Use specific version of package per directory / project

### ISSUE THREAD

**Issue by karlingen** [Homebrew/homebrew#39432]
I often find myself switching to a specific version of a package installed with [homebrew][1] when switching projects. 

    $ cd ~/Desktop/projects/project1    
    $ brew switch phantomjs 2.0.0
    Cleaning /usr/local/Cellar/phantomjs/1.9.7_1
    Cleaning /usr/local/Cellar/phantomjs/1.9.8
    Cleaning /usr/local/Cellar/phantomjs/2.0.0
    2 links created for /usr/local/Cellar/phantomjs/2.0.0

And then when changing project:

    $ cd ~/Desktop/projects/project2
    $ brew switch phantomjs 1.9.8
    Cleaning /usr/local/Cellar/phantomjs/1.9.7_1
    Cleaning /usr/local/Cellar/phantomjs/1.9.8
    Cleaning /usr/local/Cellar/phantomjs/2.0.0
    2 links created for /usr/local/Cellar/phantomjs/1.9.8

Is it somehow possible to automate this so that I can force `brew` to automatically switch to a specified version when inside a certain project?

Would be nice if one could create a file called something like `.homebrew`inside the target directory and from there specify required packages and versions.

  [1]: http://brew.sh/

**Comment by xu-cheng** [comment]
`brew switch` would affect globally. So it doesn't suit for your needs. Instead of you should set PATH or other environment variable per project. e.g. `export PATH=/usr/local/Cellar/phantomjs/2.0.0/bin:$PATH`.

For this you can use IDE to set your project settings. Or you can check `direnv` which allows you set env per directory.
