### ISSUE TITLE
Jenkins seems to have different Rubocop rules in different environments

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#39620]
I'm running into a situation with a formula where I'm adding a regular expression that has exactly one slash (`/`) in it.

If I use a standard `/.../`-style regex, then when Jenkins runs `brew audit --strict` on Yosemite, it fails with "Use %r around regular expression." ([see example](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25888/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_rtl_sdr___strict/)) This, by the way, is the same error I get on my own machine running Mavericks (yes, Mavericks).

But if I use a `%r{...}`-style regex, Jenkins's run of `brew audit --strict` on _Mavericks_ fails with "Use %r only for regular expressions matching more than 1 '/' character." ([see example](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25881/version=mavericks/testReport/junit/brew-test-bot/mavericks/audit_rtl_sdr___strict/))

On the latter, I also see "Warning: unrecognized cop Style/CommandLiteral found in /usr/local/Library/.rubocop.yml"… so that may be an extra hint.

**Comment by DomT4** [comment]
The bot needs to have a `gem update` done, but there's no automated process to handle that. The most recent Rubocop release changed several of the definitions, and I pushed a PR to adapt to the new changes. Make sure your Rubocop locally is up to date, and I'm trying to work on a way to make the bot update the gems we use for `brew style`.

**Comment by L2G** [comment]
> The bot needs to have a `gem update` done, but there's no automated process to handle that.

Is there a need for extra hands to do stuff like that? Automate things, I mean. (…says the guy who's in between gigs and looking for things to do to keep busy…)

**Comment by DomT4** [comment]
I'm not entirely sure. I was discussing it with @mikemcquaid but Mike's not around at the moment and I haven't wanted to disturb his peace with enquires about test-bot gem discussions :smile_cat:.

In my mind the answer was for the test-bot to either check we were using the latest Rubocop gems by calling `gem outdated` and looking for a specific output, or just periodically running a `gem update rubocop` as part of the test-bot mechanism. We'd need to rescue the situation where the RubyGem servers weren't available otherwise the whole test-bot run would blow up. The problem with the latter is I'm not entirely sure how time-*aware* the test-bots are, so exercising "periodically" could be fun.

**Comment by L2G** [comment]
Is it something that might be better served with a configuration management tool like Ansible or Chef?

**Comment by DomT4** [comment]
Potentially, but introducing a whole new tool to deal with a relatively small and semi-harmless problem may be unnecessarily troublesome; at the moment `brew style` failures as related to `unrecognized cop` failures are ignored, the test-bot turns green regardless if that's the only issue.

Minimal intervention is more ideal for the problem, especially since if the test-bot gets broken everything goes to hell :sweat_smile:. IMO, if we wanted to bring in a third-party tool to manage auto-updating Gems something like `whenever` is a better bet - It's relatively non-invasive and has minimal dependencies.

**Comment by jacknagel** [comment]
I updated rubocop, is there an open PR we can use to test this?

**Comment by DomT4** [comment]
#39574

**Comment by jacknagel** [comment]
Failed. *shrug* Mike probably knows what do to.

**Comment by DomT4** [comment]
Mavericks did this:

```
==> brew audit rtl-sdr --strict						 FAILED
==> brew style rtl-sdr
Warning: unrecognized cop Style/CommandLiteral found in /usr/local/Library/.rubocop.yml
== /usr/local/Library/Formula/rtl-sdr.rb ==
C: 17:  7: Use %r only for regular expressions matching more than 1 '/' character.

1 file inspected, 1 offense detected
```

Yosemite was fine:

` ==> brew audit rtl-sdr --strict						 PASSED `

Mountain Lion completely blew up:

```
==> brew uses rtl-sdr							Error: compile error
/usr/local/Library/Formula/rtl-sdr.rb:19: syntax error, unexpected ')'
 FAILED
Error: compile error
/usr/local/Library/Formula/rtl-sdr.rb:19: syntax error, unexpected ')'
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/rtl-sdr.rb:21:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
```

Fun mix.

**Comment by DomT4** [comment]
FWIW, at least locally and on various "clean" Travis machines, `PASSED` is the result I get every time, so I'm presuming it's a test-bot quirk rather than something deeper. Fingers crossed anyway :weary:.

**Comment by jacknagel** [comment]
OK, sorted out the rubocop weirdness, at least for core. It will need to be done individually for each tap that is currently on CI, though.

Medium-term this should probably be managed with bundler, like our test dependencies, so that we can just push updates to the Gemfile.

**Comment by mikemcquaid** [comment]
> Medium-term this should probably be managed with bundler, like our test dependencies, so that we can just push updates to the Gemfile.

Yep. Or, alternatively just make the current thing check for and install the latest version of `rubocop` rather than any version.

**Comment by jacknagel** [comment]
:cake:
