### ISSUE TITLE
brew doctor

### ISSUE THREAD

**Issue by markknochen1** [Homebrew/homebrew#39846]
i get with brew doctor the warning:

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:

    phar
    phar.phar
    php
    php-config
    phpize
    svn
    svnadmin
    svndumpfilter
    svnlook
    svnserve
    svnsync
    svnversion

how can i clean this double paths?

Mark

**Comment by mikemcquaid** [comment]
Set your `PATH` so `/usr/local/bin` is before `/usr/bin`.

**Comment by markknochen1** [comment]
sorry, how can i do this?

**Comment by DomT4** [comment]
If you're using `bash` it'll be something like:

` echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bash_profile `.

Binaries will still appear in both places, but this is expected given the formulae you have installed. The warning in not so much that they are duplicated, but that when you call them on the command line you're using the system versions instead of the Homebrew versions.

**Comment by markknochen1** [comment]
i tried this in the console:

echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bash_profile

but no changes ...

**Comment by DomT4** [comment]
> but is it possible to clean the double file system without problems?

You can't remove stuff from `/usr/bin` without causing major, major system problems that will probably force you to reinstall OS X, and presumably you've chosen to install `subversion` and `php` formulae which cause the Homebrew dupes. You can remove the conflicting Homebrew formulae you've installed, but I presume you intentionally installed and want to use them.
