### ISSUE TITLE
`brew install odt2txt` doesn't seem to install an executable

### ISSUE THREAD

**Issue by larryhynes** [Homebrew/homebrew#39871]
I ran `brew install odt2txt` this morning. It installs to `/usr/local/Cellar/odt2txt/0.5` but the contents of that dir are just the README and INSTALL_RECEIPT. I can't seem to find an executable anywhere, which is odd! I'm running Yosemite 10.10.3, with an updated brew which usually performs flawlessly, so I'm not inclined to think it's a local problem.

For reference, the final output of `brew install` is `🍺  /usr/local/Cellar/odt2txt/0.5: 2 files, 8.0K`, which would tally with just installing the two files referenced above.

**Comment by DomT4** [comment]
It was missing its prefix argument to `make install` which caused the executable to install directly in `HOMEBREW_PREFIX/bin` and consequently not get bottled. There are checks in place in the last couple of months which would have ensured this doesn't happen, but this formula predated the addition of those checks. I've opened #39874 with the fix for this formula.

**Comment by larryhynes** [comment]
Great stuff, thanks @DomT4

**Comment by DomT4** [comment]
`brew update && brew install odt2txt` should work fine now. Thanks for the report!
