### ISSUE TITLE
iojs: binaries are not available

### ISSUE THREAD

**Issue by rstacruz** [Homebrew/homebrew#39914]
```
brew install iojs
brew link iojs --force
iojs --version #=> v2.0.2
```

If you install a package globally:

```
npm i -g uglify-js
/usr/local/Cellar/iojs/2.0.2/bin/uglifyjs -> /usr/local/Cellar/iojs/2.0.2/lib/node_modules/uglify-js/bin/uglifyjs
uglify-js@2.4.22 /usr/local/Cellar/iojs/2.0.2/lib/node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── source-map@0.1.34 (amdefine@0.1.0)
└── yargs@3.5.4 (decamelize@1.0.0, window-size@0.1.0, camelcase@1.1.0, wordwrap@0.0.2)
```

the bins arent installed onto /usr/local/bin:

```
$ uglifyjs
zsh: command not found: uglifyjs
$ uglify-js
zsh: command not found: uglify-js
```

...the iojs formula doesn't have the post_install stanza that `node` has.

**Comment by DomT4** [comment]
> ...the iojs formula doesn't have the post_install stanza that node has.

It's intentional. The `iojs` formula really isn't designed to support `npm` at this point in time, and likely won't be until we can do something like #36369. At least 3 other substantial ideas have been put on the table, and rejected. Either prepend your `$PATH`, use something like `nvm` or use the iojs [tap](https://github.com/aredridel/homebrew-iojs), at your own risk.

**Comment by jacknagel** [comment]
Closing per the above; #36369 is the place for this to be tracked.
