### ISSUE TITLE
nasm: v2.11.08 miscompiles mozjpeg (libjpeg-turbo)

### ISSUE THREAD

**Issue by pornel** [Homebrew/homebrew#39939]
mozjpeg compiled with nasm 2.11.08 generates completely invalid files. With nasm 2.11.06 it works fine.

https://github.com/mozilla/mozjpeg/issues/175

**Comment by DomT4** [comment]
Does this apply to v3.1 as well?

**Comment by DomT4** [comment]
Proposed fix in #39941. It seems to pass `make test` but if anyone wants to test it beforehand: 

```
brew install -fs https://raw.githubusercontent.com/DomT4/homebrew/mozjpeg/Library/Formula/mozjpeg.rb
```

**Comment by DomT4** [comment]
I'm not quite sure what Apple is doing with their `nasm`. It's an ancient version number, but they've recompiled it recently:

```
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on May 11 2015
```

:unamused:.

**Comment by pornel** [comment]
The compilation problem affects all versions of mozjpeg, including 3.1

**Comment by pornel** [comment]
The proposed workaround works for mozjpeg installed via homebrew, but what about other uses, e.g. mozjpeg built from source? If there's a bug in nasm it could affect other projects.

**Comment by DomT4** [comment]
> but what about other uses, e.g. mozjpeg built from source?

Feel free to submit the older `nasm` to Homebrew/versions. I'd likely merge it there, since it has a valid use case.

>  If there's a bug in nasm it could affect other projects.

Nobody has reported any other issues regarding the latest `nasm` to Homebrew, or indeed upstream, which kind of ties our hands. A revert on the basis of one formula having issues is unusual. IMO the best course of action for now is for you guys to report the failure to `nasm` with more technical detail on expected end result and actual end result and see what they say about it.

**Comment by RickyRomero** [comment]
I ran into this issue today and was going crazy trying to figure it out! Thanks for the quick fix. :+1:
