### ISSUE TITLE
librsvg fails to build under sandboxing

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#40833]
```
libtool: install: chmod 644 /usr/local/Cellar/librsvg/2.40.9_1/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.a
libtool: install: ranlib /usr/local/Cellar/librsvg/2.40.9_1/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.a
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-data-hook
if test -z ""; then \
		/bin/sh /private/tmp/librsvg20150617-17982-1u5c7pe/librsvg-2.40.9/install-sh -d /usr/local/Cellar/librsvg/2.40.9_1/lib/gdk-pixbuf-2.0/2.10.0/loaders ; \
		/usr/local/opt/gdk-pixbuf/bin/gdk-pixbuf-query-loaders > /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache ; \
	fi
/bin/sh: /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache: Operation not permitted
make[4]: *** [install-data-hook] Error 1
make[3]: *** [install-data-am] Error 2
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

CC @xu-cheng

**Comment by xu-cheng** [comment]
Need the gist logs.

**Comment by DomT4** [comment]
It's `librsvg` that's failing. I pointed at the wrong formula in the title initially. Gist-logs are [here](https://gist.github.com/anonymous/d9bb8e35554b21cc41d4).

**Comment by xu-cheng** [comment]
This is the cause. 

```
Jun 18 04:15:28 kernel[0]: Sandbox: sh(60962) deny file-write-data /usr/local/Cellar/gdk-pixbuf/2.30.8/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
```

We don't allow writing to lib during install(but allow it during postinstall)

**Comment by DomT4** [comment]
Sadly it looks like in this case the sandbox-breaching argument is being passed directly to `make`, which makes it somewhat difficult to shuffle into `postinstall`.

**Comment by xu-cheng** [comment]
After some :coffee:, I finally see what's going on here. `librsvg` is trying to write file to `/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache` which is a symlink pointed to the cellar of `gdk-pixbuf-2.0`. Of course, we don't allow this.

My suggestion of solution is:
* Make `/usr/local/lib/gdk-pixbuf-2.0/2.10.0/` a folder rather than a symlink. If it's not working, we need to make `/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache` a normal file rather than a symlink.
* Move the logic of `librsvg` writing `lib` into `postinstall`.

**Comment by DomT4** [comment]
Thanks Xu! :bow:
