### ISSUE TITLE
`brew protobuf-cpp --universal` produces non-portable static libraries

### ISSUE THREAD

**Issue by cgull** [Homebrew/homebrew#40943]
I've been reworking the OS X package build in <https://github.com/keithw/mosh>.  In order to produce a standalone universal binary, it links protobuf statically.  I had installed protobuf with `brew install protobuf-cpp --universal`.  Yesterday, I had the pleasure of tracking down why binaries produced on machine A only worked on machine A but crashed in protobuf static initializers on machine B, but binaries produced on machine B worked on A and B.  Turns out that machine A has a Haswell CPU and machine B is a Sandy Bridge, and Homebrew was enabling the `andn` instruction in the somewhat obscure `BMI1` instruction set extension with `-march`.

I worked around this with `--build-bottle`, but I'd like to suggest that at least for libraries, the combination of `--universal` and machine-specific optimizations doesn't make much sense (fat binaries are inherently about portability), and homebrew should do portable builds in that case.

**Comment by jacknagel** [comment]
We provide the `--universal` option so that users can run applications that need 32-bit libraries, like wine.  Wine uses libjpeg. I don't see why we should remove the native optimizations from the 64-bit library just because the user also happens to need the 32-bit library.

Just use `--build-bottle`.
