### ISSUE TITLE
Unable to install certain packages via cache

### ISSUE THREAD

**Issue by themicmac** [Homebrew/homebrew#41147]
This is a bit of a loaded scenario for this issue, but here goes. I'm running Mac OS X 10.6.8: Snow Leopard (Yes, I know... and, no... unfortunately, I cannot upgrade). 

I am trying to install erlang, among other packages, via homebrew, 
but because of outdated CA certificates, homebrew keeps giving me the following:
 
"curl: (60) SSL certificate problem: unable to get local issuer certificate" error left and right. 

So, to bypass this I have begun downloading the packages myself via the web browser and installing them via homebrew by placing them in the Cache folder. 

This was working beautifully until I reached the erlang package which, for some strange reason is not being detected by brew install as already downloaded. Why could that be? The package was downloaded from the specified brew install URL's and even the mirror gets totally ignored. I am trying more stuff but I would like to know if anyone has come around this type of issue and if there is a solution already. I can't seem to find any posts or articles on an issue this specific. So please, let me kno if you found a workaround for this or if I missed something and am doing(or not doing) something which might be causing this hiccup. Thank you.

**Comment by themicmac** [comment]
I would also like to add that I have already tried doing the same with other packages and am getting the same problem. They all get ignored by homebrew. Also the cache folder has been verified via brew --cache and it's the correct one. Library -> Homebrew -> Cache. Plus, I already ran brew doctor and brew update and everything seems to be up to spec and up to date. So, just wanted to add that.

**Comment by DomT4** [comment]
Do you have Homebrew's `curl` formula installed? If you do we'll be using that to fetch formulae, but otherwise we'll be using the system's `curl` which may well have some cert issues.

We tweaked the way we select certs from the Keychain last night so it's potentially worth you trying a `brew update && brew postinstall openssl` to generate a new `cert.pem` file that's free of expired certs.

> Why could that be?

We name things quite specifically. If you're just downloading the tarball and renaming it it's unlikely we'd recognise it. The `erlang` package is saved locally as `erlang-17.5.tar.gz` in `HOMEBREW_CACHE` for example whereas the upstream name is `OTP-17.5.tar.gz`.

**Comment by mistydemeo** [comment]
You can see the name to which Homebrew will save a formula's tarball by doing `brew --cache -s NAME`, for example:

```bash
$ brew --cache erlang -s
/Library/Caches/Homebrew/erlang-17.5.tar.gz
```

**Comment by themicmac** [comment]
Wow!! Thank you @mistydemeo and @DomT4 : That is exactly the info I needed. Once I changed the file names to the proper ones, brew install began recognizing them. Smooth sailing from there on to what I needed to do. Thank you.

**Comment by mistydemeo** [comment]
No problem! Let us know if you have any other issues.
