### ISSUE TITLE
subversion Perl bindings installed in the wrong place

### ISSUE THREAD

**Issue by rcaputo** [Homebrew/homebrew#41310]
I'm pretty sure this isn't intended and is at least one cause of persistent git-svn problems:

% find /usr/local/Cellar -name Core.pm
/usr/local/Cellar/subversion/1.8.13/usr/local/Cellar/perl/5.20.2/lib/site_perl/5.20.2/darwin-thread-multi-2level/SVN/Core.pm

**Comment by rcaputo** [comment]
Some part of homebrew thinks the bindings were installed in the correct location.

This file:

/usr/local/Cellar/subversion/1.8.13/usr/local/Cellar/perl/5.20.2/lib/5.20.2/darwin-thread-multi-2level/perllocal.pod

Says this:

C<installed into: /usr/local/Cellar/perl/5.20.2/lib/site_perl/5.20.2>

**Comment by DomT4** [comment]
It seems to depend on what your `PERL_MM_OPT` is.

Mine is `/Users/Dominyk/perl5` and it thinks I've installed the `perl` bindings into `C<installed into: /Users/Dominyk/perl5/lib/perl5>` consequently.

We may need to more manually tell it where to stick the Perl elements, rather than letting it sniff the environment so much, although that could be fun given we're running `subversion` under `userpaths`.

**Comment by rcaputo** [comment]
I've verified that copying subversion's perl bindings into perl's library solves git-svn problems finding Svn::Core:

cd /usr/local/Cellar/subversion/1.8.13/usr/local/Cellar/perl/5.20.2
pax -rw . /usr/local/Cellar/perl/5.20.2

**Comment by DomT4** [comment]
Should have been fixed by https://github.com/Homebrew/homebrew/commit/adaf83b57042c734a490a9cf2049bdf222b35af5.
