### ISSUE TITLE
libgcrypt failed to build on 10.11

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#41599]
Gist: https://gist.github.com/anonymous/53614a0121f75a5ad170

This is on a brand new 10.11 install, XCode 7.0, so hopefully there aren't any odd config issues messing this up.

[line 51 of 03.make.cc](https://gist.github.com/anonymous/ba09707332785a695670#file-03-make-L51) stood out to me, since it was the error that showed up closest to the bottom when run with --verbose. Looked in the temp folder when this was brewing, and didn't see anything being generated in there, but it's possible I just looked at the wrong time...

There's some errors/etc. in config.log, but I'm guessing that's just part of configuring for my system?

Could be an upstream error too, so if I'm reporting in the wrong place let me know.

**Comment by hspak** [comment]
This is a temporary workaround, but you can edit the formula and comment out `make check`. It'll install successfully and if you run make check manually yourself, the `random` test will pass as well.

I'm not sure what's messing up the path here. It's looking for the library where it would be installed before it is installed.

**Comment by lukeberry99** [comment]
How would I manually edit the formula? Complete brew noob  here.

**Comment by hspak** [comment]
My comment was for libgcrypt. You should be looking in the formula for libgcrypt, not this jabber client.

**Comment by lukeberry99** [comment]
Ahhh, of course. Thankyou.

**Comment by apjanke** [comment]
Upstream bug submitted: https://bugs.gnupg.org/gnupg/issue2056

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/29aa8ae5269d32f89e4607a5e184d4a75b019161

**Comment by DomT4** [comment]
Since this will now build on 10.11 due to the `make check` disabling, and it has been reported upstream, moving this to tracking in #40837.

**Comment by betoharres** [comment]
I did what @hspak said and when I updated my home-brew it had a merge conflict with the new update, I edited with the new line of code and now overtime I try to update( even after removing libgcrypt and installing it again) it throws this error: 

```
~ % brew update
Stashing your changes:
UU Library/Formula/libgcrypt.rb
Library/Formula/libgcrypt.rb: needs merge
Library/Formula/libgcrypt.rb: needs merge
Library/Formula/libgcrypt.rb: unmerged (6ba8dce95212d21d3e62993d3aa7a9d4c194de3e)
Library/Formula/libgcrypt.rb: unmerged (93de237d34ab53bbe608936c63d7692e824305ad)
Library/Formula/libgcrypt.rb: unmerged (e3a29d5db3639526be45c55189402e40561769a5)
fatal: git-write-tree: error building trees
Cannot save the current index state
Error: Failure while executing: git stash save --include-untracked --quiet
```

any ideas?

**Comment by betoharres** [comment]
ahh... I went to ``/usr/local`` and did a ```git reset``` and ```git stash``` and the git tree want back to normal; now I can ``brew update``

**Comment by dhess** [comment]
This appears to be happening because the "random" test forks itself several times (see tests/random.c). The initial invocation of random from the wrapper script works fine, but upon the 1st fork/exec from within the program, it does not appear to inherit the dylib path set by the wrapper script in tests/random. 

I would add this diagnosis to the gnupg bug tracker, but I can't figure out how, so if the original submitter is keeping up with this thread, maybe you could add this information there to help the issue along.

**Comment by DomT4** [comment]
Since it builds the `.lib` binaries against the `Cellar` path here I'm half tempted to do a `make check` after the `make install`.

```
====================
All 24 tests passed
(1 test was not run)
====================
```

I was fine leaving out `make check` for the duration of the El Cap beta as expecting everything to work whilst running a beta is unrealistic, but now more people are adopting El Cap I'd rather not keep it around.

`brew` will still bail out and remove the directory if `make check` fails even post `make install`, so that's not a major point of concern.
