### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by marek-step** [Homebrew/homebrew#41632]
```
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:338:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:331:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:295:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:241:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:240:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:239:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:239:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1258:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `doctor'
/usr/local/Library/brew.rb:124:in `<main>'
```

Xcode is new: Version 6.4 (6E35b)
brew update is running without any error. In my Shell everything is set to utf8 

Thank you for your great work! 

mstep at podiuminternational dot org

**Comment by bfontaine** [comment]
Which command did you run, and what was the full output?

**Comment by DomT4** [comment]
`cd $(brew --prefix) && git status` would probably be useful here as well, to see if there are any uncommitted modifications to the local repo.

**Comment by marek-step** [comment]
Thank you for your answers! 
I issued the command 
% brew doctor
And I got these error messages on my iMac. And just now I realised the same errors here on my laptop. 

the command cd $(brew --prefix) && git status is not working in my Shell tcsh - and frankly I don't understand it. In bash I get this answer:

$ cd $(brew --prefix) && git status
On branch master
nothing to commit, working directory clean

Thx again

**Comment by DomT4** [comment]
Can you try `brew doctor` in `bash` and see if you get the same failure?

**Comment by mistydemeo** [comment]
Do you have any files with non-ASCII filenames in `/usr/local`?

**Comment by marek-step** [comment]
I get the same errors in bash, yes. 

First level of /usr/local/ looks like:

CODEOFCONDUCT.md              MacGPG2/                      include/                      share/
 CONTRIBUTING.md               README.md                     lib/                          texlive/
 Cellar/                      4SUPPORTERS.md                 mysql@                        var/
 Frameworks/                   bin/                          mysql-5.6.25-osx10.8-x86_64/
 LICENSE.txt                   clamXav/                      opt/
 Library/                      etc/                          sbin/

I don't think there are any file names with outside Ascii ...

**Comment by marek-step** [comment]
I tried to move some folders out of /usr/local
clamXav
MacGPG2
texlive
mysql-5.6.25-osx10.8-x86_64

But brew doctor is still complaining about a strange encoding problem

Just to keep you updated.

**Comment by marek-step** [comment]
And to answer the question, whether I have some filenames with non-ascii characters, I made the following command (in tcsh): 

sudo find /usr/local/ -type f | pcregrep --color='auto' "[\x80-\xFF]"

Good idea? I get no results ...

**Comment by apjanke** [comment]
What do you get for the output of `locale`? It's a little strange that it's complaining about US-ASCII encoding instead of UTF-8.

You can surround code and output with triple backticks (\`\`\`...\`\`\`) to get it formatted as code (monospaced, respecting line breaks) in these GitHub comments.

The particular location in `doctor.rg` where it's erroring out is where it's checking resolved symlinks. So the non-ASCII character might not be in a filename under `/usr/local`, but rather in the target of a symlink under there.  Use this variant of your `find | grep` to locate symlinks that have non-ASCII bytes in either their name or their target path.

```
( LC_ALL=C; find /usr/local -type l -exec echo -n \{\} " -> " \; -exec readlink \{\} \; | pcregrep "[\x80-\xFF]" )
```

The LC_ALL=C is needed to make it check individual bytes instead of Unicode code points.

This might be filesystem corruption that's put bad data in a symlink. You can use Disk Utility to do a Verify and Repair on your drive.

**Comment by marek-step** [comment]
On 22/07/15 09:14, Andrew Janke wrote:
> What do you get for the output of |locale|? It's a little strange that
> it's complaining about US-ASCII encoding instead of UTF-8.
> 
> You can surround code and output with triple backticks (```...```) to
> get it formatted as code (monospaced, respecting line breaks) in these
> GitHub comments.
> 
> The particular location in |doctor.rg| where it's erroring out is where
> it's checking resolved symlinks. So the non-ASCII character might not be
> in a filename under |/usr/local|, but rather in the target of a symlink
> under there. Use this variant of your |find | grep| to locate symlinks
> that have non-ASCII bytes in either their name or their target path.
> 
> |( LC_ALL=C; find /usr/local -type l -exec echo -n \{\} " -> " \; -exec readlink \{\} \; | pcregrep "[\x80-\xFF]" )
> |
> 
> The LC_ALL=C is needed to make it check individual bytes instead of
> Unicode code points.
> 
> This might be filesystem corruption that's put bad data in a symlink.
> You can use Disk Utility to do a Verify and Repair on your drive.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/41632#issuecomment-123586303>.
> 




Hello Andrew!


No file corruption on both macs (iMac and PowerBook) is unlikely to
happen. And I am checking file corruption regularly with applejack ...


That's really interesting! I got finally an answer: Once again your
command is only working in bash and I got the following answer:

bash-3.2$ LC_ALL=C; find /usr/local -type l -exec echo -n \{\} " -> " \;
-exec readlink \{\} \; | pcregrep "[\x80-\xFF]"
find: /usr/local/mysql-5.6.25-osx10.8-x86_64/data/mysql: Permission denied
find: /usr/local/mysql-5.6.25-osx10.8-x86_64/data/performance_schema:
Permission denied
find: /usr/local/mysql-5.6.25-osx10.8-x86_64/mysql-test: Permission denied
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuPro-W3  ->
/Library/Fonts/ヒラギノ角ゴ Pro W3.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuPro-W6  ->
/Library/Fonts/ヒラギノ角ゴ Pro W6.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuProN-W3  ->
/System/Library/Fonts/ヒラギノ角ゴ ProN W3.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuProN-W6  ->
/System/Library/Fonts/ヒラギノ角ゴ ProN W6.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuStd-W8  ->
/Library/Fonts/ヒラギノ角ゴ Std W8.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraKakuStdN-W8  ->
/Library/Fonts/ヒラギノ角ゴ StdN W8.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMaruPro-W4  ->
/Library/Fonts/ヒラギノ丸ゴ Pro W4.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMaruProN-W4  ->
/Library/Fonts/ヒラギノ丸ゴ ProN W4.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinPro-W3  ->
/Library/Fonts/ヒラギノ明朝 Pro W3.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinPro-W6  ->
/Library/Fonts/ヒラギノ明朝 Pro W6.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinProN-W3  ->
/System/Library/Fonts/ヒラギノ明朝 ProN W3.otf
/usr/local/share/ghostscript/9.16/Resource/CIDFont/HiraMinProN-W6  ->
/System/Library/Fonts/ヒラギノ明朝 ProN W6.otf

Perhaps the script of brew doctor should exclude paths like
/usr/local/share/ghostscript/9.16/Resource/ ???


Thank you for your answer


marek

**Comment by apjanke** [comment]
Gotcha. Yeah, I overlooked that this was happening on multiple machines. Corruption is unlikely.

Okay. Now we're getting somewhere. Instead of having `brew doctor` exclude those paths, I think we should figure out why it's rejecting non-ASCII characters. They're totally valid, and might show up other places too.

What's output of `locale` on your machine?

**Comment by apjanke** [comment]
Oh, and here's the `csh` version of that command. The variable-setting syntax is slightly different; the rest is the same.

```
( set LC_ALL=C; find /usr/local -type l -exec echo -n \{\} " -> " \; -exec readlink \{\} \; | pcregrep "[\x80-\xFF]" )
```

**Comment by apjanke** [comment]
Where do you get those HiraKaku and HiraMaru fonts? I'd like to install them to try to reproduce this.

**Comment by apjanke** [comment]
I was able to reproduce this by making a similar symlink and misconfiguring my locale.

To set up the test case, run this while in a UTF-8 locale.
```
mkdir  -p /tmp/homebrew-non-ascii
touch  /tmp/homebrew-non-ascii/ヒラギノ角ゴ
cd /usr/local/bin
ln -s /tmp/homebrew-non-ascii/ヒラギノ角ゴ my-hirakaku-link
```

After that, `brew doctor` still runs fine. But if I set it to an ASCII locale with `LC_ALL=en_US.US-ASCII brew doctor`, then it breaks with a similar error message.

```
$ LC_ALL=en_US.US-ASCII brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.
You should probably `chown` them:

    /usr/local/share/man/mann
Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:338:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:331:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:295:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:241:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:240:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:239:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:239:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1272:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1270:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1270:in `doctor'
/usr/local/Library/brew.rb:124:in `<main>'
[✘ ~]
$
```

This makes me think that it's a locale configuration issue. @marek-step, what's the output of `locale` for you? For example, I get this.

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
[~]
$
```

**Comment by marek-step** [comment]
Thank you for your replies and the lesson in tcsh-dialect :-)

my output of locale is:

```mstep% locale
LANG="en_GB.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL="C"
```

Looks different than the output of Andrew! I am impressed of your knowledge!

Best greetings


marek

**Comment by apjanke** [comment]
You're welcome!

All right, that locale setting is part of your problem. The "C" locale only supports a limited character set, and tells things to do bytewise processing; it's used more for programmatic string manipulation than human presentation. It is usually incorrect, or at least problematic, to have an interactive shell with "C" for any of its locale settings. Especially if you're going to be working with non-English characters.

Take a look at your shell startup files and terminal configuration to figure out where those `LC_*` values are getting set, and fix it. (Probably just by removing any `LC_<whatever>=...` lines you find. There's probably an `LC_ALL=C` in there somewhere.) That will probably take care of your immediate problem.

I can reproduce this with the C locale. It looks like it is interacting poorly with Ruby's string stuff.
```
$ LC_ALL=C brew doctor
[...snip...]
Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:338:in `plus'
```

I don't know enough about Ruby's locale support to know if that's expected behavior or not. I think that from POSIX's perspective, those high-value bytes fall under "unspecified" behavior because they're not part of the base "portable" character set. (See the LC_CTYPE section in [the POSIX locale definition](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap07.html#tag_07_02); "C" is an alias for the "POSIX" locale.) In any case, `LC_ALL=C` is going to be problematic for both `brew doctor` and maybe other Homebrew stuff.

Maybe `brew doctor` should include a test that looks at the locale and issues a warning if it's something suspicious? Or even forces itself to operate in UTF-8 mode? (Or whatever the system's default encoding is? Or the encoding for the filesystem we're examining?)

**Comment by apjanke** [comment]
Maybe `brew doctor` should include a test that looks at the locale settings it's run under and issues a warning if it's something suspicious? Or even forces itself to operate in UTF-8 mode? (Or whatever the system's default encoding is? Or the encoding for the filesystem we're examining?)

**Comment by DomT4** [comment]
We already [enforce UTF-8 for all formulae](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formulary.rb#L33-L41) since https://github.com/Homebrew/homebrew/commit/1dc3975a3a8374e4210ca0b69a989757db8808bf, so extending that to Doctor wouldn't be a particularly drastic step. CC @mikemcquaid for opinions.

**Comment by marek-step** [comment]
I removed all setenv encodings of my ~/.tcshrc file. 

In my Preferences of Terminal I unchecked the `Set locale environment variable on startup`button (in Profiles > Advanced) 

My locale are now 

```mstep% locale

LANG=

LC_COLLATE="C"

LC_CTYPE="C"

LC_MESSAGES="C"

LC_MONETARY="C"

LC_NUMERIC="C"

LC_TIME="C"

LC_ALL=
```

Brew doctor is still complaining as before. in tcsh or bash.

**Comment by apjanke** [comment]
Something is not quite right here. That is not what your locale should look like, and the empty `LANG` is worse than before.

This looks like `LANG` was getting set correctly before, but something was crushing it with `LC_ALL` or `LC_*` settings later on in your terminal/shell initialization sequence. (The `LC_*` settings supersede `LANG` for various aspects of the locale.) I'm not familiar enough with the `csh` style shells to suggest where this might be happening. (Maybe `csh` shells don't even initialize the locale in the same way? I dunno.)

As long as `LC_CTYPE` is getting set to `C`, `brew doctor` will keep breaking. And setting any of the `LC_*` things to `C` will probably cause you problems. Keep digging through your config files.

**Comment by mikemcquaid** [comment]
Enforcing UTF-8 for `doctor` makes sense :+1:

**Comment by marek-step** [comment]
Commenting out `setenv LC_ALL C` in my .tcshrc file made smile my brew doctor again. My locale settings are now: 

```LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=```

Thank you again for your help and insight


marek

**Comment by hvisage** [comment]
Okay, I'm having the same issue.
I believe I can relate it to: https://blog.hqcodeshop.fi/archives/56-Mac-OS-X-terminal-UTF-8-over-SSH.html
as I'm having painful issues with perl's UTF errors I get on the plethora of Debian machine I manage.
This leaves me with BlackYos:local hvisage$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

Reading the above, it looks like brew *insists* on UTF-8??

**Comment by bfontaine** [comment]
@hvisage UTF-8 is becoming the de-facto standard; it can encode all possible Unicode characters without taking too much space. From [Wikipedia](https://en.wikipedia.org/wiki/UTF-8):

> UTF-8 is the dominant character encoding for the World Wide Web, accounting for 84.6% of all Web pages in August 2015 (with the most popular East Asian encoding, GB 2312, at 1.3%). The Internet Mail Consortium (IMC) recommends that all e-mail programs be able to display and create mail using UTF-8, and the W3C recommends UTF-8 as the default encoding in XML and HTML.

**Comment by hvisage** [comment]
@bfountaine output for reading websites, is not the same as output needed for managing systems.

**Comment by apjanke** [comment]
@hvisage UTF-8 is good for managing systems, too, for similar reasons. Especially on OS X. HFS+ uses Unicode for its file names, and there is wide support for Unicode and UTF-8 in terminal emulators and text editors. In particular, UTF-8 is the default encoding for Terminal.app and iTerm2. And it seems to be the de facto standard for non-English text in files distributed with Western software; can't recall the last time I saw something different.

Homebrew requires a Unicode or similar encoding because it supports text that falls outside the 7-bit ASCII range: some of the text in programs it handles, or in users' filesystems (as is the case in this issue), may include non-ASCII characters. 

(The post you linked to looks like an issue with locale name configuration, not encodings per se. A plain "UTF-8" isn't a valid standard locale name, and won't be recognized on all systems.)

Do you think there's an actual problem with using UTF-8 here, or a different encoding that should be used?

**Comment by hvisage** [comment]
Okay, I'll then just have to handle the situation with the remote unixen that doesn't like the UTF-8 as it gets set/forced from MacOSX and brew that needs it UTF-8

**Comment by apjanke** [comment]
You will already need to handle that situation, since the default locale in OS X is a UTF-8 one. It sounds like you're handling it now by forcing your locale to `C` in your startup scripts or terminal configuration, which is a pretty blunt approach and will break some things, including apparently Ruby. "Enforcing" the locale in `brew doctor` like mikemcquaid is referring to here will make this easier for you: it will make `brew doctor` use the UTF-8 encoding regardless of the current locale settings, so it will start working under a user with `LC_ALL="C"` set.

In the meantime, you could just define a little shell wrapper function or alias for `brew` that sets the locale to a UTF-8 one, and put that in your shell startup scripts along with the custom locale settings.

```
function brew() {
   LC_ALL=en_US.UTF-8 brew "$*"
}
```

**Comment by DomT4** [comment]
This is resolved now.
