### ISSUE TITLE
fltk: missing file Fl_Font.H

### ISSUE THREAD

**Issue by matlads** [Homebrew/homebrew#41693]
While trying to compile `dillo` I encountered this error
```
In file included from /usr/local/Cellar/fltk/1.3.3/include/FL/x.H:43:
/usr/local/Cellar/fltk/1.3.3/include/FL/mac.H:88:12: fatal error: '../src/Fl_Font.H' file not found
#  include "../src/Fl_Font.H"
```

**Comment by dunn** [comment]
Sorry you didn't get a reply sooner? Can you post `brew gist-logs dillo`, please, so we can take a closer look?

**Comment by matlads** [comment]
https://gist.github.com/b8c8d49ef0b29d60c8c0

**Comment by dunn** [comment]
This is something I should have noticed, but we don't have a formula for `dillo` in Homebrew.  Are you installing this from a tap?

**Comment by matlads** [comment]
Indeed we do not have a formula for `dillo`. I am trying to create one, but I am getting this (current) issue. The dillo.rb I am using is:

```ruby
class Dillo < Formula
  desc "A multi-platform graphical web browser"
  homepage "http://www.dillo.org"
  url "http://www.dillo.org/download/dillo-3.0.5.tar.bz2"
  sha256 "db1be16c1c5842ebe07b419aa7c6ef11a45603a75df2877f99635f4f8345148b"

  depends_on :x11
  depends_on "fltk" => :build

  def install
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}"
    system "make", "install"
  end

  test do
    system "true"
  end
end
```

**Comment by dunn** [comment]
We don't have the time to offer a lot of support for unofficial formula, but my guess is that's an issue with dillo rather than Homebrew.

**Comment by igorclark** [comment]
Hi there, I've got the same problem, it doesn't look like a Dillo problem on my system (`10.9.5`) though, unless I'm missing something:

```bash
In file included from /usr/local/include/FL/x.H:43:
/usr/local/include/FL/mac.H:88:12: fatal error: '../src/Fl_Font.H' file not found
```

Here's line 88 of `mac.H`, as installed by the Homebrew `fltk` formula:

```c
#  include "../src/Fl_Font.H"
```
(NB the 2 spaces between `#` and `include` are intentional, they're in the source file.)

There's no `/usr/local/include/FL/../src` directory, and in fact no `Fl_Font.H` anywhere under `/usr/local`.

I installed FLTK using `brew install fltk`, and it seems to look otherwise OK:

```bash
$ fltk-config --version --api-version
1.3.3
1.3
```
There doesn't seem to be any `fltk` source package available:

```bash
$ brew search /.*fltk.*/
fltk (installed)
```
And there don't seem to be any source options for the `fltk` package:

```bash
$ brew options fltk
--universal
        Build a universal binary
```


Am I missing something? :-)

Thanks!

**Comment by igorclark** [comment]
Aha. I just downloaded `fltk` from [fltk.org](http://www.fltk.org/), installed from source and tried to build `dillo` against it, and got exactly the same error. So FYI it looks like this is a problem with `fltk` on Mac OS - or even a `dillo` problem, though that seems less likely - rather than anything to do with the Homebrew `fltk` formula. I'll follow up there.

Cheers!

**Comment by matlads** [comment]
It is a dillo problem. I tracked it down to where dillo unconditionally includes X headers when it detects X, even though fltk was not compiled with X support.

I am still trying to setup my email account to talk dillo-dev, and then was going to report this, and send in a patch to potentially fix the issue

**Comment by andeElliott** [comment]
Having exactly the same issue (trying to build dillo on mac not make a homebrew formula), thank you very much for this useful thread

**Comment by yesyves** [comment]
Do you have the patch ready ? The easiest way for dillo is usually to email the main developper.

**Comment by matlads** [comment]
upstream seems to have fixed this issue; see http://hg.dillo.org/dillo/rev/3483500fcec7
