### ISSUE TITLE
iojs and npm

### ISSUE THREAD

**Issue by pvinis** [Homebrew/homebrew#41719]
when installing iojs, it says that npm is not installed. it doesnt say how to actually install npm. would be nice if there was some more guidance. thanks.

**Comment by DomT4** [comment]
We don't formally support `npm` with `iojs` in Homebrew at this time due to the need to patch `npm` still, which makes it difficult to switch between node & iojs installations without breakage. You can see ongoing progress working towards that in #36369.

There is a [way](https://github.com/Homebrew/homebrew/pull/36369#issuecomment-98920689) to do so, but we don't formally support it yet, so at your own risk, etc.

There's also the unofficial [iojs](https://github.com/aredridel/homebrew-iojs) tap which does support `npm` use in `iojs`.
