### ISSUE TITLE
ghc formula can't be used as a stage0 compiler for GHC itself

### ISSUE THREAD

**Issue by rodlogic** [Homebrew/homebrew#41777]
The issue has been reported [here](https://ghc.haskell.org/trac/ghc/ticket/10543#comment:3) and is caused by the following line: https://github.com/Homebrew/homebrew/commit/b160b165d42f07abc912b1903095c593de61a0df#diff-e06a9de6bb362e22e1ceb9a66eaf171eR72

The above line doesn't seem to be needed in this specific case, since GHC build system will select the right default for each platform. The question is why was this line needed in the first place. Can it be removed?

Here are the steps to reproduce on OS X 10.10:
```bash
brew update
brew install ghc
git clone --recursive git://git.haskell.org/ghc.git
cd ghc
./validate
```

And this is the error:
```
libraries/Cabal/Cabal/Distribution/Simple/BuildTarget.hs:392:24:
     error: \u used with no following hex digits; treating as '\' followed by identifier [-Werror,-Wunicode]
matchBuildTarget pkg = \utarget fexists ->
                       ^
1 error generated.
make[1]: *** [utils/ghc-cabal/dist/build/tmp/ghc-cabal] Error 1
make: *** [all] Error 2
```

**Comment by mikemcquaid** [comment]
@geoff-codes Thoughts?
@rodlogic Could you submit a PR to remove it? Thanks!

**Comment by geoff-codes** [comment]
So, the line referenced above was added to override https://github.com/ghc/ghc/blob/master/aclocal.m4#L2263, as not all the supported versions of clang (i.e., the ones that Apple provides) support these `-Wno-`s. We may still have been targeting 10.7 still at the time — I don't remember precisely — so I'm more than happy to take the line out and see what @BrewTestBot makes of it. But if we get build failures, a decision will have to be made.

@rodlogic Is there a reason why the stage 0 bootstrap _has_ to be built with `-Werror`? These warnings are pretty benign (indeed, more benign than the flags to suppress them). And what exactly is the significance of the `\u` in the source file, in this particular case? [Unicode literals are not supported in POSIX](http://stackoverflow.com/questions/27652458/whats-the-best-way-to-embed-a-unicode-character-in-a-posix-shell-script#comment50176924_27652458), and Mac OS X being a certified UNIX system, this is unlikely to change. The only way to encode an arbitrary character in ASCII is is to use the octal sequences that comprise the glyph in an encoding. And of course, you could simply use the actual glyph, treating the source file as UTF-8. But this seems particularly odd to me here, since the character that follows is `t`, so why is this needed here at all? What am I missing?

**Comment by geoff-codes** [comment]
Ok, lets see how #41930 fairs.

**Comment by trommler** [comment]
> Is there a reason why the stage 0 bootstrap has to be built with `-Werror`?
It is set in the standard validate build used before submitting a patch. There is a way to disable it though.  
> But this seems particularly odd to me here, since the character that follows is t! So why is this needed here at all? What am I missing?
GHC uses the C preprocessor on Haskell files and `-Wno-unicode` and others are needed to silence warnings that do not apply to Haskell code.

`\utarget` is a lambda abstraction in Haskell.

I guess it would be best for GHC to detect whether the C preprocessor supports the required flags in `configure`. I'll add that information to the ticket on Haskell trac.

**Comment by geoff-codes** [comment]
@trommler
> GHC uses the C preprocessor on Haskell files and -Wno-unicode and others are needed to silence warnings that do not apply to Haskell code. 
>
> \utarget is a lambda abstraction in Haskell.

I see. I would say this is a much larger issue, in light of this, since that's in direct conflict with C99/C++ extended identifiers. See:
http://llvm.org/releases/3.3/tools/clang/docs/ReleaseNotes.html#id4
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=9449
https://github.com/haskell/cabal/issues/2414
https://ghc.haskell.org/trac/ghc/ticket/9257

Perhaps there's a way to use something like `-traditional-cpp` or a `-std=c89` flag when you're using the C preprocessor on Haskell files, but I'm not sure.

**Comment by geoff-codes** [comment]
Well it looks like #41930 is now passing on all three targets. Not sure why bot.brew.sh didn't like it the first time, but I guess we'll never know; in any case it looks like we can stop overriding this flags, which takes care of it on the homebrew end of things. @mikemcquaid, merge and close?
