### ISSUE TITLE
undefined method `desc' for Formulary::Formulae::Cmake:Class

### ISSUE THREAD

**Issue by gbersac** [Homebrew/homebrew#41822]
For the command :

```
brew install homebrew/versions/glfw3
```

the ouput is :
```
==> Installing glfw3 from homebrew/homebrew-versions
Error: undefined method `desc' for Formulary::Formulae::Cmake:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/nfs/zfs-student-3/users/2013/gbersac/.brew/Library/Formula/cmake.rb:2:in `<class:Cmake>'
/nfs/zfs-student-3/users/2013/gbersac/.brew/Library/Formula/cmake.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:88:in `block in expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:76:in `expand'
/usr/local/Library/Homebrew/formula.rb:574:in `recursive_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:96:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:89:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:163:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:84:in `install'
/usr/local/Library/brew.rb:135:in `<main>'
```

The output of :
```
brew doctor 
```

is : 
```
[...]
Error: Failed to import: zebra
undefined method `desc' for Formulary::Formulae::Zebra:Class
Error: Failed to import: zeromq
undefined method `desc' for Formulary::Formulae::Zeromq:Class
Error: Failed to import: zile
undefined method `desc' for Formulary::Formulae::Zile:Class
Error: Failed to import: zinc
undefined method `desc' for Formulary::Formulae::Zinc:Class
Error: Failed to import: zint
undefined method `desc' for Formulary::Formulae::Zint:Class
Error: Failed to import: zmap
undefined method `desc' for Formulary::Formulae::Zmap:Class
Error: Failed to import: znc
undefined method `desc' for Formulary::Formulae::Znc:Class
Error: Failed to import: zookeeper
undefined method `desc' for Formulary::Formulae::Zookeeper:Class
Error: Failed to import: zopfli
undefined method `desc' for Formulary::Formulae::Zopfli:Class
Error: Failed to import: zorba
undefined method `desc' for Formulary::Formulae::Zorba:Class
Error: Failed to import: zpaq
undefined method `desc' for Formulary::Formulae::Zpaq:Class
Error: Failed to import: zpython
undefined method `desc' for Formulary::Formulae::Zpython:Class
Error: Failed to import: zsh
undefined method `desc' for Formulary::Formulae::Zsh:Class
Error: Failed to import: zsh-completions
undefined method `desc' for Formulary::Formulae::ZshCompletions:Class
Error: Failed to import: zsh-history-substring-search
undefined method `desc' for Formulary::Formulae::ZshHistorySubstringSearch:Class
Error: Failed to import: zsh-lovers
undefined method `desc' for Formulary::Formulae::ZshLovers:Class
Error: Failed to import: zsh-syntax-highlighting
undefined method `desc' for Formulary::Formulae::ZshSyntaxHighlighting:Class
Error: Failed to import: zshdb
undefined method `desc' for Formulary::Formulae::Zshdb:Class
Error: Failed to import: zssh
undefined method `desc' for Formulary::Formulae::Zssh:Class
Error: Failed to import: zsync
undefined method `desc' for Formulary::Formulae::Zsync:Class
Error: Failed to import: zurl
undefined method `desc' for Formulary::Formulae::Zurl:Class
Error: Failed to import: zxcc
undefined method `desc' for Formulary::Formulae::Zxcc:Class
Error: Failed to import: zzuf
undefined method `desc' for Formulary::Formulae::Zzuf:Class
```

**Comment by blj** [comment]
I am getting similar error for brew instal mysql on OS X 10.11

**Comment by bfontaine** [comment]
Please run `brew update` and try again.

**Comment by Diti** [comment]
```bash
$ brew update
Already up-to-date.
```

Same problem here. And exact same configuration than @gbersac, because we’re both using [our school](http://www.42.fr)’s Homebrew installation.

Here’s a relevant part of `brew doctor` about what the problem may be:
```
Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!
```
Also, have a look at how Homebrew is installed on our machines:
```
$ brew --prefix
/usr/local
$ brew --cellar
/nfs/zfs-student-5/users/2013/<student_login>/.brew/Cellar # Basically ${HOME}/.brew
```

Our home directories are on the network, and that’s where our individual Homebrew packages are installed. We do _not_ have the _write_ permissions on `/usr/local`; that directory stays local.

Any idea how we can make it work (considering that the school’s staff is pretty open, maybe we can find a better way to manage our thousand computers’ Homebrew installation in a better way)? Why did it use to work before, but not any more?

**Comment by DomT4** [comment]
Ah, this problem again. We saw this a while back with another student, I seem to recall. The problem last time was that the Homebrew in `/usr/local` was outdated and there was `$PATH` cross-contamination on which `brew` was being used.

Can you detail the setup a little bit more? Does only the `cellar` live in `<student_login>/.brew/` or is there a `.brew/bin/brew` in there as well?

Are your installed package executables installed into `<student_login>/.brew/bin` and that added to the `$PATH`, since you don't have write access to `/usr/local`?

**Comment by gbersac** [comment]
For me the problem seemed to solve without really knowing why.

I have a configuration like the one you mention : I installed brew in my home (~/.brew) while there seems to be some brew parts in /usr/local/Library/.

**Comment by Diti** [comment]
Hmm, interesting, so it could be a `$PATH` problem. In that case, could [`Superenv`](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-0.9.3.md) be the issue here?

About our setup: the Homebrew binary lies in `/usr/local/bin/brew`, and a `brew --version` returns `0.9.5` (I believe we are up-to-date). Surprisingly (for me at least), **yes, there is a `~/.brew/bin/brew`, and using it instead of the system’s one actually work**.

Yes, installed package executables are always put in `~/${HOME}/.brew/bin`, and it’s always been asked by the staff to add this line in our `~/.zshrc`:

```bash
export PATH=$HOME/.brew/bin:$PATH'
```

As I said, it is surprising to me to find a `brew` binary there.

I believe the issue is definitely related to `Superenv` after all, since it is said in your changelog that the user’s `$PATH` is ignored. Thus we are unconditionally using the `/usr/local/bin/brew` binary (but I can’t be 100% sure, I don’t know how to check the ./configure flags).

So, one workaround would be to ask our staff to roll back to Homebrew < v0.9.3, I guess? Or is it fixable by you in a future version?

**Comment by DomT4** [comment]
> export PATH=$HOME/.brew/bin:$PATH

Yes, this is how we solved it last time. There was cross-contamination with the `/usr/local` brew being out-of-date and that being used instead of the `brew` executable in the user's local directory (The latter of which the user could actually update).

> and a brew --version returns 0.9.5 (I believe we are up-to-date).

`brew --version` isn't really a super accurate indicator of how up-to-date someone is. There's a `Last commit` line in `brew config` that's a better indicator on that :).

> I believe the issue is definitely related to Superenv after all, since it is said in your changelog that the user’s $PATH is ignored.

This only applies during installations. For normal runtime, running brew update/upgrade, brew config, etc it will use your regular ol' `$PATH` setup. The only time we modify the `$PATH` is when you do `brew install xyz`. I don't think this is a superenv issue - I think it's a fairly regular `$PATH` placement issue.

If you do `export PATH=$HOME/.brew/bin:$PATH` and then do `brew update` do the errors you were seeing previously go away?

> So, one workaround would be to ask our staff to roll back to Homebrew < v0.9.3, I guess?

I suspect your entire Homebrew installation would break horribly if you did :wink:.

**Comment by Diti** [comment]
> If you do `export PATH=$HOME/.brew/bin:$PATH` and then do brew update do the errors you were seeing previously go away?

No, they didn’t! The reason I was suspecting `Superenv` is that my `$PATH` seemed to be ignored by `brew`! Since the issue “magically” got fixed, I do believe our school’s staff just changed something and that our configuration (including the `export`) wasn’t the problem.

Anyway, consider this issue fixed! (And hopefully noone else will get this error ever again haha!)

**Comment by DomT4** [comment]
It's not a superenv thing - Even if it was, you'd only be seeing it during installations and not for `brew doctor` and such.

As you can see from @gbersac's comment, it seems to be picking up Formula from `$HOME/.brew/Library/Formula` but using the `brew` files in `/usr/local`. If the school doesn't keep the latter up-to-date with the former, you will hit failure.

It may be useful for your school to run `brew update` on `/usr/local` once a day or such, that should reduce the amount of errors you hit from cross-contamination significantly.

Fingers crossed this doesn't reproduce. Feel free to hit us up again if it does. Thanks for the report!

**Comment by mikemcquaid** [comment]
It'd be useful if your school just didn't install Homebrew into `/usr/local` at all or forked Homebrew so that they fixed the issues caused by their silly installation method rather than us having to. To be clear: this isn't the fault of the students, though.
