### ISSUE TITLE
pidgin failed to build on 10.11 (Tcl development headers missing)

### ISSUE THREAD

**Issue by urdh** [Homebrew/homebrew#41968]
The `pidgin` formula fails to build on 10.11:

```
==> Installing pidgin
==> Downloading https://downloads.sourceforge.net/project/pidgin/Pidgin/2.10.11/
Already downloaded: /Library/Caches/Homebrew/pidgin-2.10.11.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/pidgin/2.10.11_1 --disable-avahi --di
checking for tclConfig.sh... no
configure: error:
Tcl development headers not found.
Use --disable-tcl if you do not need Tcl scripting support.
```

Presumably this means Tcl headers are no longer shipped with 10.11.

`brew gist-logs pidgin`: https://gist.github.com/3358fb122334a3bb5890

**Comment by apjanke** [comment]
I can reproduce.

I think this means you need to install the Xcode Command Line Tools. The headers for Tcl and other frameworks in `/System/Library/Frameworks` aren't shipped with the base operating system, but are installed along with the Xcode CLT.

I couldn't find any way in Xcode 7's GUI to install the command line tools. But running `xcode-select --install` brought up the dialog to install them. After that, the `/System/Library/Frameworks/*/Headers` directories appeared, and `brew install pidgin` worked for me. (This is on 10.11 Public Beta 2.)

```
$ xcode-select --install
xcode-select: note: install requested for command line developer tools
[~]
$ brew install pidgin
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://downloads.sourceforge.net/project/pidgin/Pidgin/2.10.11/
Already downloaded: /Library/Caches/Homebrew/pidgin-2.10.11.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/pidgin/2.10.11_1 --disable-avahi --di
==> make install
==> Downloading https://otr.cypherpunks.ca/pidgin-otr-4.0.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/pidgin/2.10.11_1 --mandir=/usr/local/
==> make install
🍺  /usr/local/Cellar/pidgin/2.10.11_1: 961 files, 34M, built in 2.5 minutes
[~]
$
```

**Comment by DomT4** [comment]
Does this path exist?

```
Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tcl.framework
```

**Comment by apjanke** [comment]
Yes, `Xcode-beta.app/.../MacOSX10.11.sdk/System/Library/Frameworks/Tcl.framework` exists for me, and it contains Tcl 8.4 and 8.5. They look like the same as in older OSes.

I notice that in the `configure` output in the logs gist for this, the `CMAKE_*_PATH`s are pointing at `/Applications/Xcode.app/` instead of `/Applications/Xcode-beta.app/`. Could that be related?

**Comment by urdh** [comment]
Hm, I was certain I had installed CLT, and `brew doctor` wasn't saying anything.
The path `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tcl.framework/` already exists (I renamed the Xcode beta to `Xcode.app`).

Running `xcode-select --install` does not work for me.

**Comment by DomT4** [comment]
Can you try adding this line to the top of `def install`?

```
ENV.append "CFLAGS", "-I#{MacOS.sdk_path}/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers" unless MacOS::CLT.installed?
```

And see if install passes.

**Comment by apjanke** [comment]
I'm afraid I can't perform a clean test of this right now.

I did a fresh install of OS X 10.11 PB and Homebrew, and it picked up the CLT and headers when I chose the defaults on the interactive prompts after installing stuff. I don't have time to re-test on variants at the moment.

###  Details   ###

I blew away my old El Capitan box and did a clean reinstall, since there doesn't seem to be an "uninstall" option for the `xcode-select --install` thing: it will change where the CLT are pointing, but won't uninstall the header files to get you back to a "clean" state.

I did a clean install of OS X El Cap Public Beta, did the update from the App Store, and installed Xcode. From there, I installed Homebrew using the `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` command from http://brew.sh.

After that, when I did `brew install pidgin` (with no other formulae installed), it popped up a prompt saying this.

![screen shot 2015-07-25 at 1 27 08 am](https://cloud.githubusercontent.com/assets/2618447/8888222/d09d2662-3272-11e5-8c98-38c701ca36c5.png)
```
The "xcrun" command requires the command line developer tools. Would you like to install the tools now?
Get Xcode / Not Now / Install
```

I already had Xcode installed at this point, so I picked "Install" (which was also the highlighted default choice in the dialog). It looks like this had the effect of `xcode-select --install`: while the `brew install ...` process was still working, I popped open another Terminal.app window, and sure enough, all the `/System/Library/Frameworks/*/Headers` directories were there now.

So, `brew install pidgin` worked fine for me with no formula changes. But it's not a valid test. I'm not sure how to reproduce the state (headers not installed, but formula commands not producing a prompt to install CLT) that OP is having. And I don't have time to try a fresh reinstall and hit the other "Get Xcode"/"Not Now" buttons.

For reference: The old box that I was able to reproduce this error with was from a clean partition on which I installed OS X 10.9 and then upgraded to 10.11 from an installer downloaded from the App Store on that machine. I don't remember the exact sequence of other things I did on that box. I don't recall ever being presented with this dialog for installing the Xcode CLT on that path.

**Comment by apjanke** [comment]
Also, that `xcrun` CLT dialog popped up pretty early in the process, while it was installing pig-config, intltool, xz, or gettext. (gettext also popped up the prompt to install the JDK a couple times.) Output from the install attempt [here](https://gist.github.com/apjanke/39894bcc521c851ec2b7).

**Comment by DomT4** [comment]
@apjanke Are you sure your `xcode-select` is pointing at a valid path? It's been a while since I used a completely clean system that I didn't immediately install Xcode onto, but I thought that window only popped up if you tried to use various development tools without either a valid Xcode or CLT installed. Could be wrong, has been a while.

> (gettext also popped up the prompt to install the JDK a couple times.) 

This is known, and frustrating. CMake does the same thing - Both of them probe for Java and then fire a `-version` command at one of the Java executables. On most platforms would be harmless and silent, but Apple pops up a special GUI telling you to install them, which isn't suppressed. There's discussion on that in #42042.

> Output from the install attempt here.

Libpng's was updated upstream, and the old version apparently pulled from the server afterwards. The error there should be fixed by https://github.com/Homebrew/homebrew/commit/ac3e1367c01248e09a0852356510c103f4696b4c after an update.

**Comment by apjanke** [comment]
@DomT4: That was it. I had not done an `xcode-select --switch` to point it to a valid path. I didn't know that worked without doing an `xcode-select --install` first. Sorry for being obtuse about it.

I did a clean wipe & reinstall of OS X 10.11, installed Xcode 7 beta 4 and did `xcode-select --switch` to point at it. Doing `brew install pidgin` reproduced OP's issue with the Tcl failure.

That `ENV.append "CFLAGS", ...` did not fix it. Same error: `configure: error: Tcl development headers not found.`.

I also tried moving [these tcl-related lines](https://github.com/Homebrew/homebrew/blob/4c6857b0e337b2d5afd49dcf7209b6b5091709f4/Library/Formula/pidgin.rb#L67-L68) outside the `if build.without? "gui"` block so they were run unconditionally, including in the default case when building the GUI.

```
    args << "--with-tclconfig=#{MacOS.sdk_path}/usr/lib"
    args << "--with-tkconfig=#{MacOS.sdk_path}/usr/lib"
```

So now it looks like this.

```
    args << "--with-tclconfig=#{MacOS.sdk_path}/usr/lib"
    args << "--with-tkconfig=#{MacOS.sdk_path}/usr/lib"
    if build.without? "gui"
      args << "--disable-gtkui"
    else
      args << "--disable-idn"
    end
```

That fixed it. With that change, `brew install pidgin` succeeded without errors.

Pidgin and finch run, though `pidgin` did complain about its plugin directory.

```
Andrews-MacBook-Pro:Frameworks janke$ pidgin
Couldn't create plugins dir
```

**Comment by apjanke** [comment]
This issue might not be specific to 10.11. I put together a clean OS X 10.10 Yosemite test box with Xcode 6.4 (but without doing `xcode-select --install), and `brew install --build-from-source pidgin` errored with the same "`Tcl development headers not found`" error.

Here's the logs: https://gist.github.com/9fbed3bf6f9882597356

This looks like a broader issue that is being exposed on 10.11 because of the lack of bottles for that version. is it possible the bottle building machine has the CLT and headers installed, so it's avoiding this error?

**Comment by DomT4** [comment]
> So now it looks like this.

I wonder if the tcl/tk requirement is necessary all the time rather than just for Finch, given that works for you.

> Couldn't create plugins dir

Hmm. That's a little odd. It should be `~/.purple/plugins` and created on initial run.

> Is it possible the bottle building machine has the CLT and headers installed, so it's avoiding this error?

Yup, the bots always have both the CLT & Xcode installed.

**Comment by mistydemeo** [comment]
This is a problem with Apple's `tclConfig.sh`, unfortunately; even the version located in the Xcode SDKs points to headers in locations only present in the CLT. We my need to turn Tcl off if the CLT isn't installed, unless we're willing to try some big workarounds.

**Comment by apjanke** [comment]
> I wonder if the tcl/tk requirement is necessary all the time rather than just for Finch, given that works for you.

I suspect it is. The Pidgin doco has a [Tcl scripting HOWTO[(https://developer.pidgin.im/doxygen/dev2.x.y/html/tcl-howto.html). I also took a look through the source code, and there were lots of Tcl references in libpurple, the lower protocol-level layer. So it doesn't seem that the Tcl stuff is specific to the terminal-based front end; I think either the GUI or non-GUI versions can be scripted with Tcl and have that dependency if it's enabled, which it is by default.

> Hmm. That's a little odd. It should be ~/.purple/plugins and created on initial run.

That dir is there and looks like it was created on the first run.

@mistydemeo: 
> This is a problem with Apple's tclConfig.sh

At what point does the error show up? I see those hardcoded CLT (and `/Applications/Xcode.app`, despite this being `Xcode-beta.app`) paths in Xcode's `tclConfig.sh`. But the `pidgin` build succeeded on my test machines, which don't have the CLT installed. Would it cause a runtime error, or break plugins or other things that would be compiled against it later? I don't know Tcl so I don't know what the impact would be.

Maybe it's not a deal-breaker, if programs have an alternate way of finding the headers? E.g. `$TCL_INCLUDE_SPEC` looks like the one with the path to the CLT-installed headers. In the pidgin source distribution, it uses that, but also looks under `$TCL_PREFIX` for the headers.
```
➜  pidgin-2.10.11  grep -r TCL_INCLUDE_SPEC *
configure:			CPPFLAGS="$CPPFLAGS $TCL_INCLUDE_SPEC -I$TCL_PREFIX/include"
configure:	TCL_CFLAGS="$TCL_INCLUDE_SPEC -I$TCL_PREFIX/include"
configure.ac:			CPPFLAGS="$CPPFLAGS $TCL_INCLUDE_SPEC -I$TCL_PREFIX/include"
configure.ac:	TCL_CFLAGS="$TCL_INCLUDE_SPEC -I$TCL_PREFIX/include"
```

**Comment by apjanke** [comment]
Here's the logs from the Python link error I get on 10.9 (only) after the formula fix lets it get past the Tcl header errors. Let me know if I should open this as a separate issue.

https://gist.github.com/1a7c16b8b0f9b859a4cb

**Comment by apjanke** [comment]
>> Hmm. That's a little odd. It should be ~/.purple/plugins and created on initial run.

> That dir is there and looks like it was created on the first run. Dunno why it's complaining.

Aha. The `~/.purple` directory gets created on the first run, but the `~/.purple/plugins` directory under it doesn't get created until the second run. Looks like it's trying to create them out of order. Doing `rm -rf ~/.purple; pidgin &` will reproduce the `Couldn't create plugins dir` error message.

Happens on both 10.11 and 10.9.

I'll see if there's an upstream bug report for this.

**Comment by DomT4** [comment]
> even the version located in the Xcode SDKs points to headers in locations only present in the CLT

Not sure whether to laugh or cry :confounded:. I'm fine with us disabling it if we can't find an acceptable solution, I don't know if it's used more widely than scripting.

> Here's the logs from the Python link error I get on 10.9 (only) after the formula fix lets it get past the Tcl header errors.

`/usr/lib/libpython2.7.dylib` is a symlink to `/System/Library/Frameworks/Python.framework/Versions/2.7/Python` I believe. Not sure why linking against that wouldn't work though. Any thoughts @tdsmith?

**Comment by apjanke** [comment]
Ah. The OS X 10.9 SDK [does not include the Python framework](http://stackoverflow.com/questions/19555395/python-framework-is-missing-from-os-x-10-9-sdk-why-also-workaround). It's there in the 10.8 SDK, was removed for 10.9, and added back in 10.10 for some reason.

I think this means: on a 10.9 system with CLT installed, it can use the `/System` Python framework which has had `Headers` installed. On later systems, without CLT installed, it can use the SDK from Xcode again.

Looks like this is what #23837 was addressing. Can't tell why it's not working.

Maybe it's because superenv is passing `--sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk` to `clang`, effectively relocating the root for library paths, so [the `python_dependeny.rb` pointing to `/System/Library/Frameworks/Python`](https://github.com/algrs/homebrew/blob/32900f2cc1a6203a3463f1e6cfcbbc86d43c30d4/Library/Homebrew/requirements/python_dependency.rb#L150) effectively points into the 10.9 SDK, too?

**Comment by tdsmith** [comment]
No particular insight but I had to do this silliness to get vim to link against the python framework on Xcode-only systems: #38471

I don't think it's a clear win to disable features to allow things to build without the CLT.

**Comment by apjanke** [comment]
I put in a PR for the Tcl/Tk fix: #42192.

Still breaking on 10.9 w/o CLT with that Python link error, but I'm putting the PR in anyway since I'm pretty sure the Python link error is independent, and just uncovered by the environment we're testing it in. Plus, it's not a regression.

@tdsmith: That sounds like the exact same link issue. I'm going to test out some of the other Python-linking formulae on my non-CLT 10.9 box and see if they're all subject to it. If so, that workaround or something like it should maybe be promoted to the core Python selection stuff.

**Comment by apjanke** [comment]
>>    (gettext also popped up the prompt to install the JDK a couple times.)
>
> This is known, and frustrating...

I think `freeling` might have popped up a modal iTunes license agreement dialog, too. Not sure about that; it might have been iTunes popping up on its own on my 10.11 test box, but its license dialog was up and progress on my build job seemed stalled inside `freeling` after `brew install freeling` being launched 30+ minutes previous.

**Comment by DomT4** [comment]
Is this resolved now with the two merged PRs?

**Comment by urdh** [comment]
I can build `pidgin` without issues now, so I guess the PRs fixed it.

**Comment by apjanke** [comment]
Same here; `master` is now working for me in my non-CLT 10.11 box.

**Comment by DomT4** [comment]
Great, Thanks for the confirmation both!
