### ISSUE TITLE
Support installing different versions of formula

### ISSUE THREAD

**Issue by nhjk** [Homebrew/homebrew#42036]
For example if I want to install version 1.9.3 of git, I should be able to do something like `brew install git 1.9.3`. `brew switch git 2.4.5` already provides a clean way of switching between versions.

Part 3b of this [stackoverflow answer](http://stackoverflow.com/a/4158763/2990742) shows how to do it. Based on the number of upvotes it seems like the above command version of this could be useful to many people.

**Comment by DomT4** [comment]
There was some discussion about why we killed the `Versions` command in #38414. It was a nightmare, essentially, and we had no way of digging back into the git history and retroactively apply fixes to old Versions that people were still using.

For that reason, and others, the Homebrew/Versions tap exists and I've spent a not insignificant chunk of time over the last 5+ months bringing it back into standard with the core, and adding bottles to almost everything that should be bottled. It is a significantly better experience than it was.

What people were hoping to use the `Versions` command for is more or less the same gig as being able to do `brew install homebrew/versions/xyz`.

The difference for us, massively, is that we have the ability to keep old versions *supported* in Versions and apply fixes where we wouldn't otherwise be able to. It also (to a degree) keeps older versions from ramming into core formulae and creating obscure compile failures.

Per everything mentioned above, and talked about in the many issues you can find on the `brew versions` command, I'm really quite :-1: on trying to roll some kind of support old versions stuck in the git history mechanism back into the core.

**Comment by mikemcquaid** [comment]
Closing as discussed, sorry!
