### ISSUE TITLE
Latest update to poppler, 0.34.0 breaks gdal --with-complete

### ISSUE THREAD

**Issue by JesseCrocker** [Homebrew/homebrew#42031]
Relevant portion of gdal build log https://gist.github.com/JesseCrocker/d6da469ec906c1890e75

Reverting to poppler 0.29.0 fixes the issue.

**Comment by DomT4** [comment]
Will probably be fixed when someone submits a version update to the [latest version](https://trac.osgeo.org/gdal/wiki/DownloadSource). Updating `gdal` tends to be quite involved, which is the delay. If you want to take a crack at it, we'd welcome a PR!

Otherwise we'll need to dump an older `poppler` in `libexec` or something.
