### ISSUE TITLE
Installing gettext asks to install Java?

### ISSUE THREAD

**Issue by victorhooi** [Homebrew/homebrew#42042]
I'm running OSX 10.11 (El Capitan) DP4.

I just did a `brew update`, followed by `brew upgrade --all`. As part of upgrading `gettext`, I got a prompt to install Java:

![screenshot 2015-07-23 11 03 28](https://cloud.githubusercontent.com/assets/243499/8840879/7d20ad7c-312a-11e5-8d50-958bd51bd2fc.png)

Is this expected?

**Comment by chdiza** [comment]
I don't know if it's expected, but I see the same thing.  I always just hit OK, since that doesn't download a JDK and the build proceeds anyway.

**Comment by chdiza** [comment]
Forgot to mention that I see it on Yosemite, and can recall seeing it on Mavericks as well.

**Comment by DomT4** [comment]
We might be able to do something about this. It reproduces on clean machines as far as I can see, tested a couple now.

```
  --disable-java          do not build Java sources
  --disable-native-java   do not compile Java to native executables
```

I'm not sure if it goes ahead and builds the Java stuff if Java isn't available or not. If it doesn't build it, we should probably make it optional or recommended.

**Comment by DomT4** [comment]
Doesn't make a difference. The Java window pops up anyway.

They run this block of code in their various deeper configure scripts:

```
  echo "$goodcode" > conftest.java
  echo "$failcode" > conftestfail.java
        if test -n "$JAVAC"; then
        if $JAVAC --version 2>/dev/null | sed -e 1q | grep gcj > /dev/null; then
            if $JAVAC --version 2>/dev/null | sed -e 's,^[^0-9]*,,' -e 1q | sed -e '/^4\.[012]/d' | grep '^[4-9]' >/dev/null; then
                        rm -f conftest.class
```

Running `javac --version` on OS X will produce the response `No Java runtime present, requesting install` which is suppressed followed by the GUI pop-up which isn't.

**Comment by chdiza** [comment]
FWIW, `cmake` also causes such a dialog box.

**Comment by DomT4** [comment]
`cmake` run a very similar check of asking for the version.

**Comment by DomT4** [comment]
Going to close here. The problem is irritating, but non-fatal and easily dismissed. Sadly there's not much Homebrew can do that's not incredibly hacky to try and handle this.

The answer would be to either ask Apple to change the way they handle pings to the Java executables when a full JDK isn't installed, or to notify upstream projects that Apple's Java handles this situation less silently than they intend. These installations are generally routing the Java check to `/dev/null` but that has no halting mechanism against the GUI being thrown.
