### ISSUE TITLE
Openssh from homebrew appears to be backdoor'ed.

### ISSUE THREAD

**Issue by seclorum** [Homebrew/homebrew#42119]
Per the instructions here:

http://www.welivesecurity.com/2014/04/10/windigo-not-windigone-linux-ebury-updated/

.. it appears that the openssh that ships with Homebrew is backdoor'ed:

````
$ /usr/local/bin/ssh -G 2>&1 | grep -e illegal -e unknown > /dev/null && echo "System clean" || echo "System infected"
System infected
$ /usr/bin/ssh -G 2>&1 | grep -e illegal -e unknown > /dev/null && echo "System clean" || echo "System infected"
System clean
````

Note that the '-G' option to ssh should result in the message "illegal option" .. but if the version of openssh that is shipping with homebrew right now has been patched with this patch:

https://github.com/openssh/openssh-portable/commit/957fbceb0f3166e41b76fdb54075ab3b9cc84cba

.. then the '-G' option is valid (but should produce a different message output, however - i.e. dumping the current configuration).  I have verified that this is not the case - so it makes me wonder if indeed brews' ssh is backdoor'ed?

**Comment by DomT4** [comment]
Thanks for the report.

Please note for security issues we have the security@brew.sh email address, where you can send us [PGP-Encrypted messages](https://keybase.io/homebrew/key.asc) if desired. We prefer to keep these things out of the Issue tracker until we know whether something is a threat so users aren't targeted en mass suddenly.

The Apple default OpenSSH on OS X 10.10 is `6.2p2`, which you can verify [here](https://opensource.apple.com/source/OpenSSH/OpenSSH-189/OpenSSH.plist). That version of OpenSSH has no `-G` functionality, which is why as you note you get the `System clean` message flagged at you.

Homebrew's OpenSSH is currently version `6.9p1`, which is the latest upstream available portable release. The report on the Ebury vulnerability was made public early March 2014, and details on how to test for the vulnerability were made public in the post you linked to in the middle of April.

In October 2014, OpenSSH committed new functionality to OpenSSH Portable that uses the `-G` flag, as you note also. I believe we merged that version of OpenSSH in early January of this year, with the 6.8p1 release.

The new functionality is also referenced in the [Changelog](ftp://ftp.ca.openbsd.org/pub/OpenBSD/OpenSSH/portable/ChangeLog) and the [Github mirror](https://github.com/openssh/openssh-portable/commit/957fbceb0f3166e41b76fdb54075ab3b9cc84cba) as commit `957fbceb0f3166e41b76fdb54075ab3b9cc84cba`.

Per the Changelog:

>  Add a -G option to ssh that causes it to parse its configuration and dump the result to stdout, similar to "sshd -T"

There's also reference to it in `man ssh`, if you wish to look, which is [mirrored here](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/slogin.1?query=ssh).

> (but should produce a different message output, however - i.e. dumping the current configuration).

This seems to be a misunderstanding in functionality. From the manpage:

> -G      Causes ssh to print its configuration after evaluating Host and Match blocks and exit.

You need to feed it something like `ssh -G dave awesome.ssh.com`. You can feed it anything except nothing. [There's been discussion of that before on Homebrew's mailing list](http://librelist.com/browser/homebrew/2015/4/21/openssh-6-8-ssh-g-not-working/).

All functionality is as expected and intended but OpenSSH here. No vulnerability or backdoor in Homebrew's OpenSSH appears to be present.
