### ISSUE TITLE
Vim python functionaly breaks when python is updated

### ISSUE THREAD

**Issue by ptzz** [Homebrew/homebrew#42171]
I'm using homebrew python as my default python and with homebrew vim I currently see `[...] -F/usr/local/Cellar/python/2.7.10_2/Frameworks  -framework Python [...]` when doing `vim --version`. Mostly/always vim plugins using python (e.g. `pymode`) breaks ("Python's site module could not be loaded" etc.) after upgrading python and `vim --reinstall´ is required to make it well-behaved again.

Does vim rely on the version of python available during install being the same as during runtime? If yes, would it make sense to force reinstall of vim if python is upgraded? It's not always obvious that a python version mismatch is the problem as some vim plugins will just start failing silently.

**Comment by DomT4** [comment]
We build vim under `std`, which means we adopt the user's `$PATH` exactly how it was before compile.

Relevant to your problem, we use `depends_on :python` rather than `depends_on :python if MacOS.version <= :snow_leopard`. The latter would normally mean *"Use the system Python unless building on 10.6 or below"*, but enforcing that wouldn't be effective here.

Instead we use `depends_on :python` which roughly means *"Use the first Python in the `$PATH`"*. In this case, because you have Homebrew's Python installed, Vim will link to that on compile, and will likely need rebuilding when you change something that was in your `$PATH` at the time of compile, whether that's Ruby or Python version.

>  If yes, would it make sense to force reinstall of vim if python is upgraded

Sadly, this is also difficult. We can't assume every user has Homebrew's Python installed, so revisioning the formula to force a rebuilt would be worthless for everyone who has Vim built against the system Python.

I'm afraid there's little we can do on these situations; We're aware of the various Vim complications and are working over time to try and handle them, but for now, you'll need to manually `brew reinstall vim` when things like this happen. Sorry! Thanks for filing the issue.
