### ISSUE TITLE
Cannot brew update (plus a long list of problems)

### ISSUE THREAD

**Issue by adv0r** [Homebrew/homebrew#42277]
MacOsX 10.9.5 ,  Xcode uptodate 

I believe brew is kind of broken on my machine, so broken I can't even update. 

```
⇒  brew update
error: pathspec 'master' did not match any file(s) known to git.
Error: Failure while executing: git checkout -q master
```

Here is the looong list of warnings the `doctor` told me https://gist.github.com/adv0r/0f2e9b033f2ea714ce6b 

I wish there was a way to start over.

**Comment by DomT4** [comment]
> I wish there was a way to start over.

[This](https://github.com/Homebrew/install/blob/master/uninstall) will destroy your Homebrew installation.

You should be able to fix the update errors with:

```
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```

Some of the other errors can be fixed by doing things like:
* `brew unlink berkeley-db4`
* `brew link automake freetype libyaml`
* `rm /usr/local/lib/libpng*`
* `echo export PATH='/usr/local/bin:$PATH' >> ~/.bash_profile`

**Comment by adv0r** [comment]
it worked, thanks!

**Comment by DomT4** [comment]
Great! Let us know if you have any further issues.
