### ISSUE TITLE
Mercurial lists /usr/bin/python even if Homebrew-installed /usr/local/bin/python is available

### ISSUE THREAD

**Issue by indygreg** [Homebrew/homebrew#42416]
If you `brew install mercurial`, the shebang from /usr/local/bin/hg is `#!/usr/bin/python` instead of `#!/usr/local/bin/python`. even if you have brew installed python. This is wrong.

https://stackoverflow.com/questions/28512350/homebrew-path-env-var-is-modified-before-installation-of-formulae-mercurial-wi has more details. I suspect this is a common problem with Python Homebrew packages. But I'm not sure exactly what. I'm not ready to just to the SO conclusion that this is strictly the result of using distutils. Then again, Python packaging is wonky.

I'm a Mercurial contributor. If this is an upstream bug, I'll land a fix upstream once the cause is identified.

**Comment by mikemcquaid** [comment]
This is because we provide a prebuilt package which assumes you're using the system Python.

**Comment by indygreg** [comment]
Which is problematic since Python <2.7.9 doesn't have a secure SSL/TLS implementation. But I understand your predicament: pre-built packages are preferred to building them locally.

Could the Mercurial package be updated to list Python as a dependency so it can reference /usr/local/bin/python[2.7]? Not sure what Homebrew's policy on this is...

**Comment by DomT4** [comment]
I've asked about this before and been shot down for understandable reasons. The answer is essentially to do `pip install mercurial` and use the SSL available via that.

I'm not sure how @tdsmith feels about adding a `depends_on :python => :optional` which would permit users to build against Homebrew's Python & OpenSSL as desired.

**Comment by tdsmith** [comment]
If Mercurial can use PyOpenSSL, we can bundle that, but this is functioning as intended.

**Comment by DomT4** [comment]
From the documentation it looks like `PyOpenSSL` would only be used for `hg serve`. Probably still worth bundling, but doesn't look like it solves the core "issue".

**Comment by DomT4** [comment]
If people want to play with it and decide if it resolves any of the issues that people want solving, I've opened #42431.

**Comment by indygreg** [comment]
I'm pretty sure PyOpenSSL requires explicit cooperation from Python code to actively use it. Mercurial has no such code. So installing PyOpenSSL by itself will do nothing to core Mercurial.

However, Mercurial extensions can do things like import requests/urllib3, which does use PyOpenSSL. FWIW, this bug was discovered from someone at Mozilla using a Mercurial extension that imported urllib3, which complained about the system Python not having a secure SSL context implementation. See https://bugzilla.mozilla.org/show_bug.cgi?id=1190218

**Comment by indygreg** [comment]
Here is Mercurial's SSL code for the latest 3.5 release: https://selenic.com/repo/hg/file/79f0cb97d753/mercurial/sslutil.py

The tl;dr is Mercurial will speak deprecated protocols like SSL (as opposed to TLS) on Python <2.7.9 because these older Python versions lacked an API to toggle individual protocols/versions. While you can argue Mercurial should look for and use PyOpenSSL (if available), in its current state, Homebrew's decision for Mercurial to use the system Python means Mercurial's security is compromised due to use of older, busted protocols.

There was a recent discussion about Mercurial's behavior at https://selenic.com/pipermail/mercurial-devel/2015-July/072153.html. The takeaway was Mercurial is urging people to run Python 2.7.9+ instead of working around badness in earlier Python versions. Personally, I'd like to see Mercurial optionally support PyOpenSSL. But if Homebrew could just use /usr/local/bin/python, that seems like an easier solution. Not sure what reasons against doing this @DomT4 was referring to.

**Comment by tdsmith** [comment]
Mercurial claims to support Pythons ≥ 2.6; if Mercurial isn't doing secure things, that's a Mercurial bug. (And yet, we must confront the world as it is.)

Per this message in the thread you provided (and the code you link), because of OpenSSL's API limitations, Mercurial uses exactly TLS 1.0 (i.e. not 1.1 or 1.2) on Python < 2.7.9 to avoid allowing SSL2/3: https://selenic.com/pipermail/mercurial-devel/2015-July/072158.html -- so it's not quite as bad as you're suggesting.

Bundling PyOpenSSL with Mercurial will eliminate the InsecurePlatformWarning you noticed because it's being emitted by requests. I think that's worth doing.

The problem with a `:python` dependency, which is how we specify "use the python we find in $PATH", is that bottles with a :python dependency are built against Homebrew's python when they're bottled (because we have to choose one), and Homebrew python is installed as a dependency of the bottles as a consequence. That annoys people who don't want to use Homebrew's python.

**Comment by tdsmith** [comment]
I guess we could always bundle Mercurial with its own private Python interpreter. (:trollface:, I think)

**Comment by indygreg** [comment]
Err, yeah, Mercurial on <2.7.9 only use TLS 1.0, which isn't so bad since server-side mitigations for its badness are possible. But still, it prevents people from requiring a newer version of TLS.

To be clear, requests/urllib3 is being injected from a 3rd party Mercurial extension, not from Mercurial or its official, bundled extensions.

For the people who don't want to use Homebrew's Python, I'd point them at the changelog for 2.7.9 where secure SSL was implemented. I would argue the system Python (2.7.6) is known insecure software and Homebrew should take the initiate to upgrade its users to secure software by installing its secure Python whenever possible. But, yeah, Python^W packaging is painful, so this would cause lots of pain.

Would it be possible for Homebrew to install Python into the Cellar but not link it in /usr/local? Then, Mercurial could reference /usr/local/Cellar/python/2.7.X/bin/python directly? I argue Python packages should already be doing this, as I've seen virtualenvs and other environments break when a Python is switched out from under them. Of course, this creates a mess for upgrades, as you need to find links to Cellar and update accordingly. What a mess.

Of course, I could probably add support for PyOpenSSL to Mercurial. I really don't think people would say no to giving <2.7.9 users better security.

**Comment by tdsmith** [comment]
Not quite either here or there but dstufft helpfully points to this as an example of getting ssl.wrap_socket-compatible behavior from PyOpenSSL: https://github.com/shazow/urllib3/blob/master/urllib3/contrib/pyopenssl.py

**Comment by tdsmith** [comment]
Donald also points to this list of ways SSL in python < 2.7.9 is bad: http://stackoverflow.com/a/29572470/892260

I'm starting to think we should consider bottling applications against Homebrew python by default on 10.10 and below, beginning a couple weeks after 10.11 is released, to mitigate the SSL issues.

**Comment by xu-cheng** [comment]
We may also consider to make `depends_on :python` meaning 2.7.10 or above. At the same time, is mercurial written in pure python , i.e. It doesn't actually link to Python library? If so, we can use `depends_on :python => :run` which won't create hard dependency to Homebrew Python.

**Comment by tdsmith** [comment]
distutils writes shebangs that will point to a specific python interpreter, i.e. /usr/bin/python or /usr/local/opt/python/bin/python, so we would need to rewrite them to avoid introducing a hard dependency.

**Comment by xu-cheng** [comment]
Changing shebang to `!/user/bin/end python` doesn't seem too dramatical. Also it would make Linuxbrew happier.

**Comment by mikemcquaid** [comment]
> I'm starting to think we should consider bottling applications against Homebrew python by default on 10.10 and below, beginning a couple weeks after 10.11 is released, to mitigate the SSL issues. (El Cap is expected to ship with Python 2.7.10.)

Didn't you say above that this is a Mercurial issue? Pretty much every single system duplicate that we have will have some sort of security issue (even if rated `LOW`) and Apple have decided it's not enough of a big deal to be worth migrating. I don't think this is anywhere near OpenSSL level security problems and we should think carefully before we start installing duplicates for everyone because we've decided on a higher security standard than the OS vendor we're using.

**Comment by aleth** [comment]
> Didn't you say above that this is a Mercurial issue? Pretty much every single system duplicate that we have will have some sort of security issue (even if rated LOW) and Apple have decided it's not enough of a big deal to be worth migrating. I don't think this is anywhere near OpenSSL level security problems and we should think carefully before we start installing duplicates for everyone because we've decided on a higher security standard than the OS vendor we're using.

The problem is that the current state of affairs is pretty misleading. If you brew install python and mercurial, "which python" will happily tell you that your security concerns are fixed, as you are using the latest python. But mercurial doesn't use it, despite also being installed via brew. I think it's safe to say that's unexpected behaviour from the point of view of most users (even if you might call it naive).

**Comment by mikemcquaid** [comment]
I don't think that's necessarily misleading; that's not how other package managers work either.

**Comment by DomT4** [comment]
>  (El Cap is expected to ship with Python 2.7.10.)

Just FWIW, 10.10.5 is shipping with Python 2.7.10 as well.

```
~> /usr/bin/python
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version)
2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
```

**Comment by DomT4** [comment]
For the curious, also landing in 10.10.5 are OpenSSL, Emacs, cURL & PHP updates. Mostly minor bumps, OpenSSL to the latest 0.9.8 release, Emacs gets a .x.x.1 bump, cURL is updated to the latest release.

**Comment by indygreg** [comment]
I have certainly operated under the assumption that *any* Python-related package installed by Homebrew "links" against Homebrew's Python. There have certainly been enough issues with Apple's system Python over the years to warrant avoiding it like the plague. (Although SSL issues aside, I think it has been at least a few years since anything major.)

To answer @xu-cheng, Mercurial has Python C extensions. Without them, performance drops off a cliff.

In response to @mikemcquaid's comment about Homebrew providing a higher security standard than the OS, I don't see a problem here. OS releases aren't very frequent. And, any out-of-band update has to meet a high threshold for acceptance (e.g. high security risk) because they are costly for Apple and users. Homebrew thus fills a gap between OS releases and can facilitate upgrades and fixes for things that don't meet Apple's high threshold for mid-release update. I think enabling better security of Python applications by having all Python-related packages use Homebrew's modern and secure Python should be highly considered. That being said, perhaps 10.10.5's shipping of Python 2.7.10 makes this irrelevant. But even then, you need 10.10.5. Do you want to exclude non-10.10.5+ users?

**Comment by tdsmith** [comment]
> 10.10.5 is shipping with Python 2.7.10 as well.

:tada: That's great news.

There are a couple of distinct issues and I think discussing them individually will be more helpful than describing the platform as secure or insecure. tl;dr is after looking at these separately I think I'm not too concerned anymore, especially since now we know this problem will go away for most of our user base if we wait a couple weeks.

The first is that the SSL API in the Python standard library before 2.7.9 has limited configurability: it's impossible to disable TLS Compression and it's not possible to refuse to connect over SSLv2 or SSLv3 without pinning exactly to TLS 1.0 (i.e. not 1.1 or 1.2). It also doesn't support SNI. I think that this does not have known security implications for most clients, connecting to responsibly maintained servers. It does make clients less featureful, because they cannot securely connect to TLS 1.2-only servers (which can be a problem for some audited environments) and cannot connect to services hosted with SNI. This has recently become visible because a popular library has begun issuing InsecurePlatformWarnings on Pythons < 2.7.9; this ticket originally arose from one of those warnings. The solution for developers is to avoid the standard library, using something like PyOpenSSL instead, but PyOpenSSL can be difficult to distribute because its dependency `cryptography` contains compiled extension modules that build against openssl.

A second issue is that handling secure transports correctly in Python prior to 2.7.9 requires attention from package authors; it is easy to accidentally build an application that fetches data over HTTPS without verifying server certificates. PEP 0476 gives a list of [several CVE assignments](https://www.python.org/dev/peps/pep-0476/#rationale) in Python software that resulted from failing to use the APIs correctly, due to poor API design. [CVE-2014-9365](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-9365) was assigned to Python for its default behavior and given a score of 5.8 (MEDIUM). The default behavior was changed in 2.7.9 to validate certificates.

For the specific case of mercurial: the former issue affects mercurial; the latter presumably does not. Since Mercurial is a mature project that intends to support legacy Python versions, I do think the onus is on mercurial to do something reasonable on pythons prior to 2.7.9. I think the current behavior (of mercurial and of the mercurial formula) is reasonable. Using PyOpenSSL if it's available would be a useful enhancement.

Using Homebrew's python for python applications by default would provide some defense against vulnerabilities in code using the standard library poorly. I don't have a sense of how widely stdlib functions are used against secure endpoints in the Python code that Homebrew can install. I'm sympathetic to the defense-in-depth ideal but having Python 2.7.10 in OS X 10.10.5 makes me much less worried because much less of our user base will be exposed to the consequences of SSL stdlib usage errors.

**Comment by jeffstyr** [comment]
FWIW I have an older Homebrew-installed Mercurial version (2.1.2) still, and for it the `#!` line in `/usr/local/bin/hg` is `#!/usr/bin/env python`, which seems like the most flexible. Not sure what changed, installer-wise.

**Comment by mikemcquaid** [comment]
> FWIW I have an older Homebrew-installed Mercurial version (2.1.2) still, and for it the #! line in /usr/local/bin/hg is #!/usr/bin/env python, which seems like the most flexible. Not sure what changed, installer-wise.

That's something that Mercurial sets themselves, we don't control it.

**Comment by tdsmith** [comment]
I think there is no outstanding action to take here, so I'll close the ticket.

I'm weakly concerned that using `/usr/bin/env python` adds entropy but for the case of mercurial it probably doesn't matter much. It should make no difference to Linuxbrew, since the shebang is written by whichever python does the installation, to point to itself.
