### ISSUE TITLE
Error when run "brew update"

### ISSUE THREAD

**Issue by besser** [Homebrew/homebrew#42588]
The error below appeared when I tried to update homebrew packages:

```
[~]$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by angelXwind** [comment]
If you run `brew update` a second time, this goes away. Not sure why this happens.

See issue #42553

**Comment by xvoland** [comment]
@angelXwind confirmed
```
$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
xvoland at MacBook-Pro-Vitalii.local  ~/Desktop
$ brew update
Updated Homebrew from 70752bb2 to 70752bb2.
==> New Formulae
homebrew/versions/antlr3
==> Updated Formulae
homebrew/science/nextflow
```

**Comment by DomT4** [comment]
@angelXwind It's pretty awesome that you use Homebrew!

The issue was triggered with https://github.com/Homebrew/homebrew/commit/e696e966c6cdf6bf9d7adf8b36f1457c0a01cbfe & resolved by https://github.com/Homebrew/homebrew/commit/ac5707c37470c25583d8fb712bf5dc04ab91db4b.

Quoting from the team chat:

> This is caused by different version of core files are loaded during `brew update`.

Moving the `require` to the top of the file in https://github.com/Homebrew/homebrew/commit/ac5707c37470c25583d8fb712bf5dc04ab91db4b ensures that all the files are loaded at initial execution and won't trip over itself later in the process. The update bug, as people have noticed, will happen once and never reproduce.

Closing here.

**Comment by besser** [comment]
Yes, I ran "brew update" a second time and that's gone ok!
Thanks
