### ISSUE TITLE
azmq formula

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew#42836]
I've created a [small formula for the library azmq](https://github.com/ahundt/homebrew-robotics/blob/master/azmq.rb). However, I'm not sure what tests could be done for the library, which mostly consists of headers. I'm also not sure if it meets the criteria for inclusion in homebrew yet.

**Comment by DomT4** [comment]
It meets our minimum requirements in terms of popularity. We would need a tagged, stable release though for inclusion into Homebrew - Otherwise it would be welcome in `homebrew/head-only`. It looks like there's example code available on the project [README](https://github.com/zeromq/azmq#example-code) which looks perfectly acceptable to use. You'd write that to the testpath with something like:

```ruby
test do
  (testpath/"test.c").write <<-EOS.undent
    #include <azmq/socket.hpp>
    #include <boost/asio.hpp>
    #include <array>

    another line
    another line
    so on
  EOS

  system ENV.cc, "test.c", "-lazmq", "-o", "test"
  system "./test"
end
```

If you get upstream to tag a stable release, add the test and check it functions, remove the default comments that are placed around the formula for tutorial then we'd be more than happy to review a PR on this. Thanks!
