### ISSUE TITLE
URL rewrite on-the-fly (Insecure Redirect, ie. Sourceforge)

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#42953]
Hi,

For case `HOMEBREW_NO_INSECURE_REDIRECT` set, SourceForge has like *no HTTPS/SSL enabled mirrors*, so this DownloadStrategy rewrites the `download.sourceforge.net` url to use `mirrorservice.org` (which has valid SSL certificate)

## Better idea

Because Homebrew provided should imho not prefer any specific mirror (what would be point of mirrors in that case, isn't it?) but qualified user should be able to provide custom Ruby module (not part of Homebrew github project) and on-the-fly rewrite URLs 

Given solution could be tweaked using ENV variable like `HOMEBREW_SOURCEFORGE_DOMAIN_REPLACE` which would be by default `"www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/"` but that is not really flexible.

## Original DownloadStrategy idea
```diff
diff --git a/Library/Homebrew/download_strategy.rb b/Library/Homebrew/download_strategy.rb
index 5243a75..dfbcf57 100644
--- a/Library/Homebrew/download_strategy.rb
+++ b/Library/Homebrew/download_strategy.rb
@@ -388,6 +388,25 @@ class CurlApacheMirrorDownloadStrategy < CurlDownloadStrategy
   end
 end
 
+class CurlSourceForgeSecureMirrorDownloadStrategy < CurlDownloadStrategy
+  def fetch
+    if !ENV["HOMEBREW_NO_INSECURE_REDIRECT"].nil?
+      oldurl = @url
+      @url = https_mirror
+      ohai "Sourceforge HTTPS: #{oldurl}"
+      ohai "=> converted to #{@url}"
+    end
+    super
+  end
+
+  def https_mirror
+     re = /(^https?:\/\/)(.+\.net\/project\/)(.+)/
+     @url.gsub(re) do
+       $1 + "www.mirrorservice.org/sites/download.sourceforge.net/pub/sourceforge/" + $3[0] + "/" + $3[0,2] + "/" + $3
+     end
+  end
+end
+
 # Download via an HTTP POST.
 # Query parameters on the URL are converted into POST parameters
 class CurlPostDownloadStrategy < CurlDownloadStrategy
@@ -853,6 +872,8 @@ class DownloadStrategyDetector
       SubversionDownloadStrategy
     when %r{^https?://(.+?\.)?sourceforge\.net/hgweb/}
       MercurialDownloadStrategy
+    when %r{^https://(.+?\.)?sourceforge\.net}
+      CurlSourceForgeSecureMirrorDownloadStrategy
     else
       CurlDownloadStrategy
     end
```

**Comment by mikemcquaid** [comment]
Could you submit a pull-request instead? It's much easier to comment and review.

**Comment by smarek** [comment]
@mikemcquaid surce if you want me to, however I'd be more happy with somebody propose PR for user-provided URL rewrite module

**Comment by DomT4** [comment]
FWIW, I am pretty :-1: on adding `ENV` or Download Strategy workarounds for specific use cases here.

Apache has a special download strategy because it actually requires fairly unique handling to use their geolocating mirrors and there's no workaround that isn't defaulting to Apache central mirrors which they've actively asked people to rarely use; this would add not insignificant code for an optional `ENV` which the manpage actively warns currently breaks stuff.

The long-term solution is to add secure mirrors to each formula that needs them and implement that fallback - We haven't implemented the automated fallback yet because it's not super super easy to knock out & I'm a fan of believing in the need to talk to upstreams about potentially heavier traffic flow before enabling it. There is a blanket solution in the pipeline.

I'm not convinced that dumping the responsibility for choosing alternative mirrors onto users is great; It'll make debugging connection errors harder for us which is already kind of a nightmare area.

Others can disagree me with as desired, and PRs are easier to review than Issues, but I'm concerned about going down this path.

**Comment by smarek** [comment]
@DomT4 I fully agree, that's why I think providing common URL rewriting module integrated with Homebrew environment would be more useful. This PoC solves just the situation with HOMEBREW_NO_INSECURE_REDIRECT being enabled and formulas being downloaded from Sourceforge, which has no official HTTPS mirrors (meaning no HTTPS redirect from `https://downloads.sourceforge.net/` URLs.

Also I don't think it's optimal to add manually secure mirrors to every formula, as these mirrors usually mirror whole domain/site (in this case sourceforge)

And the "better idea" is not talking about dumping responsibility on users, but providing supported workaround.

**Comment by mikemcquaid** [comment]
I think a happy medium could be to only adjust the download location if `HOMEBREW_NO_INSECURE_REDIRECT` is set. I also agree that setting a mirror for every formula seems to be redundant.

**Comment by smarek** [comment]
@DomT4 
Also, I'm not aware of any `list mirrors for specific file` mechanism working on SourceForge, like `download.gnome.org` has with Mirror Brain implementation (see https://download.gnome.org/WELCOME.msg.mirrorlist and https://mail.gnome.org/archives/gnome-infrastructure/2015-May/msg00035.html )

If there is any mechanism like that, then we for sure should use that for list and prioritize HTTPS mirrors.

@mikemcquaid 
currently PoC does modify the URL only in case `HOMEBREW_NO_INSECURE_REDIRECT` is set (not null), so that's cool :)

**Comment by DomT4** [comment]
On the ENV idea: To be somewhat blunt, I don't think anything great can come from allowing users to rewrite Homebrew URLs easily and conveniently on-the-fly.

It carries a small chance that it'll make life easier for people who are comfortable enough to use the method, whilst opening the window to making diagnosing local connection issues nigh impossible and ending up in situations where users downgrade their own security because someone on the web told them the best way to restore access to xyz was to do xyz.

> downloaded from Sourceforge, which has no official HTTPS mirrors

We've said this before, but this isn't really a Homebrew bug that Sourceforge supports zero HTTPS mirrors. There are plenty of upstream tickets Sourceforge is aware of on this.

> And the "better idea" is not talking about dumping responsibility on users, but providing supported workaround.

As I said, one is in the pipeline. It isn't an abandoned feature by any definition of the word. Our manpage on this feature is pretty explicit that enabling it right now will break stuff.

There will eventually be a whitelist of mirrors & safe fallbacks per domain, and to be honest, I don't really want to get three months down the line and have to revert a bunch of stuff to make the feature work as expected because we slotted in a short-term workaround to fix something we explicitly said would break in this circumstance.

**Comment by DomT4** [comment]
Feel free to submit a PR and we'll review it.

I'm just unconvinced on the need to insert workarounds to features that we explicitly warn are broken in places right now. I don't want to get into a cycle of warning people features are broken in certain circumstances and then creating this expectation that we fix them regardless of any long-term plan.

**Comment by smarek** [comment]
@mikemcquaid provided PR

@DomT4 I somewhat agree
Also from what you wrote, do I understand correctly you're currently working on mirrors whitelist/fallback solution? That seems to me like a proper long-term solution.

**Comment by DomT4** [comment]
Closing in favour of reviewing the PR.
