### ISSUE TITLE
Circular symlink on Lua formula

### ISSUE THREAD

**Issue by ketiko** [Homebrew/homebrew#42952]
``` sh
File system loop detected; `/usr/local/opt/lua/include/lua5.2' is part of the same file system loop as `/usr/local/opt/lua/include'.
```

Looks like lua5.2 is a symlink to it's parent directory.

**Comment by DomT4** [comment]
This is intended. Some software looks for Lua libs in `/usr/local/include` directly, other pieces of software check `/usr/local/include/lua5.2` so we cover both checks.

Where is the error you are seeing being thrown from?

**Comment by ketiko** [comment]
@DomT4 I was doing a find / -name man and came across it.  Nothing is crashing because of it, just saw the warning and thought I'd report it.

**Comment by DomT4** [comment]
Ah. Yeah, It's basically harmless. It's just `find`'s way of saying "Not going to look in here because I already have" really.

Theoretically we could fix it by creating a directory inside `include` instead and then symlinking each of the headers into there, but I'm not hugely bothered unless someone finds there's an issue somewhere.
