### ISSUE TITLE
ocaml will never be detected by llvm during configuration

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#43335]
OS X 10.11, XCode + CLT 7.0.0

First two gists are for `brew install llvm --with-clang --with-lld --with-lldb --HEAD [--env=std]`,
third is for plain `brew install llvm`

[Gist with --env=std](https://gist.github.com/aw1621107/255a653b4f317e707444)
[Gist without](https://gist.github.com/aw1621107/4dfb3da6abbd125e6edc)
[Plain install](https://gist.github.com/aw1621107/53fe98ea2b6960cc06e0)

Edit: First two links go to two copies of the same thing...

Short of it is that llvm will not be configured with ocaml bindings whether ocaml is 
installed or not.  Seems the $PATH used during configure/build doesn't include a 
path to the ocaml folders` (`~/.opam/<version>/bin or /usr/local/Cellar/ocaml/<version>/bin on my machine), even if the user's $PATH includes it.

I tried looking around for ways to fix this in the ruby file, but I didn't see anything 
about setting build variables/adding to superenv in the docs (or at least anything I
understood). I probably just missed it, though...

**Comment by mikemcquaid** [comment]
We'll probably need an option and `Requirement` to specifically enable this.

**Comment by RandomDSdevel** [comment]
Just wanted to note that building LLVM's OCaml bindings requires having ocamlfind, ctypes, and OUnit 2 installed from OPAM.

**Comment by RandomDSdevel** [comment]
Also, I've noticed that the earliest part of an LLVM build (the part you get manually when you just do `cmake -G "Unix Makefiles" /path/to/llvm/` or `cmake -G "Xcode" /path/to/llvm/`) doesn't seem to detect either Doxygen or Sphinx from the run-time environment, though I think I may have seen that the full-blown compilation process might find the former relatively soon after that step finishes, if not relatively early in the build.  That issue's a little more general, though, so I should probably file a separate, new one for that (or maybe even one for Doxygen and one for Sphinx?)

**Comment by aw1621107** [comment]
I don't remember whether Doxygen/Sphinx are normally in $PATH, but if not, maybe LLVM needs an explicit pointer there. I know the OpenJDK builds have issues finding jtreg because it normally isn't on the path, so maybe it's a similar issue?

If Doxygen/Sphinx can't be found in either the homebrew environment or in your normal env with an altered $PATH, then I would guess it's a different issue.

**Comment by RandomDSdevel** [comment]
OK, guess I'll get around to filing it eventually, then.

**Comment by UniqMartin** [comment]
Can this issue be closed in favor of PR #47076?

**Comment by aw1621107** [comment]
Sure!

**Comment by RandomDSdevel** [comment]
@aw1621107:  Just remembered that LLVM only detects and uses Doxygen and Sphinx when the `LLVM_ENABLE_DOXYGEN` and `LLVM_ENABLE_SPHINX` CMake variables, respectively, are set either in `CMakeCache.txt` or via the command line while invoking CMake.  I've only experienced this in my personal builds of LLVM, though, and I don't know what OCaml/OPAM

**Comment by aw1621107** [comment]
@RandomDSdevel Oh, that's different than what happened with my builds with OCaml -- I didn't have to do anything different beyond saying the formula depended on opam/ocaml and checking for the correct packages.

Sounds like Doxygen/Sphinx could go into a `--with-docs` option?

**Comment by RandomDSdevel** [comment]
@aw1621107 on OPAM/OCaml:  Given that what you said implies that a default installation of OPAM/OCaml either has `ocamlfind`, `ctypes`, and OUnit 2 baked into it or that you already had those packages installed for some other purpose; I think that attempting to build LLVM's OCaml bindings only fails if you don't have OCaml and OPAM set up properly.  In my case, I've been trying to do a system-wide installation of OCaml and OPAM, but I haven't yet succeed in doing that, especially since it isn't currently supported directly by those programs' internally just yet (I've filed a tracking issue for this at [OPAM's GitHub repository](https://github.com/ocaml/opam) under the name ['Official Support for System-Wide Installation of OPAM and its Packages (Tracking)'](https://github.com/ocaml/opam/issues/1950) as a feature request for this, so let's hope it gets worked on and pushed from [their 'Next' milestone](https://github.com/ocaml/opam/milestones/Next) into OPAM 1.3…)  

@aw1621107 on the possibility of a `--with-docs` option for the LLVM formula:  Perhaps, but which one of us should file an issue requesting that, and should we deal with any other LLVM CMake options by adding Homebrew ones?

**Comment by aw1621107** [comment]
@RandomDSdevel Turns out I was mistaken about not having to do anything special to build the bindings. The formula for LLVM currently uses superenv, so OPAM actually *shouldn't* be visible to LLVM. Something I did causes the superenv PATH to be replaced with my normal PATH when `--with-ocaml` is passed, though; that's why OPAM and OCaml were visible without me having to change the PATH in the formula. I filed a bug about that as #47260 . 

As for the docs, I should probably stop hogging all the LLVM PRs :P So you're free to take care of that if you would like. As for the other CMake options, I think it'd be nice to add them eventually, but I don't think there's any rush.

**Comment by RandomDSdevel** [comment]
@aw1621107:  
On the OCaml craziness:  Heh, go figure!  And that explains why OPAM _sort of_ works for me:  I was running `cmake -G "Xcode" ../` from the `./build/` subdirectory of a development copy of the LLVM repository that I keep outside of Homebrew at `/Volumes/Development/Repositories/LLVM/`.  

On the docs and options:  I'll try and get to it, but don't quit just yet; I don't mind if you ninja me, especially since you've done some great work with the LLVM formula already!  As for the other CMake options, I may open an issue to request discussion concerning which ones should be mirrored by some Homebrew options and how.

**Comment by RandomDSdevel** [comment]
@aw1621107:  OK, master issue created as #47269, and I'll post a link to whatever discussion ends up being had about the implementation of a `--with-docs` option once it pops up.

**Comment by aw1621107** [comment]
@RandomDSdevel Unexpected behavior is always fun!

And that issue looks pretty comprehensive; much more than I would have done at first. I'll shift over there.

**Comment by RandomDSdevel** [comment]
@aw1621107…
…on unexpected behavior:  Yeah, it _can_ be…but then there are the _really_ big cases that _aren't_ fun, right?  

…on the issue's scope:  You're very welcome; I just thought I'd point out whatever needed covering.
