### ISSUE TITLE
python integration breaks when Python upgrades

### ISSUE THREAD

**Issue by hacpai** [Homebrew/homebrew#43356]
When I open anything.py with vim, it prompt

    E887: Sorry, this command is disabled, the Python's site module could not be loaded.

Then I run `:python`

    E471: Argument required

`:python print 'anything'`

    E887: Sorry, this command is disabled, the Python's site module could not be loaded.

Recently homebrew upgrades Python so this might be relevant

**Comment by DomT4** [comment]
Try `brew reinstall vim`.

Vim is one of the few formula in Homebrew with semi-mandatory Python dependencies that aren't tied to the system's Python (because it uses `:std` env to build we essentially can't force it to pick one or the other). It seems to retain whatever paths it was compiled against.

**Comment by hacpai** [comment]
@DomT4 Thanks. It works.

**Comment by DomT4** [comment]
Thanks for the confirmation, closing here.
