### ISSUE TITLE
how to brew unlink specific formulae version?

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#43391]
This happened to me right now

    $ brew cleanup
    Warning: Skipping (old) /usr/local/Cellar/gnutls/3.3.16 due to it being linked
    Warning: Skipping (old) /usr/local/Cellar/zeromq/4.1.2 due to it being linked

I have installed two different versions of each formulae (have no idea why it happened):
/usr/local/Cellar/gnutls/3.3.16
/usr/local/Cellar/gnutls/3.3.17.1

and 
/usr/local/Cellar/zeromq/4.1.2
/usr/local/Cellar/zeromq/4.1.3

How to  unlink and remove the old versions?

**Comment by chdiza** [comment]
If `gnutls 3.3.16` is linked, all you have to do is `brew unlink gnutls`, since at most one version of a keg can be linked at a given time.

After unlinking it, do `rm $(brew --cellar)/gnutls/3.3.16` to remove it.

Then do `brew link gnutls` to link the most recent version of `gnutls` into your prefix.

**Comment by Drewshg312** [comment]
thanx for reply!
I've already done it this way:
```
$ brew switch gnutls 3.3.17.1
$ brew switch zeromq 4.1.3
$ brew cleanup
