### ISSUE TITLE
cmd/update: changed behaviour

### ISSUE THREAD

**Issue by vladshablinsky** [Homebrew/homebrew#43472]
https://github.com/Homebrew/homebrew/commit/3b98a75802024d40dc7b3b125d33fe6644e12e7a#diff-278960b31d25036b2a5e7e041556f671

Noticed these changes only today, I think the previous behaviour was pretty comfortable for working with formulae not on the master branch. I think, when you're not on the master branch, it's very likely that you make some development stuff and it is comfortable for you to get the changes you have on your not master branch.

It might be useful to have a flag or something to include that changes from not-master branch to report, because now we don't have anything from not-master branch. Am I the only one who found that behaviour comfortable? Before this commit it was very easy to test something related with adding/deleting/renaming formulae: you could just make a new branch, do whatever you want with a formula and then update from that branch.

I think if you don't need to have stuff from not master branch in the report, you can just update from master branch.

**Comment by UniqMartin** [comment]
Some information can be found in #42074, but since I'm more or less responsible for that change, let me provide a bit more context.

From my point of view `brew update` is basically doing only one thing, no matter the current branch: It updates the master branch. Therefore, it should also generate a report based on what it has done, i.e. the changes to the master branch only.

I think the use case you have, shouldn't be handled by `brew update`. If I understand you correctly, what you'd like to have is something like `git diff master..current-branch` but with the reporting of `brew update`. I believe something like `brew report master..current-branch` would be cool to have and it should only do the comparison, but shouldn't fetch changes and shouldn't touch the master branch at all. What do you think?

> I think if you don't need to have stuff from not master branch in the report, you can just update from master branch.

Unfortunately, this would not really work for me. I tend to work in a branch called `dev` that if basically `master` with a number of branches merged into it (work in progress, customizations that will never be accepted upstream, …). Because at least one of those branches tweaks the update process, I have to be in `dev` before running `brew update` for my customizations to have an effect. Does that make sense?

**Comment by vladshablinsky** [comment]
Hm, everything you said really has sense. I agree, that update updates only master so should include diff from what it really updates. So the current behaviour is OK, but I think something can be added.

Sometimes we need to do something with formulae and we want update to operate on that changed formulae. Since we can't change upstream Homebrew repository add/delete/rename formula there for fun/testing we need to have another Homebrew repository locally (let's call it homebrew-2) and have remote origin set to this local Homebrew copy. So the process of simulating formula rename looks like:

1. Go to `homebrew-2` repo.
2. Rename the formula in it, then commit.
3. Go to `homebrew` repo.
4. `brew update`
5. Analyse the results.
6. Checkout master and reset it to the previous state.
7. Checkout feature branch
8. Repeat 4-7 until you're happy.

For taps it looks almost the same.

I had used that algorithm until `Updater` became more intelligent and started to stash changes and return back to the initial branch. With that changes the behaviour of `report` was changed, so it included changes from the working branch. So you can see, that my algorithm could have been simplified:

1. Rename the formula on the working branch and commit.
2. `brew update`
3. Repeat until you're happy.

And it could be automatized:

1. `git checkout -b test-renames-branch`
2. rename and commit
3. `brew update`
4. `git checkout initial-branch`
5. `git branch -D test-renames-branch`

So it's easy to include to the script.

Sorry for so long description. Finishing. Once we had a similar conversation with @jacknagel about local diffs and he didn't want Homebrew to become a diff-parser. But then described behaviour appeared and it was implemented quite good and much better than I tried it to implement. And it made things easier for me, but don't know about the others. 

So what am I suggesting? @UniqMartin @mikemcquaid @xu-cheng how do you think maybe it worth having a `--include-local` or `--devel` or some other flag and include diff from local branch or as a variant both from local and updated master?

**Comment by UniqMartin** [comment]
Thanks for the detailed response! I wasn't aware of the discussion in #40104, but it has some good points in there and an interesting approach of solving the original problem using only Git.

I believe a more fundamental problem is that `brew update` is not only updating the repositories, but also performs additional actions based on those updates (tap migrations, migrations due to renames, maybe more in the future). This works perfectly for the typical user, who is always on the master branch and where history is only ever moving forward. For Homebrew developers who frequently switch branches and who test formula renames and tap migrations, this could easily lead to an inconsistent state between the Homebrew cellar and and their working copy of the repository. (Is this only a theoretical problem or have others actually experienced this?)

> So what am I suggesting? \[…\] how do you think maybe it worth having a `--include-local` or `--devel` or some other flag and include diff from local branch or as a variant both from local and updated master?

I think it would be quite difficult to get this right, especially if the local feature branch and the (updated) master branch have diverged. (And they will necessarily diverge, if master is pulled from upstream.)

Here's another suggestion. It seems a bit simpler to me, so maybe it could be more acceptable:

1. If `brew update` (without options) is invoked, do the usual thing, i.e. more or less `git checkout master`, `git fetch origin`, and `git merge origin/master`, followed by the usual processing and reporting.

2. If `brew update --update-to=<branch>` is invoked, run `git checkout master` and `git merge <branch>`, followed by the usual processing and reporting.  Ideally `<branch>` would be some feature branch for which the developer wants to test the update procedure. (It might be a good idea to make sure `HOMEBREW_DEVELOPER=1` is set and otherwise refuse to do anything.)

  It would be the developer's responsibility to reset `master` back to e.g. `origin/master`, such that subsequent invocations of `brew update` would work as expected.

  To me this seems more convenient than changing `origin` to a local repository and wrestling with what would be basically two Homebrew installations (as suggested in #40104). I don't know if it's worth the maintenance effort. And maybe I'm overstating the effort to handle two local repositories.

Sorry for the long comment. Just brainstorming here in the hopes of finding a good solution, maybe even one that can be integrated into Homebrew. :smile:

@vladshablinsky, I think I fully understand your use case and can sympathize with you. And hopefully you understand now why I pushed for the change that broke your workflow. (Sorry for that.)

**Comment by mikemcquaid** [comment]
> For Homebrew developers who frequently switch branches and who test formula renames and tap migrations, this could easily lead to an inconsistent state between the Homebrew cellar and and their working copy of the repository. (Is this only a theoretical problem or have others actually experienced this?)

I think this is somewhat theoretical and somewhat that Homebrew developers generally know how to resolve these sorts of issues locally. Would definitely like to find solutions to these problems though.

**Comment by vladshablinsky** [comment]
> To me this seems more convenient than changing origin to a local repository and wrestling with what would be basically two Homebrew installations (as suggested in #40104). I don't know if it's worth the maintenance effort. And maybe I'm overstating the effort to handle two local repositories.

@UniqMartin I think it's not much easier or convenient. Again, I'm speaking about what's convenient for me personally, don't know about the others. I'll try to come up with something this/next week.

**Comment by vladshablinsky** [comment]
I haven't come up with really good solution, but here are some thoughts. First of all the default behaviour is :+1: and I wanted to change it only if some flag is passed. I though about having two diffs: 
`initial_revision...current_revision`  and `initial_revision...current_other_branch_revision` and merging these diffs somehow into one, but it's tricky and I didn't want to change a lot of `diff` logic, so the solution is here:
* use `initial_revision...current_other_branch_revision` diff if `--from-branch` passed, otherwise use `initial_revision...current_revision` diff.

Here is the diff:
https://github.com/Homebrew/homebrew/compare/master...vladshablinsky:update-from-branch

I think having this flag is better than nothing, but it still can be not the good solution.

**Comment by UniqMartin** [comment]
@vladshablinsky If I'm understanding you correctly, you want an answer to the following question: What would happen if the branch `master` was updated to my current HEAD via `brew update`?

If that's the case, you don't need to do all the complicated stuff that is going on in `Updater#pull!` (stash, checkout, pull, …). You probably don't even want to fetch/pull updates from upstream. And really, why should `master` be moved to `origin/master`, if you are then looking at `master..some-other-branch` and acting on the changes introduced there? Instead, you could do something as simple as this at the very beginning of `Updater#pull!` (untested):

```ruby
if ARGV.include?("--from-branch")
  @initial_revision = `git rev-parse -q --verify master`.chomp
  @current_revision = read_current_revision
  begin
    safe_system "git", "merge-base", "--is-ancestor", @initial_revision, @current_revision
  rescue ErrorDuringExecution
    odie "Your HEAD is not a descendant of 'master'."
  end
  return
end
```
(And I think you really want that check using `git merge-base` at the end, because you don't want to end up with two revisions that have no meaningful relationship. If you perform a regular pull, the `--ff` option ensures you have this relationship.)

**Comment by vladshablinsky** [comment]
Firsly, I should say that I didn't think about updating without fetching/pulling, so I wanted to
1. get master updated from upstream
2. have report including `master..some-other-branch` diff. 

```
Before update:

-- A (master)
    \
     B (some-other-branch)

After update:

-- A -- C (master, origin/master)
     \
      B (some-other-branch)
```
If I could easily merge `A..C` diff with `A..B` diff I would do that.

Basically yes, I'm interested in `A..B` diff and if we don't need push/fetch stuff I'm totally agree with you.

**Comment by UniqMartin** [comment]
> If I could easily merge `A..C` diff with `A..B` diff I would do that.

If it was easy, we wouldn't need `git merge`. ;) I think the only reasonable way to get this merged diff is to actually create a temporary merge commit `D` from `B` and `C`, then look at `A..D`, and finally clean up by throwing away `D`. And if the merge cannot be done automatically (i.e. there are merge conflicts) it might be better to give up and ask the user to rebase their branch.

**Comment by vladshablinsky** [comment]
Maybe I confused you a little: by merging I meant any files included only in `A..B` are included in the result diff and if there are same files in bot `A..B` and `A..C` then include them from `A..C` to result "merged" diff.

**Comment by UniqMartin** [comment]
I see. As you say, merging those two diffs might be feasible, but I'm not sure it's worth the effort.

Maybe the snippet I suggested in [my comment above](https://github.com/Homebrew/homebrew/issues/43472#issuecomment-143653300) sufficiently covers your use case. If enough people feel it's useful, it could be adopted into Homebrew core. And if not, it shouldn't be too difficult to create an external command (e.g. `brew update-local`) that monkey-patches `Updater#pull!` and then simply runs `Homebrew.update` to do the actual work.

**Comment by vladshablinsky** [comment]
> but I'm not sure it's worth the effort.

Neither am I.

OK, I'm agree with you.

**Comment by mikemcquaid** [comment]
I think it could be a cool change but I guess it's up to @UniqMartin or @vladshablinsky if you'd like to implement it?

**Comment by vladshablinsky** [comment]
@UniqMartin I added those lines you suggested and I like how it works. 
Here is PR for the changes https://github.com/Homebrew/homebrew/pull/44893 .
