### ISSUE TITLE
moreutils does not install with --without-parallel if parallel is already installed

### ISSUE THREAD

**Issue by ljos** [Homebrew/homebrew#43662]
If parallel is already installed, moreutils will not install even if the --without-parallel flag is added.

**Comment by DomT4** [comment]
This is intentional I'm afraid, see https://github.com/Homebrew/homebrew/commit/55ee343824d0db27a950db170fc903a9566850b0.

Our conflict mechanism isn't intended to be as fine-grained yet as "x only conflicts with x if x options are used". Long-term we may consider changing that, but there's only a couple of cases where this applies. You can always `brew unlink parallel` to install `moreutils`.
