### ISSUE TITLE
Re-creating branch from #40640

### ISSUE THREAD

**Issue by nnutter** [Homebrew/homebrew#43679]
I would have liked to have commented on #40640 with easy instructions to restore the branch from the PR but @dunn locked it.  For the record I find that frustrating from the perspective of someone trying to help.

@knakayama could checkout #40640 [locally][1] to recreate the branch:

```
# remotes: origin is Homebrew, knakayama is fork
$ git fetch origin pull/40640/head:add-procmail-formula
$ git push knakayama add-procmail-formula
```

[1]: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by DomT4** [comment]
I suspect Alex locked it because people were pinging Jack, who is no longer involved with the project and we try to respect that by not nudging him.

You don't really need to recreate the branch. It's easier in this case where the PR has been closed for a while just to create a new branch locally &

```
curl -O https://raw.githubusercontent.com/knakayama/homebrew/a5016ebba27e166f72bc88cd0a032410ca78c1e4/Library/Formula/procmail.rb
```

And then push + resubmit it.

We welcome a PR on this, as Mike said.

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew/pull/40640#issuecomment-138357040.

**Comment by dunn** [comment]
Sorry about that @nnutter. I was trying to encourage a fresh PR, rather than trying to discourage discussion. Old PRs get buried and are harder to keep track of, so we don't mind people opening new issues.

**Comment by knakayama** [comment]
Sorry for my bad manner. I re-submit PR(#43686).
