### ISSUE TITLE
Offensive names

### ISSUE THREAD

**Issue by dale-ackerman** [Homebrew/homebrew#43822]
Do we really new a Formula named "thefuck"?

**Comment by DomT4** [comment]
That what upstream calls it, so yes, for better or worse. That particular formula has almost 13,500 stars on Github, 344 watchers & 630+ forks; It's not a minor or insignificant project.

Unless something is explicitly racist, sexist, homophobic, transphobic, hate speech or in some other way in conflict with our [Code of Conduct](https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md) we are unlikely to censor it. We include formula on merit rather than name, except in the aforementioned circumstances.

**Comment by dale-ackerman** [comment]
Thats a very politically correct list. So foul language is ok?  Its not surprising I guess.  Sure don’t want to offend anyone!


Dale Ackerman
dale8458@gmail.com

**Comment by DomT4** [comment]
If by politically correct you mean inclusive of people from a variety of socioeconomic, cultural & life backgrounds, sure. Homebrew isn't ashamed to be actively inclusive.

Formulae aren't banned from simply using words like "thefuck" or "bitchx" as that is what the upstream project has chosen to call itself.
