### ISSUE TITLE
`brew doctor` shows many unexpected header files

### ISSUE THREAD

**Issue by dbkaplun** [Homebrew/homebrew#43832]
I have compiled node from source, so I'm getting:

```
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/node/android-ifaddrs.h
    /usr/local/include/node/ares.h
    /usr/local/include/node/ares_version.h
    /usr/local/include/node/libplatform/libplatform.h
    /usr/local/include/node/nameser.h
    /usr/local/include/node/node.h
```

This makes sense. However I don't think this should be a default check as the presence of these header files shouldn't have any adverse effects.

**Comment by tdsmith** [comment]
Thanks for the feedback. This check is often very informative when people run in to trouble building software with Homebrew and it's hard to tell in advance what will cause problems. There's no concept of a non-default check because it's not very useful; if we need to diagnose something we want all the output. We don't plan to disable this check.
