### ISSUE TITLE
"brew deps --1" Sometimes Shows Double Entries.

### ISSUE THREAD

**Issue by the-real-tokai** [Homebrew/homebrew#43955]
In some cases `brew deps --1` seems to lists some entries (perhaps the last only) multiple times.

From my 97 installed formulas I only can reproduce it with a single one:

```
$ brew deps --1 imagemagick
fftw
fontconfig
freetype
ghostscript
jpeg
liblqr
libpng
librsvg
libtiff
libtool
libwmf
little-cms
little-cms2
openexr
pango
pkg-config
webp
xz
xz
```

(Note: the double "xz" at the end.)

**Comment by DomT4** [comment]
Pretty sure this happens because in this case `xz` is both a build time dependency and a run time dependency.

You need Homebrew's `xz` installed to be able to untar `.xz` source packages, so that's the silent (in terms of not being explicitly listed in any formula) build-time dep and the runtime dep is probably for LZMA.

You get the same thing with any `.tar.xz` formula which also has an `xz` runtime dep, such as `dpkg`.

**Comment by the-real-tokai** [comment]
Right, it lists it two times (in different categories) with `brew info imagemagick` too:

```
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: xz ✔, libtool ✔
Recommended: jpeg ✔, libpng ✔, libtiff ✘, freetype ✔
Optional: fontconfig ✔, little-cms ✘, little-cms2 ✔, libwmf ✘, librsvg ✘, liblqr ✘, openexr ✘, ghostscript ✘, webp ✘, fftw ✘, pango ✔
```

Interesting it only happens when `--1` is used. Nonetheless it probably should filter out the double entries to avoid confusion. :)

*(feature request)*

**Comment by DomT4** [comment]
To be honest, I'm not sure it's worth adding code complexity to solve a relatively niche case unless someone else really wants to work on this. I'll let a couple of the other maintainers comment their thoughts on this.

**Comment by dunn** [comment]
If it's something straightforward like `Array.uniq!` then I don't see the harm in looking at a PR.

**Comment by DomT4** [comment]
> unless someone else really wants to work on this

Xu did: #43966 :wink:

**Comment by the-real-tokai** [comment]
Works!

:+1:
