### ISSUE TITLE
Glade-3.18.3

### ISSUE THREAD

**Issue by dummys** [Homebrew/homebrew#43982]
Hi,

Is it possible to update glade to add the galde 3.18.3 which use gtk+3 and not gtk+ ?
Thanks

**Comment by dunn** [comment]
We'd love a pull request! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions :ok_woman:

**Comment by tschoonj** [comment]
I have also looked into this in the past but had to give up since this version needs a lot of patching before it can be compiled with gtk-quartz backend and gtk-mac-integration. The 3.18.3 version was unfortunately never tested properly on a Mac before it was released.

The current master branch compiles nicely so the issues have been fixed upstream. Hopefully they will make a release soon, perhaps already next week when gnome 3.18 will be launched.

**Comment by DomT4** [comment]
Closing per the above, but we'll take a PR when there's a release that builds/functions as expected. Note if you refer to `glade` the existing formula that has moved to `homebrew/x11` and the PR would need to be filed there.

**Comment by tschoonj** [comment]
Ideally there would be two formulas: the existing one in `homebrew/x11` which is the last version to support `gtk2` and the new one (perhaps to be called glade3?) which supports `gtk3`.

I will keep an eye on this
