### ISSUE TITLE
Unclear error message re: Xcode/iOS

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew#44191]
It's unclear how to resolve an error message while upgrading 

$ brew upgrade 

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool
$ sudo brew upgrade 
Error: Cowardly refusing to `sudo brew upgrade`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.

**Comment by DomT4** [comment]
The message: 
> Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Is actually be thrown from OS X, rather than Homebrew. It isn't something we have a huge amount of control over. If you do `sudo xcodebuild -license` you should be able to agree to the license & then be able to use everything as expected again.

**Comment by jasonhemann** [comment]
Hmm. I'm thinking about a way to sidestep things like that. Maybe a verbose-update that, for instance, would always prompt to agree to the xcode license?

**Comment by DomT4** [comment]
Our options are limited, to be honest.

I personally don't really want to go sniffing in the expected document for the right string on every `brew` run to see whether it's going to be an issue.

On a more fully automated measure, the problem kind of is that `brew` is not run under `sudo`; we explicitly don't support doing so, so suddenly being asked on `brew update` or such for your password has the possibility to be a rather confusing surprise. We also don't support interactivity in update/install because it's terrible UX.

**Comment by jasonhemann** [comment]
Fair answer.
