### ISSUE TITLE
kind of warning when "brew update"

### ISSUE THREAD

**Issue by noctuelle** [Homebrew/homebrew#44234]
Hello,
before writing I checked if this issue has been reported, but I have found no answer. I hope not to have miss it.

When I run brew update, I obtain:

Stashing your changes:
 M qhull.rb
?? qhull.rb~
Restored your changes:
 M qhull.rb
?? qhull.rb~
Already up-to-date.

Then brew doctor works fine, as well as when installing new packages. This is to say that I have no problem so far, but I would like to know what the above lines mean, please.

Best regards,
noctuelle

**Comment by DomT4** [comment]
You or something non-brew has modified the `qhull` formula from [homebrew/science](https://github.com/Homebrew/homebrew-science). If you aren't expecting that to be modified, you could do:

```shell
cd $(brew --prefix)/Library/Taps/homebrew/homebrew-science && git fetch && git reset --hard origin/master
```

That should reset the Science repo to the latest upstream commit and overwrite any local changes that conflict with that.

**Comment by noctuelle** [comment]
Thank you very much, DomT4, it worked smoothly!
Cheers!

**Comment by DomT4** [comment]
Glad to hear everything is as expected again! Thanks for closing :)

**Comment by mikemcquaid** [comment]
@DomT4 I'm almost wondering if this should just be silent and only output if there is an error?

**Comment by DomT4** [comment]
@mikemcquaid I'm not sure. I think they can be genuinely useful in the sense that if a user isn't intending for a formula file to be modified it's a point of interest that it has been.

The verbosity may be an issue though for some users; perhaps we could wrap it in an `env` for the update output and unconditionally complain in `doctor` or something.

**Comment by mikemcquaid** [comment]
@DomT4 Not sure I understand your proposal, can you elaborate? I agree somewhat about it being useful and I wonder if we maybe could just stash but not reapply in that case or something?

**Comment by DomT4** [comment]
@mikemcquaid I presumed your concern was that it hits users on `update`, where it may not be an actual problem, and because it was in `update` they'd see it frequently? Perhaps I misunderstood.

My reply to that presumption was the idea of only displaying the `update` warning to `HOMEBREW_DEVELOPER` env users who may actually have things they expect to be modified lying around.

For non-developer users we could either just stash unconditionally or move the warning to `brew doctor` where we explicitly throw the `These aren't necessary a problem, ignore them if everything is great` style caveat.

**Comment by mikemcquaid** [comment]
@DomT4 that all makes sense to me :+1:
