### ISSUE TITLE
Failure to build glib on OSX 10.8.5

### ISSUE THREAD

**Issue by dcwar** [Homebrew/homebrew#44286]
With glib v2.46, there seems to be a new requirement for 10.9. Is this deliberate, and if so, documentation as to why?

Output of `brew gist-logs glib` is at the link below:
https://gist.github.com/a9eeab731629f683842b

Many Thanks!!

**Comment by DomT4** [comment]
Thanks for creating the issue! It turns out this was wholly intended by upstream: https://bugzilla.gnome.org/show_bug.cgi?id=747146

We're discussing how to react to this, but given MacPorts raised a complaint upstream unsuccessfully I don't think we have much choice but to respect GNOME's decision here in some manner, sadly.

**Comment by mistydemeo** [comment]
I intend to patch this in Tigerbrew to restore support for OS X 10.4 and later, if that's feasible, but Homebrew may not decide to do the same as the patch won't be accepted upstream.

**Comment by tdsmith** [comment]
This is the only gtk-devel-list thread I see: https://mail.gnome.org/archives/gtk-devel-list/2015-September/msg00025.html

**Comment by mistydemeo** [comment]
Applied a patch on 10.8 and below which reverts the relevant GNotification commits.
