### ISSUE TITLE
gcc can't find compatible ISL

### ISSUE THREAD

**Issue by apaszke** [Homebrew/homebrew#44444]
Today I tried to install gcc, which failed with message: `configure: error: Unable to find a usable ISL.  See config.log for details.`. I had ISL v0.14 installed (and as far as I can see this is the default version that is installed with `brew install isl`).

The fix was quite simple - I had to tap `homebrew/versions` and install `isl012`. Can't this be included into gcc formula somehow?

**Comment by bfontaine** [comment]
Could you please post the output of `brew gist-logs gcc`? Thanks!

**Comment by DomT4** [comment]
We saw this failure message when someone hadn't installed the Command Line Tools on OS X 10.11 the other day. Not sure if the situation/config is similar here? The core `isl` hasn't been updated since May and was compatible then. The only recent change is the addition of the El Cap bottle in https://github.com/Homebrew/homebrew/commit/38a182b8c559d33c2d7af6c049fe7a983e6302ea.

**Comment by apaszke** [comment]
I had Command Line Tools installed earlier and I rerun the installation, but as far as I remember it wasn't enough to make it work.

The gist is available at: `https://gist.github.com/anonymous/45007ef3f6bbd6b68d59`

**Comment by apaszke** [comment]
But it's probably holding only the latest log, which has succeeded

**Comment by DomT4** [comment]
#44486 may fix this.

**Comment by kjhollen** [comment]
Encountered this today, too, on Yosemite. Here's my `brew gist-logs gcc`: https://gist.github.com/anonymous/11ba87cc932b253ecd0c

The last bit said I didn't have the developer tools installed, but I could have sworn I did to use git on the command line (maybe I just hadn't updated them since the El Capitan beta came out). Anyway, hope this helps.

**Comment by bogdan** [comment]
Having the same issue on 

```
Darwin worldwind 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

**Comment by bfontaine** [comment]
@bogdan Please don’t interrupt `brew gist-logs gcc` and post its output.

**Comment by bogdan** [comment]
@bfontaine thanks for your note, I thought it hangs forever. Updated my previous comment with full output.

**Comment by audiofeature** [comment]
Having the same problem. Can you tell the exact steps to solve this?
How do I "tap homebrew/versions and install isl012"?

**Comment by bogdan** [comment]
I was able to fix with: `xcode-select --install`

**Comment by audiofeature** [comment]
Yes it worked now doing this before.
