### ISSUE TITLE
/usr/local/lib exists while linking

### ISSUE THREAD

**Issue by mananwason** [Homebrew/homebrew#44532]
I was trying to brew install node but I had some unlinked files when I ran ```brew doctor``` . I tried running ```brew link node``` but I got 
``` Linking /usr/local/Cellar/node/4.1.1... Error: File exists - /usr/local/lib ```.

What should I do now to make this work?

**Comment by DomT4** [comment]
That's a bit odd. Can you `ls -l /usr/local`? Thanks.

**Comment by mananwason** [comment]
Thanks for the quick reply. This is the output
``` 
-rw-r--r--   1 user  admin    3161 Sep 14 09:38 CODEOFCONDUCT.md
-rw-r--r--   1 user  admin    1103 Sep 14 09:38 CONTRIBUTING.md
drwxr-xr-x  12 user  admin     408 Oct  2 21:22 Cellar
-rw-r--r--   1 user  admin    1241 Sep 14 09:38 LICENSE.txt
drwxr-xr-x  10 user  admin     340 Sep 29 11:38 Library
-rw-r--r--   1 user  admin    2134 Sep 14 09:38 README.md
-rw-r--r--   1 user  admin   23801 Sep 14 09:38 SUPPORTERS.md
drwxrwxr-x  48 user  admin    1632 Oct  2 21:27 bin
drwxrwxr-x   5 user  admin     170 Oct  2 21:27 etc
drwxrwxr-x   9 user  admin     306 Oct  2 21:27 include
drwxrwxrwx   3 user  wheel     102 Sep 29 11:38 join_air_data
-rwxr-xr-x   1 user  wheel  106124 Aug 21 08:36 lib
drwxr-xr-x   9 user  admin     306 Oct  2 15:29 opt
drwxrwxr-x  16 user  admin     544 Oct  2 21:27 share
```

**Comment by DomT4** [comment]
Try `sudo chown -R $(whoami):admin /usr/local/lib`. It looks like something has tweaked the permissions on that directory.

**Comment by mananwason** [comment]
No doesn't work. Why do you think this is something related to permissions?

**Comment by DomT4** [comment]
Because it has been tagged with `wheel` instead of `admin`, and `wheel` is usually the territory of `root`.

**Comment by mananwason** [comment]
Now it is admin but then also ```brew link```doesn't work.

**Comment by DomT4** [comment]
What does `brew link node` say now?

**Comment by mananwason** [comment]
Same ``` Linking /usr/local/Cellar/node/4.1.1... Error: File exists - /usr/local/lib ```

**Comment by DomT4** [comment]
Hmm. `brew doctor` should tell you if there are any further permission issues. Anything interesting in that?

**Comment by mananwason** [comment]
I just got same warnings same as that from before 
```
Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/opencv2/cvconfig.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    git
    node
    x264
```

**Comment by DomT4** [comment]
Nothing there that should be causing trouble here. Does the same link failure happen if you try `brew link git` or `brew link x264`?

**Comment by mananwason** [comment]
yep exactly same.

**Comment by chrmoritz** [comment]
```
-rwxr-xr-x   1 user  wheel  106124 Aug 21 08:36 lib
^
```
I think the issue is related to `/user/local/lib` being a file instead of a directory.

**Comment by mananwason** [comment]
@chrmoritz Yes it is a file. What should I do with it?

**Comment by chrmoritz** [comment]
I can't give you a general advice for this, because it depends on how important this file is for you (it's  >100kb). Maybe it was installed by a 3rd-party app and deleting it would break this app or maybe it's just some kind of archive or something else.

Finding out who or what has created this file and trying to move it somewhere else would be a good start. If it is important for some 3rd-party app and can't be moved, installing homebrew to a non default location would be a solution for you.
But if it's just some random junk and can be deleted `sudo rm /usr/local/lib` and `mkdir /usr/local/lib` followed by relinking every non-key-only formula and reinstalling formulas that install stuff directly into `/usr/local/lib` like node and python would fix your issue too (while loosing the old content of /usr/local/lib).

**Comment by DomT4** [comment]
Nice spot @chrmoritz.

It's very unlikely you'll get much joy out of leaving `/usr/local/lib` as a file, either inside or outside of Homebrew. It's possible that at some point something executed `touch /usr/local/lib` instead of `mkdir  /usr/local/lib`; you'd be alarmed at how common that is.

I'd probably move it out of the way and `mkdir /usr/local/lib`, after checking what the file is.

**Comment by mananwason** [comment]
@chrmoritz @DomT4 I just renamed the old file and performed linking and everything worked. Thanks for your help :smile:

**Comment by DomT4** [comment]
Glad to hear everything is functional again! :smiley_cat:

**Comment by maddypatel9900** [comment]
Thanks...this saved me too.
