### ISSUE TITLE
10.11 freetype is wrong architecture?

### ISSUE THREAD

**Issue by timvisher** [Homebrew/homebrew#44570]
I came across this trying to launch dwarf fortress. I just upgraded to 10.11 yesterday but I think things were working fine in 10.10.

```
dyld: Library not loaded: /usr/X11R6/lib/libfreetype.6.dylib
  Referenced from: /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/libs/SDL_ttf.framework/Versions/A/SDL_ttf
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libfreetype.6.dylib: mach-o, but wrong architecture
```

Here's a [gist](https://gist.github.com/timvisher/e7164355cae3bcf2fbbb) of my configuration and the error message I get. The logs were produced by the following commands

```bash
brew config
brew doctor
brew info dwarf-fortress
brew cask info dwarf-fortess
./df
dwarffortress
ls -l /usr/local/lib/libfreetype.6.dylib
lipo -info /usr/local/lib/libfreetype.6.dylib
```

If I can provide any more information, please let me know.

**Comment by timvisher** [comment]
`brew switch`ing between `2.5.5` and `2.6_1` also doesn't seem to make a difference.

**Comment by DomT4** [comment]
```
/usr/X11/lib/libfreetype.6.dylib: Mach-O universal binary with 2 architectures
/usr/X11/lib/libfreetype.6.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/usr/X11/lib/libfreetype.6.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
```

Freetype built without the universal option will produce:

```
/usr/local/lib/libfreetype.6.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
```

> dyld: Library not loaded: /usr/X11R6/lib/libfreetype.6.dylib

You're seeing this because Apple killed off the old `/usr/X11R6` folder with the OS X 10.11 release and left just `/usr/X11` pointing at `/opt/x11` for users with `xquartz` installed.

You're seeing this message because it's looking for alternative dylibs to use instead of the one that no longer exists, and it finds Homebrew's `freetype` installation but recognises by default we don't build for both `i386` and `x86_64`.

You could try `brew install freetype --universal` which may work, but this isn't a Homebrew error you're seeing. It's upstream's problem; they need to stop `dwarf-fortress` pointing at `/usr/X11R6` and use `/usr/X11` instead on at least newer OS X versions.

You can hack it in the mean time by doing something like:

```shell
install_name_tool -change /usr/X11R6/lib/libfreetype.6.dylib /usr/X11/lib/libfreetype.6.dylib /opt/homebrew-cask/Caskroom/dwarf-fortress/0.40.24/df_osx/libs/SDL_ttf.framework/Versions/A/SDL_ttf
```
But can't absolutely guarantee that'll work.

**Comment by timvisher** [comment]
@DomT4 Thanks! `brew reinstall freetype --universal` did the trick. Maybe that could be added as a `caveat` to the `df` recipe?

**Comment by DomT4** [comment]
> Maybe that could be added as a caveat to the df recipe?

The Caskroom is a separate project within the `brew` ecosystem; whilst we try to cooperate on bits and pieces the two teams are separate. You'd need to ask them about this [here](https://github.com/caskroom/homebrew-cask).
