### ISSUE TITLE
Misdetecting Xcode version

### ISSUE THREAD

**Issue by fatalaa** [Homebrew/homebrew#44637]
```brew doctor``` says:
```Warning: Your Xcode (7.0) is outdated
Please update to Xcode 7.0.1.
Xcode can be updated from the App Store.```

The problem is I already have Xcode 7.0.1

OS is 10.11.1 beta

**Comment by DomT4** [comment]
Do you have multiple Xcodes installed? Is `xcode-select -p` pointing at a path different from the 7.0.1 Xcode?

**Comment by fatalaa** [comment]
No, I only have Xcode 7.0.1 installed and

**Comment by DomT4** [comment]
Can you `brew config`? Thanks.

**Comment by fatalaa** [comment]
brew says:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: d430de476103b52e1d8d5b4ebbe5ce63f9900618
Last commit: 21 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.11.1-x86_64
Xcode: 7.0
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/tmolnar/.rvm/rubies/ruby-2.1.6/bin/ruby
Java: 1.8.0_60, 1.7.0_79
```

**Comment by DomT4** [comment]
And the output of `xcodebuild -version` and the last line of `xcodebuild -version -sdk macosx10.11 Path`?

**Comment by fatalaa** [comment]
xcodebould -version output:
```
Xcode 7.0
Build version 7A220
```

xcodebuild -version -sdk macosx10.11 Path output:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
```

**Comment by externl** [comment]
I don't think you have Xcode 7.0.1 installed. 

```
 xcodebuild -version
Xcode 7.0.1
Build version 7A1001
```

This is what I get.

**Comment by DomT4** [comment]
Haven't seen `xcodebuild -version` output the wrong version yet, so it does seem that the Xcode at `/Applications/Xcode.app` is indeed version 7.0 rather than 7.0.1.

You can confirm this visually by launching the app:

![screen shot 2015-10-06 at 19 19 33](https://cloud.githubusercontent.com/assets/6998367/10318017/380d60de-6c5f-11e5-8053-173c806bcc37.png)

**Comment by fatalaa** [comment]
It's weird. App Store says I downloaded the Xcode 7.0.1.
Xcode says I didn't. I will reinstall Xcode.

**Comment by externl** [comment]
I had an "issue" upgrading to 7.0.1 as well. Xcode.app was at 7.0 but there was no update in the App Store. After going to  Xcode in the App Store I noticed that it said I could "Install" it; it did not consider Xcode already installed. 

I suspect this was caused by the various upgrades from El Capitan beta to GM.

**Comment by fatalaa** [comment]
The reinstall of Xcode solved the issue.

**Comment by ChennyBaBy** [comment]
How did you reinstall Xcode?

**Comment by externl** [comment]
Remove `Xcode.app` from /Applications, then download Xcode from the App Store.
