### ISSUE TITLE
Unable to install Homebrew.

### ISSUE THREAD

**Issue by danechitoaie** [Homebrew/homebrew#44680]
Daniels-MacBook-Pro:~ daniels$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
	Failed to locate Homebrew!
	Daniels-MacBook-Pro:~ daniels$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	It appears Homebrew is already installed. If your intent is to reinstall you
	should do the following before running this installer again:
	    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

Any idea what's going on here?

**Comment by DomT4** [comment]
Try the instruction [here](https://github.com/Homebrew/homebrew/issues/44460#issuecomment-144195941).

**Comment by danechitoaie** [comment]
Yep, that worked. Also found the issue (or at least I guess this is the issue).

I use GitTower and that has a setting in there to add support to call it from command line and it installed something in /usr/local/bin so I guess Homebrew had an issue with that.

I've removed the files that Homebrew creates https://github.com/Homebrew/homebrew and now installation worked fine.

**Comment by DomT4** [comment]
I'd be surprised if GitTower was the issue here. We're pretty much fine with stuff being dumped in `/usr/local/bin` as long as it doesn't conflict with anything Homebrew itself installs, or overwrites system calls like `clang`, etc.

Glad to hear the install is working for you now. Let us know if you hit any further issues; Happy to help :smiley:

**Comment by danechitoaie** [comment]
Thanks.
