### ISSUE TITLE
If an inline patch contains a tab, brew audit fails

### ISSUE THREAD

**Issue by wvangeit** [Homebrew/homebrew#44711]
The test for the existence of tabs defined in:
https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/audit.rb
ignores patches that are defined in a DATA block. However, inlines patches as in
https://github.com/wvangeit/homebrew-science/blob/master/neuron.rb
are not ignored, causing the brew audit to fail

**Comment by DomT4** [comment]
We don't presently support inline patches in the manner applied there. Inline patching in general is extremely prone to breaking when people submit updates and their favourite editor is set to stripping whitespace, etc.

In terms of patching the options are more-or-less `patch :DATA` with the `__END__` block which as you note is happily ignored by the audit, or dumping the patch into a Gist and then calling it from a `patch do` block.

In terms of preventing frustrating errors that don't debug particularly cleanly, I'd really nudge people towards the `patch do` rather than trying to inline these things.

**Comment by xu-cheng** [comment]
Closing because we have deprecated inline patch other than `patch :DATA`. Thanks for reporting.

**Comment by wvangeit** [comment]
Ok, will switch to placing the patch in a gist. Maybe it would useful to mention in the formula cookbook the fact that the inline patches are not supported in this way ?
