### ISSUE TITLE
pango 1.38.0 doesn't create pango-querymodules or etc/*/pango/pango.modules

### ISSUE THREAD

**Issue by The-Cecil** [Homebrew/homebrew#44764]
A recent brew upgrade brought in pango 1.38.0 which broke my builds.

Is this a brew oversight or something new in pango?

Is there a way to remove the pango 1.38.0 in my home brew?

**Comment by tschoonj** [comment]
`pango-querymodules` no longer exists in 1.38.0. The pango developers killed it off since all modules are now built statically by default.

**Comment by ccoupe** [comment]
Thanks @tschoonj for the confirmation.  I'm happy to see it go although it's going to be some work for me to deal with.

**Comment by xu-cheng** [comment]
Close as it is not Homebrew related.

**Comment by ccoupe** [comment]
I really need a way to roll back brew upgrades, by hand if necessary. My app no longer runs in 10.9 because 4 months ago I did a brew upgrade on 10.10. Brew doctors advice to upgrade frequently is the  WRONG thing to do to a working app.  How do I back up to a glib that works in 10.9?

**Comment by tschoonj** [comment]
I assume you are experiencing a segfault at startup which traces back to the system libraries?

Generally speaking, Homebrew packages are not useful when you plan on using the libraries it provides in app bundles since Homebrew's compilation and linking environment does not provide backwards compatibility for running the binaries on older versions of Mac OS X.

Crucial here is the `MACOSX_DEPLOYMENT_TARGET` environment variable which sets the minimum version of Mac OS X that will be supported at runtime, and is read by both compiler and linker. This would need to be set from within Homebrew (currently not possible I think), and all packages need to be recompiled.

However in my experience this is pretty cumbersome. I had a custom MacPorts setup back when I was running ML that allowed my packages to run also on SL and Lion, using this environment variable set both in my bashrc and the MacPorts config files. It worked but I had to be really careful, because some packages would refuse to build under these conditions completely since they just didn't support those older OS releases. 

What I will do next time I make a release of my app bundle is use a SL (or ML, not sure yet) VM in Parallels and compile everything on it without using that variable. I will be limited in terms of features (no access to recently added OS X APIs) as I have to work with an older Xcode release, but it will work on all OS X versions released since that OS running in my VM.

You will have to go through a similar solution I am afraid in order to get your app running on an older version of OSX that you compiled it on :cry:

**Comment by ccoupe** [comment]
Thanks @tschoonj - actually it's illegal instruction, not segfault. Mine is a cross platform app so I  have to build many of the dependencies myself for windows and linux. I'll just give up on home brew brew and build them myself on OSX. More control and probably the same amount of time vs getting brew to do what I want.
