### ISSUE TITLE
Unlinked kegs for docker-completion with prefixed installation. False warning?

### ISSUE THREAD

**Issue by elmar-hinz** [Homebrew/homebrew#44941]
I run docker on a prefixed installation. `brew doctor` is warning to do this. However it works surprisingly well for me and it is the only option I know to install software on an portable USB stick.

There is only one issue and I would like to fix this:

```
> brew doctor

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    docker-completion
```

When I run `brew link` 

```
Linking /Users/ElmarHinz/Homebrew/Cellar/docker-completion/1.8.1...
Error: Could not symlink etc/bash_completion.d/docker
Target /Users/ElmarHinz/Homebrew/etc/bash_completion.d/docker
is a symlink belonging to docker. You can unlink it:
  brew unlink docker
```

Now I can unlink `docker` and link it again, after which `brew doctor` comes up with the above warning again. 

Endless cycle. Maybe a little simplified. In fact the cycle switches between warnings about `docker` and `docker-completion` back and forth.

I don't fully understand the issue. I have the feeling that my links are o.k. and `brew doctor` throws a false warning. 

In this case the question are: Why? What to fix?

**Comment by bfontaine** [comment]
It seems that `docker-completion` installs the same completion script as `docker`. Remove the former and link the latter to fix this:

```
brew rm docker-completion
brew link docker
```

**Comment by bfontaine** [comment]
Just checked: they both install the exact same files; you’re fine removing `docker-completion`.

**Comment by bfontaine** [comment]
Sorry for the multiple comments.

> I don't fully understand the issue. I have the feeling that my links are o.k. and brew doctor throws a false warning.

`docker` installs completion scripts that are then symlinked in `bash_completion.d/`. `docker-completion` installs these same completion scripts in its own cellar directory then try to symlink them in `bash_completion.d/` too. The issue is that both try to symlink the same files; so if you unlink one and link the other, the first one will complain it’s not linked. If you unlink the latter and link the former, the last one will complain, etc.

I just pushed [a fix](https://github.com/Homebrew/homebrew-completions/commit/687474e67cf2b1373d7ef51c62b7ccde74c8d7b0) to `homebrew/completions` that will prevent this from happening in the future.

**Comment by elmar-hinz** [comment]
Thank you for your answer an the quick fix. It's already merged.
