### ISSUE TITLE
Get size of formula

### ISSUE THREAD

**Issue by qw3rtman** [Homebrew/homebrew#45088]
It would be convenient if the size of the formula (with and without dependencies) was listed in `homebrew info [FORMULA]`.

**Comment by xu-cheng** [comment]
The size information(without dependencies) is available via `brew info`. For example:

$ brew info gcc
gcc: stable 5.2.0 (bottled)
GNU compiler collection
https://gcc.gnu.org
<b>/usr/local/Cellar/gcc/5.2.0 (1353 files, 248M) * </b>
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb
...

**Comment by qw3rtman** [comment]
This info is only displayed if the formula is given. I'm looking to see, for example, what the download size and (possibly) size after installation will be before I execute `brew install [FORMULA]`.

**Comment by xu-cheng** [comment]
That would be hard to get. Although, for bottled formulae, you can get size of the bottle files. For example:

```
$ curl -I -L "$(brew info --json=v1 gcc | jq -r '.[0].bottle.stable.files.el_capitan.url')"
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 18 Oct 2015 07:49:03 GMT
Content-Type: application/x-gzip
Content-Length: 78356444
Connection: keep-alive
Last-Modified: Mon, 05 Oct 2015 05:45:50 CEST
ETag: 4069abc29f438197a2e5ce20daeca29d02d3587a
X-Checksum-Sha1: 4069abc29f438197a2e5ce20daeca29d02d3587a
Accept-Ranges: none
```

**Comment by qw3rtman** [comment]
On my machine, `brew info --json=v1 gcc` contains no URL (**GCC is not installed**):

```json
[
  {
    "name": "gcc",
    "homepage": "http://gcc.gnu.org",
    "versions": {
      "stable": "4.9.2",
      "bottle": true,
      "devel": null,
      "head": null
    },
    "revision": 1,
    "installed": [],
    "linked_keg": null,
    "keg_only": null,
    "dependencies": [
      "gmp",
      "libmpc",
      "mpfr",
      "cloog",
      "isl"
    ],
    "conflicts_with": [],
    "caveats": "GCC has been built with multilib support. Notably, OpenMP may not work:\n  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670\nIf you need OpenMP support you may want to\n  brew reinstall gcc --without-multilib\n",
    "options": [
      {
        "option": "--with-java",
        "description": "Build the gcj compiler"
      },
      {
        "option": "--with-all-languages",
        "description": "Enable all compilers and languages, except Ada"
      },
      {
        "option": "--with-nls",
        "description": "Build with native language support (localization)"
      },
      {
        "option": "--without-fortran",
        "description": "Build without the gfortran compiler"
      },
      {
        "option": "--without-multilib",
        "description": "Build without multilib support"
      }
    ]
  }
]
```

```sh
$ brew --version
0.9.5

$ zsh --version
zsh 5.0.5 (x86_64-apple-darwin14.0)

$ sw_vers   
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E26a
```

**Comment by xu-cheng** [comment]
Your homebrew is outdated. Please run `brew update`

**Comment by qw3rtman** [comment]
My bad. The JSON now includes the download sizes. Is there a documented API for retreiving this data directly from the homebrew servers?

I think displaying this info before installation would be useful for developers who have access to limited bandwidth, as an example.

Example output:
```
gcc: stable 5.2.0 (bottled) (78.36 MB)
```

**Comment by rakkesh** [comment]
Rather than displaying this additional bit of data on executing `brew info <formula>`, which would take time to fetch from the internet, and thus delaying to show the locally available information for a formula; it would be great to have this as an additional option like `--pkg-size` ( or any other name ). Having said that, the download size varies depending on whether a formula offers `bottles` or when a user decides to build from source.

**Comment by mikemcquaid** [comment]
> My bad. The JSON now includes the download sizes. Is there a documented API for retreiving this data directly from the homebrew servers?

Maybe the Bintray API but we don't provide support for that. I don't think this is something we can provide for non-bottled stuff really.

**Comment by apjanke** [comment]
We could do it for the simple case of a single-file source download by doing a HTTP HEAD request on the formula's `url` and grabbing the returned `Content-Length`. Same for any `resource`s, and then add them all up. It'd still cost you network access and latency (esp when calculating for dependencies), but would use minimal bandwidth.
 
It wouldn't cover the case for sources or resources exposed as VCS repos, but it could work for a lot of "normal" formulae. Depending on whether the servers hosting them support HTTP HEAD and report the right length. Since the files are never expected to change, the size data could be cached locally on a per-file (url+sha256) or just per-shasum basis, so you'd only ever have to eat one network trip per distinct resource.

(In theory, this info could even be baked in to the formulae along with the SHA sum as part of the test+bottling process: if you have the file to calculate the checksum, you've got the file size available too. Sounds like a lot of work for a seldom-used feature, though.)

This would be nontrivial to implement though. Would like to see more indication of interest before tackling this, at least personally.

**Comment by mikemcquaid** [comment]
> We could do it for the simple case of a single-file source download by doing a HTTP HEAD request on the formula's url and grabbing the returned Content-Length. Same for any resources, and then add them all up. It'd still cost you network access and latency (esp when calculating for dependencies), but would use minimal bandwidth.

That's a good/clever idea. If it would work for others (e.g. this information requires you to be online) I'd think it's worth having.

**Comment by mikemcquaid** [comment]
Passing on this feature request. We'd accept a pull request in future.
