### ISSUE TITLE
brew cat of cask gives error: undefined method path

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/homebrew#45300]
pb3:~ jhawk$ brew cat Caskroom/cask/mysqlworkbench 
Error: undefined method `path' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/cat.rb:9:in `cat'
/usr/local/Library/brew.rb:146:in `<main>'

I imagine I should tap the cask first, but there should be a better error message.

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew/issues/44630#issuecomment-145626431. It isn't intended to be possible on our end to `brew cat` Casks at this point - The Cask is part of the `brew` ecosystem but we don't share the same expect codebase or syntax choices.

That may change if https://github.com/caskroom/homebrew-cask/issues/14384 goes ahead and we can harmonise the core code a bit more, but for now there's no expectation of complete compatibility in this way.

**Comment by johnhawkinson** [comment]
If so, it shouldn't show up in "brew search"?

**Comment by DomT4** [comment]
The logic as far as `brew` is concerned is more or less `brew search` searches taps, and the Caskroom *is* a tap. `brew cat` prints formulae, but Casks are *not* formulae.

**Comment by johnhawkinson** [comment]
hrmmmm. I think it does not lead to a good user experience this way. Users are taught to "brew search" for formulas.

Objections to a helpful message from brew cat in this case?

--jhawk (mobile)


-----Original Message-----

**Comment by DomT4** [comment]
There's special [logic](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/search.rb#L87-L110) to include the Cask in our `search` results. In contrast the `cat` command hasn't really [changed](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/cat.rb) in a long time.

The nice thing about `brew cat` is that it's quick, due to being extremely simple. There is something of a check in there as doing a simple `brew cat 1password` for example will throw:
```
Error: No available formula with the name "1password"
```
The error only raises when a full tap path *to* the Caskroom is passed. I've opened #45300.

**Comment by DomT4** [comment]
I've opened #45302, even. Tagged the wrong thing.

**Comment by mikemcquaid** [comment]
Perhaps Casks could be a separate section of search to avoid confusion?
