### ISSUE TITLE
brew install fails when one package name is a substring of another

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew#45522]
In my homebrew tap [hombrew-robotics](https://github.com/ahundt/homebrew-robotics) I have two formulas `robone.rb` and `robonetracker.rb`. In this case `brew install robone` doesn't seem to run.

```
athundt at Andrews-2013-MacBook-Pro in ~/source/homebrew-robotics on master
± brew install ahundt/robotics/robone
Error: No available formula with the name "ahundt/robotics/robone"
==> Searching for similarly named formulae...
These similarly named formulae were found:
ahundt/robotics/robone                                                   ahundt/robotics/robonetracker
To install one of them, run (for example):
  brew install ahundt/robotics/robone
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by UniqMartin** [comment]
The substring overlap is not the issue here. Both formulae use the class name `Grl` inside which doesn't match the formula file name. Also, one of them has a duplicate `homepage` line.

I'd suggest to run `brew audit --strict` on these formula after fixing the class name to check for any other issues that might have went unnoticed.

**Comment by mikemcquaid** [comment]
As @UniqMartin said: not a Homebrew bug.

**Comment by ahundt** [comment]
You're right, thanks. Sorry about that!
