### ISSUE TITLE
[brew pin] Not correctly processing dependency correctly?

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/homebrew#45629]
Hi,

I pined php56, but there's upgrades for php56-mcrypt, so brew still wants to upgrade php56

Was it a bug?

**Comment by DomT4** [comment]
Afraid this is intended behaviour. If you install something which relies on the formula you've pinned it'll be updated because that's the only way we can be certain the compile isn't going to die on you for some obscure reason. Formulae are intended to be built against the latest version of each other, essentially.

You could always upgrade and then `brew switch` back to your desired version of `php56` afterwards, presuming that doesn't cause breakage.
