### ISSUE TITLE
Stop the ElCap recommendation to recursively set perms on files brew isn't responsible for

### ISSUE THREAD

**Issue by arubdesu** [Homebrew/homebrew#45625]
https://github.com/Homebrew/homebrew/blob/fdc0570d82e8f55adef3a0c5ac3d8d5f65db1093/share/doc/homebrew/El_Capitan_and_Homebrew.md#L16
This recommendation will make other tools less secure (e.g. that want to be set to `root:wheel`).
Related issue: #44495

**Comment by DomT4** [comment]
We're aware of the issue and have some fixes in mind. We'll likely go down the route of having a command which re-owns things we're aware `brew` should own, but how broad/narrow in scope that would be hasn't been discussed hugely yet.

"Less secure" is a more complicated issue than it necessarily sounds; The barrier of entry is higher in that it requires `sudo`, but the damage it can do to your system once it gains that `sudo` access is significantly broader.

Those other tools are also often fond of recursively (and silently and persistently) chowning directories that they install things into with full `root:wheel` permissions instead of just the files they install. Recursive chowning is popular, problems and all :confounded:.

**Comment by arubdesu** [comment]
Agreed, and I appreciate the reasoned response when I'm sure you/the dev team deal with nastygrams about every little thing. 
Irregardless of other ways the same mistake can be made, giving any local user ownership of all those files, or specifically endorsing the overwriting of perms in what's now going to be a crowded directory is a bad idea™.

This tool has always been in /usr/local, is used on tens of thousands of machines worldwide, and will (understandably) bark if you mess with its perms:
https://github.com/munki/munki/blob/b2913d6d7ca5e48b40220f3bf42cea0291f47cae/code/client/munkilib/utils.py#L84

**Comment by mikemcquaid** [comment]
> This tool has always been in /usr/local, is used on tens of thousands of machines worldwide, and will (understandably) bark if you mess with its perms

This also applies to Homebrew except we're on hundreds of thousands (if not millions) :wink:. This is something we're going to probably improve at some point with a `brew fix-permissions` command or similar.

**Comment by hunty1** [comment]
I have 50k Macs with Munki on it alone.... I think Munki users are well into the millions as well.

This is basically like saying chmod -R $USER /Applications

/usr/local is not yours, its not the users, its the systems. you want a place to play? You can have /usr/local/homebrew for example anything in there is yours and you can have permissions however you want.

**Comment by DomT4** [comment]
Let's keep the discussion productive and free of sass, Thanks. Happy to discuss the technical issue of permission fixing, but we're not going to endlessly bikeshed over prefix *again* in this particular issue.

**Comment by mikemcquaid** [comment]
I'm closing this issue because the document it mentions is about creating `/usr/local`. If `/usr/local` is being created by the user: it's not currently being used by other software. That software can have its own recommendations for what permissions to set and we'll have ours.
