### ISSUE TITLE
libarchive: keg-only package should still install pkg-config file

### ISSUE THREAD

**Issue by outlyer** [Homebrew/homebrew#45891]
libarchive is a keg-only package. However, the purpose of installing it is to build packages that depend on it. 

As of right now, the package does not install a ```/usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc``` symlink into the pkg-config directory (```/usr/local/lib/pkgconfig```) so it can't be used to build anything. 

I'm can submit a patch against libarchive.rb but this is something that should be considered in the context of all keg-only packages.

**Comment by DomT4** [comment]
Installing a `.pc` file would kind of negate the point of making the formula `keg_only` since anything that used `pkg-config` to find things would find the package it isn't supposed to routinely finding.

We recommend passing flags or adding it to your `PKG_CONFIG_PATH` temporarily instead. Quite a few configure scripts have taken the path of checking for `brew` and then asking for `brew --prefix libarchive`.

**Comment by DomT4** [comment]
Closing per the latter part of above.
