### ISSUE TITLE
Impossible uninstall brew

### ISSUE THREAD

**Issue by federicocappelli** [Homebrew/homebrew#45905]
After a failed attempt to re-install brew now i'm trying to remove it completely but the uninstall script is failing:

```
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
-e:100:in `realpath': No such file or directory - /usr/local/bin/brew (Errno::ENOENT)
	from -e:100:in `realpath'
	from -e:100:in `<main>'
$ ls -al /usr/local/
total 0
drwxr-xr-x@ 10 xxxx      wheel   340 11 Nov 22:41 .
drwxr-xr-x@ 12 root       wheel   408  6 Nov 21:25 ..
drwxr-xr-x@ 12 423630511  admin   408 13 Nov  2014 .git
drwxr-xr-x@  8 423630511  admin   272 13 Nov  2014 Library
drwxrwxr-x@ 48 xxxx      admin  1632 11 Nov 22:41 bin
drwxr-xr-x@  3 root       wheel   102  2 Mar  2015 cuda
drwxr-xr-x   3 root       wheel   102  8 Jan  2015 include
drwxrwxr-x@ 14 root       admin   476  6 May  2015 lib
drwxrwxr-x@  3 root       wheel   102 13 Nov  2014 libexec
drwxrwxr-x@  6 root       admin   204 13 Nov  2014 share
```

system:
```
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42
Darwin MacVac 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

```

**Comment by DomT4** [comment]
Sigh. I fixed one bug on the uninstall script the other day and managed to apparently unearth another. Will go check it out; apologies.

**Comment by bradsjl** [comment]
I had the same issue. The only reason I was trying to uninstall/reinstall homebrew is because I was getting an SSL error when running my run.rb script. Should a reinstall fix this issue? Is there a manual way to uninstall while the script is broken?

The error is SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed: 

  SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (RestClient::SSLCertificateNotVerified)

**Comment by DomT4** [comment]
Should be fixed by https://github.com/Homebrew/install/commit/7220feb5d667e2173377d9b24c33fc4c858ab27e.

**Comment by federicocappelli** [comment]
Fixed!
