### ISSUE TITLE
gdrive formula is outdated and doesn't build

### ISSUE THREAD

**Issue by mralexgray** [Homebrew/homebrew#45916]
[`gdrive`](https://github.com/prasmussen/gdrive)'s current version is [`1.9.0`](https://drive.google.com/uc?id=0B3X9GlR6EmbnVjIzMDRqck1aekE).  However `brew` _tries to install_ `1.6.x`.  Why the big disconnect?  

Regardless of version, the current formula crashes and burns, on install, _for me_...

```
Last 15 lines from /sd/localadmin/Library/Logs/Homebrew/gdrive/01.go:
2015-11-11 22:16:54 -0500

go
build
drive.go

package github.com/prasmussen/gdrive/cli
	imports github.com/prasmussen/gdrive/gdrive
	imports github.com/prasmussen/gdrive/auth
	imports github.com/prasmussen/gdrive/util
	imports github.com/prasmussen/google-api-go-client/drive/v2
	imports github.com/prasmussen/google-api-go-client/googleapi
	imports google.golang.org/api/googleapi/internal/uritemplates: use of internal package not allowed

READ THIS: https://git.io/brew-troubleshooting

```

Why does the formula even mess with trying to compile it when the maintainer is so dilligent with providing up-todate binary releases?  The formula should be simplified and simply install [those binaries](https://github.com/prasmussen/gdrive#downloads).

**Comment by DomT4** [comment]
> However brew tries to install 1.6.x. Why the big disconnect?

Because we're all volunteers and rely on the wider community to update their particular favourite packages a lot of the time, and nobody has updated `gdrive` since submission.

We'd love it if you wanted to update the formula. There's some documentation on that [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) if it's useful.

> Why does the formula even mess with trying to compile it when the maintainer is so dilligent with providing up-todate binary releases?

Because we provide our own binaries and producing them allows us a measure of control over the build process and handling breakage rather than just shrugging when breakage gets reported to us and waiting for upstream to crank out the next fix release, which in many cases *(although not necessarily this one)* is not a quick process.

**Comment by dunn** [comment]
I was just looking at this formula today.  It won't build with Go 1.5+: https://github.com/prasmussen/gdrive/issues/81

That, in addition to the fact that we currently have to use the developer's fork of `google-api-go-client` (https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gdrive.rb#L29-L31), makes me almost want to boneyard this formula.

**Comment by DomT4** [comment]
> makes me almost want to boneyard this formula.

We could always see if the Cask would be willing to take it if there's no real possibility of it being updated to support Go 1.5+ soon? They'll happily accept the binaries I suspect.

**Comment by benholtz** [comment]
+1 looking for a resolution

**Comment by DomT4** [comment]
I'd recommend submitting a Cask for the binary download to the [Caskroom](https://github.com/caskroom/homebrew-cask). It sounds like the binary releases are going to be the easiest fix here since there are no imminent plans for upstream to start using 1.5+.

We don't accept binary releases in the core, but the Cask is likely to be happy enough to take this, IMO. Otherwise feel free to submit to Homebrew/binary.
