### ISSUE TITLE
How does homebrew avoid conflicts and crashes for key dependencies?

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew#45949]
How does homebrew avoid conflicts with key dependencies that already come with OS X such as gcc, libstdc++, and particularly anything that has to interact with system stacks such as graphics and X11? 

Are there any words of wisdom that could be carried over to linuxbrew where key dependencies conflict such as those I've run into at https://github.com/Homebrew/linuxbrew/issues/640?

Thanks for your consideration regarding my question on some of the homebrew inner workings! I hope this question isn't too out of scope.

**Comment by ahundt** [comment]
It looks like there are a number of items in the docs that implicitly refer to such underlying problems that had to be dealt with, but don't explain what/why/how to deal with new such problems, which is the information I'm interested in.  For example see the [custom gcc](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Custom-GCC-and-cross-compilers.md) instructions, and perhaps some hints on how to do this are in the [TipsNTricks](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Tips-N'-Tricks.md) page?

**Comment by UniqMartin** [comment]
I think the situation on OS X (compared to Linux) is much simpler, because on OS X you have a much more standardized environment with many key dependencies provided by Apple. The philosophy in Homebrew is to use the tools and libraries provided by the system unless there is a good reason to do something different. That's also the reason why the recommended and best-supported compiler is Apple Clang.

GCC hasn't been distributed by Apple for a long time. `libstdc++` (a rather old version from GCC 4.2) is mostly there to support legacy software and the default is `libc++` nowadays.

I'm not entirely sure what conflicts and crashes you are talking about in the issue title. Maybe you can provide more specific examples and actual issues you came across on OS X.

**Comment by mikemcquaid** [comment]
@ahundt `superenv` and `keg_only` are the two methods, basically. The source should help explain more there but feel free to ask more questions here.
