### ISSUE TITLE
ImageMagick 6.9.2-5 pulled. 404's for an install

### ISSUE THREAD

**Issue by justinxreese** [Homebrew/homebrew#46010]
It looks like `http://www.imagemagick.org/download/releases/ImageMagick-6.9.2-5.tar.xz` has also been pulled. #40969 had the same problem, so should have the same fix. I'd love to help and submit a PR but I'm not sure where to get the SHA you referenced in your change

This version is used when you try to install imagemagick with `brew reinstall --with-libtiff --ignore-dependencies --with-x11 imagemagick`

**Comment by justinxreese** [comment]
"you" meaning @mikemcquaid who was the one to fix the mentioned issue

**Comment by DomT4** [comment]
Will be fixed by #46011.

Getting the SHA is easy enough if you want to do so in future. Either `brew edit xyz`, update the URLs and then execute `brew fetch xyz` which will print out the SHA256 checksum for you to copy, or download the tarball from the website and run a `shasum -a 256 /path/to/tarball` on it.

**Comment by justinxreese** [comment]
Thanks @DomT4!
