### ISSUE TITLE
#bin within test-block returns incorrect path

### ISSUE THREAD

**Issue by paddor** [Homebrew/homebrew#46090]
I'm trying to create a formula for https://github.com/imatix/gsl. I started by `brew create https://github.com/imatix/gsl.git`, which opened the editor (very nice). I got the formula to install the software.

In the `test do ... end` block, there's a comment:

```
      # The installed folder is not in the path, so use the entire path to any
      # executables being tested: `system "#{bin}/program", "do", "something"`.
```

So I did as described in the above comment. Here's my `test` block:

```ruby
    test do
      (testpath/TEST_SCRIPT_NAME).write(TEST_SCRIPT)
      system bin/"gsl", testpath/TEST_SCRIPT_NAME      # <--- relevant line
      assert_equal TEST_OUTPUT, (testpath/TEST_OUTPUT_NAME).read
    end
```

However, when I try to run the tests for this formula (`brew test --HEAD imatix-gsl`) software, it fails. `bin` expands to a weird path `/usr/local/Cellar/imatix-gsl/HEAD/bin`. That directory doesn't even exist. Up until the HEAD directory, it exists.

When I change the test line to just

```ruby
      system "gsl", testpath/TEST_SCRIPT_NAME
```

it works, which is what I expect, since it's already installed.

So either the method #bin is broken or that comment is wrong.

**Comment by paddor** [comment]
You're right. It does work as expected. :sweat_smile: 

What I didn't realize is that this GSL software only has a Makefile (no configure script), and one has to manually specify the DESTDIR. Now that I'm doing this (see commit fa67a62406cc543d211fef7f681d06ee8a764e5a), it works perfectly, since it now actually gets installed into the `/usr/local/Cellar/imatix-gsl/HEAD`.

I have to agree, it is a little odd that it's possible (according to `man brew`) to specify `--HEAD` or `--devel` while running the tests of a formula. Maybe this is to be able to distinguish between multiple installed versions (stable and HEAD) of the formula.

**Comment by apjanke** [comment]
Okay, good to hear.

So, I checked with a couple of the other maintainers. The need to specify `--HEAD` or `--devel` in `brew test` is just a technical limitation of `brew`, and we're working on removing the need for it. Hopefully this will be a moot point soon. (And it seems to work all right now if you just omit them, at least for simple formulas.)

BTW, it looks like [this test setup code](https://github.com/Homebrew/homebrew/blob/fa67a62406cc543d211fef7f681d06ee8a764e5a/Library/Formula/imatix-gsl.rb#L13-L20) should also go inside the `test do` block. It'll still work outside it, but since it's only used for testing, it should be scoped to the test, and that way the `test do` has 100% of the code you need to understand the test process.

**Comment by paddor** [comment]
@apjanke Thanks for the hint. I thought constants can't be defined inside a block.

**Comment by apjanke** [comment]
You're right; they can't. You'd need to change them to local variables. That's the idiom that other Homebrew formulae use for their tests. E.g., from `commonmark.rb`:

```ruby
  test do
    test_input = "*hello, world*\n"
    expected_output = "<p><em>hello, world</em></p>\n"
    test_output = `/bin/echo -n "#{test_input}" | #{bin}/cmark`
    assert_equal expected_output, test_output
  end
```

So, something like this.
```ruby
  test do
    test_script_name = "hello_world.gsl"
    test_output_name = "hello_world.txt"
    test_script = <<-GSL
.output "#{test_output_name}"
.who = "world"
>Hello $(who)!
GSL
    test_output = "Hello world!\n"

    (testpath/test_script_name).write(test_script)
    system bin/"gsl", testpath/test_script_name
    assert_equal test_output, (testpath/test_output_name).read
  end
```

And a lot of formulae don't even bother storing the names in variables for short tests. So you'd see something like this.

```ruby
  test do
    (testpath/"hello_world.gsl").write(<<-GSL)
.output "hello_world.txt"
.who = "world"
>Hello $(who)!
GSL
    system bin/"gsl", testpath/"hello_world.gsl"
    assert_equal "Hello world!\n", (testpath/"hello_world.txt").read
  end
```

**Comment by paddor** [comment]
@apjanke Actually, I tried to move the constant definitions inside the `test` block, just to be sure, and it works! No need for local variables.

I like using constants when it's values that don't change.

Hehe, I sure won't go the last way. It just doesn't read that well.

**Comment by apjanke** [comment]
Makes sense.

You *might* want to stick with local variables just to be safe for future use cases. The way I understand Ruby constants is that you get a warning if they're assigned to multiple times in a single program. So it works inside a block of code that's only going to be called once during the lifecycle of a Ruby process. And this is the case with `test do` blocks in Homebrew. (At least for now. And I think probably forever, because the tests are each run inside a separate process for isolation.) But you may not be able to use them cleanly inside blocks in the general case, because some might get run repeatedly in a single program execution.

**Comment by paddor** [comment]
Okay, you have a point there. But then again, why not define the constants outside of the `test` block, like I had it before? To me, the `test` block defines what needs to be run for tests, which isn't necessarily everything related to tests. Or is that completely against the Homebrew coding style?

**Comment by apjanke** [comment]
I'm a newer maintainer, so I'll defer to others on official style. But in all the formulae that I've seen, everything that's test-specific goes in the `test` block. The formula scripts are treated as a DSL, and I think part of the intent of the `test` block is to collect all the info about the test, not just the procedural part.

**Comment by paddor** [comment]
Done. :smile: 

The problem is still that these two projects, which I created formulae today for, don't actually have releases, AFAIK. So you guys won't accept the formulae anyway, since they're HEAD only. :stuck_out_tongue_closed_eyes:

**Comment by apjanke** [comment]
Yep. Afraid we'll have to wait on a release from the maintainers. :/ Stuff like that I just put in my own [personal tap](https://github.com/apjanke/homebrew-custom) so I can still manage it across multiple machines like the official formulae.
