### ISSUE TITLE
How Do I Specify and Use Homebrew gcc-4.8 in a Formula Instead of OS X Bundled gcc?

### ISSUE THREAD

**Issue by adilinden** [Homebrew/homebrew#46169]
How can I specify a specific gcc version that I install via Homebrew in a new formula?  Basically I'd like to specify gcc-4.8 as a dependency and have the formula contain the necessary statement to install gcc-4.8 if it is not already present.

I believe that my current formula just uses the OS X gcc instead of the one installed via Homebrew.

Thanks,
Adi

**Comment by UniqMartin** [comment]
That's quite an unusual request. Ideally, software would build with the default compiler on a platform and that happens to be Clang on OS X (not GCC, unless we are talking about very old versions of OS X). Assuming there is a good reason why it doesn't build with Clang and there's no easy way to resolve that, it's still not very reasonable to force a specific GCC release. And it sounds very suspicious if it doesn't build with anything else and is unlikely to be accepted, because that sounds like a nightmare to support in the future.

That said, there is a way to express the opposite, namely that a software doesn't build with a certain compiler. This is done via `fails_with`, e.g.:

- `fails_with :clang` (the default on modern OS X releases)
- `fails_with :gcc => "4.8"` (e.g., when there is a known issue with a single release)

This will tell the user if she tries to install the formula and doesn't have a supported compiler. There is also the [Formula API documentation](http://www.rubydoc.info/github/Homebrew/homebrew/master/Formula#fails_with-class_method) for more detail. Or have a look at how existing formulae use `fails_with`.

**Comment by dunn** [comment]
If it's for your own personal use, you can add `depends_on "homebrew/versions/gcc48"` and set `ENV["CC"]` to `gcc-4.8` during installation.  But we wouldn't accept that as a core formula, for the reasons Martin mentioned (and we just don't allow cross-tap dependencies in core).

**Comment by DomT4** [comment]
Presuming question answered. Let us know otherwise!
