### ISSUE TITLE
openssl failed to build on 10.10.5

### ISSUE THREAD

**Issue by bpennypacker** [Homebrew/homebrew#46337]
I want to see if I can get wine installed and operational on my MBP, but brew is failing on building openssl-1.0.2d_1.  Here's the gist containing my logs, etc: https://gist.github.com/0e24eb5fd0c2ea5b676e

Any suggestions would be appreciated.

-Bruce

**Comment by mikemcquaid** [comment]
This should have used a binary package. Did you request to build it from source?

**Comment by bpennypacker** [comment]
no, I just did "brew install wine"

**Comment by mikemcquaid** [comment]
Can you Gist the output from the terminal (rather than the gist-logs) so I can take a look? Thanks!

**Comment by mistydemeo** [comment]
@mikemcquaid Wine requires universal deps, because it builds 32-bit; openssl is a recursive dependency via `sane-backends`, so it makes sense it built from source.

**Comment by mikemcquaid** [comment]
@mistydemeo Doh, of course.

**Comment by bpennypacker** [comment]
@mikemcquaid Here's a gist with the console output (at the very bottom) and the output from the make command: https://gist.github.com/bpennypacker/016f7a260ead084d04a5

**Comment by DomT4** [comment]
There are some known issues upstream around `make test` against Xcode 7 that have been fixed but not yet released.

**Comment by mikemcquaid** [comment]
> There are some known issues upstream around make test against Xcode 7 that have been fixed but not yet released.

@DomT4 Maybe disable it for `universal`?

**Comment by DomT4** [comment]
Probably. I'll poke around locally in a bit and see if I can break it. I'd normally backport on something like this, but am loathe to backport OpenSSL stuff given the nature of the library.

**Comment by DomT4** [comment]
Kind of chasing my tail on this one.

Couldn't reproduce it locally, went hunting for a root cause, discovered a whole bunch of OpenSSL problems around evp, including one from 2012 where instead of being fixed the functionality was just disabled "temporarily", heh. Discovered some more broken functionality that has been reported upstream this year but is still accessible.

Locally I get:
```
Testing cipher id-aes256-GCM(encrypt/decrypt)
Key
0000 fe ff e9 92 86 65 73 1c 6d 6a 8f 94 67 30 83 08
0010 fe ff e9 92 86 65 73 1c 6d 6a 8f 94 67 30 83 08
IV
0000 ca fe ba be fa ce db ad
Plaintext
0000 d9 31 32 25 f8 84 06 e5 a5 59 09 c5 af f5 26 9a
0010 86 a7 a9 53 15 34 f7 da 2e 4c 30 3d 8a 31 8a 72
0020 1c 3c 0c 95 95 68 09 53 2f cf 0e 24 49 a6 b5 25
0030 b1 6a ed f5 aa 0d e6 57 ba 63 7b 39
Ciphertext
0000 c3 76 2d f1 ca 78 7d 32 ae 47 c1 3b f1 98 44 cb
0010 af 1a e1 4d 0b 97 6a fa c5 2f f7 d7 9b ba 9d e0
0020 fe b5 82 d3 39 34 a4 f0 95 4c c2 36 3b c7 3f 78
0030 62 ac 43 0e 64 ab e4 99 f4 7c 9b 1f
AAD
0000 fe ed fa ce de ad be ef fe ed fa ce de ad be ef
0010 ab ad da d2
Tag
0000 3a 33 7d bf 46 a7 92 c4 5e 45 49 13 fe 2e a8 f2
```

Your gist has:
```
Testing cipher id-aes256-GCM(encrypt/decrypt)
Key
0000 fe ff e9 92 86 65 73 1c 6d 6a 8f 94 67 30 83 08
0010 fe ff e9 92 86 65 73 1c 6d 6a 8f 94 67 30 83 08
IV
0000 ca fe ba be fa ce db ad
Plaintext
0000 d9 31 32 25 f8 84 06 e5 a5 59 09 c5 af f5 26 9a
0010 86 a7 a9 53 15 34 f7 da 2e 4c 30 3d 8a 31 8a 72
0020 1c 3c 0c 95 95 68 09 53 2f cf 0e 24 49 a6 b5 25
0030 b1 6a ed f5 aa 0d e6 57 ba 63 7b 39
Ciphertext
0000 c3 76 2d f1 ca 78 7d 32 ae 47 c1 3b f1 98 44 cb
0010 af 1a e1 4d 0b 97 6a fa Tag mismatch
Got
0000 f6 7a 4f d6 f5 22 7e 2f 8c ed fc 90 3f a7 ea af
Expected
0000 5f ea 79 3a 2d 6f 97 4d 37 e6 8e 0c b8 ff 94 92
c5 2f f7 d7 9b ba 9d e0
0020 fe b5 82 d3 39 34 a4 f0 95 4c c2 36 3b c7 3f 78
0030 62 ac 43 0e 64 ab e4 99 f4 7c 9b 1f
AAD
0000 fe ed fa ce de ad be ef fe ed fa ce de ad be ef
0010 ab ad da d2
Tag
0000 3a 33 7d bf 46 a7 92 c4 5e 45 49 13 fe 2e a8 f2
```

@bpennypacker Does this reproduce again if you try another `brew install openssl --universal` build? Trying to reduce the variables here.

I'm not opposed to disabling the tests for universal builds until the next OpenSSL release, but I think it's very possible there's some underlying hardware or local issue here.

**Comment by bpennypacker** [comment]
@DomT4 It looks like the exact same error if I try to build with --universal:

$ brew install openssl --universal
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2d.tar.gz
==> make clean
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2d_1 --openssldir=/u
==> make depend
==> make
==> make test
Last 15 lines from /Users/bpennypacker/Library/Logs/Homebrew/openssl/05.make:
Plaintext
Ciphertext
AAD
0000 d9 31 32 25 f8 84 06 e5 a5 59 09 c5 af f5 26 9a
0010 86 a7 a9 53 15 34 f7 da 2e 4c 30 3d 8a 31 8a 72
0020 1c 3c 0c 95 95 68 09 53 2f cf 0e 24 49 a6 b5 25
0030 b1 6a ed f5 aa 0d e6 57 ba 63 7b 39 1a af d2 55
0040 52 2d c1 f0 99 56 7d 07 f4 7f 37 a3 2a 84 42 7d
0050 64 3a 8c dc bf e5 c0 c9 75 98 a2 bd 25 55 d1 aa
0060 8c b0 8e 48 59 0d bb 3d a7 b0 8b 10 56 82 88 38
0070 c5 f6 1e 63 93 ba 7a 0a bc c9 f6 62 89 80 15 ad
Tag
0000 5f ea 79 3a 2d 6f 97 4d 37 e6 8e 0c b8 ff 94 92
make[1]: *** [test_evp] Error 9
make: *** [tests] Error 2

**Comment by DomT4** [comment]
I presume the error doesn't reproduce if you try `brew install openssl -s` without the `--universal` element?

**Comment by bpennypacker** [comment]
`brew install openssl -s` resulted in the same error:

$ brew install openssl -s
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2d.tar.gz
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2d_1 --openssldir=/u
==> make depend
==> make
==> make test
Last 15 lines from /Users/bpennypacker/Library/Logs/Homebrew/openssl/04.make:
Plaintext
Ciphertext
AAD
0000 d9 31 32 25 f8 84 06 e5 a5 59 09 c5 af f5 26 9a
0010 86 a7 a9 53 15 34 f7 da 2e 4c 30 3d 8a 31 8a 72
0020 1c 3c 0c 95 95 68 09 53 2f cf 0e 24 49 a6 b5 25
0030 b1 6a ed f5 aa 0d e6 57 ba 63 7b 39 1a af d2 55
0040 52 2d c1 f0 99 56 7d 07 f4 7f 37 a3 2a 84 42 7d
0050 64 3a 8c dc bf e5 c0 c9 75 98 a2 bd 25 55 d1 aa
0060 8c b0 8e 48 59 0d bb 3d a7 b0 8b 10 56 82 88 38
0070 c5 f6 1e 63 93 ba 7a 0a bc c9 f6 62 89 80 15 ad
Tag
0000 5f ea 79 3a 2d 6f 97 4d 37 e6 8e 0c b8 ff 94 92
make[1]: *** [test_evp] Error 9
make: *** [tests] Error 2

**Comment by DomT4** [comment]
Is this still the case with the new `openssl` release?

**Comment by bpennypacker** [comment]
I was just able to successfully build wine and launch a Windows app with it, so it looks like the most recent release did in fact resolve this.  Thanks!

**Comment by DomT4** [comment]
Phew :tada:. Thanks for the confirmation!

**Comment by cmayer** [comment]
I do get this same error today when upgrading openssl with homebrew on a Mac.

==> Installing neon dependency: openssl
dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/sudo) is setuid or setgid
==> Downloading https://www.openssl.org/source/openssl-1.0.2e.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2e.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/312f6228/openssl/fix-Apple-clang-version-detection.patch
Already downloaded: /Library/Caches/Homebrew/openssl--patch-a3e0e13e6c70d85d916bb88cbddc134952794d6292fbab4f2740ac9a07759606.patch
==> Patching
patching file crypto/aes/asm/aesni-mb-x86_64.pl
patching file crypto/aes/asm/aesni-sha1-x86_64.pl
patching file crypto/aes/asm/aesni-sha256-x86_64.pl
patching file crypto/bn/asm/rsaz-x86_64.pl
patching file crypto/bn/asm/x86_64-mont.pl
patching file crypto/bn/asm/x86_64-mont5.pl
patching file crypto/ec/asm/ecp_nistz256-x86_64.pl
patching file crypto/modes/asm/aesni-gcm-x86_64.pl
patching file crypto/modes/asm/ghash-x86_64.pl
patching file crypto/sha/asm/sha1-mb-x86_64.pl
patching file crypto/sha/asm/sha1-x86_64.pl
patching file crypto/sha/asm/sha256-mb-x86_64.pl
patching file crypto/sha/asm/sha512-x86_64.pl
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2e --openssldir=/usr/local/etc/openssl no-ssl2 zlib-dynamic shared enable-cms darwin64-x86_64-cc enable-ec_nistp_64_g
==> make depend
==> make
==> make test
Last 15 lines from /Users/cm/Library/Logs/Homebrew/openssl/04.make:
Plaintext
Ciphertext
AAD
0000 d9 31 32 25 f8 84 06 e5 a5 59 09 c5 af f5 26 9a
0010 86 a7 a9 53 15 34 f7 da 2e 4c 30 3d 8a 31 8a 72
0020 1c 3c 0c 95 95 68 09 53 2f cf 0e 24 49 a6 b5 25
0030 b1 6a ed f5 aa 0d e6 57 ba 63 7b 39 1a af d2 55
0040 52 2d c1 f0 99 56 7d 07 f4 7f 37 a3 2a 84 42 7d
0050 64 3a 8c dc bf e5 c0 c9 75 98 a2 bd 25 55 d1 aa
0060 8c b0 8e 48 59 0d bb 3d a7 b0 8b 10 56 82 88 38
0070 c5 f6 1e 63 93 ba 7a 0a bc c9 f6 62 89 80 15 ad
Tag
0000 5f ea 79 3a 2d 6f 97 4d 37 e6 8e 0c b8 ff 94 92
make[1]: *** [test_evp] Error 9
make: *** [tests] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
openssl failed to build on 10.9 https://github.com/Homebrew/homebrew/issues/46053
openssl: add 'enable-ssl-trace' option https://github.com/Homebrew/homebrew/pull/45250
wine dependency openssl/1.0.2d https://github.com/Homebrew/homebrew/issues/43752


So this error occurs when installing version 
https://www.openssl.org/source/openssl-1.0.2e.tar.gz

This should be the last stable release.

Are there any suggestions. Is this critical?

**Comment by mikemcquaid** [comment]
@cmayer Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information in a new issue so we can help you with your problem.

Thanks!

**Comment by cmayer** [comment]
Thanks - and sorry for not following all steps!

 A DYLD_LIBRARY_PATH variable was set and pointed to outdated libraries causing the test to fail.
