### ISSUE TITLE
gnu-units: gunits_cur uses wrong Python 2 path

### ISSUE THREAD

**Issue by fenhl** [Homebrew/homebrew#46527]
Running `gunits_cur` (or `units_cur` if the `gnu-units` formula was installed with the `--with-default-names` flag) gives the following error:

```
zsh: /usr/local/bin/units_cur: bad interpreter: /usr/bin/python2: no such file or directory
```

The reason appears to be the first line of the script (`less $(where gunits_cur)`), which says:

```zsh
#!/usr/bin/python2
```

But `python2` is located inside `$(brew --prefix)/bin`, i.e. `/usr/local/bin` by default.

**Comment by dunn** [comment]
And on OSX there's just `python` instead of `python2`.  We'll have to patch it like we do for a few other formulae: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/reposurgeon.rb#L27-L32

Interested in opening a PR?  If you want, take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by fenhl** [comment]
I'd like to submit a PR, but I'm not too familiar with Ruby, nor the process. For instance, what do I need to use instead of `%W[reposurgeon repodiffer]`? I tried just adding `inreplace "units-cur", "#!/usr/bin/python2", "#!/usr/bin/env python"` to the `def install` block, but that gives me a “No such file or directory - units-cur” error when I rey to reinstall `units-cur`. Also, running `brew tests` gives me

```
Could not find docile-1.1.5 in any of the sources
Run `bundle install` to install missing gems.
```

but `bundle install` gives me `Could not locate Gemfile or .bundle/ directory`.

**Comment by dunn** [comment]
Shouldn't it be `inreplace "units_cur"` rather than `inreplace "units-cur"`
