### ISSUE TITLE
Unable to install Homebrew on OS X 10.9 Mavericks: curl says "curl: (7) Failed to connect ... Operation not permitted"

### ISSUE THREAD

**Issue by gw666** [Homebrew/homebrew#46686]
I can't install Homebrew on my OS X 10.9 MacBook Pro, despite searching the Internet in various ways (including searching for the error message). Here's what happens:

    greggs-mbp-7:local gr$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    curl: (7) Failed to connect to 199.27.79.133: Operation not permitted

Somewhere I found instructions on how to install Homebrew, starting by cloning the Github repository. That doesn't work, either:

    greggs-mbp-7:local gr$ git clone git@github.com:Homebrew/homebrew
    Cloning into 'homebrew'...
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

Following @maxton's advice on superuser.com, this happened:

    greggs-mbp-7:local gr$ git clone https://github.com/Homebrew
    Cloning into 'Homebrew'...
    fatal: repository 'https://github.com/Homebrew/' not found
    greggs-mbp-7:local gr$ 

Here are some things that I did before executing either of the above two commands:

    * sudo chown -R `whoami` /usr/local  ; reset permissions to /usr/local

    * created and installed new SSH keys

    * installed XCode and XCode Command Line Tools

    * confirmed that the curl command exists on my computer

I also used Github Desktop for Mac to successfully clone the Github repository for Homebrew (!), so I don't think it's a problem of being unable to retrieve data from the Internet.

I have a feeling it's one of those cases where the error messages are misleading.

Thanks for whatever insight you can give me!

**Comment by rakkesh** [comment]
The URL which you have used to `git clone` is not complete. Try the following,

```
$ git clone https://github.com/homebrew/homebrew /usr/local
```

By the way, it's strange that curl failed with `Operation not permitted`. Are you able to retrieve any other URL using curl?

**Comment by apjanke** [comment]
That "`Operation not permitted`" error from `curl` sounds like a problem with your local system or internet connection setup. Let's try to fix that instead of using the alternate installation methods: if that `curl` operation is failing, you may well run in to errors with fetching and installing formulae anyway.

"`Operation not permitted`" is probably a local error coming from `curl`, and not a server response. If it were failing on the server side, you'd see something like "`curl: (22) The requested URL returned error: 403 Forbidden`". Are you running a firewall on your machine which may limit outgoing connections? (Check the Firewall tab under System Preferences > Security & Privacy.) Or other security software? If your GitHub desktop is able to clone repos (using https), then maybe it was added to the rules in your firewall configuration, but as a command line program, `curl` hasn't been added, and isn't triggering a dialog to prompt you about adding it. (Or maybe GitHub desktop is configured to use `ssh`, so it's using a different port.)

> I have a feeling it's one of those cases where the error messages are misleading.

Could well be.

Try using the `--verbose` or `--trace-ascii <file>` options to `curl` to get more debugging info, and maybe it will have some more informative messages to pinpoint what's going wrong.

**Comment by gw666** [comment]
Thanks to @rakkesh and @apjanke. The first part of @apjanke's advice was easiest to implement. Turned off the Apple firewall—no change. Turning off my Intego NetBarrier—problem solved! Many thanks to you both! (And I've learned a new thing to be aware of. Ah, open-source software!)

**Comment by apjanke** [comment]
Excellent! Glad this was a relatively quick fix.
