### ISSUE TITLE
MPICH over OpenMPI

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew#46712]
I'm wondering what it would take to switch MPICH to be the default MPI implementation. Most supercomputing centers prefer MPICH or MPICH based MVAPICH over OpenMPI and generally find the performance to be better. Perhaps this could cause problems, and the folks over at [homebrew-science](https://github.com/homebrew/homebrew-science) could weigh in here, @dpo, etc. In my experience most HPC centers prefer MPICH. I'm just hoping to start a conversation to evaluate reasons for picking and staying with OpenMPI as a default MPI implementation.

**Comment by UniqMartin** [comment]
Disclaimer: I don't know the reason. I'm not sure if it's really relevant what HPC centers prefer as they are unlikely to run on OS X. Could it be that Open MPI had or still has better OS X support than MPICH? Another reason might be that Open MPI was bundled with OS X in the passt, according to [this FAQ entry](https://www.open-mpi.org/faq/?category=osx#osx-bundled-ompi).

**Comment by jsquyres** [comment]
That's quite the generalization there. :)

If you ask 10 different people, you'll find 10 different opinions about which MPI is "better" and/or which should be and/or is the default at any given organization. So you might want to stay away from overly broad comments. 

That being said, I agree that the default MPI in home brew is quite a different discussion than the strong religious opinions from any given HPC environment. 

FWIW: it might actually be *good* to have a different MPI as the default on your laptop vs the production environment you run in, because it'll help stress your code and actually ensure that it is compliant with the MPI specification, and not accidentally falling into the trap of unknowingly relying on the quirks of any single MPI installation. 

Just my $0.000000001.

**Comment by zbeekman** [comment]
Fair, it is an un-scientific generalization. Right now I don't have the energy to back this up with evidence, but I may find the motivation later.

If the point is to develop and test code on a Mac, then yes it is nice to test a different case. BUT, those users will certainly be comfortable switching and installing one or both MPI libraries. For other applications that `depends_on => :mpi` they will be built and linked against OpenMPI in the bottled distribution, and end users of those applications might not have the know how or patience to figure out which MPI implementation is faster or "better" for the software package in question. If they have not installed MPI yet, the choice will be made for them, and OpenMPI will be installed and used for the software in question.

Any way, just a thought that I had, that I believe is worth discussing.

**Comment by jsquyres** [comment]
Sure, fair enough. But at the end of the day, there may not be a Right answer. 

There are many benefits to having a duopoly of MPI implementations, but the "which should be the default?" Question is definitely not one of them.

**Comment by UniqMartin** [comment]
And I think even *if* MPICH actually offers superior performance, there are other factors to consider when selecting a default and raw speed is not always the most important aspect when targeting a desktop operating system like OS X. The answer as to why `open-mpi` is the default might be as simple as: it has been part of Homebrew since 2010, while the `mpich` formula was only added in 2012.

**Comment by mikemcquaid** [comment]
> The answer as to why open-mpi is the default might be as simple as: it has been part of Homebrew since 2010, while the mpich formula was only added in 2012.

This and because it was included with OS X in the past. That seems a good enough reason to leave it as-is for now unless someone cares to produce some benchmarks or compiler support or something that makes this a slam-dunk.

**Comment by zbeekman** [comment]
OK fair... I just wanted to get some input from other Homebrew users.
