### ISSUE TITLE
mplayer: cannot build with x11 because X11/Xlib.h not found

### ISSUE THREAD

**Issue by JMoVS** [Homebrew/homebrew#46748]
Hi,
I am working on cleaning up the mplayer formula and getting it to work (more) properly.

It by now requires X11 to be usable in such a scenario. Building it outside of homebrew with just ./configure --prefix=/somehwere/else works. (I have installed x11 by brew cask install xquartz).

But if I want to do the same thing in homebrew and manipulate the formula so that it only runs ./configure --prefix=/usr/local/Cellar/mplayer/1.2 and works, it fails with this: in .../mplayer02.make

In file included from mplayer.c:133:
./libvo/x11_common.h:23:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^
1 error generated.
make: *** [mplayer.o] Error 1
make: *** Waiting for unfinished jobs....

.configure of mplayer 1.2 has autodetect for x11, so if I pass --disable-x11, it works

Not urgent, just a general error that made me curious.

**Comment by DomT4** [comment]
As a heads-up, if X11 becomes mandatory it'll have to move to the `homebrew/x11` tap.

We don't insert the X11 paths into the build env unless you invoke X11; is it still failing with either a hard X11 dependency or `brew install mplayer --with-x11`?

**Comment by JMoVS** [comment]
ok, well, it is not needed for the basic version though ;-)

it does fail when I supply ````--with-x11 ````. I don't know how I could test a "hard dependency".

**Comment by DomT4** [comment]
Alright. The less `x11` we have in the core, the better for everyone :wink:.

> I don't know how I could test a "hard dependency".

You'd just make the dependency `depends_on :x11` unconditionally, essentially. I think when I looked at this in the past I couldn't get it to pick up X11 either, but since it wasn't essential I gave up, heh.

Closing this in favour of the PR you opened, since it's easier to centralise discussion in one place :). https://github.com/Homebrew/homebrew/pull/46749 for reference.
