### ISSUE TITLE
openssl fails to build on 10.7.5

### ISSUE THREAD

**Issue by genekeats** [Homebrew/homebrew#46751]
The openssl formula (v1.0.2e) fails for 10.7.5 during 03.make.

https://gist.github.com/535cccb1797b03566f8e#file-03-make

**Comment by mvkorpel** [comment]
This seems to be a problem in OpenSSL. https://github.com/openssl/openssl/issues/494

**Comment by DomT4** [comment]
Yes, it has been reported to them quite a few times now. Waiting to see if they do anything to resolve the problem before we poke around.

**Comment by mojca** [comment]
Maybe their primary bug tracker is on rt.openssl.org rather than on github. The initial ticket (that lead to broken functionality) is here:
  * https://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=4142

**Comment by DomT4** [comment]
They tend to use a mixture of Github, RT and the mailing list. Github stuff often gets linked to on the mailing list, but I don't know how actively they watch it. I'm not convinced the "fix" commit they pointed to isn't part of the latest release and is causing the problem still. I'll download the tarball and double check.

**Comment by mojca** [comment]
Which "fix commit" are you talking about? There was only a commit that was supposed to fix a problem on Xcode 7, but that broke the behaviour on 10.7. There was no fix for the problem on 10.7 yet.

**Comment by DomT4** [comment]
Apologies, misread the bug report. The joys of juggling a bunch of open webpages.

**Comment by dossy** [comment]
In case anyone else is dealing with this, and wants to use 1.0.2d in the meantime:

    $ cd "$(brew --prefix)/Library/Formula"
    $ git checkout e9660e55^ ./openssl.rb

I discovered that if I don't do this, even if I try to `brew pin openssl 1.0.2d_1`, if I install something that lists `openssl` as a dependency (e.g., `python`), it'll still try to build OpenSSL 1.0.2e, and then error and fail.  I had to revert the formula in order to get Homebrew to not try and build 1.0.2e.

**Comment by DomT4** [comment]
Homebrew builds everything against the latest formula version and enforces that, even overriding `brew pin`. It's too many variables to handle otherwise, chasing down obscure bug reports on obscure local change.

Obviously, be aware if you install 1.0.2d it has publicly known security vulnerabilities now.

**Comment by mojca** [comment]
A possible workaround might be to use a different (newer clang) compiler to compile openssl until a patch is applied or a newer fixed version gets released. (I guess that can be achieved with `HOMEBREW_CC` and `HOMEBREW_CXX`?)

**Comment by neverpanic** [comment]
I've patched this in MacPorts with a patch that could be suitable for upstream to accept.

See openssl/openssl#494 for a link to the patch.

**Comment by FranklinChen** [comment]
I hope this gets fixed... I have two old Macs I still actively use that are stuck on Mac OS X 10.7.5!

**Comment by DomT4** [comment]
Thanks Clemens; nice to see you here. Have you poked the upstream mailing list with that at all? OpenSSL are semi-notorious for not noticing patches unless you get insistent about it, alas.

**Comment by nodje** [comment]
Just asking: would a MacPorts openssl install be recognized by Homebrew and would it allow it to further install command dependent on openssl?
More generally, is Homebrew looking for dependencies in its own space or is it looking in the available PATH for existing command's versions?

**Comment by DomT4** [comment]
> would a MacPorts openssl install be recognized by Homebrew and would it allow it to further install command dependent on openssl?

No. MacPorts and Homebrew don't exist alongside each other particularly well. We have some differing philosophies, none of which are invalid or wrong or fundamentally flawed or such on either side, but can make us problematic for each other.

> More generally, is Homebrew looking for dependencies in its own space

Yeah. We use the system where a dependency isn't declared and our dependencies where they are declared. Prevents random build errors, obscure bug reports, etc. Package management is complex enough without odd variables you can't control in the mix, sadly.

**Comment by DiagonalArg** [comment]
Same problem - OS/X 10.7.5...  (Not the first time openssl have been problematic...)

**Comment by DomT4** [comment]
Should be fixed after a `brew update`. Tested @neverpanic's patch in a Lion VM with success, and applied. Thanks @neverpanic :heart:

**Comment by mewo2** [comment]
I'm getting this error on Mountain Lion (10.8.5) after a `brew update`. Possibly an over-zealous version check in the patch?

**Comment by DomT4** [comment]
The patch wasn't applied to Mountain Lion because to date nobody using 10.8 had come forwards and gone "It's broke", so rather than applying a potentially needless patch, limited it to the scope of what is known to be problematic.

Is the error identical?

**Comment by mewo2** [comment]
Yes, I believe so.

**Comment by DomT4** [comment]
`brew update` and try again now. Extended the patch one OS further.

**Comment by mewo2** [comment]
Success!

**Comment by DomT4** [comment]
:tada: Thanks for the confirmation!

**Comment by mojca** [comment]
Just a short note about Mountain Lion: the problem is related to the version of compiler (= the version of Xcode being installed). So Mountain Lion users with an "old" version of Xcode (Xcode < 5, for example those using clang-425) should experience exactly the same problem as Lion users. The only difference between Lion and Mountain Lion users is that the latter should be able to upgrade their Xcode to get the problem fixed. (The problem is in the fact that openssl does a configure test to check for a particular feature, clang-425 passes that simplified test, but fails during a more complex usage. (Sufficiently) older compilers would fail the test and newer compilers work as expected.)

The patch is supposed to be safe to apply for all users and should not have any influence on newer Xcode / OS versions.

**Comment by DomT4** [comment]
Aye. Appreciate that. Just not big on applying patches not yet accepted upstream (to my knowledge) more broadly than we have to.

**Comment by mojca** [comment]
The patch 2345dcb0d182c9306339b0ad56e317629545e1b6 is perfectly fine. I just hope that the explanation about why ML users might be affected was helpful to someone.
