### ISSUE TITLE
Homebrew's sbin was not found in your PATH after brew doctor

### ISSUE THREAD

**Issue by erow80** [Homebrew/homebrew#46865]
Apologies if this has already been addressed here, but I searched and couldn't find a solution. 

Running `brew doctor` gives this warning:

```
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

The suggested command `echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile` doesn't seem to fix the issue.

**Comment by DomT4** [comment]
> The suggested command echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile doesn't seem to fix the issue.

Note that you'd need to open a new terminal tab/window/etc for the new change to apply. Which shell are you using?

**Comment by erow80** [comment]
Thanks @DomT4, I did restart terminal after running the command. I am using fish.

**Comment by DomT4** [comment]
Ah, yeah, that'll happily ignore the bash configuration file. You may find [this document](http://fishshell.com/docs/current/tutorial.html#tut_path) useful.

**Comment by erow80** [comment]
Okay, thanks for letting me know. I figured it was something along those lines. Should I ignore the warning and close this issue? Everything seems to be working normally.

**Comment by DomT4** [comment]
Yeah, we cover a few common shells that share a compatible syntax but [not fish](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/utils.rb#L440-L448) because it doesn't.

If you change your `$PATH` in `fish` as recommended in that document the warning in `brew doctor` should go away. Otherwise, you can ignore it as desired.

The warning just means that a formula has installed an executable into `sbin` and you won't be able to call it from the command-line without a full path until that directory is available to `$PATH`.

**Comment by DomT4** [comment]
Closing here, but feel free to comment again if you need any help resolving this further. Thanks!
