### ISSUE TITLE
brew update doesn't pop stash?

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#46919]
Last few times I've updated I noticed that the changes I made were being lost every update instead of being applied after the pull. `/usr/local` had something like 8+ stashes when I checked, and I'm fairly certain I didn't create them manually.

Did something change recently?

**Comment by UniqMartin** [comment]
Yes, this is a recent change. It is supposed to make the update procedure more resilient for the majority of our users and thus to lower our support burden a bit. Technically, your changes were never lost as `brew update` stashed them and also printed a message telling you how to restore the stashed changes. It cannot do this automatically because the changes may no longer apply after the update.

However, all of the stuff stated above only applies if you are working directly in the `master` branch; and you shouldn't. If you keep your work in a separate branch, then changes will be preserved across `brew update` and all uncommitted changes in your working directory will be automatically stashed and then fully restored once the update finishes.

Does that answer your question?

**Comment by aw1621107** [comment]
Ah, ok, that makes sense. I probably missed the message about restoring changes because I have brew in verbose mode which would push the message off-screen pretty fast.

Didn't know the changes were restored for branches; I've been lazy and just symlinked changes in my fork to /usr/local. I'll have to fix that...

That answers my question. Thanks!

**Comment by UniqMartin** [comment]
I can see how that message can be easily lost given all the other output of `brew update` in verbose mode. I'm glad I was able to help. :smile_cat:
