### ISSUE TITLE
How to write a formula for package that require email to download

### ISSUE THREAD

**Issue by valkjsaaa** [Homebrew/homebrew#46925]
Hi everyone, I'm trying to write a formula for speech recognition framework [htk](http://htk.eng.cam.ac.uk/download.shtml). It needs email to start download. Any idea to implement some way for the user to enter email to download the package? Thanks!

**Comment by tdsmith** [comment]
We're not likely to accept a formula that does this into Homebrew's repositories (because formulas are strictly non-interactive, this is a niche requirement, and the license forbids redistribution so it is not FOSS) but you could maintain a formula that does this yourself [in a tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md). An example of formulas that depend on user input are the pebble SDK formulas: https://github.com/pebble/homebrew-pebble-sdk

You could use any Ruby functions that interact with the user but that's outside the scope of the Homebrew issue tracker. Let us know if we can help with anything.

**Comment by bfontaine** [comment]
As Tim wrote we won’t accept this formula but if you’re maintaining it in your tap and respect upstream’s license you can do what you want.
Here it’s more complicated than just asking for an email because you need to register with a username/name/email/address then wait for an email to get your password.
If you find a way to figure out this part you can give the username/password to Homebrew with `:user => "..."`:

```rb
class Htk < Formula
  desc "..."
  homepage "http://htk.eng.cam.ac.uk"
  url "http://htk.eng.cam.ac.uk/ftp/software/HTK-3.4.1.tar.gz",
    :user => "yourusername:yourpassword"
  # ...
```

I was successfully able to run `brew fetch htk` with this.

**Comment by valkjsaaa** [comment]
Thanks a lot, this is really helpful!
