### ISSUE TITLE
clamav 0.99.0

### ISSUE THREAD

**Issue by the-real-tokai** [Homebrew/homebrew#46932]
I don't know who maintains the **clamav** formula, but a new version (0.99.0) of **clamav** seems to be available since a while, see http://www.clamav.net/

**Comment by DomT4** [comment]
We don't have specific formula maintainers. It's up to anyone in the community wants to update things, really. I've done it in https://github.com/Homebrew/homebrew/pull/46948 this time, since there's a few changes I wanted to make at the same time. Feel free to track that PR.

In future, if you're feeling kind, you can submit the update yourself [like this](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) :smiley:.

**Comment by the-real-tokai** [comment]
Works, thanks for the update! :+1:
