### ISSUE TITLE
brew update lossage: "*** Please tell me who you are. ..." ?

### ISSUE THREAD

**Issue by DiagonalArg** [Homebrew/homebrew#46930]
running `brew update` returns:

```
*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --lobaluser.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'me@my-laptop.(none)')
Cannot save the current index state
Error: Failure while executing: : git stash save --include-untracked --quiet
```

running `brew doctor` returns only:

```
Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours.  This is a long time in brewland!
To update Homebrew, run 'brew update'
```

The only things I have seen come up of late (in trying to upgrade) has been that openssl fails to build (issue #46751) and so it's dependency, curl, can not be upgraded.  I also tried to install keybase, and it failed for the same reason.

This is OS/X 10.7.5

**Comment by tdsmith** [comment]
Have you tried following git's advice? That will let `brew update` stash changes that you've made in your local version of the repository. If you definitely don't care about any changes you've made to formulas, you can do something like `cd $(brew --repository) && git reset --hard origin/master` instead of configuring your email address.

**Comment by DiagonalArg** [comment]
@tdsmith - I tried `cd $(brew --repository) && git reset --hard origin/master`, as you said, and the result of `brew update` is unchanged.

While I could follow git's "advice", the fact that I have never been offered this advice in the past, seems to indicate that something is awry.  So I'd like to understand what that might be.

**Comment by the-real-tokai** [comment]
When I updated brew very recently (`brew update`) it suddenly created a stash (git) during the update. I also wondered if that is any normal behaviour. I did not had any local modifications that should have triggered this. Probably unrelated to the issue reported here, but I also felt like something is awry and I'm still puzzled about this. In the end I manually killed off the git stash. 

Just before I had updated to the latest **Xcode** (7.2 7C68). Maybe related. Else it has to be some change in brew itself, I guess.

**Comment by DiagonalArg** [comment]
@the-real-tokai Thanks for your input.  I hadn't upgraded Xcode, so that's not my issue.  

Not being knowledgeable regarding git, can you tell me what it means to kill off a git stash?  How do I do that?

**Comment by the-real-tokai** [comment]
I'm not very knowledgable with **git** and its (IMHO bloated) command set either (I prefer Subversion for my own stuff :smile:), but it seems one can put all local modifications into a separate buffer (a "stash") before updating to the latest (remote) version. For some reason git did that automatically for me during the brew update.

To check for the currently available stashes on can use `git stash list`:
```
$ git stash list
stash@{0}: WIP on master: 0ABCDEF ...
...
```

And to delete a specific stash (assuming one doesn't need the modifications stored in it):
```
$ git stash drop stash@{0}
```

or to get rid of them all in one go (I did not try this):

```
$ git stash clear
```

**Comment by DiagonalArg** [comment]
@the-real-tokai - Ok, I have to thank you gain, though unfortunately, `git stash list` returns an empty list for me.  It seems it was trying to *save* a stash, though, as the error reports failure on: `git stash save --include-untracked --quiet`.

**Comment by UniqMartin** [comment]
Yes, there have been changes to `brew update` recently, that may cause you to see this changed behaviour. We could probably a bit more cautious with stashing changes if Git hasn't been configured with a name and e-mail address yet.

We only create a stash, if there have been local modifications. We do this, because we don't want to blindly destroy user changes during a `brew update`, but also need to return to a known-good state before performing the update to avoid all kinds of issues that would arise if any of those local modifications conflicted with the updates we are fetching.

@DiagonalArg You probably have local modifications in your Homebrew repository, as we don't try to stash otherwise. You can check that with `cd "$(brew --repository)" && git status --untracked-files=all`. What's the output of this command?

@the-real-tokai There shouldn't be any connection to the Xcode update. Also, you should have been notified that local changes have been stashed during `brew update`, so the existence of this stash should be no surprise. (Could be that you haven't noticed because you haven't updated in a while, so the formula change report is quite long.)

**Comment by the-real-tokai** [comment]
@UniqMartin Yes, during the update it told me that it created a stash. That's how I got aware of it. If this is a new feature then all is well (in my case), I guess. :smile:  The way *brew* updates (itself) probably makes it somewhat hard to communicate such (behavioural) changes to its users. That's a bit easier/ more transparent for projects with versioned stable release points and corresponding change logs.

I'm still puzzled why it would stash things when I never had any (local) modifications, but maybe I don't understand git's *modus operandi* properly here. Basically I only ever did `brew update` more or less regularly (but at least once a week).

**Comment by UniqMartin** [comment]
> That's how I got aware of it. If this is a new feature then all is well (in my case), I guess. :smile:

@the-real-tokai Great. Yes, that's a relatively new feature with apparently not all edge cases properly ironed out yet. Our update model indeed makes it a bit harder to communicate such changes. And I'd guess that 99% of our users don't care about such a change.

> I'm still puzzled why it would stash things when I never had any (local) modifications, […]

As Homebrew is entirely built on top of Git, we also rely on Git to check for local modifications. There are various corner cases where Git will believe there are local changes without the user having actively changed anything, often caused by non-standard Git configurations. We try to avoid these situations by being careful about how we invoke Git and by overriding some configuration that is known to cause trouble, but there will always be situations we cannot foresee …

**Comment by DiagonalArg** [comment]
@UniqMartin Thanks for your response!

Ok, well I didn't actually have any local modifications, though I did once play with the command `brew edit`, just to see what it did.  Then I cancelled and exited or killed it or something.

Running `git status --untracked-files=all` returns:

```
On branch master
Untracked files:
   (use "git add <file>..." to include in what will be committed)

      Library/Formula/hamsterdb.rb

nothing added to the commit but untracked files present (use "git add" to track)
```

So, when I do `brew update`, perhaps there should be a way for me to tell it that it's ok to ignore changes?

**Comment by UniqMartin** [comment]
> So, when I do `brew update`, perhaps there should be a way for me to tell it that it's ok to ignore changes?

As I tried to explain in an earlier comment, we can't ignore such changes without very quickly running into all kinds of issues. If you don't care about those changes, the best solution would be to remove `Library/Formula/hamsterdb.rb` (the `hamsterdb` formula was recently renamed to `upscaledb`), and if you do care, the best option really depends on the nature of those changes.

**Comment by UniqMartin** [comment]
@DiagonalArg I think the issue should be fixed now and `brew update` should be able to stash local modifications (if any) without asking for your name and e-mail address. However, to benefit from those changes, you'll first have to clean up your local copy of the Homebrew repository and successfully run a `brew update` to fetch my changes. (Let me know in case you have trouble with that.)

**Comment by DiagonalArg** [comment]
@UniqMartin - Thanks for the work.  Actually I deleted `hamsterdb` and `upscaledb`, but it still didn't work.  After some combination of git commands, trying to get it to ignore any changes, it allowed the update; but it still complained about the name/email.  I just gave up and supplied it something random.

**Comment by the-real-tokai** [comment]
I never encountered the name/ email stuff, it seems an auto-generated `.gitconfig` file did hide the problem for me.

```
$ cat ~/.gitconfig 
...
[user]
	name = the-real-tokai
	email = the-real-tokai@users.noreply.github.com
...
```

Seems the file was generated by the GitHub Desktop app. I find it rather strange it does mess with the global git config (it also messes with ssh keys), but that's a different story. :smile:

Anyway... just wanted to mention this here, in case someone has trouble upgrading to the fixed brew with `brew update`. Such `.gitconfig` file could be a solution in that situation.
