### ISSUE TITLE
llvm shouldn't build with assertions by default?

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#47069]
Should the `llvm` formula default to building with assertions? I thought homebrew typically installs release builds, and I'd imagine assertions wouldn't be that useful with optimizations.

The [llvm docs on cmake](http://llvm.org/docs/CMake.html) say that assertions are normally enabled by default only for debug builds, too, if that makes any difference.

**Comment by UniqMartin** [comment]
I agree with your reasoning and think we should remove this option completely, building optimized release binaries by default. Scanning through the `git log` of the `llvm` formula I got the impression that this flag is from a time when LLVM was much less mature and then carried over from the `autoconf` to `cmake` based build without much thought.

**Comment by aw1621107** [comment]
Alright, I'll get a PR submitted sometime today

**Comment by DomT4** [comment]
Feel free to file a PR here if you still want to make the change, Cheers!

**Comment by aw1621107** [comment]
Huh, could have sworn I submitted one already....

**Comment by UniqMartin** [comment]
> Huh, could have sworn I submitted one already....

You did in PR #47145, but then you closed it yourself a week ago and I don't really understand why that happened and why there's a need for a new one (#47575).

There's a lot of PRs and issues (both open and closed) floating around `llvm` and I have to admit that I lost track over the holidays. It would be good if all the people passionate about this formula (as there are obviously several) could collaborate more closely instead of creating numerous concurrent PRs and issues. (Just my gut feeling from the stuff I observed over the past few weeks. I might be wrong.)

**Comment by aw1621107** [comment]
I think I got that branch mixed up with the one adding `-DNDEBUG` as a standard CMake arg, so when that PR got merged I deleted that branch too. My mistake.
