### ISSUE TITLE
moving cmake from macports to homebrew(/opt to /usr/local)

### ISSUE THREAD

**Issue by vikrantvm** [Homebrew/homebrew#47084]
I moved from macports to homebrew and reinstalled cmake. Running ```which cmake``` gives me:
 ```
/usr/local/bin/cmake
```

I'd installed opencv using the earlier cmake and I want to uninstall it, but running ```make uninstall``` gives me:

```
$ sudo make uninstall
make: /opt/local/bin/cmake: No such file or directory
make: *** [cmake_check_build_system] Error 1
```

How can I make my cmake point to its new home?

**Comment by bfontaine** [comment]
Try restarting your shell session or use `rehash -r` in Bash. When you type `cmake` your shell does the equivalent of `which cmake` to find the right executable and then remembers it so it doesn’t have to run `which <command>` every time. `rehash -r` tells Bash to forget all the paths and try to find `cmake` again instead of looking at the old location. Restarting your shell session has the same effect.

**Comment by mikemcquaid** [comment]
You need to rerun `cmake .` in the `opencv` directory.

**Comment by vikrantvm** [comment]
Thanks for the suggestions bfontaine and mikemcquaid. ```cmake . ``` was the easier way out. I changed cmake paths in the makefile.
