### ISSUE TITLE
"brew tap --list" shows backtrace

### ISSUE THREAD

**Issue by proski** [Homebrew/homebrew#47162]
I would expect `brew tap --list` to show me that the `--list` option is invalid or ambiguous. Instead, it causes a backtrace. I'm running up-to-date Homebrew on up-to-date El Capitan.
```
~ $ brew tap --list
Error: undefined method `split' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/tap.rb:22:in `fetch'
/usr/local/Library/Homebrew/cmd/tap.rb:16:in `tap'
/usr/local/Library/brew.rb:143:in `<main>'
```

**Comment by apjanke** [comment]
Yep, that's an argument-parsing bug in `brew`. [Here](https://github.com/Homebrew/homebrew/blob/e973ef0052af62bf63be98de9c4dfa252a82cbf1/Library/Homebrew/cmd/tap.rb#L5-L16), `cmd/tap.rb` is basically conflating `ARGV.empty` with `ARGV.named.empty`, which it should also be checking, to avoid passing `nil` to `tap.fetch`.

In general, invalid options to `--brew` are silently ignored. It's partially a consequence of the design for `install` and related commands where the various formulae can specify arbitrary options that `brew` doesn't know about up front. But also because the code in `brew` is pretty loose about argument handling: generally, there's no global argument parsing or definition; code that cares about a particular option just checks for its presence locally.

This shouldn't be too hard to take care of. Thanks for reporting.
