### ISSUE TITLE
fontconfig bottle is broken at non-standard prefix

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew#47173]
I have homebrew installed at `/Homebrew` rather than `/usr/local`.

All applications that use fontconfig (see https://github.com/Homebrew/homebrew-x11/issues/168 ) complain on startup and many crash.

Reinstalling with `brew reinstall --build-from-source fontconfig` fixes it.

It seems that fontconfig should not be setting `cellar :any`?

**Comment by DomT4** [comment]
Can you reproduce this with other pieces of software? Couldn't hit the failure on `emacs --with-x11` for example from the core. I can't get GTK+ to build from source in a non-standard prefix at the moment so stuck on not being able to test `inkscape` personally.

**Comment by glyph** [comment]
The easiest way to see it is just to run `fc-cache`; it doesn't crash, but it spits out the warning.

**Comment by glyph** [comment]
If you've *previously* installed fontconfig at the standard prefix it may have generated the configuration in the standard location which will mask this bug, so be sure you're testing on a pristine system.

**Comment by NVD-R** [comment]
hi i try to re install but i see this error in my console again :
Last 15 lines from /home/navid.rajaie/.cache/Homebrew/Logs/fontconfig/02.make:
Using catalogs: /etc/sgml/sgml-docbook-3.1.cat
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#html
Working on: /tmp/fontconfig20160114-31657-1ru8pqe/fontconfig-2.11.1/doc/fontconfig-user.sgml
Using catalogs: /etc/sgml/sgml-docbook-3.1.cat
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#html
Working on: /tmp/fontconfig20160114-31657-1ru8pqe/fontconfig-2.11.1/doc/fontconfig-devel.sgml
Using catalogs: /etc/sgml/sgml-docbook-3.1.cat
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#print
Working on: /tmp/fontconfig20160114-31657-1ru8pqe/fontconfig-2.11.1/doc/local-fontconfig-devel.sgml
make[2]: Leaving directory '/tmp/fontconfig20160114-31657-1ru8pqe/fontconfig-2.11.1/doc'
Makefile:1167: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/tmp/fontconfig20160114-31657-1ru8pqe/fontconfig-2.11.1/doc'
Makefile:561: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

can you help me?

**Comment by p0fi** [comment]
I'm having the same issue, I can't build it form source with the same error message. Any tips how to fix?

**Comment by mikemcquaid** [comment]
> Any tips how to fix?

Install into `/usr/local`; it's the only prefix that's regularly tested. Otherwise you may have to help us work on a fix.

**Comment by glyph** [comment]
@NVD-R @p0fi See my original comment: there's an easy workaround.  `brew reinstall --build-from-source fontconfig`.

**Comment by NVD-R** [comment]
@glyph i tried but :
$ brew reinstall --build-from-source fontconfig
==> Reinstalling fontconfig
==> Downloading http://fontconfig.org/release/fontconfig-2.11.1.tar.bz2
Already downloaded: /home/navid.rajaie/.cache/Homebrew/fontconfig-2.11.1.tar.bz2
==> Patching
patching file fc-cache/fc-cache.c
patching file fontconfig/fontconfig.h
patching file src/fccache.c
patching file src/fcdir.c
patching file src/fcfs.c
patching file src/fcint.h
patching file src/fcpat.c
==> ./configure --disable-silent-rules --enable-static --with-add-fonts=/System/Lib
==> make install RUN_FC_CACHE_TEST=false
Last 15 lines from /home/navid.rajaie/.cache/Homebrew/Logs/fontconfig/02.make:
Working on: /tmp/fontconfig20160204-30087-13mle9k/fontconfig-2.11.1/doc/local-fontconfig-devel.sgml
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#html
Working on: /tmp/fontconfig20160204-30087-13mle9k/fontconfig-2.11.1/doc/fontconfig-devel.sgml
rm -f fontconfig-user.pdf; \
docbook2pdf fontconfig-user.sgml
/bin/sh: line 1: docbook2pdf: command not found
Makefile:1304: recipe for target 'fontconfig-user.pdf' failed
make[2]: *** [fontconfig-user.pdf] Error 127
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/fontconfig20160204-30087-13mle9k/fontconfig-2.11.1/doc'
Makefile:1167: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/tmp/fontconfig20160204-30087-13mle9k/fontconfig-2.11.1/doc'
Makefile:561: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
fontconfig bottle is broken at non-standard prefix https://github.com/Homebrew/homebrew/issues/47173

**Comment by mikemcquaid** [comment]
@NVD-R We don't support Linuxbrew here.

**Comment by NVD-R** [comment]
@mikemcquaid oh, I'm sorry, thanks for your attention

**Comment by mistydemeo** [comment]
@glyph Does the output of `fc-cache` have anything possibly pertinent in it?

**Comment by mistydemeo** [comment]
Oh, heh. Looking at the formula, it has this comment above the bottle block:

```ruby
  # The bottle tooling is too lenient and thinks fontconfig
  # is relocatable, but it has hardcoded paths in the executables.
  bottle do
    cellar :any
    revision 4
    sha256 "ebf34b370ba91f92df903e7b080135f3cc6e0492156002ee3fdd899128f60aa8" => :el_capitan
    sha256 "5b27c11fd4dc7ccc4c37484775efa581f5c6cb3b447ea744a8d14573800ae516" => :yosemite
    sha256 "bd0b9ce3d85d4767ac326d1ec58eb99825a6218e20d32ca20508f399867be700" => :mavericks
  end
```

However, we accidentally let a test-bot autogenerated commit update that to `cellar :any` back in 2014: 4d384b897f7b2f929b32eed06cb3ac9264a10350

**Comment by DomT4** [comment]
Oh. We can probably apply the same hack from the `lua` formula for now then (?)

**Comment by mistydemeo** [comment]
Borrowed the hack from lua. At some point it would be nice to fix the underlying issue!

**Comment by DomT4** [comment]
Thanks Misty! Poking around the Lua problem is on my to-do list, but I'm not massively familiar with `fontconfig`'s inner workings so if anyone wants to volunteer there, feel free :smiley:.

**Comment by UniqMartin** [comment]
@DomT4 @mistydemeo The underlying issue is to be found [in these lines in `cmd/bottle.rb`](https://github.com/Homebrew/homebrew/blob/b10a9b625207b5da84c78ab40e10fcfd59396524/Library/Homebrew/cmd/bottle.rb#L238-L242). On our bots, this means we are only checking for the strings `/usr/local/opt` and `/usr/local/Cellar` to determine if the bottle is relocatable. To take `fontconfig` as an example, the effect is that strings like `/usr/local/etc/fonts` or `/usr/local/var/cache/fontconfig` (to be found in `lib/libfontconfig.1.dylib`) are not causing the bottle to be marked as non-relocatable, though that should be the case.

The distinction between a `/usr/local` prefix and any other prefix was originally introduced in ba057f6b9a568ab2097d021c657996ffc28f2fa4, which makes clear that just removing the `/opt` suffix in the check probably isn't the solution. A rather expensive fix is to build the formula in a non-standard prefix, check if it is relocatable, and

- if it is, create the bottle and be done, or
- if it isn't, rebuild with a `/usr/local` prefix, create the bottle, and mark it as non-relocatable.

The current strategy is to occasionally tag a bottle as relocatable, even if it isn't, which will only be noticed by users who have a non-standard prefix. The safer alternative would be that all remaining occurrences of `/usr/local` mark the bottle as non-relocatable, possibly decreasing the number of (seemingly) relocatable bottles. (An interesting exercise would be to determine how many of the existing bottles would produce a different result if `/usr/local` was checked instead of `/usr/local/opt`.)

Feel free to further investigate and fix this issue as I don't see myself addressing it anytime soon. But if I do before someone else does, at least I have a summary of the underlying cause as a starting point. :smile_cat:

**Comment by mikemcquaid** [comment]
@UniqMartin I think a happy middle ground may be to check for more strings for relocatability.

**Comment by UniqMartin** [comment]
> I think a happy middle ground may be to check for more strings for relocatability.

That's true. If `fontconfig` and `lua` are representative cases, adding `/usr/local/{etc,lib,var}` to the list should solve the issue with very high probability without introducing too much noise.

**Comment by mikemcquaid** [comment]
@UniqMartin I think `/usr/local/lib` is a bad idea because it's a default link path and we symlink it (similarly: `/usr/local/{bin,share,sbin}`. `/usr/local/etc`, `/usr/local/var` and `/usr/local/lib/something` all seem reasonable :+1:
