### ISSUE TITLE
LibreSSL stable: 2.2.5

### ISSUE THREAD

**Issue by rakkesh** [Homebrew/homebrew#47211]
I have noticed that `libressl` formula is following the development snapshot (2.3.1) release instead of the latest stable, 2.2.5. Is there any reason for doing so? 

http://www.libressl.org/releases.html

**Comment by DomT4** [comment]
Because at the moment the "Current" branch rather than "Stable" branch is remaining compatible with 99% of formulae and retaining more desirable short-term security goals (Bye SSLv3, `libtls` which upstreams have started using already matures quicker, cleaner codebase, etc).

At some point, possibly in March when the current branch becomes the "stable" branch we'll probably choose to keep tracking that.
