### ISSUE TITLE
algol68g download URL broken

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew#47433]
Trace:

```
$ brew install algol68g 
==> Downloading http://jmvdveer.home.xs4all.nl/algol68/algol68g-2.8.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "algol68g"
Download failed: http://jmvdveer.home.xs4all.nl/algol68/algol68g-2.8.1.tar.gz
```

**Comment by DomT4** [comment]
Looks like upstream moved homepage to http://jmvdveer.home.xs4all.nl/algol.html stuck a redirect in place but didn't do the same for the URL, which is also outdated.

Formula should be:
```ruby
homepage "http://jmvdveer.home.xs4all.nl/algol.html"
url "http://jmvdveer.home.xs4all.nl/algol68g-2.8.2.tar.gz"
sha256 ""
```

With the new `sha256` for the version update where the empty commas are there.

Submit a PR if you like, otherwise I'll get round to it at some point in the next 24 hours.

**Comment by DomT4** [comment]
Fixed by https://github.com/Homebrew/homebrew/commit/e34466243ac92915c47ad2ceeab78edbecc469aa, Thanks!
