### ISSUE TITLE
subversion 1.9.2 install fails due to 404.  Can the formula be updated to use 1.9.3?

### ISSUE THREAD

**Issue by jmdilley** [Homebrew/homebrew#47465]
Homebrew's formula for subversion is set to use 1.9.2, which for some reason isn't available on Apache's site (they go from 1.9.1 to 1.9.3).

Since 1.9.3 is out, anyway, would it be possible to get the formula updated to use 1.9.3 of subversion?  I did so locally, by editing the .rb file to the new version and sha256, but I don't know what all normally goes into this, i.e. are there any dependency changes needed that I didn't do locally?

Thanks!

**Comment by DomT4** [comment]
> did so locally, by editing the .rb file to the new version and sha256, but I don't know what all normally goes into this, i.e. are there any dependency changes needed that I didn't do locally?

Since it's a minor version bump you should be okay with only updating the url/sha256 of the `subversion` formula itself. [File a PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) to handle the update here, if you'd like to.

**Comment by clayshieh** [comment]
I ran into the same problems while using linuxbrew and changed the download urls and SHA256 accordingly but I still get errors telling me: "/bin/sh: 1: /usr: Permission denied" Would that be a different issue?

**Comment by mikemcquaid** [comment]
> Would that be a different issue?

Yes. Please report Linuxbrew issues to Linuxbrew.
