### ISSUE TITLE
rethinkdb bottle doesn't include backup/restore

### ISSUE THREAD

**Issue by JurgenJocubeit** [Homebrew/homebrew#47483]
Tried to backup databases using `rethinkdb dump` command only to be presented with the following error:
```
Error when launching 'rethinkdb-dump': No such file or directory
The rethinkdb-dump command depends on the RethinkDB Python driver, which must be installed.
If the Python driver is already installed, make sure that the PATH environment variable
includes the location of the backup scripts, and that the current user has permission to
access and run the scripts.
Instructions for installing the RethinkDB Python driver are available here:
http://www.rethinkdb.com/docs/install-drivers/python/
```
I checked the `\bin` directory (version 2.1.4) and it doesn't appear to have `rethinkdb-dump` or `rethinkdb-restore` python scripts. Are there any plans to include these scripts?

**Comment by mikemcquaid** [comment]
There are no current plans but you could always start them. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by larkost** [comment]
For clarity: the reason that the `dump` command (and others) is not included is because those are actually part of the RethinkDB Python driver. Since the driver is in `pip`, adding it would run afoul of the Acceptable Formulae guidelines (at least in my reading).

In my opinion the route to fix this (and a couple of other RethinkDB problems) is for (at least) the Python driver to be included with the RethinkDB server install. There is already [a proposal](https://github.com/rethinkdb/rethinkdb/issues/4507)  on the [RehtinkDB issue tracker] for that.

For full disclosure, I work for RethinkDB, and was the one to post that suggestion in our tracker.

**Comment by mikemcquaid** [comment]
Closing this as it's a feature request rather than a bug. We'd welcome a pull request.
