### ISSUE TITLE
Homebrew should check for installed packages before downloading

### ISSUE THREAD

**Issue by nirvana74v** [Homebrew/homebrew#47576]
Noticed that even if the system has the same package/library in formula installed, brew downloads the files as coded in formula file. Had same version cmake installed on my system but while installing mysql it was forcing itself to download cmake, later it couldn't find the patch for it and failed.

**Comment by mistydemeo** [comment]
This is on purpose; for most packages, unless they come with the OS, Homebrew prefers its own versions because we can't guarantee compatibility with other versions installed on your system. We make some exceptions; an example is Python, where we allow various installations of Python to satisfy Homebrew's requirements check. However, we do this on a case-by-case basis, in places where we are confident that compatibility problems are not likely to be an issue. Sorry for the inconvenience!

Regarding the patch, can you please provide more details on your issue?

**Comment by nirvana74v** [comment]
I appreciate the concerns but let me put the steps which defeats the first reason, please let me know if I understood it wrong.
Installed homebrew, as mentioned in docs
Executed: brew install mysql
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/cmake.rb
==> Downloading http://www.cmake.org/files/v3.2/cmake-3.2.3.tar.gz
==> Downloading from https://cmake.org/files/v3.2/cmake-3.2.3.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-645; OS X 10.11.2) https://cmake.org/files/v3.2/cmake-3.2.3.tar.gz -C 0 -o /Library/Caches/Homebrew/cmake-3.2.3.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) SSL certificate problem: Couldn't understand the server certificate format
Error: Failed to download resource "cmake"

Same error shows with
brew update

- I can't provide more details on patch as I had closed my terminal

**Comment by dunn** [comment]
Can you post the logs generated by `brew gist-logs cmake`? Thanks!

**Comment by mistydemeo** [comment]
Can you post your `brew --config` and `brew doctor`? Is there anything unusual about the openssl and curl on your system?

**Comment by DomT4** [comment]
Please let us know if we can help further here, Thanks!
