### ISSUE TITLE
brew reinstall: support the --interactive option

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew#47622]
Comparing [`reinstall.rb` L23-29](https://github.com/Homebrew/homebrew/blob/7d714ac258b986a3bde2045c2b2f478973c9c095/Library/Homebrew/cmd/reinstall.rb#L23-L29) to [`install.rb` L203-L213](https://github.com/Homebrew/homebrew/blob/7d714ac258b986a3bde2045c2b2f478973c9c095/Library/Homebrew/cmd/install.rb#L203-L213), it appears that `brew install` takes into account more command line options than `brew reinstall`: `ARGV.ignore_deps?`, `ARGV.only_deps?`, `ARGV.interactive?`, `ARGV.git?`, `ARGV.quieter?`, corresponding to `--ignore-dependencies`, `--only-dependencies`, `--interactive`, `--git`, and ??. I can understand the omission of `--ignore-dependencies` and `--only-dependencies`, but `--interactive` (and by extension, `--git`, which I personally never used but must be useful in certain cases) is sorely missed when developing a new formula with options, or revising an existing formula for major changes that break things. `brew uninstall foo` then `brew install --debug --interactive foo` just seem pointlessly redundant. Is there any reason `--interactive` is excluded from `reinstall`? If not, I hope to see it added. Thanks.

**Comment by mikemcquaid** [comment]
It's excluded because `reinstall` does more than just `uninstall; install`. Often `--interactive` will write e.g. just metadata files which would mean the backup is destroyed. Regardless, some of this may be worth adding. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
