### ISSUE TITLE
libgit2 broken on Yosemite

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#47668]
This is pretty much a self-notation to go look at this later.

`libgit2` is no longer building on Yosemite since at least a week or so ago. Before that it was passing okay, so perhaps we've broken something there.

```
In file included from /tmp/libgit220160104-60990-1gkl0m2/libgit2-0.23.4/src/stransport_stream.c:11:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/SecureTransport.h:1105:2: error: expected function body after function declarator
        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_2, __MAC_10_11, __IPHONE_5_0, __IPHONE_9_0);
        ^
/usr/include/Availability.h:165:53: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED'
                                                    __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep
                                                    ^
<scratch space>:50:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_2_DEP__MAC_10_11
^
```

**Comment by mikemcquaid** [comment]
Sounds like CMake SDK stuff?

**Comment by DomT4** [comment]
Aye, probably. It's newish as far as I know, I seem to remember `libgit2` passing through CI fine a couple weeks back, so I suspect either Misty's Xcode SDK tweak or my CMake tweak broke something.

**Comment by DomT4** [comment]
Currently poking around a Yosemite VM. Doesn't reproduce with pure CLT, but that was mostly expected.

**Comment by mikemcquaid** [comment]
@DomT4 Mind reverting your change locally and see if that fixes it? Bonus points if you have time to test Misty's.

**Comment by DomT4** [comment]
Working on it. Currently downloading Xcode on the local VM since CLT alone is fine, and both mine and Misty's changes touched primarily the Xcode situation.

**Comment by mistydemeo** [comment]
Is this occurring on a CLT+Xcode system? I'm wondering, judging from the listed error, if there's a conflict between headers included from the SDK and the headres in `/usr/include`.

**Comment by DomT4** [comment]
Aye; It reproduces on the CI which are all dual-dev-tool systems. I was thinking the same thing in terms of header clash, but wasn't sure whether it was my change or your's that would be more likely to cause it. Once Xcode is downloaded I'll poke about with some reverts locally.

**Comment by DomT4** [comment]
Should have an answer finally in about 15 minutes. My 100MB/s connection is currently providing 2.3MB/s :see_no_evil:

**Comment by DomT4** [comment]
Hurrah, reproduced the failure locally. It was my fault, apparently. Tested 10+ CMake using formulae without issue, but not this particular one, le sigh. Reverting, one sec.

**Comment by DomT4** [comment]
The original issue around CMake SDK selection will return, alas, but it was at least known. Need to find a better method to do that in a specific way, only passing the path if the system is Xcode-exclusive or something.

**Comment by mikemcquaid** [comment]
> only passing the path if the system is Xcode-exclusive or something.

Sounds sensible :+1:

**Comment by UniqMartin** [comment]
The problem here is that the wrong `Availability.h` header gets picked up, which (unsurprisingly) doesn't define the macros the error messages are complaining about. (The messages are somewhat misleading.) 

I believe the proper fix would be to make adjustments in `superenv`, which is basically undoing the effect of setting the CMake `-DCMAKE_OSX_SYSROOT=` flag by later killing the `-isysroot` flag that was inserted in response to the CMake flag. This happens when both Xcode and the CLT are installed. The problematic code is in [these lines of `ENV/super.rb`](https://github.com/Homebrew/homebrew/blob/7d714ac258b986a3bde2045c2b2f478973c9c095/Library/Homebrew/extend/ENV/super.rb#L105-L107).

I wrote a more detailed analysis in https://github.com/Homebrew/homebrew/pull/46776#issuecomment-168457948 but I didn't realize this is a more widespread issue.
