### ISSUE TITLE
baresip test is bad

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#47947]
The baresip test fails (in the sandbox?): http://bot.brew.sh/job/Homebrew%20Pull%20Requests/39804/version=mavericks/testReport/junit/brew-test-bot/mavericks/test_baresip/

```
==> /usr/local/Cellar/baresip/0.4.13/bin/baresip -t
baresip v0.4.13 Copyright (C) 2010 - 2015 Alfred E. Heggestad et al.
config: creating config template /Users/brew/.baresip/config
[31mconfig: writing /Users/brew/.baresip/config: No such file or directory
[;m[31mmain: configure failed: No such file or directory
[;m
Error: baresip: failed
Failed executing: /usr/local/Cellar/baresip/0.4.13/bin/baresip -t
/usr/local/Library/Homebrew/formula.rb:1472:in `system'
/usr/local/Library/Homebrew/formula.rb:1409:in `open'
/usr/local/Library/Homebrew/formula.rb:1409:in `system'
/usr/local/Library/Formula/baresip.rb:32:in `test'
/usr/local/Library/Homebrew/formula.rb:1318:in `run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1314:in `run_test'
/usr/local/Library/Homebrew/test.rb:28
/Users/brewadmin/Homebrew/Cellar/ruby187/1.8.7-p374_1/lib/ruby/1.8/timeout.rb:67:in `timeout'
/usr/local/Library/Homebrew/test.rb:27
```

Spotted in #47650.

**Comment by apjanke** [comment]
Yeah, it's sandbox. Disabling sandbox lets it pass.

```
$ brew test --no-sandbox baresip
Testing baresip
==> /usr/local/Cellar/baresip/0.4.13/bin/baresip -t
$
```

It only seems to do the autocreation if `baresip -t` or similar has never been run before. Once you've run `baresip -t` as the user once and the file exists, it doesn't try to recreate it, and no sandbox error happens.

Setting `$HOME` doesn't help because it's detecting the config directory location by using `fs_gethome()` from `libre` to get the home directory, which in turn calls `getpwnam()` to get the user's home directory from `/etc/passwd` entries or equivalent.

```
	const char *loginname;
	struct passwd *pw;

	if (!path || !sz)
		return EINVAL;

	loginname = sys_username();
	if (!loginname)
		return ENOENT;

	pw = getpwnam(loginname);
	if (!pw)
		return errno;

	str_ncpy(path, pw->pw_dir, sz);
```

The `-f` command line option lets you specify a configuration dir, though. Added it in #47952.

**Comment by tdsmith** [comment]
Awesome, thanks!
