### ISSUE TITLE
Redirects from HTTPS to HTTP should be disabled by default

### ISSUE THREAD

**Issue by ecneladis** [Homebrew/homebrew#47979]
Currently this functionality is disabled by default and requires setting env variable HOMEBREW_NO_INSECURE_REDIRECT.

https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/download_strategy.rb#L274

**Comment by tdsmith** [comment]
Unfortunately, that would break downloads from many popular sites. You can search the issue tracker for the previous discussions. I think it's too soon to revisit that decision since the underlying facts have not changed.

Using HTTP transport without TLS does expose some information about which packages a user is installing but does not increase the risk of obtaining untrusted code since downloads are still protected by secure checksums.

**Comment by DomT4** [comment]
They won't get enabled by default for a long time (if ever), in large part because it would instantly break every SF, Qt and most GNOME downloads from us, but the functionality is slowly expanding on that check and people are free to choose to enable it at their own understanding of the risks.

> I think it's too soon to revisit that decision since the underlying facts have not changed.

I agree with Tim here.
