### ISSUE TITLE
Two versions of some pkgs installed, possibly due to being keg-only

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew#48139]
Every once in a while when running "brew cleanup" I get one or more warnings about keg-only packages, and in those cases it turns out two different versions of those packages are installed for some reason. 

What might be going on is that packages that are keg-only are not properly handled when running "brew upgrade" and instead of an upgrade, the newer versions of the packages are installed on top of the existing older versions.

For example, to clean things up properly I had to do the following sequence of steps: uninstall all versions of the packages with issues (ran 'brew uninstall' twice on them), then re-installed them. Details below:

    $ brew cleanup

````
Warning: Skipping (old) keg-only: /usr/local/Cellar/gettext/0.19.6
Warning: Skipping (old) keg-only: /usr/local/Cellar/icu4c/55.1
Warning: Skipping (old) keg-only: /usr/local/Cellar/openssl/1.0.2d_1
Warning: Skipping (old) keg-only: /usr/local/Cellar/sqlite/3.8.11.1
````

    $ brew uninstall gettext icu4c openssl sqlite

````
Uninstalling /usr/local/Cellar/gettext/0.19.7... (1,929 files, 16.6M)
gettext 0.19.6 is still installed.
Remove them all with `brew uninstall --force gettext`.
Uninstalling /usr/local/Cellar/icu4c/56.1... (244 files, 63.7M)
icu4c 55.1 is still installed.
Remove them all with `brew uninstall --force icu4c`.
Uninstalling /usr/local/Cellar/openssl/1.0.2e_1... (465 files, 11.9M)
openssl 1.0.2d_1 is still installed.
Remove them all with `brew uninstall --force openssl`.
Uninstalling /usr/local/Cellar/sqlite/3.10.0... (9 files, 2.8M)
sqlite 3.8.11.1 is still installed.
Remove them all with `brew uninstall --force sqlite`.
````

    $ brew uninstall gettext icu4c openssl sqlite

````
Uninstalling /usr/local/Cellar/gettext/0.19.6... (1,921 files, 16.4M)
Uninstalling /usr/local/Cellar/icu4c/55.1... (244 files, 65M)
Uninstalling /usr/local/Cellar/openssl/1.0.2d_1... (464 files, 12M)
Uninstalling /usr/local/Cellar/sqlite/3.8.11.1... (9 files, 2.8M)
````

    $ brew install gettext icu4c openssl sqlite

**Comment by edrozenberg** [comment]
I do some configuration on the Mac via Ansible, including running Ansible tasks that install and upgrade Homebrew packages. Don't think it's relevant to the issue here but mentioning it just in case.

**Comment by UniqMartin** [comment]
If you are sure that you always only want to keep the latest version of an installed formula, you can run `brew cleanup --force` (see `man brew` for the documentation). This will additionally remove outdated keg-only formulae instead of warning about them. No need for uninstalling and reinstalling. If you're even more confident that you won't need the older versions, you can also run `brew upgrade --cleanup` which will automatically clean up after upgrading. Does that solve your issue?

**Comment by edrozenberg** [comment]
Thanks @UniqMartin, those commands would certainly clean things up more easily. Still interesting why I wound up with two versions of those packages - since I never purposefully installed two versions of any packages, I've always just done upgrade --all.

**Comment by UniqMartin** [comment]
That's because `brew cleanup` (without the `--force`) would keep old keg-only formulae around. So with every `brew upgrade && brew cleanup` cycle some outdated keg-only formulae would remain untouched. One reason for doing this was to not break paths to formulae used by users outside of Homebrew, e.g., when using a library for a personal project.

**Comment by edrozenberg** [comment]
@UniqMartin thanks for the explanation, it's good to understand the rationale - some users install specific versions of pkgs as keg-only on purpose and don't want those blown away by upgrades. For those users who are not doing it on purpose, of course it surprises us that keg-only pkgs are treated differently by brew upgrade. Perhaps a future homebrew could consider some kind of "sticky" option - if you specify sticky to a pkg install, it tells homebrew not to delete that version when doing regular upgrades.

**Comment by UniqMartin** [comment]
Thank you for the suggestion, @edrozenberg. I'll add it to my TO DO list and will discuss it with the other maintainers. Glad I was able to help in the mean time.

**Comment by mistydemeo** [comment]
> Perhaps a future homebrew could consider some kind of "sticky" option - if you specify sticky to a pkg install, it tells homebrew not to delete that version when doing regular upgrades.

That feature exists now, as the `brew pin` feature!

The other reason that we don't clean up old kegs is historical. We didn't always have the `opt` paths; that is, paths which always point to the current version of a package. For keg-only libraries, that meant that any packages which linked to them had install_names pointing at a specific version of the package. (This didn't affect non keg-only libraries, because their install_names pointed at the public `/usr/local` location.) If `cleanup` removed older versions of the libraries, then any software linked against them would break and need to be rebuilt.

We left the `cleanup` behaviour in place for a long time after making that change, since many of those packages are updated rarely and it's quite possible that users will still have software linked against them. However, it's now been about four years since we introduced `opt` paths, so we may not need to worry about this anymore.
