### ISSUE TITLE
Why do libraries require full recompilation?

### ISSUE THREAD

**Issue by forthrin** [Homebrew/homebrew#48152]
In Homebrew, more and more tools come precompiled, so they take just seconds to install.

However, for example, if I want `FDK AAC` with my `ffmpeg` (and I do), I'm pushed back to good, old CPU-devastating compilation, which turns my MacBook Air into a frying pan / airplane cabin for five minutes.

Why does inclusion of a library require a full re-compile, rather than being available as a separate unit which connects elegantly with the core application simply by copying a library file into a library folder?

Is the programming done by putting #IF LIB_FDK_AAC statements everywhere?

Please note that this is a generic question, and I'm just using ffmpeg as an example.

**Comment by gaming-hacker** [comment]
stop whining.  i recompile ffmpeg from source with 50+ libraries 3 to 4x a week to do regression and codec testing and it only takes 20 min per build on my macbook unless someone has commited some bad code and broken the build.

it's not a plugin, it's a library.  learn what an API is and does as well as dynamic library vs static.  when you compile a library with the program, it is available in memory. a plugin is not.

you don't HAVE to recompile, write your own code in c/c++ and link the ffmpeg libs to the new libs.

**Comment by DomT4** [comment]
@gaming-hacker I'll leave your comment there, but from this point for an undecided amount of time you aren't welcome around Homebrew. You were warned about your tone and conduct towards others last week and came back from a 24 hour ban and once again you're violating the [Code of Conduct](https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md).

You have zero right to belittle or demean users who just want a question answered, whatever their level of technical experience. We're an inclusive community, and your tone is the kind of thing that murders open-source communities and makes vulnerable/inexperienced/new people run in the opposite direction and never want to return. That attitude is not welcome here, and you've actively dumped on the second chance we gave you to tone it down.

**Comment by DomT4** [comment]
@forthrin My apologies you had to deal with that. We'll provide an answer to your actual questions as soon as possible; Thank you for creating the Issue.

**Comment by UniqMartin** [comment]
@forthrin Whether this can be done in theory largely depends on the architecture of the program or library you want to use. For almost all software, support for certain features/libraries is decided before the compilation and then baked in into the software, so that it cannot be changed afterwards without recompiling it. The `ffmpeg` formula you mention is an example of such a case.

Because of this situation it would be very difficult if not impossible for us to provide a solution to your problem. Thus, we provide formulae with a certain set of default features that work for most of our users. Unfortunately, we cannot provide multiple variants of precompiled formulae, as that would quickly lead to an enormous number of possible combinations (and thus formulae we would have to compile and offer for users to download). Again, `ffmpeg` with all its options is a good example. We also cannot simply enable all options in a formula, as they are sometimes mutually exclusive, so we also cannot provide something like a “feature-complete build” in addition to the default build we offer.

Does that answer your question or did I miss to address some aspect?

**Comment by mikemcquaid** [comment]
Another thing is that we only provide binary packages for the default options. In `ffmpeg`'s specific case the `FDK AAC` support is also not GPL compatible so we can't legally redistribute binary packages.

**Comment by forthrin** [comment]
Thanks for getting back to me. It's obvious you can't pre-compile 2^EXTENSIONS versions of a each tool. But maybe you could go into a little more detail explaining just *why* the tools haven't been made module-based to begin with. Did development start so long ago that no-one simply thought of it at the time? Or are there other great advantages with programming extensions in an entwined/non-detached way?

PS! The problem is only relevant for huge utilities with long compilation time (`ffmpeg`, ImageMagick, et al.) If a tool compiles in a few seconds, it doesn't really matter to the end user how the underlying architecture and linking happens.

**Comment by bfontaine** [comment]
> But maybe you could go into a little more detail explaining just *why* the tools haven't been made module-based to begin with. Did development start so long ago that no-one simply thought of it at the time? Or are there other great advantages with programming extensions in an entwined/non-detached way?

This is a question for the tools developpers, not us :wink: 
With statically typed programming languages it’s also harder to make module-based architectures. Having everything at compile-time means you can detect (most) bugs earlier rather than have to actually run the program to detect issues. It also enables more optimizations.

**Comment by UniqMartin** [comment]
> But maybe you could go into a little more detail explaining just why the tools haven't been made module-based to begin with. Did development start so long ago that no-one simply thought of it at the time? Or are there other great advantages with programming extensions in an entwined/non-detached way?

Ultimately, that has to be answered individually for each project (and that's beyond our scope as a package manager). I'm sure I'm missing a lot, but some of the reasons that come to mind are:

- Developer time is scarce and supporting a plug-in mechanism is more work than compiling everything in or conditional compilation, especially in Open Source projects where the source code is the usual distribution format.
- Some projects prioritize portability over modularity, and providing a reliable plug-in mechanism across a wide range of operating systems is still not a trivial thing to do.
- There's usually a minor loss in performance.
- Because of some overhead and some necessary code duplication in every plugin, the overall size of the installed package rises (probably less of a concern nowadays).

> PS! The problem is only relevant for huge utilities with long compilation time (`ffmpeg`, ImageMagick, et al.) If a tool compiles in a few seconds, […]

Note that we wouldn't usually consider these to be huge utilities. :wink: We have a few formulae that require somewhere around 1-3 hours to compile (depends on the used machine, of course).

**Comment by forthrin** [comment]
Good enough answer for me. And I hope I won't ever be in need of tools that require 3 hours compiling, especially since brews are updated often, and re-compilation will be required not only once but for each version bump. Only workaround I can think of is pinning the large ones or crontab-ing the update/upgrade to happen at night as long as the laptop isn't in the bedroom :)

Keep up the great work with a great tool! I particularly appreciate the simple and intuitive CLI syntax (compared to apt-get / dpkg...)

**Comment by apjanke** [comment]
Martin covered this well. To expand on his answer just a little bit:

This is mostly relevant to C-based projects. In some newer programming languages, like Java or anything "scriptier", doing conditional usage of libraries detected at run time is easier and more common, because the languages provide facilities to support this portably and with less developer effort.

When Martin says it's "not a trivial thing to do", he's being characteristically understated. To get an idea of what it entails in C, you can read through the `dlopen` man page and related entries, keeping in mind that there will be differences between platforms and distributions.

Also, there are other things, including non-library-related configuration choices, compile-time configuration differences in linked libraries themselves, or the desire to do optimized builds for your particular hardware, that can require full compilation anyway. So the number of cases where run-time library detection and loading will save people a compile may not be as large as it seems, and it makes less sense to spend the time and effort to plugin-ize it.

"Pluginization" can also make it more difficult for you as a user/sysadmin to manage and debug your system. With normally-linked files, you (or a tool like `brew`) can do things like run `otool -L` on them to see their library dependencies, and identify missing library dependencies. With a plugin-architecture program, you probably can't, and you have to rely, at run time, on whatever diagnostics the program has built in to itself to resolve link issues.

From what I've seen, plugin architectures are used less to avoid the need for compilation, and more to allow libraries or features to be developed in a fully independent manner (either by different groups, or at different times), where the main program has no knowledge of them at the time it was written.
