### ISSUE TITLE
upgrading from gnutls 3.3 to 3.4 breaks applications linked against it (in particular: emacs)

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew#48168]
I pulled down the gnutls upgrade today, ran Emacs, and got:

```
dyld: Library not loaded: /Homebrew/opt/gnutls/lib/libgnutls.28.dylib
  Referenced from: /Homebrew/Cellar/emacs/25.0-dev/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by DomT4** [comment]
This is expected. We force a rebuild of everything with a mandatory or recommended dependencies on the newly-incompatible formula, but we don't do the same for `:optional` dependencies because it'd enforce a lot of people rebuilding packages needlessly.

You can `brew reinstall emacs` to solve the issue there.

**Comment by ilovezfs** [comment]
It's worth noting that even if gnutls 3.3 had already been "fixed" to have its shared library identification name be /Homebrew/opt/gnutls/lib/libgnutls.dylib instead of the specific library version /Homebrew/opt/gnutls/lib/libgnutls.28.dylib, and Emacs had been built with that shared library identification name change already made, and then gnutls upgraded from 3.3 to 3.4, it still would not have loaded, but for a different reason:
```
bash-3.2$ ./Emacs 
dyld: Library not loaded: /usr/local/opt/gnutls/lib/libgnutls.dylib
  Referenced from: /usr/local/Cellar/emacs/25.0-dev/Emacs.app/Contents/MacOS/./Emacs
  Reason: Incompatible library version: Emacs requires version 70.0.0 or later, but libgnutls.dylib provides version 37.0.0
Trace/BPT trap: 5
```
Rebuilding emacs does indeed fix the problem.

**Comment by ilovezfs** [comment]
@DomT4 Since the install receipts know what options were used, why would it cause needless rebuilding if it only rebuilt in cases where people actually had used the option?

**Comment by DomT4** [comment]
@ilovezfs The `revision` system isn't subjective based on the receipt. The revision system enforces a rebuild unconditionally on stable or devel, regardless of options used. It's designed almost entirely to handle API/ABI incompatibility and security issues that need to be fixed right now.

At this point there are no plans to change that system to become subjective, but it's not a "never ever" thing.

**Comment by ilovezfs** [comment]
@DomT4 If nothing else, it might be nice if it warned in the caveats that some already installed formulas may have just been made incompatible, and even if it cannot say exactly which ones, it could proactively suggest the users run <code>brew uses --installed --recursive gnutls</code> to identify what may need imminent rebuild, and recommend <code>brew switch</code> as a remedy if immediate triage is needed. 

@glyph mentioned on IRC that he upgraded gnutls just before getting on an airplane, only to have the lovely surprise that his Emacs.app was borked. If he'd known to do <code>brew switch</code>, that probably would saved the day, but do know that this missing feature causes actual harm in some cases.

**Comment by DomT4** [comment]
@ilovezfs We're happy to review a PR if you have ideas on this front.

**Comment by ilovezfs** [comment]
@DomT4 BTW, is it expected behavior that the shared library identification name for dylib libraries in /usr/local/opt/*/lib/* include the version number?

**Comment by DomT4** [comment]
@ilovezfs It's not something we attempt to control as far as I'm aware.

We rewrite linkage so it points at `HOMEBREW_PREFIX/opt/formula` rather than `HOMEBREW_PREFIX/Cellar/formula/version` [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/keg_relocate.rb#L153-L159) but I don't think we attempt to unversion the dylib it built against.
