### ISSUE TITLE
bottle files missing problem

### ISSUE THREAD

**Issue by gaoyifan** [Homebrew/homebrew#48236]
The following files is missing: (return 404)
http://homebrew.bintray.com/bottles/autossh-1.4e.el_capitan.bottle.tar.gz
http://homebrew.bintray.com/bottles/cctools-806.el_capitan.bottle.tar.gz
http://homebrew.bintray.com/bottles/cctools-806.mavericks.bottle.tar.gz
http://homebrew.bintray.com/bottles/cctools-806.mountain_lion.bottle.tar.gz
http://homebrew.bintray.com/bottles/cctools-806.yosemite.bottle.tar.gz
http://homebrew.bintray.com/bottles/fleetctl-0.11.5.el_capitan.bottle.tar.gz
http://homebrew.bintray.com/bottles/httrack-3.48.21.el_capitan.bottle.tar.gz
http://homebrew.bintray.com/bottles/imap-uw-2007f.el_capitan.bottle.tar.gz
http://homebrew.bintray.com/bottles/png2ico-2002-12_1.yosemite.bottle.tar.gz
http://homebrew.bintray.com/bottles/schroedinger-1.0.11.el_capitan.bottle.tar.gz

Is there any ways to let bots rebuild these formula?

**Comment by DomT4** [comment]
> http://homebrew.bintray.com/bottles/autossh-1.4e.el_capitan.bottle.tar.gz

Confirmed.

> http://homebrew.bintray.com/bottles/cctools-806.el_capitan.bottle.tar.gz
http://homebrew.bintray.com/bottles/cctools-806.mavericks.bottle.tar.gz
http://homebrew.bintray.com/bottles/cctools-806.mountain_lion.bottle.tar.gz
http://homebrew.bintray.com/bottles/cctools-806.yosemite.bottle.tar.gz

Your Homebrew might be outdated or may be a misunderstanding here. The version we supply now, which has bottles, is `855`. We only supply `806` if your OS X version is Leopard or below because 806 is the last broadly compatible version there. Since we don't bottle for Leopard or below in Homebrew no bottles exist for that version.

> http://homebrew.bintray.com/bottles/fleetctl-0.11.5.el_capitan.bottle.tar.gz

Confirmed.

> http://homebrew.bintray.com/bottles/httrack-3.48.21.el_capitan.bottle.tar.gz

Confirmed.

> http://homebrew.bintray.com/bottles/imap-uw-2007f.el_capitan.bottle.tar.gz

Confirmed.

> http://homebrew.bintray.com/bottles/png2ico-2002-12_1.yosemite.bottle.tar.gz

Confirmed.

> http://homebrew.bintray.com/bottles/schroedinger-1.0.11.el_capitan.bottle.tar.gz

Confirmed.

**Comment by gaoyifan** [comment]
> Your Homebrew might be outdated or may be a misunderstanding here. The version we supply now, which has bottles, is 855. We only supply 806 if your OS X version is Leopard or below because 806 is the last broadly compatible version there. Since we don't bottle for Leopard or below in Homebrew no bottles exist for that version.

Maybe the following style is better?

```
   if MacOS.version >= :snow_leopard
     url "https://opensource.apple.com/tarballs/cctools/cctools-855.tar.gz"
     sha256 "751748ddf32c8ea84c175f32792721fa44424dad6acbf163f84f41e9617dbc58"
     bottle do
       cellar :any_skip_relocation
       sha256 "398333f85c3944de889172ca9d3aa5ffd709403ca2225316f130be817f09873a" => :el_capitan
       sha256 "a76a710f5f164feace5ad107eb40bf5e6a25e916f7334e69ee197a8e3d02b90c" => :yosemite
       sha256 "3b0c895c6f0832ef9509720ebc15478e188ea6396ba41729273eb64d7b2f7ec2" => :mavericks
       sha256 "f9f74d98119d2efd5530f8d98eb7838a77be35576880ecec73fe9d535aa2afb0" => :mountain_lion
     end
   else
     # 806 (from Xcode 4.1) is the latest version that supports Tiger or PowerPC
     url "https://opensource.apple.com/tarballs/cctools/cctools-806.tar.gz"
     sha256 "6116c06920112c634f6df2fa8b2f171ee3b90ff2176137da5856336695a6a676"
   end

```

**Comment by DomT4** [comment]
We don't really nest bottle blocks because it can cause weird edge-case issues that aren't much fun to invest time in debugging. `cctools` is fairly unique in the core; there aren't many formulae which have an `if/else` URL/checksum block _and_ are bottled.

I've rebottled everything else aside `imap-uw`, which is pretty dead at this point.
