### ISSUE TITLE
HALP! Brew Update Fails (git pull issue)

### ISSUE THREAD

**Issue by ecbrodie** [Homebrew/homebrew#48308]
I do not develop locally for Homebrew, I just use it as a package manager. I am trying to run `brew update` just like I would normally run it on any other day. However, I am suddenly getting this message printed out:

> error: unable to unlink old 'Library/Homebrew/test/tarballs/testball-0.1.tbz' (Operation not permitted)
> Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master

I ran `brew doctor`, but there was no debugging information printed. So, I went into /usr/local and tried to bring its git repository back to a clean state via `git rest --hard`. After this, I still get the same error running `brew update`. So I try running `brew doctor` and I get this output now:

> Warning: You have uncommitted modifications to Homebrew
> If this is a surprise to you, then you should stash these modifications.
> Stashing returns Homebrew to a pristine state but can be undone
> should you later need to do so for some reason.
>    cd /usr/local/Library && git stash && git clean -d -f

Alright, I execute the commands listed above, but I still get the same error the next time I run `brew update`. Something is really wrong here with Homebrew. I feel like my only troubleshooting step remaining is just reinstalling Homebrew on my machine, but that seems drastic to me. Anyone have any ideas how to get around this?

**Comment by UniqMartin** [comment]
It could be that the recent update to OS X 10.11.3 caused the permissions of `/usr/local` to be reset (just guessing). Can you please try `sudo chown -R $(whoami) /usr/local` and see if that fixes your issue?

**Comment by ecbrodie** [comment]
Yea, I forgot to mention...I had run that `sudo chown` command before when looking up troubleshooting steps online. Even though I specify `sudo` in my command, I still get a bunch of output lines with the _Operation not permitted_ message being printed. Running `brew update` right after results in the same error.

What if I deleted the entire _Library_ directory and then `git pull` or `git checkout master` to bring it all back? Would I love my `brew leaves` and thus have to reinstall everything again?

**Comment by UniqMartin** [comment]
If you are sure you haven't made modifications to Homebrew itself, you can try `cd /usr/local && git reset --hard origin/master` to return it to a good state (please don't use `sudo` with that, as this will create more permission issues). This will leave the formulae you have installed via Homebrew intact.

If that doesn't solve it already, please post the complete output of `brew config` and `brew doctor` as a Gist (and link to it here), so that we have more information when trying to help you.

**Comment by ecbrodie** [comment]
**brew config output**

> HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 9db8f635be7c537e8dc9ed77e7600e0307071694
Last commit: 2 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
OS X: 10.10.5-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.0.0-p247/bin/ruby
Java: 1.8.0_51, 1.8.0_31, 1.7.0_55, 1.7.0_05, 1.6.0_65-b14-466.1

**brew doctor output**

> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

> Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /usr/local/Library && git stash && git clean -d -f

**Comment by UniqMartin** [comment]
Sorry, if I'm repeating myself or you have already tried some of these, but please try the following steps in the suggested order. Please also post the output, so that I see any error or status messages that could try to help me debug this with you:

1. `cd /usr/local && git status --branch --untracked-files=all` – This is just here so that I can see the current state of your Homebrew repository.
2. `sudo chown -R $(whoami) /usr/local` – This should fix any still remaining permission issues.
3. `cd /usr/local && git stash --include-untracked` – This should stash away any local modifications there are and that showed up in the first step.
4. `cd /usr/local && git reset --hard` – This should bring the currently checked out branch into a clean state.
5. `cd /usr/local && git checkout --force -B master origin/master` – This should re-create and check out the `master` branch.

It could be that some of those commands are not needed, but I'm trying to cover all possibilities here. Afterwards, hopefully `brew update` and every other `brew` command should work again.

**Comment by DomT4** [comment]
Please let us know if we can assist further here, Thanks!

**Comment by ecbrodie** [comment]
Sorry for not responding, this slipped through the cracks and other personal stuff distracting me. This is still indeed an issue, so I will need to reopen the issue. I will be following @UniqMartin's steps and posting all output.

**Comment by DomT4** [comment]
No worries. Generally if people don't respond to an Issue they've created after a week or so they almost never do, so we shut them. Let us know how you get on with Martin's steps.

**Comment by ecbrodie** [comment]
Here is what happened when I ran through each of @UniqMartin's steps:
1. `cd /usr/local && git status --branch --untracked-files=all`. See output in this Gist: https://gist.github.com/ecbrodie/0d3eaaa622512c141150
2. `sudo chown -R $(whoami) /usr/local`. Although the command succeeded, there were many files where I got an "Operation not permitted" error. Most file, but not all, were related to the *rbenv* library.
3. `cd /usr/local && git stash --include-untracked`. Successful. Result is that I am now at the commit with message "HEAD is now at 9db8f63 exceptions: hotfix".
4. `cd /usr/local && git reset --hard`. Okay.
5. `cd /usr/local && git checkout --force -B master origin/master`. I get the following error:
> error: unable to unlink old 'Library/Homebrew/test/tarballs/testball-0.1.tbz' (Operation not permitted)

My spidey senses tell me to just delete this file, but I don't want this to somehow brick my Homebrew installation. Let me know what you think. Thank you.

**Comment by UniqMartin** [comment]
> (2) `sudo chown -R $(whoami) /usr/local`. Although the command succeeded, there were many files where I got an "Operation not permitted" error. Most file, but not all, were related to the rbenv library.

This doesn't sound right. Can you please retry and provide the output so that I can see exactly for which files this fails?

> My spidey senses tell me to just delete this file, but I don't want this to somehow brick my Homebrew installation.

To be honest, I don't fully understand what's going on with that file. Please try removing it. I can assure you that it is not essential to the proper operation of Homebrew.

**Comment by ecbrodie** [comment]
I created this Gist that contains the output of the `chown` command. Python is also a library with a lot of Operation Not Permitted lines. https://gist.github.com/ecbrodie/a872315ec740fe6c3a93

BUT.... I decided to remove that one file that had an unlinking problem. Then `brew update` finally started working again. Same with `brew upgrade` and `brew doctor`. So maybe that one file was the problem? Le shrug. I never added in that file myself, it must have come from a Homebrew command somehow. That's worth looking into, IMO.

**Comment by UniqMartin** [comment]
> I created this Gist that contains the output of the `chown` command.

That doesn't look right. Are you sure you issued the `chown` command with the `sudo` in front of it? It wouldn't surprise me that your regular user doesn't have permissions to change the owner, but the `root` user normally should be able to do that (and that's why I suggested to use `sudo chown`)…

> BUT.... I decided to remove that one file that had an unlinking problem. Then `brew update` finally started working again.

That's good to hear. I guess your problem is solved and this issue can be closed?

> I never added in that file myself, it must have come from a Homebrew command somehow. That's worth looking into, IMO.

That file is part of Homebrew, but it apparently had the wrong permissions on your system and thus could not be updated by `brew update`. Not that you removed it manually, `brew update` was able to recreate it again … this time hopefully with the right permissions.

**Comment by ecbrodie** [comment]
Yes Martin, I used sudo.

**Comment by UniqMartin** [comment]
> Yes Martin, I used sudo.

Thanks for clarifying. I have to admit that I'm a bit confused why even `root` doesn't have sufficient permissions to change ownership of these files. In any case, I didn't want to insult you. It's just that experience of Homebrew users varies quite widely and that's an easy mistake to make.

**Comment by ecbrodie** [comment]
Anyhow, since the issue is fixed on my end, I'll leave it up to you whether you want to close the ticket. Thanks for the help.
