### ISSUE TITLE
formulas for mingw 32/64bit 

### ISSUE THREAD

**Issue by drewwells** [Homebrew/homebrew#48370]
It's possible to cross compile from OS X to Windows with mingw. I've had success installing mingw and building binaries for windows with this script: https://gist.github.com/drewwells/ee5d42dc29b70b7b61af

It already leverages work done from homebrew `isl`, `cloog`, etc. The last step is to add a formula to support it. Before proceeding, I've opened this ticket to track discussion. Are there any reasons homebrew doesn't already offer mingw? There wasn't any mention of it from searching the repo. Future PR with ming formula coming

**Comment by drewwells** [comment]
References:

https://developer.mozilla.org/en-US/docs/Cross_Compile_Mozilla_for_Mingw32#Build
http://pete.akeo.ie/2010/07/compiling-mingw-w64-with-multilib-on.html

**Comment by mistydemeo** [comment]
There's no specific reason, beyond the fact they haven't been submitted in the past. We tend to include formulae when they've been submitted by users, rather than proactively. Unless the buildsystem is extremely arcane and brittle (read: the support load would be disproportionately high), I'd be very happy to have a formula for mingw!

**Comment by drewwells** [comment]
I'm probably out of my realm on this. It looks like gcc needs to be custom built, unless there's a good way to install the existing gcc with a new or even multiple host targets. I'll PR so others can see progress on this.

**Comment by DomT4** [comment]
Closing in favour of the open #48385 PR, Thanks!
