### ISSUE TITLE
libjson-rpc-cpp Yosemite bottle looking for wrong libmicrohttpd

### ISSUE THREAD

**Issue by area** [Homebrew/homebrew#48450]
We are seeing exactly the same symptoms that we saw on https://github.com/Homebrew/homebrew/issues/47806 with Yosemite (see https://github.com/ethereum/webthree-umbrella/issues/133). I have confirmed that the Yosemite bottle (`https://homebrew.bintray.com/bottles/libjson-rpc-cpp-0.5.0.yosemite.bottle.1.tar.gz
`) is linking to the wrong library. Should the bottle refresh to fix the last issue have fixed this, or does it need to be done explicitly for every version of OSX? Or are old versions of OSX not refreshed going forward?

**Comment by DomT4** [comment]
Bumped the version in https://github.com/Homebrew/homebrew/pull/48603, which should resolve this for now.

It _looks_ like this isn't being picked up on because the binary (which is what is being tested in `test do`) isn't linked directly to `libmicrohttpd` and consequently doesn't complain that it's missing or mismatched when we run `libmicrohttpd` updates through CI.
