### ISSUE TITLE
A flag to prevent certain formula from being removed while running `brew cleanup`?

### ISSUE THREAD

**Issue by kenips** [Homebrew/homebrew#48486]
I'm wondering if it makes sense to add a flag in formula to prevent cleanup automatically for certain libraries?

With Postgres major upgrades, you need to perform some manual steps using old bins and new bins together. I'm so used to cleaning up after upgrading so this caught me a few times. It's not end of the world, just had to reset brew manually to old formula and install it again, but it'd be great if we can specify a flag so that cleanup for formula like these only happens with an extra flag?

The upside is really giving the formula editors another layer to warn users about certain formula require retaining older versions in Cellar. Thoughts?

**Comment by mikemcquaid** [comment]
`cleanup` isn't done automatically so I'm not sure I understand the question?

**Comment by bfontaine** [comment]
I think what @kenips is asking for is a formula DSL to prevent `brew cleanup` from happening without an extra flag.

**Comment by kenips** [comment]
@bfontaine precisely. Thanks for pulling out the right terms.

**Comment by mikemcquaid** [comment]
@kenips I think we'll pass on this given `brew cleanup` isn't automatic.

**Comment by kenips** [comment]
@mikemcquaid yes, it's certainly a very "nice to have" given `brew cleanup` isn't automatic. But I don't think we should only think in terms of whether `brew cleanup` is run automatically or not. Without this, I need to rely on a manual check to see what formulas are safe to remove before running `brew cleanup`. This is quite different from what I was expecting `brew cleanup` to be - I was expecting it to be always safe to run, like `brew update`, as long as you have time.

What I'm saying instead, by looking into the formula hooks, that certain formula should return false on `eligible_kegs_for_cleanup` without an additional flag as they shouldn't be automatically removed unless the user has performed additional requirements.

I'm just not certain on how widely this is applicable - if postgres is the only one, then I guess it's not so useful.

Anyway, something to keep in mind if more formula have this behavior? (feel free to close)

**Comment by bfontaine** [comment]
> they shouldn't be automatically removed unless the user has performed additional requirements.

What are these requirements for PostgreSQL? Maybe we could add instructions in the caveats for them?

**Comment by kenips** [comment]
@bfontaine Something like: https://kkob.us/2016/01/09/homebrew-and-postgresql-9-5/. Essentially you'll need to run:

```
pg_upgrade \
  -d /usr/local/var/postgres \
  -D /usr/local/var/postgres9.5 \
  -b /usr/local/Cellar/postgresql/9.4.5_2/bin/ \
  -B /usr/local/Cellar/postgresql/9.5.0/bin/ \
  -v
```

before the cleanup step. For me I forgot about this a few times on a few machines and I had to go back and install old postgres so I can run this.

Caveats will be printed during upgrades too, right?

**Comment by apjanke** [comment]
I can see the use of that. `cleanup` isn't automatic, but because of that, I usually tack it on to my regular `brew update; brew upgrade; brew cleanup` maintenance. Bet lots of other users do too. And this "oops" would be kind of a pain to fix, since we don't support installing old versions without some `git` fiddling. I dunno.

The logic to detect this correctly (e.g. for postgres, it's only needed across major version upgrades, not minor versions, or (probably but maybe not always) revisions to the formula) would probably be complicated and iffy. Homebrew really doesn't track formula relationships across versions. Might be easier to do this as part of the `upgrade` step: if postgres' `install()` detects an older version with a live database, it could "lock" that specific older version some how. Fiddly and probably breakage-prone and difficult to test.

This may well be only useful for postgres and maybe a handful of other formulae. Most programs I've seen with data migration just include back-compatibility support in their newer versions, and don't require side-by-side installation with the old version to do it. I'd bet caveats are probably more appropriate than trying to handle this automatically.
