### ISSUE TITLE
ArangoDB formula slowing down on El Capitan

### ISSUE THREAD

**Issue by pipeult** [Homebrew/homebrew#48559]
Since I upgrade to El Capitan (10.11.3), ArangoDB seems to work slower.
Just an example, the access to the ArangoDB REST API Interface page take 1'30s.
This independently of the versions, 2.7.3 or 2.8  
To be sure to have no interference with other software, I erased the hard disk, reinstalled El Capitan, made an update of the system, then installed Xcode, Xcode CLT, brew, openssl and finally ArangoDB ( 2.8  now) in this order.  
The test is made without personal data and Foxx app, and with the basic config.  
By comparison, on a PC Ubuntu less fast than the MAC, the page sets 3s to display.

**Comment by UniqMartin** [comment]
This sounds like a problem that is unrelated to Homebrew. I'd suggest to get in contact with upstream to see if this is a known issue and to find out how to debug this issue. Thanks!

Feel free to get in contact again if it turns out that the slowdown is caused by Homebrew itself, i.e. by the way we build ArangoDB on OS X.
