### ISSUE TITLE
brew install gcc --without-multilib stucks during 'make bootstrap'

### ISSUE THREAD

**Issue by rob2go** [Homebrew/homebrew#48612]
Hi guys,
I've tried everything. Unistalling gcc end instal it directly without multilib , or reinstalling it w/o multilib after installing it 'normally'. I've alsso reinstalled every dependencies from gcc
And i'm alwais getting the same problem, it stucks.

brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-5.3.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> ../configure --build=x86_64-apple-darwin15.2.0 --prefix=/usr/local/Cellar/gcc/5.3.0 --libdir=/usr/local/Ce
==> make bootstrap

And it stucks here for hours

Any idea of a solution?
Thank you

**Comment by tdsmith** [comment]
Literally hours? It could definitely take an hour, depending on your hardware. If you pass `-v` to `brew reinstall` you should see more about what it's trying to do, at least.

If you'd like to show us logs of a stuck build, run `brew gist-logs gcc` after you cancel a build which you're very sure is stuck.

**Comment by rob2go** [comment]
I'll try the verbose. No I'm not sure it is really stucked, but it was what I observed.
Yes, this morning it run for 2 hours. This afternoon for 3 hours.
I've just stopped it and rerun with `-v`

I'll let you know. I'm using a MBA 4GB memory, 1.3 GHz

**Comment by rob2go** [comment]
After waiting for 2,5 half I had to let it continues to run at work.
At my MBPro at home, i've tried it too, and at the end I got

==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
==> Summary
🍺  /usr/local/Cellar/gcc/5.3.0: 1,292 files, 224.9M, built in 45 minutes 49 seconds

It was faster (8GB memoy, 2,6 GHZ) but it has not installed without multlib :-(
I'm 100% sure I've put it because i had a doubt too (LOL), then I take a look at the history.

I run `brew gist-logs gcc` and got this [https://gist.github.com/f707850bc417f246f137](url)

thank you in advance

**Comment by apjanke** [comment]
Compilation is a CPU-intensive operation and is going to depend a lot on your hardware. A 1.3 GHz MBA sounds like a dual-core i5. 4+ hours to build `gcc` there is not unrealistic.

The log in your gist looks like `gcc` actually was built without multilib. From [the `configure` output](https://gist.github.com/anonymous/f707850bc417f246f137#file-01-configure-L3-L24):

```
../configure
--build=x86_64-apple-darwin15.2.0
--prefix=/usr/local/Cellar/gcc/5.3.0
...
--with-pkgversion=Homebrew gcc 5.3.0 --without-multilib
--with-bugurl=https://github.com/Homebrew/homebrew/issues
--enable-plugin
--disable-nls
--disable-multilib
```

Maybe there's something wrong with how the caveats are displayed in the formula.

Check this out, in the `gcc` formula.

```
  # enabling multilib on a host that can't run 64-bit results in build failures
  option "without-multilib", "Build without multilib support" if MacOS.prefer_64_bit?
...
    if build.without?("multilib") || !MacOS.prefer_64_bit?
      args << "--disable-multilib"
    else
      args << "--enable-multilib"
    end
...
    if build.with?("multilib") then <<-EOS.undent
      GCC has been built with multilib support. Notably, OpenMP may not work:
```

The multilib flags [passed to the compiler](https://github.com/Homebrew/homebrew/blob/4b1da8961f68f607cce510e014f96d6415b75ae9/Library/Formula/gcc.rb#L137) are conditionalized on both `build.without?("multilib") ` and `!MacOS.prefer_64_bit?`, but the caveats display is conditionalized on [just `build.without?("multilib")`](https://github.com/Homebrew/homebrew/blob/4b1da8961f68f607cce510e014f96d6415b75ae9/Library/Formula/gcc.rb#L197). Could that result in the multilib caveats being spuriously displayed in some cases?

Seems unlikely for this case, though, since they're on 10.11 and a 64-bit CPU.

If I do a `brew info gcc --without-multilib`, then I still get the multilib caveats displayed. Seems like that shouldn't happen.

```
$ brew info gcc --without-multilib
gcc: stable 5.3.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org
/usr/local/Cellar/gcc/5.3.0 (1,361 files, 261.4M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gcc.rb
...
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib
```

I'm doing a `brew install -s gcc --without-multilib` on my 10.9.5 box now to see what happens. Stay tuned.

**Comment by apjanke** [comment]
Hmm. Look [here in `caveats.rb`](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/caveats.rb#L8-L16).

```
  def caveats
    caveats = []
    begin
      build, f.build = f.build, Tab.for_formula(f)
      s = f.caveats.to_s
      caveats << s.chomp + "\n" if s.length > 0
    ensure
      f.build = build
    end
```

The formula's `build` options are swapped out for a "`Tab`" based on it before querying the formula for caveats. The `Tab` defines a slightly different logic for `with?`.

```
  def with?(val)
    option_names = val.respond_to?(:option_names) ? val.option_names : [val]

    option_names.any? do |name|
      include?("with-#{name}") || unused_options.include?("without-#{name}")
    end
  end
```

And that [`Tab.for_formula(f)` initialization logic](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/tab.rb#L95-L129), if I'm reading it right, initializes its build options state from the receipt file in the installation, and not from the live `f` object it was passed. 

```
    paths << f.prefix
    path = paths.map { |pn| pn.join(FILENAME) }.find(&:file?)
    if path
      tab = from_file(path)
```

Then that [Tab.from_file()](https://github.com/Homebrew/homebrew/blob/03c925589896962938c2b1f6fec641895b0d737c/Library/Homebrew/tab.rb#L41) uses a cache

```
  def self.from_file(path)
    CACHE.fetch(path) { |p| CACHE[p] = from_file_content(File.read(p), p) }
  end
```

Does this mean that if a `Tab` for the `gcc` formula had been previously constructed during this process, subsequent ones would get a `CACHE` hit and be constructed with the same values? In the case of a `brew reinstall`, I think a `Tab` would have been built for the formula to determine its initial install state. And does that mean that in the installation step when it called `Caveats.caveats()`, the `Tab` would be built from the cache, and thus the post-reinstall caveats would be displayed based on the options for the old installation, and not the new one resulting from the `reinstall`? I think it does.

To test this, instead of doing a `brew reinstall gcc`, do a `brew rm gcc; brew install -s gcc --without-multilib`. I'll try this myself too and see what happens.

**Comment by apjanke** [comment]
For that matter, before doing anything else, do a `brew info gcc` and paste its output here. Let's see what happens there.

**Comment by apjanke** [comment]
Yup, I think that's it. [Here's](https://github.com/apjanke/homebrew/blob/caveats-conditionality-demo/Library/Formula/cowsay-caveats.rb) a quicker way to reproduce. `cowsay-caveats` is a copy of `cowsay`, with an added `--without-foo` option, and caveats that depend on it.

```
class CowsayCaveats < Formula
...
  option "without-foo", "Build without Foo"
...
  def caveats
    if build.with?("foo")
      "Cowsay was built --with-foo."
    end
  end
...

Here's the results of doing `brew install -s cowsay-caveats` and two `brew reinstall cowsay-caveats --without-foo`. The first `brew reinstall cowsay-caveats --without-foo` still issues the `--with-foo` caveats. A `brew info` after the first reinstall correctly omits them.

```
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew install -s cowsay-caveats
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
==> Caveats
Cowsay was built --with-foo.
==> Summary
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew reinstall -s cowsay-caveats --without-foo
==> Reinstalling cowsay-caveats with --without-foo
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
==> Caveats
Cowsay was built --with-foo.
==> Summary
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew info cowsay-caveats
cowsay-caveats: stable 3.03 (bottled)
Configurable talking characters in ASCII art
https://web.archive.org/web/20120225123719/http://www.nog.net/~tony/warez/cowsay.shtml
Conflicts with: cowsay
/usr/local/Cellar/cowsay-caveats/3.03 (53 files, 32.6K) *
  Built from source with: --without-foo
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cowsay-caveats.rb
==> Options
--without-foo
	Build without Foo
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$ brew reinstall -s cowsay-caveats --without-foo
==> Reinstalling cowsay-caveats with --without-foo
==> Using the sandbox
==> Downloading http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/
Already downloaded: /Library/Caches/Homebrew/cowsay-caveats-3.03.tar.gz
==> /bin/sh install.sh /usr/local/Cellar/cowsay-caveats/3.03
🍺  /usr/local/Cellar/cowsay-caveats/3.03: 53 files, 32.6K, built in 0 seconds
[/usr/local/Library/Formula on ⇄ caveats-conditionality-demo]
$
```

**Comment by apjanke** [comment]
I've broken out the underlying cause of what I think are misdisplayed caveats to #48657.

**Comment by rob2go** [comment]
Thqnk you apjanke.
As I maybe forgot to say is I have two macbooks.
The one at work MBair 1.3GHz and my MBPro 2.6GHZ
When I came back on monday, there was an error during the installation of gcc without multili.
I've tried to `brew gist-logs gcc` but it said there were no logs for gcc...

So I'll try again another day, because it really demotivated me :-/
I'll let you know very soon!!!!

**Comment by rob2go** [comment]
Oh and I forgot to say that the misdisplaying disappeared when I restarted the PC
