### ISSUE TITLE
brew upgrade fails with Error: undefined method `apply' for #<Resource:0x007ffc9a88de68> 

### ISSUE THREAD

**Issue by pardery** [Homebrew/homebrew#48812]
I reviewed the troubleshoot guide, followed the steps, and reviewed the Common Issues document.  There is a very similar Common Issue that stems from an outdated brew-upgrade.rb file in the examples directory.  This does not appear to be case here.  An explanation of this, and all troubleshooting steps are included in the following gist.

https://gist.github.com/pardery/abd3a3348ec2a65eb2bb

**Comment by UniqMartin** [comment]
If the output of `brew config` is correct, you haven't updated Homebrew in about 5 months. A lot of things have changed since then. Please run `brew update` (note that it's “update”, not “upgrade”) as was also suggested by the [troubleshooting guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md) and see if that fixes your issue.

**Comment by DomT4** [comment]
Yeah, this is a rehash of the old update bug we saw. Had a few reports from people who haven't updated their Homebrew installations for a long time. Doing another `brew update` should resolve it.

**Comment by pardery** [comment]
Hmmm. That's very weird.  I update+upgrade multiple times a week.  Here's a new gist form right now.

https://gist.github.com/pardery/4613c55c46ea356e9357

The only thing that I can think of is that I did do some weird workaround a couple of weeks ago that included some git commands in order to install an old version of some package.  If I remember correctly it was to install x265 version 1.7, which fixed an error that some ffmpeg operation was throwing.  When I installed that version and did a "brew switch" to point to it, the ffmpeg issue was resolved, but this is what triggered the

"Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage."

warning that you see in my outputs.  But everything I read, including some homebrew outputs, suggested that I could ignore this message.  I'm wondering if there is something I need to reset given the weird git operation I did for x265.  Sorry I don't remember more details.

Thank you very much for the support, by the way.

**Comment by ilovezfs** [comment]
cd /usr/local
git remote show origin
git fetch --all
git checkout -q master
git reset --hard origin/master
git status
brew update
brew upgrade

**Comment by pardery** [comment]
Wow, thanks for the quick and detailed instructions.  I'll play around with that and report back.

**Comment by ilovezfs** [comment]
@pardery The actual output may be interesting too since it may show in what way your local setup went astray. Your config clearly indicates that the HEAD in /usr/local is outdated, even if the underlying repository is up to date. Those are very distinct things.

**Comment by pardery** [comment]
@ilovezfs you've done it.  The upgrade is running now, but there are 22 packages to update.  When its done I'll run through the last few commands and include a gist of all outputs.  It turns out that my suspicion was correct--I screwed something up when installing the old 1.7 version of x265 (only version offered by HB was 1.8).  I got myself onto the x265 repo to checkout that old version from a direct commit number, and must never have set myself straight again after.  Will post full output shortly.

**Comment by ilovezfs** [comment]
@pardery Yup, that totally makes sense. When the dust clears, you may want to "practice" with different ways of bringing something in besides checking out a commit hash, which is almost never what you want to do. Some relatively user-friendly ways are described here: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-get-a-formula-from-someone-elses-branch

A more advanced approach is to manually add their repo as a git remote, and then use git fetch / git merge / git pull / git reset / git rebase / etc. to manage the situation, but that requires more git knowledge than the methods suggested by the FAQ.

Rule of thumb: don't ever run `brew update` until you're in the local branch "master," with HEAD equal to the head revision of origin/master and a clean "git status." (Side note: don't ever actually checkout origin/master itself, that isn't the same as checking out the local branch "master").

**Comment by pardery** [comment]
You, @ilovezfs , are awesome.  All is well now.  I do think that the 3.0.9 rsync was a specific dependency for a backup process I was using, but it's probably time to just rework that anyways.  Hopefully the ffmpeg issue was resolved in the newest (1.9) x265 release, though I suppose I can always switch to 1.7 if need be--no need to check it out from a commit and break everything again since it's already installed.  On that note, thanks for linking that article in your last comment.  If I ever find myself in that situation again, I will definitely revisit this bookmark.  I think I ended up using the more advanced option that you mentioned on my initial go round, I just half assed it and didn't realize/remember that I had to reset/rebase... I've probably been using git a little to long to make that mistake.  

Without further ado, here is the gigantic gist: https://gist.github.com/pardery/93179d158d9e1e0f1d61

Thanks again @ilovezfs  / @UniqMartin  / @DomT4

**Comment by UniqMartin** [comment]
@pardery The main problem, as I can now see from your transcript, was that you were on a different branch. That's causing `brew update` to switch to the `master` branch for the update, and once it's done it happily switches back to the branch you had checked out, naively assuming you're fully aware of this.

@ilovezfs Thanks for chiming in and helping to solve the issue! Just a thought for future cases: The huge list of commands you suggested in your first comment looks a bit over the top and I imagine many users might be put off by this. (More so because there's no explanation what they do and why they are necessary.) Maybe break that up into separate parts like “run these commands to query the status of your working copy”, then wait for a response, then check the information obtained that way and suggest (possibly destructive) commands to fix that. But really, appreciate your thorough and well thought out comments and suggestions! :heart:

**Comment by ilovezfs** [comment]
@UniqMartin You're of course right, and the commands are obviously highly redundant (to be instructive, to be self-documenting, and to make sure the exact problem didn't get buried by the sufficient solution (git checkout master && git reset --hard origin/master)). In this case, the problem was pretty obvious (detached HEAD or wrong branch), so I figured we might as well avoid the ping-pong, especially since I was pecking on my iPhone.

**Comment by ilovezfs** [comment]
@UniqMartin I wonder if `brew config` should be enhanced to print `git branch -vv | grep -E '^\*'` and `brew doctor` enhanced to complain when `git rev-parse --symbolic-full-name HEAD` != `refs/heads/master` and/or `git status -b --porcelain|head -1` != `## master...origin/master`

**Comment by pardery** [comment]
@UniqMartin, you are right, @ilovezfs 's wall of commands was a bit of an overload upon first glance, and was definitely redundant, as @ilovezfs  mentioned, but it was definitely informative to me and I learned a bit about how homebrew does it's thing.  I appreciate both of your all's assistance very much.  Also, #48873 was a good idea, and I also agree with @mikemcquaid 's response
