### ISSUE TITLE
Error: uninitialized constant HOMEBREW_INTERNAL_COMMAND_ALIASES

### ISSUE THREAD

**Issue by gaguerra** [Homebrew/homebrew#48890]
I am attempting to install Homebrew on mac os 10.10, 

using the following command:

`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

 I get many instances of 
`Can't unlink already existing object`
and
`Can't create...`
during installation. 
Also,  when I try any "brew" commands, i.e.

`brew doctor`

(really anything that uses "brew") I get the following error

```
Error: uninitialized constant HOMEBREW_INTERNAL_COMMAND_ALIASES
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/brew.rb:49:in `<main>'
```

So is homebrew installed? But just not functional? I even tried to follow the steps to uninstall it, but they require the "brew" command, which clearly won't work in this situation.

**Comment by UniqMartin** [comment]
Are you trying to install Homebrew on top of an already existing installation? In any case the installation you attempted didn't succeed, probably due to some permission issues, as far as I can tell from the output you provided. I believe you now have a mix of old and new Homebrew files or an incomplete installation and that would explain the error regarding `HOMEBREW_INTERNAL_COMMAND_ALIASES`.

Create a backup if you think you might lose important data, and then please try to run the [uninstall script](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-uninstall-homebrew) followed by running the install script again. Please capture the *complete* output of the terminal in a file and upload it as a [Gist](https://gist.github.com/) if you still have any trouble, as that will make it easier for us to help you.

**Comment by gaguerra** [comment]
I am now running into the error that I cannot uninstall whichever version of Homebrew is currently installed. 

Here is the output of the terminal: 
[Gist File](https://gist.github.com/gaguerra/a94961437684308b6c7f)

**Comment by UniqMartin** [comment]
> I am now running into the error that I cannot uninstall whichever version of Homebrew is currently installed.

Alright, apparently there's not enough left of your previous Homebrew installation (if there ever was) for the uninstall script to work with. Please post the output of `ls -AlF /usr/local` and `ls -AlF /usr/local/Library` as this should give me an idea whether there are still files from a previous Homebrew installation. (If there are, the following suggestion will likely fail again.)

Can you please try the install script again and provide a *complete* log of the output it generates? You've mentioned a lot of `Can't unlink already existing object` and `Can't create` messages the last time you tried and it would be helpful to know exactly which files those messages are referring to.

**Comment by gaguerra** [comment]
Sure, here is the complete output running the 3 things you've requested. Thanks for helping me out. 

[Gist](https://gist.github.com/gaguerra/11214560bb68773166b9)

**Comment by UniqMartin** [comment]
Thanks, that's helpful information. You indeed have a Homebrew installation on you system that, unfortunately, you will have to remove manually before you can install Homebrew from scratch. I notice the existing installation is mostly owned by a user named `ssheehan` that is different from your user (`gaguerra`). Do you know why that might be?

Anyway, to remove the existing Homebrew installation, so that the installer can (hopefully) succeed next time, you will have to delete or move aside the following files and directories from `/usr/local`:

```
CODEOFCONDUCT.md
CONTRIBUTING.md
LICENSE.txt
Library/
README.md
SUPPORTERS.md
bin/brew
share/doc/homebrew/
share/man/man1/brew.1
```

If you feel more comfortable doing that from the Finder (sorry, don't know how experienced you are), type `open /usr/local` at the Terminal which should open the Finder inside this directory.

**Comment by gaguerra** [comment]
That worked! I appreciate your help.

**Comment by UniqMartin** [comment]
I'm happy I was able to help. :smile_cat: Closing now that this is resolved.
