### ISSUE TITLE
htop 2.0.0 is OSX compatible

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew#49082]
Now that [htop is fully compatible with OSX](http://hisham.hm/htop/index.php), there's no reason to use [the massively out-of-date fork](https://github.com/max-horvath/htop-osx) any longer.

I'm happy to put together a pull request to switch over, but I have a question or two:

1. Should the formula's name be changed from `htop-osx` to just `htop`?
2. Does anyone object to switching?
3. @hishamhm Would you be willing to look at [the current formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/htop-osx.rb) and give me any tips about differences between how `htop-osx` is current built and how you think `htop` should be built? (If not, I'll work it out myself, but I figured it would hurt to ask.)

Thanks all.

**Comment by UniqMartin** [comment]
There's already a pending PR #49057 that aims to offer the recently released `htop` 2.0.0 as a Homebrew formula. It would be great if you could contribute there instead of creating yet another PR. Check out the recently closed PRs and issues (all linked from the mentioned PR) for more context and discussion that has already happened in the past few hours.

**Comment by telemachus** [comment]
@UniqMartin So sorry about that. I searched, but obviously very poorly. Thanks for the redirect.

**Comment by UniqMartin** [comment]
No worries; no harm done! Just decided to redirect and close rather quickly to focus the discussion. :smile_cat:
