### ISSUE TITLE
dependency "built with a different C++ standard library" warning

### ISSUE THREAD

**Issue by jkarneges** [Homebrew/homebrew#49168]
Hi,

I recently updated the Zurl package (which was ported to Qt 5), and when installing it I see this warning:

```
Warning: zurl dependency qt5 was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
```

Presumably the bottles for qt5 and zurl were built from the same built bot, so I'm surprised by this warning. Also I'm not sure if it is actually harmful? (zurl seems to work...)

If the compiler used by the build bot was changed within the past few months, should qt5 bottles be rebuilt with it?

**Comment by DomT4** [comment]
Oh, I suspect this is happening because `macx-clang/qmake.conf` in Qt5 defines:
```
QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.7
```
Which forces Clang to build against the 10.7 default which was `libstdc++` rather than the newer `libc++`. 

Some upstreams offer a way to override the `QMAKE_MACOSX_DEPLOYMENT_TARGET` target which allows us to do things like [this](https://github.com/Homebrew/homebrew/blob/de7deebbd972fd512723ff2519c508bded31fa1d/Library/Formula/pyqt5.rb#L45-L46) but that doesn't seem to be supported by `zurl`.

>  Also I'm not sure if it is actually harmful?

It's not always, but it can cause fun subtle issues.

**Comment by jkarneges** [comment]
Interesting. If I run `otool` on `/usr/local/opt/qt5/lib/QtCore.framework/QtCore`, it shows `libc++`, whereas running it on `/usr/local/bin/zurl` shows `libstdc++`. So they are indeed different, though the reverse of what you're saying.

In any case I can try adding the qmake directive to zurl.

**Comment by DomT4** [comment]
That's what I meant. Qt5 is built for libc++ but its standard deployment target for Clang forces certain builds to be libstdc++.

**Comment by jkarneges** [comment]
Got it. This is an issue in Zurl then. See PR #49176.
