### ISSUE TITLE
Add "--unicode-path" option to subversion again

### ISSUE THREAD

**Issue by tholu** [Homebrew/homebrew#49263]
In the current subversion formula, the `--unicode-path` option is missing again. However, this is STILL not fixed in upstream (http://subversion.tigris.org/issues/show_bug.cgi?id=2464 - from 2005, so more than 10 years ago).
I used subversion17 until now, but realized it won't install in El Capitan.

`
subversion17: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
`

Since I've given up on upstream to fix this, perhaps we can try to optionally patch this issue in 1.9 (1.8 did not work anymore unfortunately, see https://github.com/Homebrew/homebrew/issues/20656)

Other option would be to get subversion17 building on El Capitan again: https://github.com/Homebrew/homebrew/issues/49265

Related issue (there are many more):
https://github.com/Homebrew/homebrew/pull/12456

**Comment by DomT4** [comment]
It's not so much missing as intentionally removed. It had to be bundled with a bunch of warnings because it can cause compatibility issues, and us applying it downstream led to the situation where nothing was happening upstream because downstream package managers did their job for them. This is really an upstream issue that _needs_ to be resolved by them.

The older `subversion` formulae in Versions had to be capped on El Cap because they won't use a newer OpenSSL and were stuck using the old, insecure system OpenSSL bundled with OS X which I already wasn't delighted about. Then El Capitan came along and removed the OpenSSL headers `svn` wants to find during configure, hence the OS X version cap.

They will likely be removed entirely in upcoming changes through Versions because we've had to a ridiculous amount of dancing to keep them alive and at this point it's a real stretch to pretend to people they are completely secure or functional and I don't want people trusting them merely because they sit under the Homebrew umbrella.

I'll ding @mistydemeo and @mikemcquaid for second opinions given they were maintainers who were around at the time, but I can't imagine we'll move forwards on this.

Refs:
* https://github.com/Homebrew/homebrew/issues/20656
* https://github.com/Homebrew/homebrew/pull/24700#issuecomment-29481171.

**Comment by tholu** [comment]
Thanks for your superfast answer. That would be really unfortunate, because then there is only like one commercial SVN client left on a recent version OSX which can handle the unicode paths (and I have tested most if not all of them).
I'm not very experienced with all the issues around OpenSSL, so forgive me if my question is naive, but can't we provide the OpenSSL headers that subversion17 expects? Thanks!

**Comment by DomT4** [comment]
We have a team chat that dings us when new Issues are filed; I was the last one to touch the patch logic in the core's `subversion` formula so this piqued my interest, heh.

Note that removing the formulae from Versions wouldn't bar them from the Homebrew ecosystem. There'd be absolutely nothing stopping anyone who wants them from supporting those formulae in their own external tap, which is a very easy and simple process.

The big problem on `homebrew/versions` is that people trust Homebrew, and I don't mean "problem" broadly at all, but people trust us to keep them secure, to keep their packages up-to-date (via `brew update`, etc), to build with sane defaults, etc, so they see these `subversion17`, etc packages sitting in Versions and think "Great, they are part of Homebrew, I'll use 'em!".

They don't necessarily see that they are built against an old and really quite insecure system OpenSSL at this point, and that we've had to do a lot of monkey-patching to keep them alive. There's an implicit trust there because they came from Homebrew official, and that makes me nervous, because the Versions tap in particular has often insecure/broken/entirely-unsupported-by-upstream versions that we don't have the humanpower or CI resources to keep on top of.

> I'm not very experienced with all the issues around OpenSSL, so forgive me if my question is naive, but can't we provide the OpenSSL headers that subversion17 expects? Thanks!

So, we can go three routes on this sort of thing.
* Disable SSL support. We did this, people complained _loudly_, it was reverted by using the insecure system OpenSSL which works (Up to El Cap).

* Vendor OpenSSL 0.9.8 for Subversion. This is problematic because it's the same version as the system OpenSSL and has all the same problems that does, but it is also unsupported by OpenSSL themselves at this point and no longer has even CVE analysis performed on it, let alone fixed/released.

* Vendor OpenSSL 0.9.8 headers in _Homebrew_ itself. This won't happen, partly because of the licensing restrictions by OpenSSL and partly because I don't want to add thousands of lines of external code into Homebrew to facilitate supporting a broken OpenSSL by external projects.

**Comment by mikemcquaid** [comment]
> Thanks for your superfast answer. That would be really unfortunate, because then there is only like one commercial SVN client left on a recent version OSX which can handle the unicode paths (and I have tested most if not all of them).

I know this is difficult to hear but: Subversion does not support unicode paths. I wouldn't rely on that behaviour to work and would migrate away from using unicode paths or to another version control system. I'm afraid that Homebrew is unable and unwilling to support effectively a custom fork of Subversion that does support unicode paths.

**Comment by tholu** [comment]
Thanks for your detailed answers! `subversion18` installs just fine under El Capitan. There seems to be an updated patch for 1.8 here: http://subversion.tigris.org/issues/show_bug.cgi?id=2464 
Since the overwhelming negative response regarding readding the patch to `homebrew/versions` I will try that in my own tap.

**Comment by tholu** [comment]
**Update:** I created my own tap with the re-added option and the new patch for `subversion18` and just tested it successfully, the updated formula is here: https://github.com/tholu/homebrew-tap/blob/master/subversion18.rb

To everyone who would like to use it, here's how:
```
brew tap tholu/tap
brew install --with-unicode-path tholu/tap/subversion18
```

I understand, if you don't want to add this patch for the `versions/subversion18` formula, but it took not that much effort using the updated patch provided.

**Comment by DomT4** [comment]
Passing on this then. I forgot `subversion18` did actually work with our OpenSSL, so that may survive the Versions axe, at least for a while.

We really want this patch accepted upstream before we touch it again. There's too much willingness upstream to let us shoulder the support burden indefinitely whilst they refuse to touch the core problem and we don't have the capacity to be Apache's stand-in, sadly.

**Comment by vizcay** [comment]
@tholu thanks for providing this (just added a macos x side to my main linux development and I've been bitten by this with accutes characters).. but when I try to install I get this:

`curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "subversion18--serf"
Download failed: https://serf.googlecode.com/svn/src_releases/serf-1.3.8.tar.bz2`

Sorry, I'm pretty new to Homebrew. I guess it has something to do with google closing google code.. there is some work around about this? Thanks

**Comment by tholu** [comment]
@vizcay I just updated my formula (https://github.com/tholu/homebrew-tap/blob/master/subversion18.rb) with a new URL directly from Apache, can you try again and tell me if it works now?

**Comment by vizcay** [comment]
@tholu  it installed correctly on el Capitan and no more strange behaviour with accute characters so far.. if anything breaks Ill let you know!

Thanks!
