### ISSUE TITLE
Invalid pkg-config for tesseract

### ISSUE THREAD

**Issue by jeroenooms** [Homebrew/homebrew#49579]
The `@OPENCL_LIB@` shouldn't be in there, should it?

```
$ pkg-config --libs tesseract --static
-L/usr/local/Cellar/tesseract/3.04.01/lib -L/usr/local/Cellar/leptonica/1.72/lib 
  -ltesseract -lpthread -llept @OPENCL_LIB@ -llept -lz -lpng -ljpeg -ltiff
```

**Comment by apjanke** [comment]
Don't think so.

Looks like it might be a typo, missing an `S` in `tesseract.pc.in`.

```
eilonwy% grep -r OPENCL_LIB *
configure:OPENCL_LIBS="-lOpenCL"
configure:        OPENCL_LIBS=""
configure:        OPENCL_LIBS=""
configure:        OPENCL_LDFLAGS="-l${OPENCL_LIBS}"
configure.ac:OPENCL_LIBS="-lOpenCL"
configure.ac:        OPENCL_LIBS=""
configure.ac:        OPENCL_LIBS=""
configure.ac:        OPENCL_LDFLAGS="-l${OPENCL_LIBS}"
tesseract.pc.in:Libs.private: -lpthread -llept @OPENCL_LIB@
```

**Comment by apjanke** [comment]
Switching it to `OPENCL_LIB` didn't do anything for me. Switching it to `OPENCL_LDFLAGS` gets the macro to be replaced, because `config.status` defines that after `configure` is run. Buuuut I'm not sure that's the right thing to do; maybe that really is supposed to be a delayed-evaluation macro for clients of `pkg-config` to use. (Don't think so though, b/c the pkgconfig file should probably capture which OpenCL lib was used by tesseract at build time.)

I'll poke around on this a bit more so I know what's going on, and then report it upstream.

If that is the case, then [this branch](https://github.com/apjanke/homebrew/tree/tesseract-fix-pkgconfig) has a fix for it.

```
$ brew install -s tesseract --with-opencl
...
🍺  /usr/local/Cellar/tesseract/3.04.01: 75 files, 39.6M, built in 1 minute 15 seconds
[/usr/local on ⇄ tesseract-fix-pkgconfig ±]
$ pkg-config --libs tesseract --static
-L/usr/local/Cellar/tesseract/3.04.01/lib -L/usr/local/Cellar/leptonica/1.72/lib -ltesseract -lpthread -llept -framework OpenCL -llept -lz -lpng -ljpeg -ltiff
```

**Comment by apjanke** [comment]
Reported upstream issue: tesseract-ocr/tesseract#241
