### ISSUE TITLE
Speedup tests

### ISSUE THREAD

**Issue by felixbuenemann** [Homebrew/homebrew#49642]
The tests have become very slow, because they do a lot of work that is uneccessary for most PRs.

I'd say > 90% of the PRs contain either new or updated formulas, so I guess it doesn't make sense to run unit and coverage tests for these PRs.

Frustratingly the most relevant and most likely to fail tests for formula contributors are also run last, so in order to see failures in formulas we might need to wait an hour instead of maybe 15 min if those tests were run first.

It should be rather simple to inspect the list of files changed by the current PR:

```sh
git diff-tree --no-commit-id --name-only -r origin/master..HEAD
Library/Formula/example.rb
```

Or only list changes in for formulas:

```sh
git diff-tree --no-commit-id --name-only -r origin/master..HEAD -- Library/Formula
Library/Formula/example.rb
```

Now if we know, that certain tests are only required for certain files or directories, we can skip those to significantly speed up the CI time.

**Comment by mikemcquaid** [comment]
> The tests

Which tests? `brew tests`? `brew test-bot`?

**Comment by felixbuenemann** [comment]
I'm looking particulary at the travis ci tests.

**Comment by felixbuenemann** [comment]
My times above are a bit skewed, because lot's of the waiting might be queue time, but I often see ~6 mins to run `brew tests` and `brew tests --coverage` which could be avoided.

**Comment by felixbuenemann** [comment]
@mikemcquaid If you think this is a valid approach, I could try to implement it.

**Comment by DomT4** [comment]
> I'm looking particulary at the travis ci tests.

Travis is rather slow, and lately having some reliability issues, particularly on fetching the gems required to run `brew tests` on a fresh machine. Without gem installation factored in the `brew tests` stage doesn't tend to take longer than a minute at the most. I think drastic changes based off recent Travis unreliability is somewhat jumping the gun.

**Comment by ilovezfs** [comment]
@felixbuenemann You can run `brew tests` locally. The command also accepts a `---only` option if you want to run them selectively.

**Comment by felixbuenemann** [comment]
I can run `brew audit`, `brew install` and `brew test` locally, but that only tells me that it's working on my system, while the CI starts with a clean slate and tests multiple Mac OS X versions.

My point is that the CI could be sped up by being smarter about which test suites to run.

**Comment by ilovezfs** [comment]
@felixbuenemann Failures that are OS-version specific are not very common. Also, `brew test` and `brew tests` are two different commands, and I was referring to the latter. If you are especially worried about OS-version specific failures for some reason, you can always run the tests in VMs for as many OS X versions as you want.

Your point is clear, and there is probably low-hanging fruit here. That said, a) the bulk of CI time is not spent on tests b) the delays are primarily caused by the length of the queue not the run time per formula c) there is value in the assurance that the full test suite passes before anything is integrated. d) If your wait time went from 45 minutes to 36 minutes, I'm skeptical it would be significantly less frustrating in any way. 

That said, I think it is probably true that most of the tests that run during `brew tests` are only relevant if files outside of Library/Formula changed, and it would be interesting to know if there is actually any known case where a change in Library/Formula caused any of the `brew tests` to fail, and, if so, what that actually entailed, because it seems somewhat far fetched.

**Comment by felixbuenemann** [comment]
I'm aware that `brew tests` and `brew test` are not the same, but I mostly contribute formula changes, so there's no need for me to run `brew tests` locally.

Yes, you can run lots of OS X VMs to check for incompatibilities locally, but it's very time consuming and not something the average contributor will bother with.

And as long as there is a limit on concurrent builds, the best way to reduce queue time is to speed up individual builds. Running `brew tests` selectively is only one of several optimization vectors, I'm sure there are more low hanging fruit and combined those could make quite a difference.

Anyway this is just a proposal and if the homebrew team doesn't think it's worthwhile I'm not going to argue it to death ;-)

**Comment by mikemcquaid** [comment]
Unit and coverage tests are comparatively not the main cause of slowdown: it's `brew install`ing big packages. It's still useful to run the unit tests to verify that on a formula failure it's the formula that's broken and not an underlying Homebrew issue. When we split formulae and core code into separate repos we'll be able to be a bit smarter here but trust me when I say there's no quick wins that don't have a similar quality compromise.
