### ISSUE TITLE
Error: /usr/local must be writable! on 10.11.4 Beta (15E61b)

### ISSUE THREAD

**Issue by mustangxu** [Homebrew/homebrew#49895]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Got

> Error: /usr/local must be writable!

again when running `brew update` after my OS X upgraded to 10.11.4 Beta (15E61b) yesterday, and this time, it's impossible to change owner/permissions on /usr/local even I use root account

**Comment by ilovezfs** [comment]
@mustangxu Nope, no problem with 10.11.4 Beta 6 (15E61b) as shown in this gist: https://gist.github.com/ilovezfs/56cefb36fee253a756e5

No changes were made between 10.11.2 and 10.11.4 Beta 6 to /System/Library/Sandbox/rootless.conf or /System/Library/Sandbox/Compatibility.bundle/Contents/Resources/paths

You have some kind of local configuration issue going on.

What is the output of
```
$ brew --prefix
$ mdutil -t `brew --prefix`
$ ls -ldOe  `brew --prefix`
$ ls -al `brew --prefix`
$ brew config
$ find `brew --prefix` -not -uid `id -u`
```

Most likely you just need to do the following (but it would be interesting to see the output of the above before actually changing anything):
```
sudo chgrp -R admin /usr/local
sudo chmod -R g+w /usr/local
```

**Comment by DomT4** [comment]
No problems here on the same beta release. @ilovezfs's troubleshooting steps should help narrow this down.

**Comment by mustangxu** [comment]
thx, fixed after using

`sudo chgrp -R admin /usr/local`
`sudo chmod -R g+w /usr/local`

**Comment by skeller88** [comment]
Thanks! Why is this line necessary? 

`sudo chgrp -R admin /usr/local`

My understanding is that root users have more permissions than admin users: https://support.apple.com/en-us/HT204012

But that doesn't appear to be the case because I got the error when I only ran 
`sudo chmod -R g+w /usr/local`

But the error was fixed when running both lines.

**Comment by ilovezfs** [comment]
There's no such thing as "root users." "root" is a single user (user id 0). You can enable account login for the root user as described in that support article, but the root user always exists either way.

By contrast, "admin" is a group. Users who are members of the admin group are characterized by their write access to /Applications, their ability to use "sudo," and their ability to install software.

By default, brew is designed around the idea that the brew prefix (/usr/local) and all of its contents will be writable by all members of the admin group. Various things (usually nothing done by brew itself) can cause one or more things in /usr/local to end up not being writable by all admin users. The commands above recursively modify (if needed) the entries within /usr/local to ensure that the group assigned to each entry is admin, and that the admin group has write access to each entry.

```
sudo chmod -R g+w /usr/local
```
won't be sufficient if a file or directory has group wheel, since admin users are usually not members of group wheel. The command would indeed ensure writability for members of wheel, but that doesn't help your user if it's a member of admin but not a member of wheel. So you also have to set the group of the file to be admin in order for g+w to actually make any difference.

**Comment by evgeniyd** [comment]
I have fixed the error by doing what `$ brew doctor` suggested me to:

    Warning: /usr/local is not writable.
    
    You should probably change the ownership and permissions of /usr/local
    back to your user account.
      sudo chown -R $(whoami) /usr/local`

After that I was able to successfully to do `brew uninstall --force brew-cask; brew update` as suggested in [v0.60.1 release notes](https://github.com/caskroom/homebrew-cask/releases/tag/v0.60.1)
