### ISSUE TITLE
Wrong version info for cmake in cpp-netlib 0.11.2

### ISSUE THREAD

**Issue by keithyipkw** [Homebrew/homebrew#50038]
The installed version is 0.11.2 but the version in ConfigVersion.cmake is 0.11.1  

MacBook-Pro:~ keithyip$ brew info cpp-netlib
cpp-netlib: stable 0.11.2 (bottled)
C++ libraries for high level network programming
http://cpp-netlib.org
/usr/local/Cellar/cpp-netlib/0.11.2 (228 files, 1.7M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cpp-netlib.rb
==> Dependencies
Build: cmake ✘
Required: openssl ✔, boost ✔

MacBook-Pro:~ keithyip$ head -n1 /usr/local/Cellar/cpp-netlib/0.11.2/lib/cmake/cppnetlib/cppnetlibConfigVersion.cmake 
set(PACKAGE_VERSION "0.11.1")

**Comment by dunn** [comment]
It looks like they just forgot to update the CMake version strings: https://github.com/cpp-netlib/cpp-netlib/blob/b540ff3bb234d9457bb67656a57bedaeb41edd2d/CMakeLists.txt#L55-L57 (that's at the 0.11.2 tag).

Since this isn't an issue specific to Homebrew, I'm going to close it; but thank you for the report!
