### ISSUE TITLE
antigen not installed properly

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/homebrew#50049]
If I install antigen with `brew` it doesn't install properly…
```sh
zsh: command not found: antigen
$ which antigen
antigen not found
```
See [here](https://github.com/zsh-users/antigen/issues/159).

**Comment by apjanke** [comment]
To get it to work, you need to add `source $(brew --prefix)/share/antigen.zsh` or similar to your `~/.zshrc`. 

That should be in the formula's caveats. Added: 2892bcdc1da716331600f008329e1ec511deacf4.

It's also weird that it's installing `antigen.zsh` directly under `/usr/local/share` instead of under `pkgshare`. Maybe we could rearrange that before too many installations get done with the current arrangement...

**Comment by danielbayley** [comment]
> To get it to work, you need to add source $(brew --prefix)/share/antigen.zsh or similar to your ~/.zshrc.

Yeah I figured that out, cheers. I does need a caveat.

I think Iv'e already moved onto [zplug](https://github.com/b4b4r07/zplug) anyway! :laughing: 

Although _that_ could do with a brew formula now…

**Comment by DomT4** [comment]
> It's also weird that it's installing antigen.zsh directly under /usr/local/share instead of under pkgshare.

We usually stick things that require sourcing in `prefix` directly. It is unusual for them to be somewhere "public" as such.

> Although that could do with a brew formula now…

It would need tagged, stable releases first :stuck_out_tongue_winking_eye:.

Closing as @apjanke's [commit](https://github.com/Homebrew/homebrew/commit/2892bcdc1da716331600f008329e1ec511deacf4) should make the necessary step afterwards more obvious now.

**Comment by apjanke** [comment]
> We usually stick things that require sourcing in `prefix` directly. It is unusual for them to be somewhere "public" as such.

Yeah, that makes sense too. Just somewhere that doesn't get linked into a public/common area without being separated into a package subdirectory.
