### ISSUE TITLE
Looking for docs and/or examples for writing a formula for a node based tool.

### ISSUE THREAD

**Issue by hartzell** [Homebrew/homebrew#50167]
I would like to assemble and submit a formula for [tidy-markdown](https://github.com/slang800/tidy-markdown).  It's a node based app and the general installation instructions boil down to:

    npm install tidy-markdown -g

I'm looking for guidance on how to do it.  I don't see anything in the Forumula cookbook or the Gems, Eggs and Perl modules document.  The formula for Kibana uses node as a resource and then does some install gymnastics.  Pow seems to be something one installs w/ node, is its formula a good example?  Or generate-json-schema?

I'd appreciate any hints, pointers and/or good role models...

**Comment by dunn** [comment]
Out of curiosity, why not just install it with `npm`?

**Comment by DomT4** [comment]
I'm not sure we'd accept it in the core but general installation would be something like [this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/autocode.rb#L14-L21).

Note the installation is restricted to its prefix so `-g` isn't allowed; you use a plain `npm install` to install locally, move everything in that directory to `libexec` and then symlink the executable from that private box into `bin`, which is then symlinked into a publicly available path.

**Comment by hartzell** [comment]
@dunn -- I like being able to use homebrew (and teach my teams) to manage the things on a system.  Want to use something?  Install it with `brew install ...`.  Don't need it any longer?  Uninstall it with `brew uninstall ...`, don't just let the crap pile up.  Makes it easy to keep systems clean and well defined.  When someone describes how to configure a system, it's `brew install All The Things`, not `brew install Some Thing` and then `pip ...` and `npm ...` and ...  How do you know what's installed on a system?  `brew list`, not `brew list` and then look around in This Dir and That Dir.  

I'm also interested in having it in both homebrew and linuxbrew (multi-platform teams).

I probably could have saved a lot of typing and said something like **brew rocks** or **because simple**... ;)

**Comment by hartzell** [comment]
@DomT4 -- Out of curiousity, [which of the criteria](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md) would it fail to meet?  I suppose it could be "too obscure" ... 

> We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.

... or is there something about *node* packages or ?

I'm not fighting to have it included [yet], just curious.

Thanks for the pointer to a good role model.

**Comment by DomT4** [comment]
If you run `brew audit --strict --online` on a prospective formula for that repo our automated code will flag it because the GitHub repo is barely watched/forked/etc. I appreciate this is tricky for Node things because almost all the package management side of the deal happens on `npmjs.com` where the package is _more_ than popular enough to merit inclusion, so I'm not saying we'd be yay/nay on this alone by any means.

The rest of the answer in regards to things like `pip` and `npm` is somewhat boring, but:

* We accept formulae that could be installed using `pip` instead so long as they include executables and aren't just Python bindings/libraries/etc.
* Our `pip`-installable formulae are a million times better handled than our `npm`-using formulae because we've a system where we vendor all the dependencies, can cache them locally so people can install offline, etc.
* This proved impractical with `npm` because of the way `npm` handles dependencies. We did some research and we'd be looking at formulae with hundreds of vendored resources, and even then the `npm` install process is complicated enough that we'd need considerable logic on top of that.
* This means realistically if a user doesn't want the bottle, they need to be online during install and have sufficient connection strength to install `npm`-using formulae. This is an annoying problem for a package manager that does caching, and people have come to expect to be able to `brew fetch` something in advance and have it install offline later. It's a niche problem certainly, but an important niche.
* It also means we can't promise security of the `npm` dependency-fetching process, unlike `pip`-installable formulae where we verify everything with `sha256` hardcoded into the formulae themselves and we can display where the file is being fetched from, including any redirects. With `npm` stuff we're trusting there's nothing problematic about the `npm` installation.

Boring package-management stuff, really, but package-management stuff is why people use us :smile:. None of these problems are fatal, but they do contribute to the reason (alongside a prior lack of request that we start including stuff `npm` can already install itself) we don't have a ton of `npm`-using formulae around.

**Comment by hartzell** [comment]
Not boring at all.  *Thank you* for the info!

**Comment by DomT4** [comment]
Please do feel free to ding if we can help further. Even if it's something we turn away from the core at some future point you can ship it using Homebrew without relying on us to do so by [creating](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) your own tap.

**Comment by hartzell** [comment]
Will do.  Already getting it set up in my own space.  Having fun curing my *npm* ignorance, but I can feel it building my character so I'm happy.
