### ISSUE TITLE
GCC with GNU LD

### ISSUE THREAD

**Issue by nash169** [Homebrew/homebrew#50393]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Feature/Formula Requests:

**Please note by far the quickest way to get a new feature or formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

Hi there,
I'd like to install gcc setting it to use gnu ld instead of default system ld. In order to get the gnu ld I installed binutils using homebrew but it doesn't install the ld. Is there something I've to change into the binutils formula to solve this problem?
After that I'd like to edit the gcc formula to set the gnu-ld as default linker. Is it possible?

**Comment by DomT4** [comment]
> In order to get the gnu ld I installed binutils using homebrew but it doesn't install the ld

It's not supported because of the options we use in that formula. We'd possibly review a PR to change this, but not at the cost of degrading current functionality there:
```
*** This configuration is not supported in the following subdirectories:
     ld gas gprof
    (Any other directories should still work fine.)
```

> After that I'd like to edit the gcc formula to set the gnu-ld as default linker. Is it possible?

Possibly, by passing the `LD` variable pointing at the `ld` you wish to `configure`, but I make no promises at all that it'll work as expected and may still be overridden by our [environment](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/extend/ENV/shared.rb#L17-L27) that we set to produce consistent builds.
